### ISSUE TITLE
win7打开闪退

### ISSUE THREAD

**Issue by getstars** [huiyadanli/RevokeMsgPatcher#1]
装了.net 4.7 打开闪退

**Comment by huiyadanli** [comment]
晚上我测试下，一般闪退基本是 .Net 框架的问题

**Comment by huiyadanli** [comment]
问题复现了。。。是没找到微信注册表的安装信息时会闪退

**Comment by huiyadanli** [comment]
[0.4](https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/0.4) 版本已经修复该问题
