### ISSUE TITLE
9.1.6版本不支持

### ISSUE THREAD

**Issue by k3sc** [huiyadanli/RevokeMsgPatcher#105]
因为这是最后一个能够看已退出群聊天记录的版本能否给加上呢作者大大

**Comment by huiyadanli** [comment]
能提供一个这个版本的QQ安装包吗？

**Comment by k3sc** [comment]
[https://dldir1.qq.com/qqfile/qq/PCQQ9.1.6/25786/QQ9.1.6.25786.exe](url)

**Comment by huiyadanli** [comment]
先尝试下这个dll能否支持，我这边暂时测试不了。
直接解压覆盖 QQ\Bin 目录下的同名文件即可（IM.dll）

[IM.9.1.6.25786.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/4943584/IM.9.1.6.25786.zip)

**Comment by huiyadanli** [comment]
[新版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases) 已把特征码防撤回的版本范围拓展到 9.1.6 版本。
