### ISSUE TITLE
微信最新版不支持防撤回

### ISSUE THREAD

**Issue by local-uan** [huiyadanli/RevokeMsgPatcher#108]
微信最新版不支持防撤回

微信2.9.5.41

手贱升级了一下，回不去旧版了

**Comment by local-uan** [comment]
> 微信最新版不支持防撤回
> 
> 微信2.9.5.41
> 
> 手贱升级了一下，回不去旧版了

**Comment by huiyadanli** [comment]
0.8 版本支持的，会显示撤回提示
