### ISSUE TITLE
任务栏固定微信后，无法使用crtl与数字键的快捷方式打开

### ISSUE THREAD

**Issue by jty9625** [huiyadanli/RevokeMsgPatcher#109]
启动防撤回后，固定在任务栏的微信，虽然已经在后台运行，但无法使用crtl+2crtl与数字键的快捷方式打开，取而代之的是打开了新的微信登录界面。
<img width="851" alt="1" src="https://user-images.githubusercontent.com/35856372/87213015-622ce500-c354-11ea-8f89-d08eb62a9f0f.png">

**Comment by BlackDriver-li** [comment]
我也有遇到这个问题，希望作者能够修复

**Comment by huiyadanli** [comment]
是多开功能导致的，后面计划把补丁的防撤回与多开功能做成可选形式。

same as #65

**Comment by huiyadanli** [comment]
[0.9 版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases) 已经可以选择需要安装的功能补丁。可以只安装 防撤回 功能，而不安装 多开 功能。

如果你已经安装过原来的补丁，并且有备份文件。请先操作备份还原，再只勾选 防撤回 功能并安装即可。
