### ISSUE TITLE
建议加个提示，有人撤回，提示一下 这条消息是撤回消息

### ISSUE THREAD

**Issue by ooiuv** [huiyadanli/RevokeMsgPatcher#11]

**Comment by huiyadanli** [comment]
#2

**Comment by ooiuv** [comment]
> 参见[＃2](https://github.com/huiyadanli/RevokeMsgPatcher/issues/2)，作者水平有限
是实现方式不同吗？所以不能像你回复的那个，可以有提示

**Comment by huiyadanli** [comment]
嗯，现在的实现方式很简单的。
复杂的可以使用：https://github.com/anhkgg/SuperWeChatPC

**Comment by ooiuv** [comment]
> 嗯，现在的实现方式很简单的。
> 复杂的可以使用：[https](https://github.com/anhkgg/SuperWeChatPC)：[//github.com/anhkgg/SuperWeChatPC](https://github.com/anhkgg/SuperWeChatPC)

收到 谢谢！
