### ISSUE TITLE
希望在被撤回的信息后面加上(已撤回)之类的显示

### ISSUE THREAD

**Issue by lynnguo666** [huiyadanli/RevokeMsgPatcher#110]
希望在被撤回的信息后面加上(已撤回)之类的显示，这个功能可以在软件上面自行选择是否开启提示
作者大大看看能不能实现类似的效果
类似于
![image](https://user-images.githubusercontent.com/39556167/87844138-01218600-c8ed-11ea-97ae-ba8271555806.png)

**Comment by huiyadanli** [comment]
现在的补丁实现方式没法做额外功能 :joy:

**Comment by lynnguo666** [comment]
emmm，好吧，一会我看看有没有什么方案能实现awa
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyadanli/RevokeMsgPatcher"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月18日(星期六) 中午12:07
收件人:&nbsp;"huiyadanli/RevokeMsgPatcher"<RevokeMsgPatcher@noreply.github.com&gt;;
抄送:&nbsp;"Baobob_Lynn"<2475274997@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] 希望在被撤回的信息后面加上(已撤回)之类的显示 (#110)





 
现在的补丁实现方式没法做额外功能

**Comment by huiyadanli** [comment]
应该有拦截网络请求的方案的，这种可以明确知道哪条信息被撤回了。

这种只修改文件，不做hook的话，做多做到能够显示出原来的撤回提示。。
