### ISSUE TITLE
希望加上QQ群消息的防撤回

### ISSUE THREAD

**Issue by yfShy** [huiyadanli/RevokeMsgPatcher#111]
单个聊天的防撤回已经做的很好了，
希望作者大大可以抽空加个QQ群消息防撤回功能。 不然群友老是开车不带我。

**Comment by huiyadanli** [comment]
QQ群撤回应该是支持的

**Comment by yfShy** [comment]
> QQ群撤回应该是支持的

我测试的是 qq微信单人消息撤回可行，   但是qq群 和微信群的消息 对方撤回了 我这边也显示撤回了。
qq版本：QQ9.3.5 (27030)
![qq版本](https://user-images.githubusercontent.com/35094951/87909088-269fc280-ca9a-11ea-9af2-1781e244ccf1.png)

微信版本：
![微信版本](https://user-images.githubusercontent.com/35094951/87909092-299ab300-ca9a-11ea-94a5-dda42b1e8a28.png)

现象：
![微信现象](https://user-images.githubusercontent.com/35094951/87909097-2c95a380-ca9a-11ea-8c52-0cdfe517789f.png)
目前微信 可多开， 单人撤回 也可显示  ，就是群消息 无法防撤回。

**Comment by huiyadanli** [comment]
微信2.9.5.41我测试群聊撤回没问题，现在的微信撤回都是会显示撤回提示的

![image](https://user-images.githubusercontent.com/15783049/87943291-641f4280-cad0-11ea-9ef8-71c40e1b0c2b.png)

![image](https://user-images.githubusercontent.com/15783049/87943338-76997c00-cad0-11ea-9905-4da6f7112ad8.png)

QQ9.3.6（27263） 群聊防撤回也没问题（不显示撤回提示），一般最新版本没问题，中间版本也不会有问题。

![image](https://user-images.githubusercontent.com/15783049/87942777-aa27d680-cacf-11ea-907b-18b344e902bf.png)

![image](https://user-images.githubusercontent.com/15783049/87943432-9cbf1c00-cad0-11ea-8cfd-e3620fb1953b.png)



请确认你是否在QQ/微信更新之后重新安装补丁，**每次更新后都是要重新安装补丁的**。

还有，防撤回必须要在你PC上登陆相关应用，**且聊天信息被PC端应用接收**。如果是消息同步出来的聊天记录，是没法看到别人撤回的内容的

**Comment by yfShy** [comment]
那应该是因为同步的记录 导致了这种现象。 只有一个账号不好测试（￣Д￣）。 感谢作者大大。那我就把这个Issues关闭啦。
