### ISSUE TITLE
防撤回使用说明.txt 乱码

### ISSUE THREAD

**Issue by FDUdannychen** [huiyadanli/RevokeMsgPatcher#112]
目测是默认编码……

**Comment by huiyadanli** [comment]
嗯，毕竟是 Windows平台下的，编码是 GB2312 。

你是用的什么工具打开的？

**Comment by FDUdannychen** [comment]
我就是用的我windows上的notepad，打开就是乱码。我估计你把编码改成UTF8应该就没问题了。

**Comment by huiyadanli** [comment]
我测试了下 win10 notepad 两种编码都可以打开，下个版本发布我看情况改下
