### ISSUE TITLE
QQ9.3.5安装插件以后所有对话窗口中，自己发的消息都从原来的右边跑到左边，跟其他人在一边了。

### ISSUE THREAD

**Issue by sunencheng** [huiyadanli/RevokeMsgPatcher#114]
QQ9.3.5安装插件以后所有对话窗口中，自己发的消息都从原来的右边跑到左边，跟其他人在一边了。在前一个版本（版本号未知）此问题为偶发情况

**Comment by huiyadanli** [comment]
跟补丁无关。

这本来就是QQ的一个自适应功能，QQ窗口最大化的时候（宽度超过一定程度）自己发的消息框就会到左边。。。
