### ISSUE TITLE
成功安装补丁，正常登陆后闪退，报错如下图

### ISSUE THREAD

**Issue by liurui2014** [huiyadanli/RevokeMsgPatcher#117]
Windows 10 的微信版本2.9.5.41在微信关闭的情况下能成功安装补丁，正常登陆后闪退，报错如下图
![image](https://user-images.githubusercontent.com/17958377/89870962-3cac2900-dbe9-11ea-80ec-089d902accb0.png)

**Comment by huiyadanli** [comment]
补丁会修改 WeChatWin.dll，看提示是WeChatWin.dll丢失（可能是补丁安装出现问题，安全软件拦截之类的？），先备份还原后登录试试，如果能登录的话，再重新安装补丁尝试登录。

如果一开始备份还原不能解决问题，那就需要重新下载微信覆盖安装。
