### ISSUE TITLE
deepin-wine-TIM可以用么，应该如何使用？

### ISSUE THREAD

**Issue by AquaIndigo** [huiyadanli/RevokeMsgPatcher#118]

**Comment by huiyadanli** [comment]
wine下不知道这么做，可以尝试下其他.net 框架下软件的运行方式。

有一个比较麻烦的解决方案就是：使用同版本TIM，在windows下安装补丁后，复制TIM安装文件夹里的Bin/IM.dll文件，覆盖deepin下的同名文件就行了。

**Comment by AquaIndigo** [comment]
> wine下不知道这么做，可以尝试下其他.net 框架下软件的运行方式。
> 
> 有一个比较麻烦的解决方案就是：使用同版本TIM，在windows下安装补丁后，复制TIM安装文件夹里的Bin/IM.dll文件，覆盖deepin下的同名文件就行了。

deepin-wine 对新版的TIM支持比较差，操作一次卡很久，只能用2.0.0的TIM才会流畅，所以目前来看不好搞……
