### ISSUE TITLE
不支持2.6.8.68 嘛？O(∩_∩)O哈哈~

### ISSUE THREAD

**Issue by Jensonhui** [huiyadanli/RevokeMsgPatcher#12]

**Comment by huiyadanli** [comment]
应该是可以的，提示什么错误吗？

**Comment by Jensonhui** [comment]
倒是没有提示错误，只是没有实现功能；

**Comment by huiyadanli** [comment]
@Jensonhui 是提示 2.6.8.68 不支持吗。这个好像有点问题，我个人没法获取到这个版本的更新没法验证防撤回是否有效

**Comment by Aircea** [comment]
@huiyadanli  提示：  当前微信版本不被支持：2.7.1.65

**Comment by cnjd** [comment]
大佬更新下2.7.1.65咯

**Comment by huiyadanli** [comment]
@Aircea @cnjd 我无法获取到最新版本的推送:joy:，如果可以提供该版本的微信的话，我可以立马制作防撤回...

**Comment by cnjd** [comment]
@huiyadanli 我没有安装包，我是从2.7.1.43检查更新升级到65的

**Comment by huiyadanli** [comment]
@cnjd 直接压缩打包微信的安装目录即可，微信是绿色软件。可以邮件发送给我，邮箱 huiyadanli@126.com

**Comment by huiyadanli** [comment]
已收到 2.7.1.65 的安装目录打包，感谢各位~
