### ISSUE TITLE
请问大佬这种纯本地修改文件的方式会有可能引起官方封号吗？

### ISSUE THREAD

**Issue by acer-xhy** [huiyadanli/RevokeMsgPatcher#123]
有没有长期使用的大佬触发过封号？

**Comment by huiyadanli** [comment]
此方式无反馈封号，个人也一直在使用。

**Comment by acer-xhy** [comment]
> 此方式无反馈封号，个人也一直在使用。
> 
> 有概率封号的大多是以下情况：
> 
> 1. 微信账号本身就有问题活动（比如：违法、营销等）
> 2. 使用dll hook的方式各类微信插件
> 3. 手机端插件（比如：Xposed持续开启抢红包插件）

收到，感谢大佬回复
