### ISSUE TITLE
微信3.0 用不了

### ISSUE THREAD

**Issue by vimingwu** [huiyadanli/RevokeMsgPatcher#125]
注意：如果出现防撤回失效的情况，请先确认以下几点再创建 issue 。

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 安全软件拦截导致的程序损坏请直接重新覆盖安装对应的应用。

更多的问题可以先看[❓常见问题](https://github.com/huiyadanli/RevokeMsgPatcher/wiki#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，或者搜索[issue列表](https://github.com/huiyadanli/RevokeMsgPatcher/issues)。

确认你的问题不在上述问题范围内，请删除本段提示文字，并提出你问题。问题中请注明你的出现问题的微信/QQ/TIM应用版本，最好能附带问题相关的截图，提供问题复现的方式。

**Comment by huiyadanli** [comment]
测试 3.0.0.47 防撤回有效。

请仔细阅读发起 issue 时的提示文档。
