### ISSUE TITLE
微信版本更新到3.0.0.47，发现插件不支持了

### ISSUE THREAD

**Issue by changshan2017** [huiyadanli/RevokeMsgPatcher#127]
Windows微信版本更新到3.0.0.47，发现本插件不支持了，
请问有支持计划吗

**Comment by huiyadanli** [comment]
我测试过是支持的，请确认以下几点

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 请使用最新0.9版本的防撤回补丁

**Comment by espandy** [comment]
> Windows微信版本更新到3.0.0.47，发现本插件不支持了，
> 请问有支持计划吗

确认微信升级后,是否重新安装了插件,我重新安装后,可以正常防撤回

**Comment by changshan2017** [comment]
确认如此，生效的
