### ISSUE TITLE
PC端聊天记录显示异常（附复现截图）

### ISSUE THREAD

**Issue by AtDoldrums** [huiyadanli/RevokeMsgPatcher#131]
![20201112_bug](https://user-images.githubusercontent.com/29479417/98888883-c8c53980-24d3-11eb-90ce-1a6ce6c9bca7.jpg)

**Comment by huiyadanli** [comment]
有无更多人测试能得到结果的。。。我个人测试没遇到这种情况。。

**Comment by safebaseline** [comment]
确实会有这个bug，就是搜索聊天记录的时候，会出现其他群的聊天记录

**Comment by safebaseline** [comment]
已收到
