### ISSUE TITLE
好像不支持最新版

### ISSUE THREAD

**Issue by luotingv1** [huiyadanli/RevokeMsgPatcher#132]
好像不支持最新版

**Comment by huiyadanli** [comment]
具体版本号是多少

**Comment by florenbai** [comment]
3.0.0.47

**Comment by huiyadanli** [comment]
@florenbai 
> 3.0.0.47

这个版本我好像测试过，没有问题

**Comment by ZeSui** [comment]
3.0.0.47
工具上显示  “当前版本：3.0.0.47（支持特征防撤回）”
但是我自己测试貌似补发看到撤回内容

**Comment by luotingv1** [comment]
> 具体版本号是多少

![image](https://user-images.githubusercontent.com/24503005/99921980-dea2ec00-2d68-11eb-939d-d6addb9c938b.png)

**Comment by luotingv1** [comment]
![image](https://user-images.githubusercontent.com/24503005/99921996-ef536200-2d68-11eb-8b50-dfd9fdb63a9c.png)

**Comment by cheechang** [comment]
最新测试版3.1.0.8打补丁失败

**Comment by JJ3322** [comment]
![image](https://user-images.githubusercontent.com/75116741/100434491-886ed980-30d7-11eb-899e-21400576dfc5.png)
没有效果

**Comment by huiyadanli** [comment]
@florenbai @ZeSui @JJ3322 
3.0.0.47 我测试过完全没有问题，请参考 #127 

---

我当前使用 3.0.0.57 测试也没有问题 @luotingv1 
PC端：
![image](https://user-images.githubusercontent.com/15783049/100492584-91f45200-3168-11eb-8119-582d955092a4.png)
手机端：
![image](https://user-images.githubusercontent.com/15783049/100492606-c962fe80-3168-11eb-8d44-1337c5763ddd.png)

---

请确认以下要点：
1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 请使用最新0.9版本的防撤回补丁

**Comment by huiyadanli** [comment]
@cheechang 暂时未收到 3.1.0.8 的版本推送，如果有安装包的话，可以提供一个，我测试下

**Comment by cheechang** [comment]
安装包下哪了？大佬知道路径吗？我这边是自动更新的。。。> @cheechang 暂时未收到 3.1.0.8 的版本推送，如果有安装包的话，可以提供一个，我测试下

**Comment by huiyadanli** [comment]
@cheechang 直接打包整个微信安装目录也行。。。正常情况下是都会支持的，现在新版本出来还没出现真正不支持的情况。。

**Comment by cheechang** [comment]
> @cheechang 直接打包整个微信安装目录也行。。。正常情况下是都会支持的，现在新版本出来还没出现真正不支持的情况。。

[https://ws28.cn/f/43htx83q8ha 密码:15498298](url)

**Comment by Albert-D** [comment]
> @cheechang 暂时未收到 3.1.0.8 的版本推送，如果有安装包的话，可以提供一个，我测试下

3.1.0.8是多开不行了，防撤回还是可以的，打补丁的时候勾选多开就会报错

**Comment by moonlune** [comment]
3.1.0 多开失效：
https://dldir1.qq.com/weixin/Windows/Beta/WeChatTest_3.1.0_Beta.exe

**Comment by huiyadanli** [comment]
@cheechang @Albert-D @moonlune 
3.1.0.151 版本已经支持  #137

**Comment by C90D** [comment]
好像又出了最新版

**Comment by veneris** [comment]
3.1.0.41 似乎不管用了，需要重新打补丁嘛

**Comment by huiyadanli** [comment]
> 3.1.0.41 似乎不管用了，需要重新打补丁嘛

测试没问题，每次更新都需要重新打补丁

**Comment by whwnow** [comment]
![image](https://user-images.githubusercontent.com/1713701/104812954-d505a400-5840-11eb-9b05-6e4ddf56d8a9.png)
刚刚自动更新了版本，已经不能安装补丁了

**Comment by whwnow** [comment]
> ![image](https://user-images.githubusercontent.com/1713701/104812954-d505a400-5840-11eb-9b05-6e4ddf56d8a9.png)
> 刚刚自动更新了版本，已经不能安装补丁了

微信又升级了，3.1.0.67 成功打了补丁

**Comment by vividmuse** [comment]
我这边qq和微信 都存在 重启后补丁失效
