### ISSUE TITLE
win10没有效果 补丁成功了

### ISSUE THREAD

**Issue by JJ3322** [huiyadanli/RevokeMsgPatcher#135]
win10没有效果 补丁成功了
![image](https://user-images.githubusercontent.com/75116741/100434720-e4396280-30d7-11eb-9fb9-342ad4f702ee.png)

**Comment by JJ3322** [comment]
![Uploading image.png…]()

**Comment by huiyadanli** [comment]
我测试过这个版本在win10防撤回没有问题

参考 #127 #132
