### ISSUE TITLE
微信最新测试版3.1.0.407无法安装补丁了

### ISSUE THREAD

**Issue by SivanWWW** [huiyadanli/RevokeMsgPatcher#136]
![Snipaste_2020-12-04_19-17-03](https://user-images.githubusercontent.com/20878096/101157575-4d375200-3665-11eb-8265-e0db5032e92d.png)
![Snipaste_2020-12-04_19-17-31](https://user-images.githubusercontent.com/20878096/101157617-5e805e80-3665-11eb-8abd-a7da935a5fa4.png)
https://dldir1.qq.com/weixin/Windows/Beta/WeChatTest_3.1.0_Beta.exe

**Comment by hannibal-dragon** [comment]
好像是多开的问题，如果只勾选防撤回，是可以正常打补丁的

**Comment by SivanWWW** [comment]
> 好像是多开的问题，如果只重置防撤回，是可以正常打补丁的

原来如此,原来是多开不兼容了  补丁已经安装了  谢啦
