### ISSUE TITLE
3.1.0 Beta提示支持，但特征不匹配

### ISSUE THREAD

**Issue by vanlin** [huiyadanli/RevokeMsgPatcher#137]
https://dldir1.qq.com/weixin/Windows/Beta/WeChatTest_3.1.0_Beta.exe

![image](https://user-images.githubusercontent.com/983627/101240138-5ccb9f00-3728-11eb-98aa-60a1728323c3.png)

**Comment by longsha911** [comment]
我的也是
版本：微信测试版3.1.0.29

**Comment by hannibal-dragon** [comment]
应该是多开的问题，如果只勾选防撤回，是可以正常打补丁的

**Comment by huiyadanli** [comment]
的确是多开的问题，更新了多开方案，现在支持了，备份还原重新打补丁即可。。

不过新的方案还要观察下，暂时只支持到3.1
