### ISSUE TITLE
可以增加pc版钉钉的防撤回吗？？？

### ISSUE THREAD

**Issue by Anurici** [huiyadanli/RevokeMsgPatcher#140]
如题，可以增加pc版钉钉的防撤回吗？？？

**Comment by huiyadanli** [comment]
#98 
防撤回的方法其实已经有了，但是会对程序有较大改造，暂不做支持。。

**Comment by Anurici** [comment]
> #98
> 防撤回的方法其实已经有了，但是会对程序有较大改造，暂不做支持。。

好的，期待支持的一天，谢谢

**Comment by zgxkbtl** [comment]
> #98 防撤回的方法其实已经有了，但是会对程序有较大改造，暂不做支持。。

请问有参考的博客吗？

**Comment by huiyadanli** [comment]
> > #98 防撤回的方法其实已经有了，但是会对程序有较大改造，暂不做支持。。
> 
> 请问有参考的博客吗？

Github 直接搜 “钉钉防撤回” 就能看到很多同类软件
