### ISSUE TITLE
对路径“...”的访问被拒绝 附图

### ISSUE THREAD

**Issue by ghnbid** [huiyadanli/RevokeMsgPatcher#143]
QQ轻聊版https://ftp.bmp.ovh/imgs/2021/01/9fc4a752ab7a098d.png

**Comment by ghnbid** [comment]
![微信截图_20210106193339](https://user-images.githubusercontent.com/77054142/103765547-4f237500-5058-11eb-9300-8312178babf6.png)

**Comment by ghnbid** [comment]
#[](url)

**Comment by ghnbid** [comment]
![Uploading 38B6B25B-147B-49EC-8B7B-A2B5D3666216.png…]()

**Comment by huiyadanli** [comment]
先关闭QQ再执行防撤回。

如果关闭了QQ还不行，这个文件就是被其他软件给占用了，看看是否是安全软件进行了拦截。

**Comment by ghnbid** [comment]
> 先关闭QQ再执行防撤回。
> 
> 如果关闭了QQ还不行，这个文件就是被其他软件给占用了，看看是否是安全软件进行了拦截。

关闭qq了，无安全软件

**Comment by huiyadanli** [comment]
那应该是这个文件没有权限

右键 IM.dll 选择属性，对所有用户设置为完全控制的权限，操作参考：

![image](https://user-images.githubusercontent.com/15783049/103967057-20161c00-519c-11eb-8de9-4acf5b592089.png)

**Comment by ghnbid** [comment]
> 那应该是这个文件没有权限
> 
> 右键IM.dll选择属性，对所有用户设置为完全控制的权限，操作参考：
> 
> ![图片](https://user-images.githubusercontent.com/15783049/103967057-20161c00-519c-11eb-8de9-4acf5b592089.png)

如图操作了，问题依旧存在。

**Comment by huiyadanli** [comment]
爱莫能助了，可能原因就两个：
1.  权限问题，软件本身无权限访问该文件，或被安全软件拦截
2.  文件占用，有其他软件或者系统占用这个文件

**Comment by ghnbid** [comment]
> 爱莫能助了，可能原因就两个：
> 
> 1. 权限问题，软件本身无权限访问该文件，或被安全软件拦截
> 2. 文件占用，有其他软件或者系统占用这个文件

好吧，多谢大佬

**Comment by Martin1224** [comment]
同样的问题，把360安全卫士和360杀毒软件退出，就安装成功了。
