### ISSUE TITLE
以安装最新版，且补丁也提示已安装，确定PC接受消息，但是没有放撤回按钮出现

### ISSUE THREAD

**Issue by lalala332** [huiyadanli/RevokeMsgPatcher#144]
![1609990555(1)](https://user-images.githubusercontent.com/63395424/103848142-ac610a00-50dc-11eb-9bba-08bcb5ddabcf.png)

**Comment by huiyadanli** [comment]
3.1.0.41 我使用的也是这个版本，测试过肯定没有问题。

你这个已经安装了，可以使用，注意显示xxx已撤回一条消息，实际还是能看到这条消息的

**Comment by lalala332** [comment]
多谢，确实能用！！！
