### ISSUE TITLE
题外问题请教：微信、TIM、QQ截图后自动放到输入框里的图片，有办法操作吗？

### ISSUE THREAD

**Issue by BruceMok** [huiyadanli/RevokeMsgPatcher#146]
![image](https://user-images.githubusercontent.com/13502521/104563718-fa4db300-5684-11eb-81e0-b7183bd3ee08.png)
例如我用TIM截图，TIM输入框就有了截图图像数据。我如何能操作这个图像呢？

**Comment by huiyadanli** [comment]
如果用的是TIM本身提供的截图功能，可能要涉及到 Hook 截图的程序对截图结果进行替换。
