### ISSUE TITLE
微信3.1.2.17不支持安装防撤回补丁

### ISSUE THREAD

**Issue by zdbss** [huiyadanli/RevokeMsgPatcher#149]
微信3.1.2.17不支持安装防撤回补丁
附微信3.1.17下载链接：https://dldir1.qq.com/weixin/Windows/Beta/WeChat3.1.2_Beta.exe
麻烦作者适配一下

**Comment by ssider** [comment]
> 微信3.1.2.17不支持安装防撤回补丁
> 附微信3.1.17下载链接：https://dldir1.qq.com/weixin/Windows/Beta/WeChat3.1.2_Beta.exe
> 麻烦作者适配一下

坐等更新

**Comment by angelmengg** [comment]
腾讯电脑管家更新，最新版微信3.1.2.19同样不支持安装防撤回补丁

**Comment by huiyadanli** [comment]
现在微信的更新速度有点小快啊。。。

**Comment by jjshijie** [comment]
> 现在微信的更新速度有点小快啊。。。

是。。 辛苦了，适配一下最新的

**Comment by yocus** [comment]
坐等适配新的Beta版微信。

**Comment by huiyadanli** [comment]
安装后发现是 3.1.3.24 ，已经支持
