### ISSUE TITLE
能说下实现原理么？

### ISSUE THREAD

**Issue by yangjiang0217** [huiyadanli/RevokeMsgPatcher#15]
我看代码好像是去一个网站上查补丁文件，然后下载下载替换？

**Comment by huiyadanli** [comment]
防撤回原理： #9 
要做到防撤回，实际就是直接编辑了dll文件里面的一个字节的内容。
核心代码：https://github.com/huiyadanli/RevokeMsgPatcher/blob/master/RevokeMsgPatcher/Util.cs 中的 EditHex 方法。

这个软件的本质就是一个十六进制的编辑器。

其余的代码都是为了让工具变的傻瓜化写的:joy:

至于从网上查的补丁信息只是为了方便更新最新的版本的修改信息（这份信息软件本身也自带，但不是最新），里面存的是修改了dll的什么位置，修改成什么字节。并没有存dll文件，下载替换的速度太慢了。

**Comment by yangjiang0217** [comment]
非常感谢作者百忙中给予的回复！^_^
