### ISSUE TITLE
Mac下的怎么改，大佬，能不能hock下啥玩意的

### ISSUE THREAD

**Issue by Ceson-L** [huiyadanli/RevokeMsgPatcher#155]
也没啥大问题，就想问下大佬，mac下的怎么改

**Comment by huiyadanli** [comment]
#119 Mac上的微信技术栈不一样，不需要像Win下那样修改二进制文件，参考：
https://github.com/MustangYM/WeChatExtension-ForMac
https://github.com/Sunnyyoung/WeChatTweak-macOS
