### ISSUE TITLE
新版失效，求更新

### ISSUE THREAD

**Issue by copperfieldd** [huiyadanli/RevokeMsgPatcher#156]
![image](https://user-images.githubusercontent.com/25824246/110918501-32f0cc80-8356-11eb-8ca8-94e2613f192f.png)

**Comment by huiyadanli** [comment]
emmmm，你获取最新的补丁信息失败了。。。
老补丁信息中的多开特征码替换已经失效

两种解决方法：
1. 多重开几次软件，直到右下角提示最新补丁信息获取成功。
2. 取消掉多开的勾选，只使用防撤回功能。
