### ISSUE TITLE
安装补丁，出现特征码匹配问题

### ISSUE THREAD

**Issue by wangxp713** [huiyadanli/RevokeMsgPatcher#159]
![image](https://user-images.githubusercontent.com/21056464/112079027-6fc08d00-8bba-11eb-9d3d-e0d9ff9c794e.png)
报错如上，以前应该是用过这个软件，安装不了 防撤回的补丁，有什么解决办法吗？备份还原也是禁用状态，也不能单独安装防撤回的补丁。

**Comment by huiyadanli** [comment]
最简单的解决方法：就是下载最新的微信安装包，然后覆盖安装，再使用防撤回补丁试试。
