### ISSUE TITLE
微信 3.2.1.154 安装失败

### ISSUE THREAD

**Issue by mofada** [huiyadanli/RevokeMsgPatcher#163]
![image](https://user-images.githubusercontent.com/22286246/115547240-a6ccb000-a2d8-11eb-95cc-da379b7307fb.png)

![image](https://user-images.githubusercontent.com/22286246/115547373-c5cb4200-a2d8-11eb-9203-70c063ff1ea3.png)

**Comment by huiyadanli** [comment]
获取最新补丁失败。。。重新启动软件等待获取成功即可

**Comment by mofada** [comment]
还是获取失败...

**Comment by huiyadanli** [comment]
那就先不勾选多开吧，我记得这个版本之前多开的特征码有问题。

**Comment by mofada** [comment]
已经可以了

![image](https://user-images.githubusercontent.com/22286246/115572440-77c33800-a2f2-11eb-9f45-656457ff77f7.png)
