### ISSUE TITLE
win10桌面版，微信 3.2.1.154 防撤回失效。当前时间为2021.04.23。 貌似防撤回在3月份上个版本就已经失效了

### ISSUE THREAD

**Issue by msh01** [huiyadanli/RevokeMsgPatcher#164]
如题

**Comment by huiyadanli** [comment]
应该没有吧。

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。

补丁无法安装的话可以参考 #163

**Comment by zhaoshijie1108** [comment]
补丁打上后现在会有问题；微信只要一打上防撤回补丁，然后打开微信登录后，就会提示网络连接错误，没有网络之类的。不安装防撤回补丁，微信就是可以正常使用。

**Comment by huiyadanli** [comment]
> 补丁打上后现在会有问题；微信只要一打上防撤回补丁，然后打开微信登录后，就会提示网络连接错误，没有网络之类的。不安装防撤回补丁，微信就是可以正常使用。

@Yue517 没有接到过类似的反馈，能具体发下微信的版本吗，我去测试下。

**Comment by bestagel** [comment]
4月26日，3.2.1.154防撤回失效。25日还正常。版本也是3.2.1.154,还原备份，重新打补丁，依旧失效。奇怪。

**Comment by h82258652** [comment]
昨天新装的PC版微信，打了补丁，扫码完登录之后，进不了主界面，重新跳回登录窗口。

**Comment by Yue517** [comment]
> > 补丁打上后现在会有问题；微信只要一打上防撤回补丁，然后打开微信登录后，就会提示网络连接错误，没有网络之类的。不安装防撤回补丁，微信就是可以正常使用。
> 
> @ Yue517没有接收过类似的反馈，能具体发下微信的版本吗，我去测试下。

是微信最新版本3.2.1.154

**Comment by Jean912** [comment]
有没有苹果手机防撤回的

**Comment by ggleo08** [comment]
微信版本3.2.1.154    PC版
已失效，望更新~~~~~~~~

**Comment by minweny** [comment]
同3.2.1.154 已失效

**Comment by msh01** [comment]
![image](https://user-images.githubusercontent.com/5895871/116666044-132c6b00-a9cd-11eb-89f2-ca055305801e.png)
各位大佬千万记得把微信的自动 给关掉

**Comment by BudSun** [comment]
2021.05.06
同微信版本3.2.1.154 PC版，Win10 20H2
测试有效

**Comment by huiyadanli** [comment]
3.2.1.154 我测试私聊群聊都能够防撤回，登录也没有问题。

Issue 暂时不关，看看有没有更多反馈。

**Comment by boganxmz** [comment]
2021.05.08
微信版本3.2.1.154 Windows版，失效

**Comment by ggleo08** [comment]
> 微信版本3.2.1.154 PC版
> 已失效，望更新~~~~~~~~

最近好像又可以了，各位重新打一下补丁试试
![image](https://user-images.githubusercontent.com/32858631/117525116-75035b00-aff3-11eb-8db6-926614a6974d.png)
![image](https://user-images.githubusercontent.com/32858631/117525139-7e8cc300-aff3-11eb-9435-48b740fbddde.png)

**Comment by minweny** [comment]
> > 微信版本3.2.1.154 PC版
> > 已失效，望更新~~~~~~~~
> 
> 最近好像又可以了，各位重新打一下补丁试试
> ![image](https://user-images.githubusercontent.com/32858631/117525116-75035b00-aff3-11eb-8db6-926614a6974d.png)
> ![image](https://user-images.githubusercontent.com/32858631/117525139-7e8cc300-aff3-11eb-9435-48b740fbddde.png)

重新安装又可以用了. 和大家讲下.
开发者辛苦~

**Comment by msh01** [comment]
重新安装下补丁，又生效了。各位遇到我这种情况可以尝试下

**Comment by ilaipi** [comment]
安装补丁 按钮是灰色不能点击的，怎么重新安装呢？

**Comment by huiyadanli** [comment]
> 安装补丁 按钮是灰色不能点击的，怎么重新安装呢？

@ilaipi 那是因为你已经安装了补丁。。重新安装要先还原再安装
