### ISSUE TITLE
QQ9.4.7测试版已无法安装补丁

### ISSUE THREAD

**Issue by SekiBetu** [huiyadanli/RevokeMsgPatcher#166]
![image](https://user-images.githubusercontent.com/38283893/116483691-2864a500-a8ba-11eb-8740-d6327cfba867.png)

特征比对：当前特征码匹配数[0]和期望的匹配数[3]不一致。
出现此种情况的一般有如下可能：
1. 你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
2. 如果当前版本为最新版本，特征码可能出现变化（可能性比较低），请联系作者处理。

https://act.qzone.qq.com/v2/vip/tx/p/1026_712c4200
https://dldir1.qq.com/qqfile/qq/PCQQ9.4.7/QQ9.4.7.27801.exe

**Comment by Beattheend** [comment]
> ![image](https://user-images.githubusercontent.com/38283893/116483691-2864a500-a8ba-11eb-8740-d6327cfba867.png)
> 
> 特征比对：当前特征码匹配数[0]和期望的匹配数[3]不一致。
> 出现此种情况的一般有如下可能：
> 
> 1. 你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
> 2. 如果当前版本为最新版本，特征码可能出现变化（可能性比较低），请联系作者处理。
> 
> https://act.qzone.qq.com/v2/vip/tx/p/1026_712c4200
> https://dldir1.qq.com/qqfile/qq/PCQQ9.4.7/QQ9.4.7.27801.exe

确实，特征码可能发生变化。

**Comment by ChenstarMr** [comment]
确实，我也安装失败

**Comment by xmhwws** [comment]
+1

**Comment by duoremi** [comment]
+1

**Comment by JIKEXIU** [comment]
+1

**Comment by huiyadanli** [comment]
已经更新支持 9.4.7.27801
