### ISSUE TITLE
QQ9.4.7.27801后面版本开始失效无法打补丁。

### ISSUE THREAD

**Issue by linhongjun** [huiyadanli/RevokeMsgPatcher#169]
重新装回QQ9.4.6.27770可以顺利打补丁

看来这是最后的可以打补丁的版本了 到目前为止

![QQ截图20210506182339](https://user-images.githubusercontent.com/16095518/117283330-42911b00-ae98-11eb-9429-6549ad9f6ca8.jpg)
![QQ截图20210506182345](https://user-images.githubusercontent.com/16095518/117283331-43c24800-ae98-11eb-9202-825c4a9ab445.jpg)

今天更新了QQ
QQ9.4.7.27801
QQ9.4.7.27805
都无法打补丁
只好装旧版了

**Comment by duoremi** [comment]
+1

**Comment by huiyadanli** [comment]
已经更新支持 9.4.7.27801 

#166
