### ISSUE TITLE
希望能增加免认证登录功能

### ISSUE THREAD

**Issue by ZQ-Qi** [huiyadanli/RevokeMsgPatcher#17]
希望可以参考mac的WechatExtension添加免认证登录功能（https://github.com/MustangYM/WeChatExtension-ForMac）

**Comment by fsnhljz** [comment]
是呀，Mac版的防撤回，免认证登录，撤回转发到手机上，这些都很好的功能啊，希望能够增加。

**Comment by LoveJessyChen** [comment]
功能不适宜添加太多，容易让整个项目被kill
