### ISSUE TITLE
撤回自己发的消息

### ISSUE THREAD

**Issue by netsonicyxf** [huiyadanli/RevokeMsgPatcher#172]
QQ9.4.7，自己发的消息撤回后，还在原地。以前用过dreamcast做的9.3.2版，自己发的可以撤回，编辑后再发出去

**Comment by huiyadanli** [comment]
9.4.7 27805 我测试没有问题

可以尝试还原后重新安装补丁，注意下是否获取到了最新的补丁信息。

**Comment by netsonicyxf** [comment]
> 9.4.7 27805 我测试没有问题
> 
> 可以尝试还原后重新安装补丁，注意下是否获取到了最新的补丁信息。
QQ 9.3.2，
发一条消息
![1WF5{4PT$U8J4A$5}R7N)TY](https://user-images.githubusercontent.com/43513391/120094681-70dedf00-c154-11eb-8f9b-151a54279d93.png)
然后撤销，还能重新编辑
![) JY6( CP_Q}{VP{ EZJD)E](https://user-images.githubusercontent.com/43513391/120094691-805e2800-c154-11eb-8c1a-836560fe0220.png)

作者的补丁也是这个效果吗？

**Comment by huiyadanli** [comment]
是的，这是原本QQ的样子，补丁不影响你本人的撤回。。

注意下，群聊如果你是管理员，撤回自己的消息，是没有重新编辑按钮的。

**Comment by Beattheend** [comment]
> 是的，这是原本QQ的样子，补丁不影响你本人的撤回。。
> 
> 注意下，群聊如果你是管理员，撤回自己的消息，是没有重新编辑按钮的。

撤回自己的消息确实没有删除，还在原地。已经尝试重新安装补丁。QQ版本 9.4.8.27840
