### ISSUE TITLE
WeChat v3.3.0.74 特征码失效，无法安装防撤回补丁，

### ISSUE THREAD

**Issue by taotieren** [huiyadanli/RevokeMsgPatcher#174]
![image](https://user-images.githubusercontent.com/13965460/120730677-9aad5280-c514-11eb-9084-cae306605885.png)

**Comment by taotieren** [comment]
![image](https://user-images.githubusercontent.com/13965460/120731011-46ef3900-c515-11eb-88ea-f0a68cdec10a.png)
使用 [Actions](https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/882705299)  编译的版本也不行。

**Comment by taotieren** [comment]
![image](https://user-images.githubusercontent.com/13965460/120731366-13f97500-c516-11eb-8c3d-d700d9789c4b.png)
并没有参与 微信内测，今天开机突然变成内测版本？？？这是微信的新套路吗？

**Comment by huiyadanli** [comment]
获取最新补丁信息失败了。。。成功获取到最新补丁信息后重试就行了

**Comment by taotieren** [comment]
> 获取最新补丁信息失败了。。。成功获取到最新补丁信息后重试就行了

是 Windows 10 的网络出问题了，重置后正常。

<kbd>Win</kbd> + <kbd>X</kbd> A <kbd>X</kbd>  选择管理员身份运行 `cmd` 或  `PowerShell`
```bash
netsh winsock reset
```
