### ISSUE TITLE
安装好了，微信没显示撤回消息，

### ISSUE THREAD

**Issue by Williamlizl** [huiyadanli/RevokeMsgPatcher#175]
1.退出微信
2.下载，解压缩，RevokeMsgPatcher.exe 管理员运行
3. 无操作，显示界面如下图界面
![6_4_2](https://user-images.githubusercontent.com/24259779/120767800-21325600-c54e-11eb-8e89-0f2dca3474e9.png)

4. 打开微信，发现未显示撤回的消息
![6_4](https://user-images.githubusercontent.com/24259779/120767893-3a3b0700-c54e-11eb-8690-110bd73cbdac.png)

**Comment by Williamlizl** [comment]
解决了，更新版本了

**Comment by huiyadanli** [comment]
看了最近的一些反馈，发现有些时候软件获取最新补丁信息后，没有进行应用。

最新版本内置了最新的补丁信息，可以表面解决这个问题。。

**Comment by HsinLX** [comment]
> 看了最近的一些反馈，发现有些时候软件获取最新补丁信息后，没有进行应用。
> 
> 最新版本内置了最新的补丁信息，可以表面解决这个问题。。

好像最新的3.3.0.84版又不能用了？装了之后消息还是被撤回了

**Comment by lilaizheng** [comment]
> 解决了，更新版本了

![image](https://user-images.githubusercontent.com/40649941/131252602-ff92e3ae-18b0-4f32-8f33-c31cdeb351bd.png)
3.3.5.50 防撤回特征也有没有 提示
