### ISSUE TITLE
代码更新了，编译版本也更新一下啊？

### ISSUE THREAD

**Issue by arsenalpoll** [huiyadanli/RevokeMsgPatcher#176]
或者作者你写个编译过程，我们自己打包也行啊。

**Comment by huiyadanli** [comment]
因为没啥功能性更新，所以一直没编译发布新版本。

Actions 中可以获取到最新的软件编译版本。

比如最新的提交：
https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/906887033

Artifacts 下可以下载最新编译版本
https://github.com/huiyadanli/RevokeMsgPatcher/suites/2912684343/artifacts/65353813

**Comment by huiyadanli** [comment]
[1.0](https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.0) 版本也已经发布
