### ISSUE TITLE
0.9版本微信出现的两个问题

### ISSUE THREAD

**Issue by 961120** [huiyadanli/RevokeMsgPatcher#182]
1、微信接收的图片会只显示部分或者花屏
2、微信内的文件打开时会受到360的风险提示（附的截图是edge浏览器触发的，当时已经做了微信和QQ的备份还原，且0.9版本已删入回收站）
![d2ad63611ea91a51aca81addc1babd1](https://user-images.githubusercontent.com/85940528/122052212-05fdfb00-ce18-11eb-92b4-2af6bca17418.jpg)
![微信图片_20210615202257](https://user-images.githubusercontent.com/85940528/122052254-12825380-ce18-11eb-841c-775f6972d22f.png)
![微信图片_202106152022571](https://user-images.githubusercontent.com/85940528/122052258-13b38080-ce18-11eb-82b0-8b49cc38b87d.png)

**Comment by huiyadanli** [comment]
1. 花屏这种情况暂时没遇到过。暂放 issue 看看有没有更多遇到相同情况的人，或者稳定的复现方式。
2. 这个提示有点意思，从edge本体触发，然后目标是Identity_Helper.exe（查资料是跟PWA有关），风险程序是微信接收的一个文件，远程注入也和补丁的操作风险提示不一样。**如果你没有启动补丁程序请阻止这个操作**，因为补丁程序不启动不可能会有任何操作。打完补丁后也不需要再次启动补丁程序。

**Comment by 961120** [comment]
> 1. 花屏这种情况暂时没遇到过。暂放 issue 看看有没有更多遇到相同情况的人，或者稳定的复现方式。
> 2. 这个提示有点意思，从edge本体触发，然后目标是Identity_Helper.exe（查资料是跟PWA有关），风险程序是微信接收的一个文件，远程注入也和补丁的操作风险提示不一样。**如果你没有启动补丁程序请阻止这个操作**，因为补丁程序不启动不可能会有任何操作。打完补丁后也不需要再次启动补丁程序。

**Comment by 961120** [comment]
每次从微信打开接收的文件都会有这个提示，是阻止还是允许啊
![微信截图_20210617120131](https://user-images.githubusercontent.com/85940528/122329416-f8558c00-cf63-11eb-8066-eb7f013ce339.png)

**Comment by huiyadanli** [comment]
> 每次从微信打开接收的文件都会有这个提示，是阻止还是允许啊
> ![微信截图_20210617120131](https://user-images.githubusercontent.com/85940528/122329416-f8558c00-cf63-11eb-8066-eb7f013ce339.png)

这个无所谓的吧，是wps在修改文件关联，阻止放行随意。在wps里面修改一些自动检查文件关联相关的设置，应该就不会再弹出这种警告了

**Comment by 961120** [comment]
没找到相关的设置，顺便反馈一下，1.0版本还存在图片不全的问题
![微信图片_20210617174408](https://user-images.githubusercontent.com/85940528/122373418-0cb17d00-cf94-11eb-874f-67e04016b0f5.jpg)

**Comment by BoxuanZng** [comment]
Ver. 1.0启动QQ时，QQ黑屏，微信没问题。
怎么解决？🙏🙏🙏

**Comment by 961120** [comment]
> Ver. 1.0启动QQ时，QQ黑屏，微信没问题。
> 怎么解决？🙏🙏🙏



我QQ目前没有出现你说的这种情况

**Comment by huiyadanli** [comment]
> Ver. 1.0启动QQ时，QQ黑屏，微信没问题。
> 怎么解决？🙏🙏🙏

跟补丁无关，请确认是否是使用的第三方修改过的版本

**Comment by BoxuanZng** [comment]
> > Ver. 1.0启动QQ时，QQ黑屏，微信没问题。
> > 怎么解决？🙏🙏🙏
> 
> 跟补丁无关，请确认是否是使用的第三方修改过的版本

不是

**Comment by letusbiu** [comment]
我这里是微信聊天图片全部加载失败，包括他人头像，点开也是加载失败
