### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by YeomanYe** [huiyadanli/RevokeMsgPatcher#185]
非常感谢您提供的这个工具，它对于我来说非常有用。然而我觉得有些不完美的地方，我想提出一些建议，希望您不要介意我不知天高地厚的想法。

隔壁的mac版虽然只支持微信，但是提供了更多的功能。其中我觉得：
- 退群监控
- 免认证登陆

非常的有用，是否可以考虑再后续的版本加上，再三拜托了🙏🏻🙏🏻🙏🏻

https://github.com/MustangYM/WeChatExtension-ForMac

**Comment by huiyadanli** [comment]
当前使用的补丁形式暂时做不到这两点

win下的方案还是有区别的。

**Comment by YeomanYe** [comment]
> 当前使用的补丁形式暂时做不到这两点
> 
> win下的方案还是有区别的。

好的😁
