### ISSUE TITLE
最新新版本防撤回点开提示初始值设定项引发异常

### ISSUE THREAD

**Issue by SK1ngslayer** [huiyadanli/RevokeMsgPatcher#189]
顺带问问怎么上传截图

**Comment by huiyadanli** [comment]
截图后直接粘贴就行了

**Comment by SK1ngslayer** [comment]
![image](https://user-images.githubusercontent.com/87061264/124736017-2ddd0c00-df49-11eb-8612-a4654f2450e3.png)

**Comment by huiyadanli** [comment]
是[release](https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.0)页面下载的版本还是[action](https://github.com/huiyadanli/RevokeMsgPatcher/actions)中下载的版本?

**Comment by SK1ngslayer** [comment]
![image](https://user-images.githubusercontent.com/87061264/124738308-5ebe4080-df4b-11eb-8bd1-dfe52fa6c557.png)
在这下载的

**Comment by huiyadanli** [comment]
弹出这个提示后，后续还能打补丁不？还是程序直接退出了。

**Comment by SK1ngslayer** [comment]
点了确定就直接退出程序了

**Comment by huiyadanli** [comment]
1. 先确认电脑上有 [.NET Framework 4.5](https://www.microsoft.com/zh-cn/download/details.aspx?id=30653) 或更高版本，没有的话安装一个就能解决了
2. 提供下操作系统版本，还有是x32的还是x64的？

**Comment by xzf520** [comment]
![image](https://user-images.githubusercontent.com/34847828/124785925-dc994080-df79-11eb-87b3-c7a658d6ec4a.png)
微信3.3.0.93防撤回失败,

**Comment by xzf520** [comment]
升级后可以了

**Comment by SK1ngslayer** [comment]
![image](https://user-images.githubusercontent.com/87061264/124874554-7274b000-dffa-11eb-924d-1a1267de1eea.png)
![image](https://user-images.githubusercontent.com/87061264/124874649-8cae8e00-dffa-11eb-81b0-dff6e841b501.png)

**Comment by SK1ngslayer** [comment]
Win 10系统

**Comment by huiyadanli** [comment]
看了下我编译的版本也是  .NET Framework 4.5 。换成0.9版本试试能不能正常打开。或者试试安装一个最新版本的 .NET Framework
