### ISSUE TITLE
WIN11 一直提示目录访问没有权限

### ISSUE THREAD

**Issue by kxshu** [huiyadanli/RevokeMsgPatcher#191]
报错如图：
![image](https://user-images.githubusercontent.com/2977440/124916151-ed52c080-e024-11eb-92bd-298f7ee01feb.png)

系统：
![image](https://user-images.githubusercontent.com/2977440/124916218-00659080-e025-11eb-834d-fe1a148266b0.png)

已经 Run as administrator，也重新下载了软件包（RevokeMsgPatcher的包），反复操作几次，仍然提示这个。

建议能单独另存dll文件，用户可以选择手动覆盖。

**Comment by huiyadanli** [comment]
我全新安装了Win11，并把微信安装到了C盘，也没复现这个问题。

不过这个明显是文件夹权限的问题，可以看下当前管理员用户权限是否拥有能够操作WeChat目录下的权限。

![image](https://user-images.githubusercontent.com/15783049/124950413-f8b5e400-e044-11eb-8335-13502f0c1fd2.png)

对应的dll文件我先发你，你尝试覆盖试试。

[WeChatWin.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/6785720/WeChatWin.zip)

**Comment by kxshu** [comment]
感谢大哥，我刚刚试了用Windows Terminal进入到目录，mkdir确实提示没有权限，必须要sudo 才行。
但是，既然sudo可以的话，就意味着Run as administrator 也可行吧？
