### ISSUE TITLE
更新3.3.0以后即使重新安装也不能防撤回和多开

### ISSUE THREAD

**Issue by MicroGalaxy** [huiyadanli/RevokeMsgPatcher#192]
更新3.3.0.115以后即使重新安装也不能防撤回和多开

**Comment by huiyadanli** [comment]
请使用最新的[1.0版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.0)

**Comment by MicroGalaxy** [comment]
目前下载的就是6月6日发布的1.0

**Comment by huiyadanli** [comment]
不可能呀，我测试安装后可以正常防撤回

**Comment by MicroGalaxy** [comment]
![image](https://user-images.githubusercontent.com/9451732/125014759-dce02b80-e0a0-11eb-8d13-385f5762101b.png)
有日志可以排查哪里出错了吗

**Comment by huiyadanli** [comment]
3.3.0.104 这个版本是从官方地址下载并安装的吗？地址： https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe 

你启动的微信是不是在这个上面显示的路径？

**Comment by MicroGalaxy** [comment]
找到问题了，你说得对，系统里面有两个位置的微信，谢谢，不过以前一直是可以的，我刚刚才发现路径有问题
