### ISSUE TITLE
刚被禁止登录了...

### ISSUE THREAD

**Issue by ArchangelXu** [huiyadanli/RevokeMsgPatcher#196]
理由是疑似使用第三方软件...有没有一样的？

**Comment by skinnyshy** [comment]
同样，由于也用了mac版小助手，现在还不确定是哪个，保险起见先都卸载了。。

**Comment by ArchangelXu** [comment]
@skinnyshy 看了下大概率是mac版的问题，那边提issue的人很多

**Comment by skinnyshy** [comment]
> @skinnyshy 看了下大概率是mac版的问题，那边提issue的人很多

我两个微信号只有一个提示，就是用过僵尸粉检测功能的那个。看issue里有人没有用这个功能也提示违反规定了。请问你也用过mac版本的小工具吗

**Comment by wenwenwen888** [comment]
同

**Comment by huiyadanli** [comment]
mac 下尽量不要使用 WeChatExtension-ForMac，

参考：
https://github.com/MustangYM/WeChatExtension-ForMac/issues/1127
https://github.com/MustangYM/WeChatExtension-ForMac/issues/1130
https://github.com/MustangYM/WeChatExtension-ForMac/issues/1128
https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/289

---

只要不要做太过分的越界行为，腾讯甚至会帮你修漏洞
https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398

---

如果哪天 RevokeMsgPatcher 被针对，我猜测提示也应该是微信已损坏而不是封号。。。

**Comment by tikdoge** [comment]
> 可能是 WeChatExtension-ForMac 的问题，
> 
> 参考：
> [MustangYM/WeChatExtension-ForMac#1127](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1127)
> [MustangYM/WeChatExtension-ForMac#1128](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1128)
> [MustangYM/WeChatExtension-ForMac#1130](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1130)
> [Sunnyyoung/WeChatTweak-macOS#289](https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/289)
> 
> 只要不要做太过分的越界行为，腾讯甚至会帮你修漏洞
> https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398
> 
> 如果哪天 RevokeMsgPatcher 被针对，我猜测提示也应该是微信已损坏而不是封号。。。

目前基本都是Mac端的微信插件，且使用了那些乱七八糟的功能，包括不限于清理僵尸、改皮肤等等一些不该用的功能，且版本大概率都是3.xx一下版本。最后还是提醒大家用用常用的防撤回和双开就好了（一般也不会超过3个微信吧，不建议开n个），不要去使用那些不该用的功能。反正自己抉择

**Comment by fangmingc** [comment]
> > 可能是 WeChatExtension-ForMac 的问题，
> > 参考：
> > [MustangYM/WeChatExtension-ForMac#1127](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1127)
> > [MustangYM/WeChatExtension-ForMac#1128](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1128)
> > [MustangYM/WeChatExtension-ForMac#1130](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1130)
> > [Sunnyyoung/WeChatTweak-macOS#289](https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/289)
> > 只要不要做太过分的越界行为，腾讯甚至会帮你修漏洞
> > https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398
> > 如果哪天 RevokeMsgPatcher 被针对，我猜测提示也应该是微信已损坏而不是封号。。。
> 
> 目前基本都是Mac端的微信插件，且使用了那些乱七八糟的功能，包括不限于清理僵尸、改皮肤等等一些不该用的功能，且版本大概率都是3.xx一下版本。最后还是提醒大家用用常用的防撤回和双开就好了（一般也不会超过3个微信吧，不建议开n个），不要去使用那些不该用的功能。反正自己抉择

只是用了防撤回，甚至多开都没用，其他的功能一个没用，照样被封

**Comment by ArchangelXu** [comment]
> > > 可能是 WeChatExtension-ForMac 的问题，
> > > 参考：
> > > [MustangYM/WeChatExtension-ForMac#1127](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1127)
> > > [MustangYM/WeChatExtension-ForMac#1128](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1128)
> > > [MustangYM/WeChatExtension-ForMac#1130](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1130)
> > > [Sunnyyoung/WeChatTweak-macOS#289](https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/289)
> > > 只要不要做太过分的越界行为，腾讯甚至会帮你修漏洞
> > > https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398
> > > 如果哪天 RevokeMsgPatcher 被针对，我猜测提示也应该是微信已损坏而不是封号。。。
> > 
> > 
> > 目前基本都是Mac端的微信插件，且使用了那些乱七八糟的功能，包括不限于清理僵尸、改皮肤等等一些不该用的功能，且版本大概率都是3.xx一下版本。最后还是提醒大家用用常用的防撤回和双开就好了（一般也不会超过3个微信吧，不建议开n个），不要去使用那些不该用的功能。反正自己抉择
> 
> 只是用了防撤回，甚至多开都没用，其他的功能一个没用，照样被封

我也是，只用了防撤回而已

**Comment by wenwenwen888** [comment]
俺也一样



发自我的小米手机
在 MK ***@***.***>，2021年7月15日 11:41写道：

可能是 WeChatExtension-ForMac 的问题，
参考：
MustangYM/WeChatExtension-ForMac#1127<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMustangYM%2FWeChatExtension-ForMac%2Fissues%2F1127&data=04%7C01%7C%7C3ee51b07b4bd463caec108d947426180%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619172686254120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u9QKmfAfL60ORrZTvJtVYMvzT0bs27jrwnELawDh4Xk%3D&reserved=0>
MustangYM/WeChatExtension-ForMac#1128<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMustangYM%2FWeChatExtension-ForMac%2Fissues%2F1128&data=04%7C01%7C%7C3ee51b07b4bd463caec108d947426180%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619172686264079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jhXWfY2pIPvGndkcte%2B2rLuOL65gzw4OhKApN0w0mck%3D&reserved=0>
MustangYM/WeChatExtension-ForMac#1130<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMustangYM%2FWeChatExtension-ForMac%2Fissues%2F1130&data=04%7C01%7C%7C3ee51b07b4bd463caec108d947426180%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619172686274033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aNvQK%2BrubCckh7vXVBdAHJwDMMH2T3b7Wf2wyd0aPDs%3D&reserved=0>
Sunnyyoung/WeChatTweak-macOS#289<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSunnyyoung%2FWeChatTweak-macOS%2Fissues%2F289&data=04%7C01%7C%7C3ee51b07b4bd463caec108d947426180%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619172686274033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NSHN0dX7WogwP%2BLmm5Cl065LUuTqvy0R7MdIuHPb3r0%3D&reserved=0>
只要不要做太过分的越界行为，腾讯甚至会帮你修漏洞
https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxlab.tencent.com%2Fcn%2F2018%2F10%2F23%2Fweixin-cheater-risks%2F%23more-398&data=04%7C01%7C%7C3ee51b07b4bd463caec108d947426180%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637619172686283989%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sDamlXNw5V4tx4WaDRU9HiEnYaboXhlZuknM%2BeuLMOI%3D&reserved=0>
如果哪天 RevokeMsgPatcher 被针对，我猜测提示也应该是微信已损坏而不是封号。。。

目前基本都是Mac端的微信插件，且使用了那些乱七八糟的功能，包括不限于清理僵尸、改皮肤等等一些不该用的功能，且版本大概率都是3.xx一下版本。最后还是提醒大家用用常用的防撤回和双开就好了（一般也不会超过3个微信吧，不建议开n个），不要去使用那些不该用的功能。反正自己抉择

只是用了防撤回，甚至多开都没用，其他的功能一个没用，照样被封

我也是，只用了防撤回而已

**Comment by popokcn** [comment]
> > > > 可能是 WeChatExtension-ForMac 的问题，
> > > > 参考：
> > > > [MustangYM/WeChatExtension-ForMac#1127](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1127)
> > > > [MustangYM/WeChatExtension-ForMac#1128](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1128)
> > > > [MustangYM/WeChatExtension-ForMac#1130](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1130)
> > > > [Sunnyyoung/WeChatTweak-macOS#289](https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/289)
> > > > 只要不要做太过分的越界行为，腾讯甚至会帮你修漏洞
> > > > https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398
> > > > 如果哪天 RevokeMsgPatcher 被针对，我猜测提示也应该是微信已损坏而不是封号。。。
> > > 
> > > 
> > > 目前基本都是Mac端的微信插件，且使用了那些乱七八糟的功能，包括不限于清理僵尸、改皮肤等等一些不该用的功能，且版本大概率都是3.xx一下版本。最后还是提醒大家用用常用的防撤回和双开就好了（一般也不会超过3个微信吧，不建议开n个），不要去使用那些不该用的功能。反正自己抉择
> > 
> > 
> > 只是用了防撤回，甚至多开都没用，其他的功能一个没用，照样被封
> 
> 我也是，只用了防撤回而已

只要你用了那个插件，不管你开了哪些功能。都容易被检测。
答主说的是只用本项目这种功能很简单的

**Comment by leoxu1007** [comment]
我是Windows版，只用了防撤回，双开都没有，也被封了
![DRQ)6NQ 5)Q8W3JR7G1K`O4](https://user-images.githubusercontent.com/22413258/125969256-22e660b3-edf4-4ecc-93f9-e0c6e96e0e98.jpg)

**Comment by leoxu1007** [comment]
我是Windows版，只用了防撤回，双开都没有，就被封了
![image](https://user-images.githubusercontent.com/22413258/125969498-7d5eeca6-a2f5-496e-9cf1-7018748470fa.png)

**Comment by ArchangelXu** [comment]
@leoxu1007 只用了windows版没用mac版？
