### ISSUE TITLE
售卖，制作，使用非官方软件，插件等微信外挂工具，可能对用户或微信造成不利影响

### ISSUE THREAD

**Issue by leoxu1007** [huiyadanli/RevokeMsgPatcher#197]
![image](https://user-images.githubusercontent.com/22413258/125969638-9aa8a38c-f2ce-42e8-8872-cba1e757ef6e.png)

**Comment by huiyadanli** [comment]
请先确认是否使用了Mac版本的防撤回，或者手机上的防撤回插件

**Comment by ilaipi** [comment]
我之前先卸载了mac版的，过了几天仍然有这个提示。想起来Windows上也装了，最好都卸载了

**Comment by yumengbdw** [comment]
猜想是撤回消息发给自己导致的

**Comment by leoxu1007** [comment]
> 请先确认是否使用了Mac版本的防撤回，或者手机上的防撤回插件

没有，我只装了Windows的，不过现在已经卸载了

**Comment by geTiger** [comment]
> > 请先确认是否使用了Mac版本的防撤回，或者手机上的防撤回插件
> 
> 没有，我只装了Windows的，不过现在已经卸载了

封号没？只是提醒了一下吗?

**Comment by Amwidtf** [comment]
应该是被人举报了吧？一般腾讯都是有人举报才会管。。。正常不会特别管的=-=
