### ISSUE TITLE
3.3.5.11版本特征值不一致，无法安装补丁。

### ISSUE THREAD

**Issue by FioonYuLoo** [huiyadanli/RevokeMsgPatcher#199]
![Snipaste_2021-07-21_14-02-41](https://user-images.githubusercontent.com/44015601/126439254-6df1717a-bed0-40a2-8c98-dc982fc77c0f.png)

**Comment by uvips** [comment]
我也反馈了，自己先手动改下吧，就是没防撤回提示

**Comment by changshan2017** [comment]
![image](https://user-images.githubusercontent.com/26756420/126856500-d7789f6b-5340-423c-83d0-6c7da9d449b9.png)

**Comment by huiyadanli** [comment]
没有这个版本的安装包，能提供一个不？或者安装当前官方的正式版吧。

**Comment by uvips** [comment]
> 没有这个版本的安装包，能提供一个不？或者安装当前官方的正式版吧。

我用阿里云盘分享了「WeChat3.3.5.15.exe」，你可以不限速下载
复制这段内容打开「阿里云盘」App 即可获取
链接：https://www.aliyundrive.com/s/tK8UGXCNmDJ

**Comment by huiyadanli** [comment]
> > 没有这个版本的安装包，能提供一个不？或者安装当前官方的正式版吧。
> 
> 我用阿里云盘分享了「WeChat3.3.5.15.exe」，你可以不限速下载
> 复制这段内容打开「阿里云盘」App 即可获取
> 链接：https://www.aliyundrive.com/s/tK8UGXCNmDJ

3.3.5.15 已经用了以前的方法支持了 #200

**Comment by uvips** [comment]
> > > 没有这个版本的安装包，能提供一个不？或者安装当前官方的正式版吧。
> > 
> > 
> > 我用阿里云盘分享了「WeChat3.3.5.15.exe」，你可以不限速下载
> > 复制这段内容打开「阿里云盘」App 即可获取
> > 链接：https://www.aliyundrive.com/s/tK8UGXCNmDJ
> 
> 3.3.5.15 已经用了以前的方法支持了 #200

可以了，只是没防撤回提示了

**Comment by motivatedloo** [comment]
> > > 没有这个版本的安装包，能提供一个不？或者安装当前官方的正式版吧。
> > 
> > 
> > 我用阿里云盘分享了「WeChat3.3.5.15.exe」，你可以不限速下载
> > 复制这段内容打开「阿里云盘」App 即可获取
> > 链接：https://www.aliyundrive.com/s/tK8UGXCNmDJ
> 
> 3.3.5.15 已经用了以前的方法支持了 #200

谢谢，我也更新到15了。下次再也不更新测试版了。

**Comment by MarkLily** [comment]
> 我也反馈了，自己先手动改下吧，就是没防撤回提示

求大佬 教一下怎么改？跪谢

**Comment by uvips** [comment]
> > 我也反馈了，自己先手动改下吧，就是没防撤回提示
> 
> 求大佬 教一下怎么改？跪谢
微信防撤回与多开教程 · huiyadanli/RevokeMsgPatcher Wiki
https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E5%BE%AE%E4%BF%A1%E9%98%B2%E6%92%A4%E5%9B%9E%E4%B8%8E%E5%A4%9A%E5%BC%80%E6%95%99%E7%A8%8B

**Comment by MarkLily** [comment]
666




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月30日(星期五) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huiyadanli/RevokeMsgPatcher] 3.3.5.11版本特征值不一致，无法安装补丁。 (#199)





   
我也反馈了，自己先手动改下吧，就是没防撤回提示
  
求大佬 教一下怎么改？跪谢
 微信防撤回与多开教程 · huiyadanli/RevokeMsgPatcher Wiki
 https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E5%BE%AE%E4%BF%A1%E9%98%B2%E6%92%A4%E5%9B%9E%E4%B8%8E%E5%A4%9A%E5%BC%80%E6%95%99%E7%A8%8B
