### ISSUE TITLE
消息撤回标记提醒

### ISSUE THREAD

**Issue by shxian** [huiyadanli/RevokeMsgPatcher#2]
被撤回的消息木有标记，无法知道哪些消息是被撤回的，是否可以考虑优化？

**Comment by karlxu11** [comment]
+1

**Comment by huiyadanli** [comment]
以现在这种修改方式实现的防撤回，没法做到这一点:joy:

**Comment by MelloChan** [comment]
只能手机PC同时开着了。

**Comment by mx4994** [comment]
> 以现在这种修改方式实现的防撤回，没法做到这一点😂

之前有在吾爱论坛看到过。https://www.52pojie.cn/thread-958024-1-1.html
