### ISSUE TITLE
微信PC版无法登录

### ISSUE THREAD

**Issue by maiohaha** [huiyadanli/RevokeMsgPatcher#20]
win10（1903）
2019年10月9日
版本2.7.1.65（直接微信内更新）

使用补丁后无法登录

**Comment by huiyadanli** [comment]
先还原试试能不能登录

**Comment by maiohaha** [comment]
> 先还原试试能不能登录

还原当然可以呀，希望能更新版本

**Comment by huiyadanli** [comment]
@maiohaha 能提供下 WeChatWin.dll 文件吗？通过这个文件我可以判断具体问题。2.7.1.65有人测试过应该是没问题的。
