### ISSUE TITLE
3.3.5.15特征码匹配失败

### ISSUE THREAD

**Issue by XY2336661** [huiyadanli/RevokeMsgPatcher#200]
![MEX}5ITHD~H~_B2O~ET}JNU](https://user-images.githubusercontent.com/62127199/126633729-a68e69b3-d516-438e-af94-483102f7750a.png)

**Comment by huiyadanli** [comment]
最近测试版本的特征总是有变化，到正式版本又恢复原样，暂时不做支持

**Comment by motivatedloo** [comment]
> 最近测试版本的特征总是有变化，到正式版本又恢复原样，暂时不做支持

明白了，我再也不更测试版了。

**Comment by XY2336661** [comment]
原来如此，可微信是自动升级到测试版的，真离谱

**Comment by moke233** [comment]
我也是自动升级的···一开微信就要管理员权限

**Comment by huiyadanli** [comment]
用了老的方法（非特征码）专门对这个版本做了下支持，且撤回提示不显示。

**Comment by moke233** [comment]
> 用了老的方法（非特征码）对版本的这个现在支持，而且撤回提示不显示。
我因为需要把多开选项给勾上了，现在打补丁提示要取消勾选多开，可是没有选项···
![QQ截图20210726193542](https://user-images.githubusercontent.com/58896274/126982679-9cfe5f9d-9d75-4b2e-8244-4a0e9182bece.png)

**Comment by moke233** [comment]
> > 用了老的方法（非特征码）对版本的这个现在支持，而且撤回提示不显示。
> > 我因为需要把多开选项给勾上了，现在打补丁提示要取消勾选多开，可是没有选项···
> > ![QQ截图20210726193542](https://user-images.githubusercontent.com/58896274/126982679-9cfe5f9d-9d75-4b2e-8244-4a0e9182bece.png)

我点了备份还原，现在好了

**Comment by huiyadanli** [comment]
> > > 用了老的方法（非特征码）对版本的这个现在支持，而且撤回提示不显示。
> > > 我因为需要把多开选项给勾上了，现在打补丁提示要取消勾选多开，可是没有选项···
> > > ![QQ截图20210726193542](https://user-images.githubusercontent.com/58896274/126982679-9cfe5f9d-9d75-4b2e-8244-4a0e9182bece.png)
> 
> 我点了备份还原，现在好了

是的，如果以前只打了多开补丁，要先还原再重新安装
