### ISSUE TITLE
3.3.5.22无法安装补丁，当前版本为最新版，特征码出现变化，请联系作者

### ISSUE THREAD

**Issue by sinscythee** [huiyadanli/RevokeMsgPatcher#201]
![image](https://user-images.githubusercontent.com/36703531/127172554-ef691491-bd7f-4f64-903a-5acaeaeab19a.png)
- [ ] 注意：如果出现防撤回失效的情况，请先确认以下几点再创建 issue 。

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 安全软件拦截导致的程序损坏请直接重新覆盖安装对应的应用。

更多的问题可以先看[❓常见问题](https://github.com/huiyadanli/RevokeMsgPatcher/wiki#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，或者搜索[issue列表](https://github.com/huiyadanli/RevokeMsgPatcher/issues)。

确认你的问题不在上述问题范围内，请删除本段提示文字，并提出你问题。问题中请注明你的出现问题的微信/QQ/TIM应用版本，最好能附带问题相关的截图，提供问题复现的方式。

**Comment by uvips** [comment]
等正式版了再催更吧，测试版先自己手动下

**Comment by huiyadanli** [comment]
能提供一个 3.3.5.22 的安装包吗？我的 3.3.5.15 并不能自动更新到这个版本

**Comment by sinscythee** [comment]
好的谢谢，我在微信的关于里面更新了，我还以为是正式版的微信，2333，他也没标注

uvips ***@***.***>于2021年7月28日 周三10:24写道：

**Comment by uvips** [comment]
> 能提供一个 3.3.5.22 的安装包吗？我的 3.3.5.15 并不能自动更新到这个版本

https://www.aliyundrive.com/s/yFqUPwLv7Bn

**Comment by uvips** [comment]
> 能提供一个 3.3.5.22 的安装包吗？我的 3.3.5.15 并不能自动更新到这个版本

又更新了，最新是3.3.5.25   https://www.aliyundrive.com/s/7QHJ9BuYkFh

**Comment by huiyadanli** [comment]
已支持
