### ISSUE TITLE
特征码失效，版本3.3.5.25

### ISSUE THREAD

**Issue by Continueder** [huiyadanli/RevokeMsgPatcher#202]
![image](https://user-images.githubusercontent.com/17880698/127453737-7f818f03-b109-48f0-aa31-0c3b7aeab93c.png)

**Comment by JRGavin** [comment]
![1627545659(1)](https://user-images.githubusercontent.com/18720222/127454622-1858010a-a10f-4dfe-bcd9-1f538edd1dcd.png)

手贱更新了，现在没法防撤回了。是微信的测试版3.3.5.25

**Comment by Continueder** [comment]
是的，手贱点了更新

**Comment by huiyadanli** [comment]
已支持

**Comment by JRGavin** [comment]
> 已支持

大佬牛逼

**Comment by 1058745043** [comment]
> 已支持

3.35.30也不支持。。。

**Comment by huiyadanli** [comment]
> > 已支持
> 
> 3.35.30也不支持。。。

有安装包不？

**Comment by Continueder** [comment]
感谢

**Comment by lonee6** [comment]
升级真快，又3.35.30了。

**Comment by MarkLily** [comment]
3.35.30了  这测试版 更新速度确实快 一两天就一次升级

**Comment by uvips** [comment]
> > > 已支持
> > 
> > 
> > 3.35.30也不支持。。。
> 
> 有安装包不？

https://www.aliyundrive.com/s/uHQETica6SY  我现在都自己改，测试版更新太快了，只是没那个防撤回提示

**Comment by huiyadanli** [comment]
@uvips 感谢你的安装包。已经升级了软件版本，3.35.30+ 也已经使用了特征码防撤回
