### ISSUE TITLE
3.3.5.30还是不支持防撤回

### ISSUE THREAD

**Issue by lyhrtb** [huiyadanli/RevokeMsgPatcher#204]
注意：如果出现防撤回失效的情况，请先确认以下几点再创建 issue 。

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 安全软件拦截导致的程序损坏请直接重新覆盖安装对应的应用。

更多的问题可以先看[❓常见问题](https://github.com/huiyadanli/RevokeMsgPatcher/wiki#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，或者搜索[issue列表](https://github.com/huiyadanli/RevokeMsgPatcher/issues)。

确认你的问题不在上述问题范围内，请删除本段提示文字，并提出你问题。问题中请注明你的出现问题的微信/QQ/TIM应用版本，最好能附带问题相关的截图，提供问题复现的方式。

**Comment by Coresi7** [comment]
读了代码发现3.3.5这几个版本都是作者手动修改的对应位置的hex
作者考虑做那种类似于特征匹配的方式嘛？针对这些版本？

**Comment by huiyadanli** [comment]
> 读了代码发现3.3.5这几个版本都是作者手动修改的对应位置的hex
> 作者考虑做那种类似于特征匹配的方式嘛？针对这些版本？

特征匹配的替换功能还不完全支持本次特征的情况，有时间我改造下这块功能。

没想到部分用户正式版会升级到测试版，然后测试版更新这么频繁。。

**Comment by Coresi7** [comment]
> > 读了代码发现3.3.5这几个版本都是作者手动修改的对应位置的hex
> > 作者考虑做那种类似于特征匹配的方式嘛？针对这些版本？
> 
> 特征匹配的替换功能还不完全支持本次特征的情况，有时间我改造下这块功能。
> 
> 没想到部分用户正式版会升级到测试版，然后测试版更新这么频繁。。


确实……可能微信灰度了一些测试版给大家了，点自动更新就更新到测试版了。

**Comment by moke233** [comment]
刚刚一点开微信又给我自动更新，然后防撤回又失效了···

**Comment by MinanaYaa** [comment]
这个强行更新到了测试版3.3.5.30

**Comment by huiyadanli** [comment]
更新了[1.1版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.1)，3.3.5.30 后也搞成了特征码防撤回了，就是暂时不支持显示撤回提示了

**Comment by MarkLily** [comment]
> 更新了[1.1版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.1)，3.3.5.30 后也搞成了特征码防撤回了，就是暂时不支持显示撤回提示了

OK~
