### ISSUE TITLE
微信测测试版 3.3.5.30 使用1.1防撤回后卡顿

### ISSUE THREAD

**Issue by buererer** [huiyadanli/RevokeMsgPatcher#211]
微信测测试版 3.3.5.30 使用1.1防撤回后卡顿，重新安装正式版3.3.0使用1.1防撤回后还是卡顿

**Comment by huiyadanli** [comment]
我个人使用没有遇到这种情况。防撤回修改的位置，只有在收发消息的时候会触发，你是否是在收发消息的时候卡顿？

**Comment by buererer** [comment]
是切换联系人的时候有卡顿，看了一下系统的cpu和内存的占用情况，并没有没有发现异常情况

**Comment by buererer** [comment]
不适用补丁的时候没有卡顿，我再观察一下

**Comment by buererer** [comment]
我在设置里清空了聊天记录，重启微信就好了

**Comment by MarkLily** [comment]
我这边不会出现卡顿现象，就是没有提示那个对方撤销的提示语了
