### ISSUE TITLE
对方撤回消息之后不显示对方已经撤回

### ISSUE THREAD

**Issue by shnke666666** [huiyadanli/RevokeMsgPatcher#212]
注意：如果出现防撤回失效的情况，请先确认以下几点再创建 issue 。

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 安全软件拦截导致的程序损坏请直接重新覆盖安装对应的应用。

更多的问题可以先看[❓常见问题](https://github.com/huiyadanli/RevokeMsgPatcher/wiki#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，或者搜索[issue列表](https://github.com/huiyadanli/RevokeMsgPatcher/issues)。

确认你的问题不在上述问题范围内，请删除本段提示文字，并提出你问题。问题中请注明你的出现问题的微信/QQ/TIM应用版本，最好能附带问题相关的截图，提供问题复现的方式。

**Comment by huiyadanli** [comment]
3.3.5.15版本后暂时不支持显示撤回提示

**Comment by shnke666666** [comment]
后期可以优化一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月4日(周三) 下午4:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huiyadanli/RevokeMsgPatcher] 对方撤回消息之后不显示对方已经撤回 (#212)




 
3.3.5.15版本后暂时不支持显示撤回提示
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whwnow** [comment]
> 3.3.5.15版本后暂时不支持显示撤回提示

求更新...这个没提示还是挺重要的功能, 不然不知道已经撤回了场面陷入尬尴

**Comment by shnke666666** [comment]
是啊，到时候就会贼尴尬😳



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月4日(周三) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huiyadanli/RevokeMsgPatcher] 对方撤回消息之后不显示对方已经撤回 (#212)




  
3.3.5.15版本后暂时不支持显示撤回提示
  
求更新...这个没提示还是挺重要的功能, 不然不知道已经撤回了场面陷入尬尴
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XYY1411** [comment]
已经很尴尬了，建议加上提示。

**Comment by MarkLily** [comment]
是呀 这个提示还是很重要的~请大佬斟酌

**Comment by xuxiaoqiu** [comment]
初始值设定项引发异常  这个怎么处理

**Comment by huiyadanli** [comment]
> 初始值设定项引发异常 这个怎么处理
 
@xuxiaoqiu 参考这个 #189

**Comment by xuxiaoqiu** [comment]
> > 初始值设定项引发异常 这个怎么处理
> 
> @xuxiaoqiu#189

我看到了 但是运行库是最新版  0.9可以打开 1.0和1.1都打不开

**Comment by xuxiaoqiu** [comment]
> > 初始值设定项引发异常 这个怎么处理
> 
> @xuxiaoqiu#189

系统是64位的

**Comment by xuxiaoqiu** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/212#issuecomment-899932975

**Comment by xuxiaoqiu** [comment]
我看到了 但是运行库是最新版 0.9可以打开 1.0和1.1都打不开

**Comment by xuxiaoqiu** [comment]
系统是64位的

**Comment by 2501432464** [comment]
看不到对方已撤回，这点好尴尬

**Comment by controllerEpoch** [comment]
能不能对已撤回的消息加个提示呢？不然不知道哪条消息是被撤回过的

**Comment by biggercousin** [comment]
这个功能真的很重要，比如哥们微信表白发错了，发到我这里来了，对方已经撤回了，但我不知道，我还认真的说：我也喜欢你，以后我1你0吧。这就很尴尬了。

**Comment by shnke666666** [comment]
哈哈，要笑死
😂😂

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月2日(周四) 下午5:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huiyadanli/RevokeMsgPatcher] 对方撤回消息之后不显示对方已经撤回 (#212)




 
这个功能真的很重要，比如哥们微信表白发错了，发到我这里来了，对方已经撤回了，但我不知道，我还认真的说：我也喜欢你，以后我1你0吧。这就很尴尬了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cxin-william** [comment]
> 这个功能真的很重要，比如哥们微信表白发错了，发到我这里来了，对方已经撤回了，但我不知道，我还认真的说：我也喜欢你，以后我1你0吧。这就很尴尬了。

笑死我对你有什么好处

**Comment by scythk** [comment]
3.3.5.15之后的版本不支持 那么有没有人有3.3.5.15之前的安装包呢...

**Comment by Sky-nt** [comment]
+1,我上来就是为了提这个问题的，发现有人已经提了，今天我跟一个哥们消息表白，但是发完后悔又撤回了，结果我忘了我给他推荐了这款补丁，他没有看到提示，居然回我了，现在场面一度非常尴尬。。。。。

**Comment by galikeoy** [comment]
> 3.3.5.15之后的版本不支持 那么有没有人有3.3.5.15之前的安装包呢...

[微信3.3.0.93](https://cloud.189.cn/web/share?code=r67nIjI7fQBr)

（访问码：jf7f）
第一个带朋友圈的一个版本，亲测没问题

**Comment by 10fun** [comment]
> > 3.3.5.15之后的版本不支持 那么有没有人有3.3.5.15之前的安装包呢...
> 
> [微信3.3.0.93](https://cloud.189.cn/web/share?code=r67nIjI7fQBr)
> 
> （访问码：jf7f） 第一个带朋友圈的一个版本，亲测没问题

感谢分享，我也装回旧版了。。。没提示尴尬

**Comment by cxin-william** [comment]
> > 3.3.5.15之后的版本不支持 那么有没有人有3.3.5.15之前的安装包呢...
> 
> [微信3.3.0.93](https://cloud.189.cn/web/share?code=r67nIjI7fQBr)
> 
> （访问码：jf7f） 第一个带朋友圈的一个版本，亲测没问题

这个有啥好玩的功能呀？

**Comment by xf11075** [comment]
> 这个功能真的很重要，比如哥们微信表白发错了，发到我这里来了，对方已经撤回了，但我不知道，我还认真的说：我也喜欢你，以后我1你0吧。这就很尴尬了。

很有道理啊，我怎么就想不到这么优秀的原因
