### ISSUE TITLE
又是我，W11以管理员身份运行之后无法安装补丁，但是同目录的QQ安装没有任何问题

### ISSUE THREAD

**Issue by kxshu** [huiyadanli/RevokeMsgPatcher#217]
安装微信补丁：

![image](https://user-images.githubusercontent.com/2977440/128628220-ee2804a7-3510-4131-80a4-3d949d2b144f.png)

![image](https://user-images.githubusercontent.com/2977440/128628228-39667e1e-1812-43b1-a0ba-e6273afcd0bc.png)

安装QQ补丁：

![image](https://user-images.githubusercontent.com/2977440/128628235-f975eb56-0e2d-458c-9479-0e25e431ce1f.png)

还是上次的诉求，能不能有独立下载补丁的方式，这样的话，本地权限问题的时候，至少可以手动覆盖。

WIN11版本：
![image](https://user-images.githubusercontent.com/2977440/128628267-1fe3eb18-66dd-4d09-a17b-9b158304482f.png)

**Comment by kxshu** [comment]
我选择把补丁复制到同文件目录下再运行，已经解决问题。

**Comment by huiyadanli** [comment]
居然这样也能解决。

有一种方法能获取打完补丁后的文件，复制微信目录（只识别了`WeChatWin.dll`与`WeChat.exe`，所以可以只复制这两个文件）到其他有权限的地方，打补丁的时候指向这个目录，就能获取到修改后的`WeChatWin.dll`，覆盖回去即可。

**Comment by kxshu** [comment]
> 居然这样也能解决。
> 
> 有一种方法能获取打完补丁后的文件，复制微信目录（只识别了`WeChatWin.dll`与`WeChat.exe`，所以可以只复制这两个文件）到其他有权限的地方，打补丁的时候指向这个目录，就能获取到修改后的`WeChatWin.dll`，覆盖回去即可。

感谢大佬，下次试试这种方式。
