### ISSUE TITLE
初始值设定项引发异常  这个怎么处理

### ISSUE THREAD

**Issue by huiyadanli** [huiyadanli/RevokeMsgPatcher#220]
初始值设定项引发异常  这个怎么处理

_Originally posted by @xuxiaoqiu in https://github.com/huiyadanli/RevokeMsgPatcher/issues/212#issuecomment-899922047_

**Comment by huiyadanli** [comment]
0.9版本是我在老电脑 VS2017 下编译，1.0以后的版本都是我新电脑 VS2019 编译。可能是编译环境造成了这个问题

**Comment by huiyadanli** [comment]
试试下Github自动构建出来的1.1版本 @xuxiaoqiu ，下载地址 https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/1087055302

**Comment by xuxiaoqiu** [comment]
我下载试一下

**Comment by xuxiaoqiu** [comment]
还是相同的问题  点开软件直接弹出那个错误窗口 然后点确认后 就什么反应都没有了

**Comment by xuxiaoqiu** [comment]
![image](https://user-images.githubusercontent.com/89053156/129654420-6e89733a-8f01-4f52-a913-52755d6c79b5.png)

**Comment by huiyadanli** [comment]
我晚上再发你一个版本，你到时候试试

**Comment by xuxiaoqiu** [comment]
好的  麻烦你啦  之前那个他是怎么解决的这个问题

**Comment by huiyadanli** [comment]
之前应该没解决 :joy:  遇到这个情况的人比较少

**Comment by xuxiaoqiu** [comment]
啊这啊这  可能不是遇到的少  最近都说微信开始严抓插件什么的  大多数不知道这个地方找提问   就以为软件无了可能是  在你没回我之前我也以为无了呢 hhhh

-

**Comment by huiyadanli** [comment]
这个是硬改方式，能做到的功能很有限，微信一般不会针对。。。

**Comment by xuxiaoqiu** [comment]
好的  么的问题  倒时候晚上就麻烦你啦

**Comment by ccccerr** [comment]
大佬，我也出现这个问题了，试过重装 .net 没有用。

**Comment by huiyadanli** [comment]
这两个版本依次运行试试，如果报错，把截图发上来我看下。
[展示详细错误版.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/7000628/default.zip)
[修改GAHelper版.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/7000627/GAHelper.zip)

**Comment by xuxiaoqiu** [comment]
第一个展示详细错误运行之后  什么也没有  没有反应  第二个修改gahelper可以正常运行   没有报错了

**Comment by ccccerr** [comment]
好奇怪，第一个“详细错误版“”在原来报“初始值设定项引发异常运行”的电脑上运行后啥都没有，和没运行一样。但是在另一台没有报“初始值设定项引发异常“的电脑上可以运行。
第二个 修改gahelper两台电脑都能正常使用。

**Comment by huiyadanli** [comment]
那我大概知道是哪边的问题了，今晚发一个测试版，应该能修复这个问题了

**Comment by huiyadanli** [comment]
[修复错误Release1.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/7007749/Release1.zip)

来试试这个可以不？

**Comment by ccccerr** [comment]
我要明天才能试，出现问题的电脑不在身边

**Comment by xuxiaoqiu** [comment]
这个可以的  可以正常运行  也可以正常使用

**Comment by ccccerr** [comment]
可以用
