### ISSUE TITLE
撤回提示功能

### ISSUE THREAD

**Issue by xuhaiL** [huiyadanli/RevokeMsgPatcher#228]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/61
https://github.com/huiyadanli/RevokeMsgPatcher/issues/36

hi，看了下issues，之前是有做这个功能的，刚才测试了下最新版，发现并没有撤回提示。能否在下个版本添加上

**Comment by huiyadanli** [comment]
3.3.5.15版本后，有撤回提示的那个修改点位已经没了，智能恢复到老方法了。

等大佬找出新的修改位置。

**Comment by xuhaiL** [comment]
难怪，坐等大佬更新。
