### ISSUE TITLE
微信测试版3.4.0出现特征码不匹配

### ISSUE THREAD

**Issue by percytia** [huiyadanli/RevokeMsgPatcher#231]
![image](https://user-images.githubusercontent.com/89447929/133738650-c8ada1c9-ef99-41a7-9976-a694c0e5ab8e.png)
![image](https://user-images.githubusercontent.com/89447929/133738706-713a8d5c-67bc-4aee-9941-309746798cdb.png)

**Comment by huiyadanli** [comment]
试试不勾选多开，或者把微信升级到最新版本

**Comment by percytia** [comment]
![image](https://user-images.githubusercontent.com/89447929/133765038-81ee13e0-2edc-4cda-bb14-15e91fd461cc.png)
![image](https://user-images.githubusercontent.com/89447929/133765102-fc9c02b1-2d62-4f67-ace9-3229e3c43f34.png)
还是不行，可能是测试版微信的问题

**Comment by huiyadanli** [comment]
应该是特征又有变化了，安装包有没有。发我一个看看

**Comment by study520x** [comment]
v3.4.0.7版官方安装包链接：https://pan.baidu.com/s/1xWEexz3Id_xoWhI-ttL8ZQ  提取码：40wm

**Comment by huiyadanli** [comment]
特征码已经更新，可以再试试。

**Comment by percytia** [comment]
可以了，跪谢大佬！
