### ISSUE TITLE
QQ 9.5.1.27878 patch后无法登陆

### ISSUE THREAD

**Issue by rama291041610** [huiyadanli/RevokeMsgPatcher#234]
QQ
版本：9.5.1.27878 
patch IM.dll后登陆，提示错误代码00001：无法连接到互联网
恢复备份后，kill qqprotect后重启qq登陆正常。

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/136185662-f27b6fe1-b4f7-45e0-a76f-646f7cb0f394.png)

我本机测试没问题，正常登录。你可以重新试试，是不是巧合

修改的点位应该不会影响任何聊天以外的功能。

**Comment by colflip** [comment]
我也是无法登录
![image](https://user-images.githubusercontent.com/26431822/136489556-a67b7ee0-f672-435a-bed1-262ef266628b.png)
