### ISSUE TITLE
调查：是否本补丁会造成电脑微信无法同步最近消息

### ISSUE THREAD

**Issue by ss1969** [huiyadanli/RevokeMsgPatcher#235]
我认为我有这个问题，重新安装原版后正常，不知道其他人是否有类似情况。

**Comment by lilaizheng** [comment]
更新到 3.4.0.38 这个版本 重新打补丁这个问题应该就没了吧

**Comment by dozen007** [comment]
最近别人的表情包没法同步了

**Comment by neville97202** [comment]
有这个问题

**Comment by MarkLily** [comment]
我也有遇到过这个问题 不知道是不是补丁引起的

**Comment by misaka-h** [comment]
一直用的原版，就有这个问题，经常没有最近的文件

**Comment by ssxwcz** [comment]
关闭自动登录功能试试，我之前测试的时候这个功能会导致PC微信消息无法同步，新版本不知道有没有修复

**Comment by wzh502887976** [comment]
> 一直用的原版，就有这个问题，经常没有最近的文件

微信只能同步最近的20条消息，与是否打补丁无关。
