### ISSUE TITLE
能否出个qq轻聊版的防撤回呢？

### ISSUE THREAD

**Issue by fan0424** [huiyadanli/RevokeMsgPatcher#24]
如题，在网上没有搜到轻聊版的防撤回补丁

**Comment by huiyadanli** [comment]
QQ官网上已经没有轻聊版的页面了，请问你用的版本是多少？能否提供一个最新版的下载地址给我，我找到的一个最新的版本是7.9。

**Comment by fan0424** [comment]
> QQ官网上已经没有轻聊版的页面了，请问你用的版本是多少？能否提供一个最新版的下载地址给我，我找到的一个最新的版本是7.9。

恩 最后一个版本就是 7.9的，我的之前是在360软件管家里面下载的：http://soft.360.cn/static/baoku/info_7_0/softinfo_104693319.html

**Comment by fan0424** [comment]
> QQ官网上已经没有轻聊版的页面了，请问你用的版本是多少？能否提供一个最新版的下载地址给我，我找到的一个最新的版本是7.9。

这个是在360上面找的，可以直接下载：http://softdl.360tpcdn.com/QQLight/QQLight_7.9.14314.0.exe

**Comment by tldzyx** [comment]
CRC32: 71560c99
MD5: 1ccc5df82e68c2f5028379dec0a047c1
SHA-1: 00c27b5f0c621f82efdf29f0f9120cd9965b9e15
SHA-256: 4758cea5cc140d018f487865983e4b13c71c96c8f864f250db3ff0a956681489

我这有个珍藏多年的版本, 在QQ官网下载的, 上面是Hash码, 可以用来做比对

**Comment by tldzyx** [comment]
![image](https://user-images.githubusercontent.com/5987706/67174142-9aba1680-f3f3-11e9-9d2b-1c0d46de6050.png)

**Comment by fan0424** [comment]
> CRC32: 71560c99
> MD5: 1ccc5df82e68c2f5028379dec0a047c1
> SHA-1: 00c27b5f0c621f82efdf29f0f9120cd9965b9e15
> SHA-256: 4758cea5cc140d018f487865983e4b13c71c96c8f864f250db3ff0a956681489
> 
> 我这有个珍藏多年的版本, 在QQ官网下载的, 上面是Hash码, 可以用来做比对

我发的哪个是在360上面找的， 和你的版本不一样

**Comment by huiyadanli** [comment]
@fan0424 提供的是 7.9.14314.0，比较新
@tldzyx 你的跟我网上下载的是同个版本 7.9.14308.0，hash我也验过对上了。

我两个都做下防撤回试试。

**Comment by fan0424** [comment]
> @fan0424 提供的是 7.9.14314.0，比较新
> @tldzyx 你的跟我网上下载的是同个版本 7.9.14308.0，hash我也验过对上了。
> 
> 我两个都做下防撤回试试。

哈哈 辛苦你了！

**Comment by huiyadanli** [comment]
@fan0424 
@tldzyx 

已更新0.6版本，支持 QQ轻聊版 7.9.14314.0、QQ轻聊版 7.9.14308.0 的防撤回，可以测试下是否有问题

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/0.6

**Comment by fan0424** [comment]
> @fan0424
> @tldzyx
> 
> 已更新0.6版本，支持 QQ轻聊版 7.9.14314.0、QQ轻聊版 7.9.14308.0 的防撤回，可以测试下是否有问题
> 
> https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/0.6

7.9.14314版本测试成功！感谢！
