### ISSUE TITLE
软件UI显示异常

### ISSUE THREAD

**Issue by xitieshiz2** [huiyadanli/RevokeMsgPatcher#241]
程序启动后无法显示ui内容，看起来像是字体异常
![image](https://user-images.githubusercontent.com/75575551/139585727-efc8e300-f11e-42d6-bb08-54253e96625f.png)
winver：
![image](https://user-images.githubusercontent.com/75575551/139585741-c9324826-038c-46c8-81cd-bb0b14de6aff.png)
我不是清楚该怎么表示我的设备上安装了哪些字体

**Comment by huiyadanli** [comment]
这种情况海真没见过，开发的时候使用的字体都是默认的，请确认是否安装[.NET Framework 4.5](https://www.microsoft.com/zh-cn/download/details.aspx?id=30653)
