### ISSUE TITLE
能否更新一下撤回提示？

### ISSUE THREAD

**Issue by smiles-seaside** [huiyadanli/RevokeMsgPatcher#243]
现在最新的版本，撤回了都没有提示，很多时候别人撤回了，如果不看手机的话，都不知道对方撤回了，所以能否增加或者修复撤回提示的功能？谢谢

**Comment by Dreamray** [comment]
支持，如果对方以光速撤回，而我又回复了，非常尴尬，露馅了。

**Comment by Damon-Yo** [comment]
附议

**Comment by Caraxes1995** [comment]
一人血书撤回提醒

a-little-headache ***@***.***> 于2021年11月9日周二 上午12:10写道：

**Comment by Hand-of-Midas** [comment]
附议，没有提示都不敢用防撤回了

**Comment by Gx-506556572** [comment]
撤回提醒没有了。

**Comment by BolinYe** [comment]
不要慌，装作网络卡了就行了

**Comment by fighting-noah** [comment]
能否加个撤回提示呢，这样很尴尬啊

**Comment by smiles-seaside** [comment]
现在好像是新版的微信不能搞撤回提示了。。。坐等大佬找到方法~

**Comment by September999999999** [comment]
附议

**Comment by BigBigBIgMan** [comment]
附议，撤回提醒真的很实用，万分期待

**Comment by BigBigBIgMan** [comment]
附议 2021年12月14日10:42:32

**Comment by 0Zarathustra0** [comment]
附议 2021-12-14 19:43:31

**Comment by XinLau1996** [comment]
附议 2021年12月16日 15:31:04

**Comment by Laoguoguo** [comment]
附议 2021年12月17日 10:27:36

**Comment by MarkLily** [comment]
个人猜测哈：1、技术方面不好加了，WX那边做了改动；2、安全方面，加了撤回提示可能会加大封号的危险系数。欢迎大佬们纠正~~~

**Comment by smoile** [comment]
附议

**Comment by niaoao** [comment]
附议 2021-12-21 09:18:55

**Comment by vdongle** [comment]
附议 2021-12-24 17:55:00

**Comment by qw576483** [comment]
附议 2021年12月28日 13:45:04

**Comment by DearBo7** [comment]
附议 2021年12月29日10:24:37

**Comment by AO2233** [comment]
都不看closed的issue吗？这issue重复了多少次了。。。。。。
ORZ
#249 
#212

**Comment by huiyadanli** [comment]
暂时没有方法能做到这个了，可以使用老版本微信然后安装补丁（2.8.0.112~3.3.5.15的版本都可以）。

坐等其他大佬研究出新方法了

**Comment by sofs2005** [comment]
悲伤
3.3.5.15哪里有安装包

**Comment by sofs2005** [comment]
> 暂时没有方法能做到这个了，可以使用老版本微信然后安装补丁（2.8.0.112~3.3.5.15的版本都可以）。
> 
> 坐等其他大佬研究出新方法了

我试过33515了，和最新版一样是没有提示的

**Comment by huiyadanli** [comment]
> > 暂时没有方法能做到这个了，可以使用老版本微信然后安装补丁（2.8.0.112~3.3.5.15的版本都可以）。
> > 坐等其他大佬研究出新方法了
> 
> 我试过33515了，和最新版一样是没有提示的

不含 3.3.5.15 这个版本。。。

**Comment by 1638276310** [comment]
现在还有撤回提示吗？

**Comment by sonce** [comment]
增加下撤回提醒。谢谢。

**Comment by yimouleng** [comment]
WeChatSetup_3.3.0.1000【微信可看见撤回提示】版本下载：
https://www.aliyundrive.com/s/A7Aj9Qcpe7b
提取码：1g9p

**Comment by WangJincheng4869** [comment]
臣附议

**Comment by chywx** [comment]
陈附议

**Comment by fency12** [comment]
附议   2022年4月18日

**Comment by fency12** [comment]
臣附议

**Comment by LovesAsuna** [comment]
[AntiRecall](https://github.com/plummm/AntiRecall)也许有参考价值

**Comment by JJ3322** [comment]
+1 实在是太尴尬啦

**Comment by Heartfilia** [comment]
是否可以把内容撤销失效  但是那句话保留呢😂

**Comment by tedonggo** [comment]
附议 2010/12/23 10:53:25

**Comment by AaaaaaU** [comment]
附议

**Comment by wyDuang** [comment]
附议

**Comment by jasonZHAOLIANG** [comment]
这个程序怎么运行

**Comment by mifashion** [comment]
附议

**Comment by code-upload** [comment]
附议 2022年7月12日10:07:52

**Comment by zoulan** [comment]
附议

**Comment by huiyadanli** [comment]
20220716：
**当前最新的 3.7 以上版本（3.7.0.30、3.7.5.23）重新开始支持撤回提示。** 3.7以上版本的 已经安装过补丁的，还原后重新安装补丁即可。

另外：
微信版本号在 2.8.0.112~3.3.5.15 区间内的（不含3.3.5.15）老版本也是支持显示撤回提示的。

对防撤回提示有要求的可以使用以上提到的微信版本。

**Comment by x4k** [comment]
> 20220716： **当前最新的 3.7 以上版本（3.7.0.30、3.7.5.23）重新开始支持撤回提示。** 3.7以上版本的 已经安装过补丁的，还原后重新安装补丁即可。
> 
> 另外： 微信版本号在 2.8.0.112~3.3.5.15 区间内的（不含3.3.5.15）老版本也是支持显示撤回提示的。
> 
> 对防撤回提示有要求的可以使用以上提到的微信版本。

作者，补丁发布了嘛？我看还是5月29日的1.5的版本？

**Comment by huiyadanli** [comment]
> > 20220716： **当前最新的 3.7 以上版本（3.7.0.30、3.7.5.23）重新开始支持撤回提示。** 3.7以上版本的 已经安装过补丁的，还原后重新安装补丁即可。
> > 另外： 微信版本号在 2.8.0.112~3.3.5.15 区间内的（不含3.3.5.15）老版本也是支持显示撤回提示的。
> > 对防撤回提示有要求的可以使用以上提到的微信版本。
> 
> 作者，补丁发布了嘛？我看还是5月29日的1.5的版本？

补丁信息是会动态获取的。

1.5版本在补丁界面展示上稍微有点bug，不影响使用，近期会发布新版本修复的

**Comment by x4k** [comment]
> 



> > > 20220716： **当前最新的 3.7 以上版本（3.7.0.30、3.7.5.23）重新开始支持撤回提示。** 3.7以上版本的 已经安装过补丁的，还原后重新安装补丁即可。
> > > 另外： 微信版本号在 2.8.0.112~3.3.5.15 区间内的（不含3.3.5.15）老版本也是支持显示撤回提示的。
> > > 对防撤回提示有要求的可以使用以上提到的微信版本。
> > 
> > 
> > 作者，补丁发布了嘛？我看还是5月29日的1.5的版本？
> 
> 补丁信息是会动态获取的。
> 
> 1.5版本在补丁界面展示上稍微有点bug，不影响使用，近期会发布新版本修复的

好的，谢谢，😁

**Comment by DreammStill** [comment]
可是图片视频撤回还是有问题，只能保留最近聊天的防撤回，唉，还是希望作者大大想想办法😘

**Comment by MarcoHoo** [comment]
我现在用最新的3.7.6.44不行，看不到提示

**Comment by Tultang** [comment]
附议2022-10-08 09:49

**Comment by BIGMONK** [comment]
3.8.0.41 别人的消息撤回时无撤回提示，自己的消息撤回时不显示重新编辑

**Comment by 991069003** [comment]
电脑版本微信3.3.0.93
电脑版本微信3.7.5.23
电脑版本微信3.7.5.31
[微信可看见撤回提示】
版本下载：https://www.aliyundrive.com/s/qcwu88yC21Q

**Comment by 991069003** [comment]
> 现在最新的版本,撤回了都没有提示,很多时候别人撤回了,如果不看手机的话,都不知道对方撤回了,所以能否增加或者修复撤回提示的功能？谢谢

电脑版本微信3.3.0.93
电脑版本微信3.7.5.23
电脑版本微信3.7.5.31
[微信可看见撤回提示】
版本下载：https://www.aliyundrive.com/s/qcwu88yC21Q

**Comment by mengyanmengyu** [comment]
附议2023-2-1

**Comment by Wangzh0113** [comment]
什么时候能更新新版本

**Comment by zcsctc** [comment]
附议，windows版本的撤回提示

**Comment by iOSreverse** [comment]
附议，windows版本的撤回提示
20230423

**Comment by notomatoes** [comment]
2023.06 附议

**Comment by chenjin0827** [comment]
复议

**Comment by as88866920** [comment]
新版的微信不能搞撤回提示了。。。坐等大佬找到方法~

**Comment by 2410655661** [comment]
2023.10.11 微信版本3.9.7.25 复议

**Comment by qqzhouhaijun** [comment]
2023.10.16 微信版本3.9.7.29 复议

**Comment by xuelang2009** [comment]
使用上面分享的微信3.7.5.23 撤回时，PC显示了2次 撤回一条消息。是我的问题吗？

**Comment by yaoyingkeji** [comment]
2023.11.01  微信 复议 没有提示

**Comment by SamWang8888** [comment]
2024fy=附议

**Comment by imtzc** [comment]
2024.2.19附议

**Comment by huiyadanli** [comment]
20230225：

微信 3.9.9.43 又可以带撤回提示了

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/8e28f361-8d00-4f08-87e8-72f4b26ab14e)

只安装带撤回提示的补丁就可以了。

**Comment by as88866920** [comment]
> 20240225：
> 
> 微信 3.9.9.43 又可以带撤回提示了
> 
> ![image](https://private-user-images.githubusercontent.com/15783049/307565821-8e28f361-8d00-4f08-87e8-72f4b26ab14e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDUxMTgsIm5iZiI6MTcwODg0NDgxOCwicGF0aCI6Ii8xNTc4MzA0OS8zMDc1NjU4MjEtOGUyOGYzNjEtOGQwMC00ZjA4LTg3ZTgtNzJmNGIyNmFiMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA3MDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4OTZlMmE3M2JjNjdhMWZmNjQyZGMzNjNlNDFiNDVjZDBjMDJjYjE0OWRmYjcyNjc1MmVmYzZhZWU5MzU1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDkt0eZR0UK_5a18DKbkkAxPoTPnAeaMOVkcFk3mrng)
> 
> 只安装带撤回提示的补丁就可以了。

如果能加入撤回编辑就好了

**Comment by imtzc** [comment]
> 20240225：
> 
> 微信 3.9.9.43 又可以带撤回提示了
> 
> ![image](https://private-user-images.githubusercontent.com/15783049/307565821-8e28f361-8d00-4f08-87e8-72f4b26ab14e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTU3MjYsIm5iZiI6MTcwODkxNTQyNiwicGF0aCI6Ii8xNTc4MzA0OS8zMDc1NjU4MjEtOGUyOGYzNjEtOGQwMC00ZjA4LTg3ZTgtNzJmNGIyNmFiMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAyNDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOGUxOWUyYmFmNWU4OTZlYWI0Zjg4NTJlODcwYzZlM2UxMGM1ZmVkNTYwNTA0MjQyMDI3MGZlNmJlMDU1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GyhpSrYRuR6yUYsMX180V1bMo7Gq4rpCmbBYc_G8u_s)
> 
> 只安装带撤回提示的补丁就可以了。

有个比较尴尬的问题就是，虽然有提示了，但是不知道具体撤回了哪条消息
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/19903889/54c91853-3536-43ee-9bcf-eb06f552efd5)
作者能否支持下显示撤回了哪条消息

**Comment by Eyion** [comment]
现在微信安装防撤回有老版和新版，新版说明里说视频图片消息撤回后会被删除无法查看，那么老版的也是如此吗？想要保留撤回后的视频图片，安装老版能做到吗？

**Comment by fhwo13** [comment]
> 现在微信安装防撤回有老版和新版，新版说明里说视频图片消息撤回后会被删除无法查看，那么老版的也是如此吗？想要保留撤回后的视频图片，安装老版能做到吗？

“新版说明里说视频图片消息撤回后会被删除无法查看”——我怎么没有看到，验证也正常？version 3.9.10.27

**Comment by TiBaiii** [comment]
qq可以更新一个撤回提醒功能吗
