### ISSUE TITLE
win11微信防撤回不能用？

### ISSUE THREAD

**Issue by 1933273372** [huiyadanli/RevokeMsgPatcher#246]
注意：如果出现防撤回失效的情况，请先确认以下几点再创建 issue 。

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 安全软件拦截导致的程序损坏请直接重新覆盖安装对应的应用。

更多的问题可以先看[❓常见问题](https://github.com/huiyadanli/RevokeMsgPatcher/wiki#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，或者搜索[issue列表](https://github.com/huiyadanli/RevokeMsgPatcher/issues)。

确认你的问题不在上述问题范围内，请删除本段提示文字，并提出你问题。问题中请注明你的出现问题的微信/QQ/TIM应用版本，最好能附带问题相关的截图，提供问题复现的方式。

**Comment by huiyadanli** [comment]
可以用，提供下具体微信版本

**Comment by 1933273372** [comment]
> 
> 
> 可以用，提供下具体微信版本

3.4.0.38

**Comment by 1933273372** [comment]
> 
> 
> 可以用，提供下具体微信版本

使用的是win11

**Comment by AO2233** [comment]
WeChat 3.4.0.38 
Win11 22000.348
可以使用
PC
![image](https://user-images.githubusercontent.com/59056753/143519430-d6329cbe-4beb-48e2-a44f-dfbf1433c566.png)
phone
![image](https://user-images.githubusercontent.com/59056753/143519500-471d48ff-3e82-4380-8853-6bc86b449140.png)

**Comment by huiyadanli** [comment]
@AO2233 感谢帮忙测试！

**Comment by WB967** [comment]
系统：win11
![image](https://user-images.githubusercontent.com/57792507/194687291-e6d19f2c-4929-4715-ab09-4637afba7a0c.png)
微信版本号：3.7.6.44
软件问题：无法获取微信安装位置
![image](https://user-images.githubusercontent.com/57792507/194687324-9e2e6a8f-7b63-4460-91ac-faa4c2088261.png)
后面三点选择文件位置，只能选择微信的安装目录，例如：D:\Program Files (x86)\WeChat，报如下错误
![image](https://user-images.githubusercontent.com/57792507/194687411-a5ea4447-06e8-4b97-a7c9-b4734650ec86.png)
在输入框中粘贴文件路径提示，
![image](https://user-images.githubusercontent.com/57792507/194687456-04e19179-c2cf-4143-a8f7-f48a1bacf78c.png)

**Comment by huiyadanli** [comment]
@WB967  要选到后续的版本路径

例如：D:\Program Files (x86)\WeChat\[3.7.6.44]\
