### ISSUE TITLE
最新的微信测试版3.4.5.22已经不能用了  提示不支持

### ISSUE THREAD

**Issue by shawnwongx** [huiyadanli/RevokeMsgPatcher#248]
![(UH$C63(HHEV$2QUL7$EY6H](https://user-images.githubusercontent.com/64091150/144529064-ce4c3ca4-fe04-4973-ab83-25669b60791e.png)

**Comment by huiyadanli** [comment]
要等补丁信息获取完...才能看到最新的支持情况

**Comment by JackyTheBest** [comment]
3.4.5.27 不支持

**Comment by JackyTheBest** [comment]
已经支持了，这个issue可以关了
