### ISSUE TITLE
希望能加个撤回的标记

### ISSUE THREAD

**Issue by Cleaney** [huiyadanli/RevokeMsgPatcher#249]
可以在撤回的那条消息上加个标记吗，不然都不知道哪些是撤回的，体验不好

**Comment by PDxtXHd** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/212
同样的问题不知道发过多少次issue了

**Comment by huiyadanli** [comment]
其他issue讨论吧，暂时没解决方案
