### ISSUE TITLE
能否添加一个，切换微信账号，而电脑端不退出，或者每次登录无需验证

### ISSUE THREAD

**Issue by SureFire2** [huiyadanli/RevokeMsgPatcher#250]
尊敬的开发者您好，因为工作的需要，每天都要在手机上来回切换两个微信账户登录，而手机上一但退出微信登陆，电脑端也会连着一起退出，因为手机都配置不高，双开微信会使我的手机出现卡顿的情况，能否加入一个手机端退出，电脑端不受影响，或者是可以直接在电脑端登陆无需向手机端发起登陆请求？

**Comment by SuperAc** [comment]
这个需求应该是找微信开发团队提，另外登录无需验证可以在扫码后勾选，不过退出登录了还是需要重新扫码的

**Comment by huiyadanli** [comment]
这种需求已经涉及到微信服务端相关的内容。

也许可以通过干掉PC端接收手机端退出消息的方式做到。

我的水平不足以做到此类需求。补丁本身也暂时只会专注于防撤回。
