### ISSUE TITLE
PC微信3.5.0 工具不能正常使用

### ISSUE THREAD

**Issue by QQ804218** [huiyadanli/RevokeMsgPatcher#253]
在输入微信路经后提示"无法找到此应用的关键文件，请选择正确的安装路径",工具无法正常使用.

**Comment by yaosj2k** [comment]
C:\Program Files (x86)\Tencent\WeChat\[3.5.0.4] 路径变了

**Comment by QQ804218** [comment]
可以考虑增加自动识别路径功能吗?或是自动识别正在运行的QQ或微信的路径.如有变化自动改变




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyadanli/RevokeMsgPatcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月25日(星期六) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] PC微信3.5.0 工具不能正常使用 (Issue #253)





 
C:\Program Files (x86)\Tencent\WeChat[3.5.0.4] 路径变了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huiyadanli** [comment]
1. 路径变化已经适配 https://github.com/huiyadanli/RevokeMsgPatcher/commit/3b929af0042a85c98d27f18999227b2b3a3b547d

2. 防撤回的特征出现了两个，定位后发现疑似 `new ab test` 灰度测试的版本。所以这个内测版本暂时不做适配，正式版发布后这个特征应该会消失，如果想要防撤回的话可以参考这个教程操作：[微信防撤回与多开教程](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E5%BE%AE%E4%BF%A1%E9%98%B2%E6%92%A4%E5%9B%9E%E4%B8%8E%E5%A4%9A%E5%BC%80%E6%95%99%E7%A8%8B)。

![image](https://user-images.githubusercontent.com/15783049/147414471-97d54774-760f-41fe-b56b-2c7b318cdfc1.png)

**Comment by zsyh** [comment]
不用那么麻烦，直接去官网下旧版本微信，覆盖安装就可以了

**Comment by yaosj2k** [comment]
> 1. 路径变化已经适配 [3b929af](https://github.com/huiyadanli/RevokeMsgPatcher/commit/3b929af0042a85c98d27f18999227b2b3a3b547d)
> 2. 防撤回的特征出现了两个，定位后发现疑似 `new ab test` 灰度测试的版本。所以这个内测版本暂时不做适配，正式版发布后这个特征应该会消失，如果想要防撤回的话可以参考这个教程手动操作😂：[微信防撤回与多开教程](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E5%BE%AE%E4%BF%A1%E9%98%B2%E6%92%A4%E5%9B%9E%E4%B8%8E%E5%A4%9A%E5%BC%80%E6%95%99%E7%A8%8B)。
> 
> ![image](https://user-images.githubusercontent.com/15783049/147414471-97d54774-760f-41fe-b56b-2c7b318cdfc1.png)

3.5.0.20 已经正式版本了； 防撤回麻烦支持下了

**Comment by huiyadanli** [comment]
3.5.0.29 已经开始支持

自动识别路径的版本可以从[Action](https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/1693809707)中下载

**Comment by Tang121337** [comment]
3.5.0.46又开始路径消失了
![image](https://user-images.githubusercontent.com/30113090/150933169-43ce981b-3a84-4e41-be3b-31ce4604b864.png)
