### ISSUE TITLE
微信3.5.0.29失效，按教程手动x32dbg生成补丁后也无效了

### ISSUE THREAD

**Issue by twy12689** [huiyadanli/RevokeMsgPatcher#273]
如题，请求协助，感谢！

**Comment by wangqian0628** [comment]
同问

**Comment by zyfwq** [comment]
3.5.0.29为正式版PC端微信，非测试版，确实是不能使用。

**Comment by huiyadanli** [comment]
有无安装包打包发下

**Comment by huiyadanli** [comment]
已经支持，暂时非特征码支持，观察几个版本，微信官网还没直接提供这个版本的下载链接。

自动识别新版微信路径的版本可以从[Action](https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/1693809707)中下载

**Comment by huiyadanli** [comment]
#275 切换成了特征码的方式
