### ISSUE TITLE
3.5.0.33撤回失败，提示特征码匹配数与期望匹配数不一致

### ISSUE THREAD

**Issue by lyhrtb** [huiyadanli/RevokeMsgPatcher#275]
注意：如果出现防撤回失效的情况，请先确认以下几点再创建 issue 。

1. 微信/QQ/TIM 更新后需要重新安装补丁才能继续防撤回。
2. 微信从 2.8.0.112 版本开始支持带提示的防撤回(QQ/TIM 暂时没有)，所以能看到撤回提示不是防撤回失效。
3. 安全软件拦截导致的程序损坏请直接重新覆盖安装对应的应用。

更多的问题可以先看[❓常见问题](https://github.com/huiyadanli/RevokeMsgPatcher/wiki#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，或者搜索[issue列表](https://github.com/huiyadanli/RevokeMsgPatcher/issues)。

确认你的问题不在上述问题范围内，请删除本段提示文字，并提出你问题。问题中请注明你的出现问题的微信/QQ/TIM应用版本，最好能附带问题相关的截图，提供问题复现的方式。

**Comment by tldzyx** [comment]
![image](https://user-images.githubusercontent.com/5987706/149624603-d5abddae-146f-4bf9-8313-1a67666c0fab.png)
2022年1月15日更新微信后无法使用防撤回, 版本号3.5.0.33

**Comment by ShaoYuJun** [comment]
附议，我这边遇到了相同的问题

**Comment by YONA-302** [comment]
我也是遇上同步问题

**Comment by huiyadanli** [comment]
有无这个版本的安装包

**Comment by ferrygao** [comment]
今天自动更新为3.5.0.0然后就不好使了

官网最新就是3.4.5.1000
https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

**Comment by huiyadanli** [comment]
> 今天自动更新为3.5.0.0然后就不好使了
> 
> 官网最新就是3.4.5.1000 https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

官网版本 3.4.5.45，检查更新已经是最新版本

**Comment by bootlegseahorse** [comment]
没找到3.5.0.33的安装包，只在Temp里抓到了这个升级包，您看看能不能用。

https://pan.baidu.com/s/1Au5BY6d5YzC_I37cgV5RzA?pwd=rq6g

**Comment by huiyadanli** [comment]
已经更新特征码，支持 3.5.0.29 以上的版本

**Comment by bootlegseahorse** [comment]
感谢大佬

**Comment by lyhrtb** [comment]
感谢大佬

**Comment by komazhou** [comment]
> 

有没有编译好的，看到有更新代码，但是不知道怎么用，文档找了一圈没有找到，

**Comment by huiyadanli** [comment]
> 有没有编译好的，看到有更新代码，但是不知道怎么用，文档找了一圈没有找到，

@komazhou 当前release版本还能用，可能需要手动选择微信所在目录，最新的防撤回特征会联网获取。。

如果要获取最新代码的编译版本，可以直接从 https://github.com/huiyadanli/RevokeMsgPatcher/actions 中下载

**Comment by ferrygao** [comment]
经过测试 最新版本 3.5.0.33（只能通过上一版本3.4.5.45在线升级到，并没有独立安装包）已经好用了，谢谢

**Comment by ferrygao** [comment]
> ![image](https://user-images.githubusercontent.com/5987706/149624603-d5abddae-146f-4bf9-8313-1a67666c0fab.png) 2022年1月15日更新微信后无法使用防撤回, 版本号3.5.0.33

请教这里如何贴图 如何上传自己的截图？

**Comment by ShaoYuJun** [comment]
我这边好了，谢谢您！

**Comment by demon-zhonglin** [comment]
@ferrygao 
贴图说明：https://docs.github.com/cn/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images

先将截图上传至网络图床，将获取的地址填入下面格式中即可
格式：![image](图片网络地址)

**Comment by demon-zhonglin** [comment]
@ferrygao 
贴图说明：https://docs.github.com/cn/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images

先将截图上传至网络图床，将获取的地址填入下面格式中即可
格式：![image ](图片网络地址)
