### ISSUE TITLE
3.5.0.44无法找到此应用关键文件

### ISSUE THREAD

**Issue by 945537063** [huiyadanli/RevokeMsgPatcher#281]
[微信截图_20220121200234](https://user-images.githubusercontent.com/45937507/150524235-5df3ec0a-a1d2-4443-9995-1c861040a9fa.png)
如图 点击浏览后找到微信文件地址，显示如图无法找到

**Comment by q123458384** [comment]
3.5.0.42 也是一样，如何关闭微信的自动更新

**Comment by Leakless** [comment]
C:\Program Files (x86)\Tencent\WeChat\[3.5.0.44]
新版本应该是改架构了，需要手动选择一下目录
![QQ截图20220122150958](https://user-images.githubusercontent.com/6134641/150628859-78bcb373-f659-470c-98b9-5532f255f08b.png)

**Comment by huiyadanli** [comment]
手动选择目录，或者下载最新版本 1.2

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.2
