### ISSUE TITLE
1.2版本无法运行

### ISSUE THREAD

**Issue by SekiBetu** [huiyadanli/RevokeMsgPatcher#282]
![image](https://user-images.githubusercontent.com/38283893/150644055-28f222f2-eb4a-4ded-8eb3-785fc7a93d0a.png)

**Comment by huiyadanli** [comment]
能截图看下你当前微信安装目录的结构吗

**Comment by SekiBetu** [comment]
> 能截图看下你当前微信安装目录的结构吗

新版本不能作为单独程序运行了吗，只能放到对应目录中？

**Comment by ViCrack** [comment]
我运行不会报错

**Comment by huiyadanli** [comment]
> > 能截图看下你当前微信安装目录的结构吗
> 
> ~新版本不能作为单独程序运行了吗，只能放到对应目录中？我之前都不是放到目录中，直接运行然后手动选目录的~
> 
> 跟目录无关吧，我是下载解压双击运行就提示值不能为 null 参数名 path

运行以后就会立即去注册表中找到微信的安装目录，应该是这一步存在问题

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/150644394-8c68df8e-80a4-4ca0-ad15-59beacf6669b.png)
![image](https://user-images.githubusercontent.com/38283893/150644399-20f7a152-2ef2-4e38-9314-a9dc7260c8e4.png)

**Comment by SekiBetu** [comment]
> > > 能截图看下你当前微信安装目录的结构吗
> > 
> > 
> > ~新版本不能作为单独程序运行了吗，只能放到对应目录中？我之前都不是放到目录中，直接运行然后手动选目录的~
> > 跟目录无关吧，我是下载解压双击运行就提示值不能为 null 参数名 path
> 
> 运行以后就会立即去找微信的安装目录，应该是这一步存在问题

我是手动解压微信安装包的绿色版，所以没有注册表信息

**Comment by SekiBetu** [comment]
或者说，先让程序启动起来，再提示找不到

**Comment by huiyadanli** [comment]
[删除默认路径查找逻辑.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/7918635/default.zip)

试试这个版本

**Comment by SekiBetu** [comment]
> [删除默认路径查找逻辑.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/7918635/default.zip)
> 
> 试试这个版本

没有错误弹窗了，但是程序没有启动

**Comment by huiyadanli** [comment]
[删除默认路径查找逻辑+添加错误堆栈Release.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/7918648/%2B.Release.zip)
换个版本

**Comment by SekiBetu** [comment]
---------------------------
错误
---------------------------
值不能为 null。

参数名: path
在 System.IO.DirectoryInfo..ctor(String path)

   在 RevokeMsgPatcher.Modifier.WechatModifier.GetRealInstallPath(String basePath)

   在 RevokeMsgPatcher.Modifier.WechatModifier.FindInstallPath()

   在 RevokeMsgPatcher.FormMain.InitControls()

   在 RevokeMsgPatcher.FormMain..ctor()

   在 RevokeMsgPatcher.Program.Main()
---------------------------
确定   
---------------------------

**Comment by SekiBetu** [comment]
windows有个沙盒功能，大佬可以先开一个在里面测试，这样就是未安装微信的环境了

**Comment by huiyadanli** [comment]
[fixed.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/7918659/fixed.zip)

已经找到问题了，主要还是没打印堆栈没法定位问题:joy: 。这个版本应该解决了，为了以防万一所有错误我都catch了

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/150645719-d047615b-0dbd-4eef-962d-ef9db9a4db49.png)
可以了

**Comment by huiyadanli** [comment]
感谢反馈，这反馈太及时了，一发新版本就一个issue过来了。我更新下下载链接
