### ISSUE TITLE
因为我微信安装在D盘根目录新建的文件夹，软件每次都能找到QQ，却不能找到微信。

### ISSUE THREAD

**Issue by CMJNB** [huiyadanli/RevokeMsgPatcher#286]
因为我微信安装在D盘根目录新建的文件夹，软件每次都能找到QQ，却不能找到微信。

![image](https://user-images.githubusercontent.com/53365071/151097098-11f06758-0798-49ed-b802-028aa9a7e96e.png)

_Originally posted by @CMJNB in https://github.com/huiyadanli/RevokeMsgPatcher/discussions/285_

**Comment by huiyadanli** [comment]
你这个是安装版的微信，还是绿色版的？是否有移动过微信的目录？

**Comment by CMJNB** [comment]
> 

安装的，没有移动过

**Comment by CMJNB** [comment]
那我卸掉重装试试？ 

> 你这个是安装版的微信，还是绿色版的？是否有移动过微信的目录？

**Comment by CMJNB** [comment]
啊哈，重装就行了。
