### ISSUE TITLE
3.5.0.46 撤回失败

### ISSUE THREAD

**Issue by doio** [huiyadanli/RevokeMsgPatcher#287]
升级到这个版本撤回失败了，也使用了 1.2 版本，可是还是失效了

现在微信是要斗智斗勇啊...

**Comment by doio** [comment]
值得注意的是 1.2 版本识别微信的版本是 3.5.0.44，而微信的版本的的确确是 3.5.0.46

![20220127122715](https://user-images.githubusercontent.com/4461202/151291980-743599ad-2af8-4081-a9f8-0b8cfef9e14d.png)

**Comment by huiyadanli** [comment]
仅多开失效吗？

**Comment by doio** [comment]
不是啊，是已经安装的防撤回，试了好几次消息图片都能撤回并且系统提示“已被撤回”

**Comment by huiyadanli** [comment]
正常情况下的补丁界面图，测试可以防撤回
![image](https://user-images.githubusercontent.com/15783049/151298060-0a750d08-535c-4bc6-86c6-fa336399677a.png)

3.5 以后的微信本体文件都在这个目录下 `\Tencent\WeChat\[3.5.x.xxxxx]` ，而你的 `\Tencent\WeChat` 目录下也能被识别到微信（3.5.0.44）， 说明升级安装可能存在问题。

解决方法也很简单，两种方法任选其一：
1. 重装
2. 删除   `\Tencent\WeChat`  目录下的 `WeChatWin.dll`

**Comment by doio** [comment]
谢谢，选择了正确目录以后能正确防撤回了，看来有必要重装了 Thanks♪(･ω･)ﾉ
