### ISSUE TITLE
1.2版本默认识别不到微信安装目录,需要手动选择,每次打开都要手动选择

### ISSUE THREAD

**Issue by junlovejing** [huiyadanli/RevokeMsgPatcher#288]
![图片](https://user-images.githubusercontent.com/24191896/151784090-55a5a34e-9d41-4daf-bc70-59ca03d441db.png)

**Comment by Githubbili** [comment]
手动选择也说有路径不对

**Comment by woyaowudile** [comment]
之前的1.1也是，但是QQ可以正常获取，微信不行
![image](https://user-images.githubusercontent.com/57313837/153787028-7c3f4284-9c06-4553-b2be-a61ce8101a53.png)

**Comment by 535544858** [comment]
![微信截图_20220214105422](https://user-images.githubusercontent.com/99628028/153792327-5b186507-109c-485d-a396-383cae39cdc1.png)
可能要选到版本的目录就可以了

**Comment by huiyadanli** [comment]
1. 微信 3.5 版本后 目录有变化
2. 微信的安装目录是通过注册表中的微信安装路径来判断的，假如你使用的不是安装版的微信，识别不到是正常现象。

**Comment by junlovejing** [comment]
> 1. 微信 3.5 版本后 目录有变化
> 
>     2. 微信的安装目录是通过注册表中的微信安装路径来判断的，假如你使用的不是安装版的微信，识别不到是正常现象。

第二条，不是安装版的微信？

**Comment by huiyadanli** [comment]
> > 1. 微信 3.5 版本后 目录有变化
> >    
> >    2. 微信的安装目录是通过注册表中的微信安装路径来判断的，假如你使用的不是安装版的微信，识别不到是正常现象。
> 
> 第二条，不是安装版的微信？

就是解压就能运行的绿色版微信，注册表中是没有相关信息的
