### ISSUE TITLE
请问能否兼容QQ 9.0.4(23786)？

### ISSUE THREAD

**Issue by Gokou-Ruri** [huiyadanli/RevokeMsgPatcher#29]
该版本安装包：https://c-t.work/s/d8ac3952a5284e

**Comment by huiyadanli** [comment]
为什么不更新最新版呢？如果是第三方修改过的版本，我这边默认是直接返回不支持的（通过对比文件SHA1，实际可能是支持的）

**Comment by Gokou-Ruri** [comment]
@huiyadanli 不是第三方修改版本，安装包是官方版，带腾讯签名的。不更新主要是嫌麻烦，而且新版乱七八糟的功能也更多，更新又那么频繁，实在是适应不能。

**Comment by huiyadanli** [comment]
已经支持，测试下吧~

**Comment by Gokou-Ruri** [comment]
@huiyadanli 非常感谢！已生效！只是对方撤回消息的时候，自己这边看不到通知，也就是不知道对方是否执行了撤回操作，关于这个可否增加一个通知？

**Comment by huiyadanli** [comment]
@Gokou-Ruri 显示撤回的哪条消息的功能暂时实现不了，要看以后有没有更好的方案了
