### ISSUE TITLE
最新版微信防撤回没用了

### ISSUE THREAD

**Issue by luotingv1** [huiyadanli/RevokeMsgPatcher#294]
大佬求更新 最新版微信防撤回没用了![a7ffa9458a0d76b8d666b7f68dbf0ef](https://user-images.githubusercontent.com/24503005/155256543-e3288bdc-df21-4e0c-96ce-e0a0f0448efa.png)

**Comment by huiyadanli** [comment]
3.5.0.46 是确认可以支持的版本。

你遇到的问题可能类似于：#287

**Comment by luotingv1** [comment]
> 3.5.0.46 是确认可以支持的版本。
> 
> 你遇到的问题可能类似于：#287

确实是这个问题   有个专门文件夹 要修改路径
