### ISSUE TITLE
win11 3.5.0.46版微信防撤回失效

### ISSUE THREAD

**Issue by Raoness** [huiyadanli/RevokeMsgPatcher#295]
大佬，本人电脑系统是win11，微信安装路径在C盘文档位置存放在了D盘，使用最新版防撤回补丁失效具体信息请看截图
![1](https://user-images.githubusercontent.com/49342307/156127771-9192742c-b56b-4090-8f17-a315230d20f8.png)
![2](https://user-images.githubusercontent.com/49342307/156127780-3bf9ed1e-e7df-45f8-ad9b-048aaecc45fb.png)
![3](https://user-images.githubusercontent.com/49342307/156127791-ae06ad3f-de37-4658-b978-833a8e7efee5.png)
![4](https://user-images.githubusercontent.com/49342307/156127806-f5e3e0f2-909c-49be-9165-2ac4a5ed7b1a.png)

**Comment by 2205794866** [comment]
行，我已经收到辣

**Comment by huiyadanli** [comment]
参考 #287 的解决方案，是一样的问题

**Comment by Raoness** [comment]
好的，已经解决了，谢谢大佬
