### ISSUE TITLE
微信[3.6.0.9]版本不支持防撤回。

### ISSUE THREAD

**Issue by wjf0214** [huiyadanli/RevokeMsgPatcher#297]
今天开机微信自动更新到【3.6.0.9】版本，安装防撤回补丁失败，多开补丁正常，图如下。
![image](https://user-images.githubusercontent.com/23102821/158002830-1c1f1462-7734-43d1-9abf-bfae1d3061f6.png)
![image](https://user-images.githubusercontent.com/23102821/158002851-a6bc9197-2de9-4147-abbe-d3170bbfba1e.png)
搜索issue，查询到 [#287](https://github.com/huiyadanli/RevokeMsgPatcher/issues/287)，并非是`非正确的目录`引起的问题，目录正确。猜测是3.6版本系列不支持。
如有需要补充的信息，可以回复联系，我可以补充。

**Comment by kaixinsoft** [comment]
求作者支持，谢谢。

**Comment by yaosj2k** [comment]
3.6.0.14 已经是公开版本了， 麻烦支持下

**Comment by ufoowan** [comment]
x64dbg按照作者提供的思路，发现dll中对应的字眼已经是修改的字眼，估计防撤回的方式变了

**Comment by huiyadanli** [comment]
有无对应 3.6 的安装包，或者直接本地打包一份发我

**Comment by huiyadanli** [comment]
> x64dbg按照作者提供的思路，发现dll中对应的字眼已经是修改的字眼，估计防撤回的方式变了

我测试就是老方法可以用，3.4的特征码依旧可以用在3.6上

**Comment by huiyadanli** [comment]
3.6的特征码已经支持，和3.4一模一样，又回到了老方法。

但是测试版本有个abtest，有些内容会出现两次，导致特征码没法正常匹配。

当前特征 3.6.0.14 验证没问题，其他我没有安装包无法测试。

**Comment by yaosj2k** [comment]
https://wss1.cn/f/7ulsdwqofzh

**Comment by ufoowan** [comment]
> 3.6的特征码已经支持，和3.4一模一样，又回到了老方法。
> 
> 但是测试版本有个abtest，有些内容会出现两次，导致特征码没法正常匹配。
> 
> 当前特征 3.6.0.14 验证没问题，其他我没有安装包无法测试。

点赞

**Comment by HappyJamie** [comment]
https://wss1.cn/f/7ulsdwqofzh 链接无了
