### ISSUE TITLE
请问特征码不符合是什么意思

### ISSUE THREAD

**Issue by JiaoBruce** [huiyadanli/RevokeMsgPatcher#298]
、
<img width="342" alt="1" src="https://user-images.githubusercontent.com/101682911/158499912-d1277de9-5e15-4942-a6b7-76e73f87a926.png">
3.6.0.14版本，说特征码匹配数1与期望的匹配数2不符合

**Comment by UI20114** [comment]
我也有这个问题

**Comment by feijihong** [comment]
![image](https://user-images.githubusercontent.com/27736975/158518947-1e5c2521-2712-4dcc-beea-ac44f46facd0.png)
刚刚更新微信客户端

**Comment by UI20114** [comment]
> 有无对应 3.6 的安装包，或者直接本地打包一份发我

发邮箱了

**Comment by UI20114** [comment]
> > > 有无对应 3.6 的安装包，或者直接本地打包一份发我
> > 
> > 
> > 发邮箱了
> 
> 似乎还在内测？无权限账号不能登录吗？

不是很清楚  微信官方那边的版本还是3.5  3.6是在一次使用中自己升级的   已经打包一份到你邮箱里了

**Comment by huiyadanli** [comment]
3.6的特征码已经支持，和3.4一模一样，又回到了老方法。

但是测试版本有个abtest，有些内容会出现两次，导致特征码没法正常匹配。

当前特征 3.6.0.14 验证没问题，其他我没有安装包无法测试。

**Comment by huiyadanli** [comment]
3.6.0.18 正式版已经放出，且原来的特征能够支持
