### ISSUE TITLE
> https://wss1.cn/f/7ulsdwqofzh 3.6.0.14

### ISSUE THREAD

**Issue by HappyJamie** [huiyadanli/RevokeMsgPatcher#302]
链接无了
> https://wss1.cn/f/7ulsdwqofzh 3.6.0.14

3.6.0.14 已经支持

_Originally posted by @huiyadanli in https://github.com/huiyadanli/RevokeMsgPatcher/issues/297#issuecomment-1070004074_

**Comment by huiyadanli** [comment]
你需要安装这个测试版本吗

**Comment by jason-liu475** [comment]
[3.6.0.18] 
![image](https://user-images.githubusercontent.com/25763344/159105119-ab217eaf-0eda-42ab-b115-05f6476b2078.png)

**Comment by huiyadanli** [comment]
> [3.6.0.18] ![image](https://user-images.githubusercontent.com/25763344/159105119-ab217eaf-0eda-42ab-b115-05f6476b2078.png)

来个安装包

**Comment by 845292785** [comment]
> > [3.6.0.18] ![image](https://user-images.githubusercontent.com/25763344/159105119-ab217eaf-0eda-42ab-b115-05f6476b2078.png)
> 
> 来个安装包

官网最新版本就是3.6.0.18
https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=page/faq/win/360/index&faq=win_360

**Comment by 845292785** [comment]
> > > [3.6.0.18] ![image](https://user-images.githubusercontent.com/25763344/159105119-ab217eaf-0eda-42ab-b115-05f6476b2078.png)
> > 
> > 
> > 来个安装包
> 
> 官网最新版本就是3.6.0.18 https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=page/faq/win/360/index&faq=win_360

但是很奇怪的一点是，我这里在微信应用内更新后，显示版本为3.6.0.18，无法安装补丁，随后使用官网的安装包再次覆盖安装，依然是3.6.0.18，但是补丁正常安装了

**Comment by huiyadanli** [comment]
> > > > [3.6.0.18] ![image](https://user-images.githubusercontent.com/25763344/159105119-ab217eaf-0eda-42ab-b115-05f6476b2078.png)
> > > 
> > > 
> > > 来个安装包
> > 
> > 
> > 官网最新版本就是3.6.0.18 https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=page/faq/win/360/index&faq=win_360
> 
> 但是很奇怪的一点是，我这里在微信应用内更新后，显示版本为3.6.0.18，无法安装补丁，随后使用官网的安装包再次覆盖安装，依然是3.6.0.18，但是补丁正常安装了

关注下右下角最新补丁信息有无获取，没获取到肯定不行。

3.6.0.18我测试已经能支持了

**Comment by LoinApex** [comment]
> > > > > [3.6.0.18] ![image](https://user-images.githubusercontent.com/25763344/159105119-ab217eaf-0eda-42ab-b115-05f6476b2078.png)
> > > > 
> > > > 
> > > > 来个安装包
> > > 
> > > 
> > > 官网最新版本就是3.6.0.18 https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=page/faq/win/360/index&faq=win_360
> > 
> > 
> > 但是很奇怪的一点是，我这里在微信应用内更新后，显示版本为3.6.0.18，无法安装补丁，随后使用官网的安装包再次覆盖安装，依然是3.6.0.18，但是补丁正常安装了
> 
> 关注下右下角最新补丁信息有无获取，没获取到肯定不行。
> 
> 3.6.0.18我测试已经能支持了

下载链接还有不?

**Comment by huiyadanli** [comment]
@LoinApex 你问的是[软件下载链接](https://github.com/huiyadanli/RevokeMsgPatcher/releases)吗？

**Comment by xx668888** [comment]
> @LoinApex 你问的是[软件下载链接](https://github.com/huiyadanli/RevokeMsgPatcher/releases)吗？

3.6.0.18 防撤回得下载地址

**Comment by LoinApex** [comment]
> > @LoinApex 你问的是[软件下载链接](https://github.com/huiyadanli/RevokeMsgPatcher/releases)吗？
> 
> 3.6.0.18 防撤回得下载地址

是的

**Comment by xx668888** [comment]
> > > @LoinApex 你问的是[软件下载链接](https://github.com/huiyadanli/RevokeMsgPatcher/releases)吗？
> > 
> > 
> > 3.6.0.18 防撤回得下载地址
> 
> 是的

我没有

**Comment by LoinApex** [comment]
> > > > @LoinApex 你问的是[软件下载链接](https://github.com/huiyadanli/RevokeMsgPatcher/releases)吗？
> > > 
> > > 
> > > 3.6.0.18 防撤回得下载地址
> > 
> > 
> > 是的
> 
> 我没有

翘首以盼大佬更新~

**Comment by xx668888** [comment]
> 



> > > > > @LoinApex 你问的是[软件下载链接](https://github.com/huiyadanli/RevokeMsgPatcher/releases)吗？
> > > > 
> > > > 
> > > > 3.6.0.18 防撤回得下载地址
> > > 
> > > 
> > > 是的
> > 
> > 
> > 我没有
> 
> 翘首以盼大佬更新~

是的

**Comment by huiyadanli** [comment]
@LoinApex 已经发了呀  https://github.com/huiyadanli/RevokeMsgPatcher/releases

3.6.0.18 的微信可以去微信官网下载

**Comment by LoinApex** [comment]
> @LoinApex 已经发了呀 https://github.com/huiyadanli/RevokeMsgPatcher/releases
> 
> 3.6.0.18 的微信可以去微信官网下载

![image](https://user-images.githubusercontent.com/15666939/159385621-9334f0e8-7dd5-44c6-9703-885f6480ba33.png)

RevokeMsgPatcher V1.2有提示这个信息~

**Comment by huiyadanli** [comment]
@LoinApex 没有自动找到微信目录，需要你手动选择微信所在目录

**Comment by LoinApex** [comment]
> @LoinApex 没有自动找到微信目录，需要你手动选择微信所在目录

这是我手动选择之后提示的信息～

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/159402316-bf1d1398-8a51-44cb-b4ec-1028b6d11a4c.png)

你应用路径都没有。。。肯定是没选啊

**Comment by LoinApex** [comment]
> ![image](https://user-images.githubusercontent.com/15783049/159402316-bf1d1398-8a51-44cb-b4ec-1028b6d11a4c.png)
> 
> 你应用路径都没有。。。肯定是没选啊

重新安装了一下微信，可以了， 谢谢大佬~

**Comment by HappyJamie** [comment]
想试试



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 18, 2022 10:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [huiyadanli/RevokeMsgPatcher] &gt; https://wss1.cn/f/7ulsdwqofzh 3.6.0.14 (Issue #302)




 
你需要安装这个测试版本吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
