### ISSUE TITLE
昨天最新版微信，今天不能防撤回了，而且那个ddl文件路径还需要自己手动添加，添加完安装补丁时报错：

### ISSUE THREAD

**Issue by 2258093686** [huiyadanli/RevokeMsgPatcher#303]
微信中：
特征比对:当前特征码匹配数[1]和期望的匹配数[2]不-致。
出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
2.如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作
者处理。
![image](https://user-images.githubusercontent.com/83654272/159196563-50f22c71-547c-4fd8-a030-3a858768295c.png)
![image](https://user-images.githubusercontent.com/83654272/159196574-68b42993-3792-45a5-93b6-f88e2692ff66.png)

**Comment by 2258093686** [comment]
特征比对:当前特征码匹配数[1]和期望的匹配数[2]不-致。
出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
2.如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作
者处理。

**Comment by bilibili98** [comment]
请更新补丁至最新版本，最新版本补丁实测可以应用于最新版本微信

**Comment by huiyadanli** [comment]
更新到最新版本，你的所有问题都会得到解决
