### ISSUE TITLE
特征比对:当前特征码匹配数[1]和期望的匹配数[2]不一致。

### ISSUE THREAD

**Issue by dcr327** [huiyadanli/RevokeMsgPatcher#308]
特征比对:当前特征码匹配数[1]和期望的匹配数[2]不一致。出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
⒉.如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作者处理。

**Comment by huiyadanli** [comment]
微信版本？

**Comment by dcr327** [comment]
3.6.0.18， 以前用过这个V1版本的，今天发现失效了。来下载新版本进行破解，然后提示上述信息。

已经尝试过重装wechat  同样不行

**Comment by HorrZzz** [comment]
同样的情况。

![1](https://user-images.githubusercontent.com/42233737/160110149-ffb09df3-096d-4c9e-9d64-8a0b9b89b6ae.png)

**Comment by rxl561** [comment]
同样的问题，昨天还能装上，今天重启后再装就出现上述问题

**Comment by q2119990** [comment]
![1](https://user-images.githubusercontent.com/41836297/160115371-966c8f12-24d4-4f14-b1b0-2b58fa454393.jpg)
一样的问题，重新装了微信还是不行。

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/160144871-00d6524f-07f2-4e3f-bca9-a640415049f6.png)
无限加载，这软件可以吃到windows的系统代理吗

**Comment by huiyadanli** [comment]
@SekiBetu 你速度太快了，刚刚那个版本提示文本有点问题，已经重新release了

**Comment by SekiBetu** [comment]
可以了

**Comment by q2119990** [comment]
可以了 谢谢

**Comment by dcr327** [comment]
可以了，感谢
