### ISSUE TITLE
[未支持版本]: 3.6.0.18

### ISSUE THREAD

**Issue by qq1986114** [huiyadanli/RevokeMsgPatcher#309]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.6.0.18

### 软件提示了什么？

无法装补丁

**Comment by huiyadanli** [comment]
支持的 #308

**Comment by filefi** [comment]
![image](https://user-images.githubusercontent.com/16501603/161073915-b4b2b933-2cf2-44ee-b055-36644d8787f6.png)

**Comment by huiyadanli** [comment]
> ![image](https://user-images.githubusercontent.com/16501603/161073915-b4b2b933-2cf2-44ee-b055-36644d8787f6.png)

没权限 or 微信正在运行

**Comment by filefi** [comment]
> > ![image](https://user-images.githubusercontent.com/16501603/161073915-b4b2b933-2cf2-44ee-b055-36644d8787f6.png)
> 
> 没权限 or 微信正在运行

WeChatWin.dll文件的属性被改为只读了，取消只读就可以成功安装补丁了。
