### ISSUE TITLE
微信闪退

### ISSUE THREAD

**Issue by Rany8864** [huiyadanli/RevokeMsgPatcher#313]
微信版本：3.60.18
最近突然发生了闪退的情况，点某个人的对话窗口时，微信会闪退。闪退的一般都是之前撤回过消息的聊天，把聊天记录删了就不会。估计可能是聊天记录损坏导致。不知道大佬能否修复

**Comment by huiyadanli** [comment]
我这边测试没出现这个问题。。

issue 暂时不关，看看有无类似的反馈
