### ISSUE TITLE
当前特征码匹配数[0]和期望的匹配数[1]不一致

### ISSUE THREAD

**Issue by wenhaolove** [huiyadanli/RevokeMsgPatcher#314]
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。

这个问题要怎么解决啊，微信版本是最新版本的，版本3.6.0.0，软件内置补丁信息已经是最新。我以前也安装过防撤回补丁的，不过后面失效了，不知道是不是这个原因。需要怎么解决啊。

**Comment by huiyadanli** [comment]
重新覆盖安装官网的最新版本微信，再使用本软件安装补丁试试。

**Comment by wenhaolove** [comment]
> 重新安装覆盖官网的最新版本信，再使用本软件安装微努力尝试。

好的好的，谢谢啦，已经成功了
