### ISSUE TITLE
[未支持版本]: 微软商店下载的qq和vx均不支持

### ISSUE THREAD

**Issue by h7ml** [huiyadanli/RevokeMsgPatcher#319]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

-  我确认当前使用的是最新版

### 微信/QQ 版本

qq9.5.4.28064

### 对应版本的下载地址

微软商店903DB504.46618D74B1ECA_9.5.4.0_x86__a99ra4d2cbcxa

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/55233292/164492236-66b09893-be93-4c91-b668-7ee7b71bfa53.png)

如上所示。已给与所有权限

**Comment by huiyadanli** [comment]
参考 #148 的方法
