### ISSUE TITLE
微信 2.7.1.88 不支持

### ISSUE THREAD

**Issue by Karonzhjr** [huiyadanli/RevokeMsgPatcher#32]
![QQ截图20191106205030](https://user-images.githubusercontent.com/44044519/68299712-3081c100-00d7-11ea-884a-02ad4d6d4810.png)

**Comment by huiyadanli** [comment]
已经更新，等待右下角自动获取最新补丁后，再点击防撤回

**Comment by Karonzhjr** [comment]
👌
