### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by zxpldt** [huiyadanli/RevokeMsgPatcher#320]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.6.0.18

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/76867967/165420587-449842cd-28c2-42e4-bb19-0b0c0c03758d.png)
提示
“---------------------------

---------------------------
对路径“C:\Program Files (x86)\Tencent\WeChat\[3.6.0.18]\WeChatWin.dll”的访问被拒绝。
---------------------------
确定   
---------------------------
”

**Comment by huiyadanli** [comment]
权限问题，检查当前用户对提示路径的文件是否有访问权限，文件是不是只读属性

通过 右键文件 - 属性 修改
