### ISSUE TITLE
[未支持版本]: 3.6.5.16

### ISSUE THREAD

**Issue by yaosj2k** [huiyadanli/RevokeMsgPatcher#321]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信测试版 3.6.5.16

### 对应版本的下载地址

链接：https://pan.baidu.com/s/1no8Ue61G_L7WuaHxXwcdAw?pwd=s186  

### 软件提示了什么？

![2022-04-28_170726](https://user-images.githubusercontent.com/260167/165718797-6c8ef0f4-e6b6-4399-b95a-020332e47db2.png)

**Comment by matresnan** [comment]
已经使用百度网盘提供的安装包，点击安装补丁依然会提示特征比对的问题，同时通用微信多开工具也尝试过，依然无法多开

**Comment by jayce1212** [comment]
更新后确实不work了，之前是work的。

**Comment by huiyadanli** [comment]
特征码没啥变化，主要是因为现在微信测试版abtest，会出现两块匹配的特征导致软件不能正常工作。。。

现在暂时通过“不那么通用的特征码”来支持 3.6.5.16。
