### ISSUE TITLE
请求关闭WechatBrowser功能

### ISSUE THREAD

**Issue by github-h** [huiyadanli/RevokeMsgPatcher#322]
sb微信现在打开连接默认唤起自己的垃圾浏览器

请求能否恢复到以前那种点击连接唤起系统默认浏览器的选项

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/166864865-02e3b2f0-d929-44ca-965b-63cc7a48e6b2.png)

最新版微信 3.6.0.18，左下角设置

**Comment by github-h** [comment]
> ![image](https://user-images.githubusercontent.com/15783049/166864865-02e3b2f0-d929-44ca-965b-63cc7a48e6b2.png)
> 
> 最新版微信 3.6.0.18，左下角设置

啊好的好的感谢！！没注意到
