### ISSUE TITLE
能否添加显示每条消息的发送时间功能？

### ISSUE THREAD

**Issue by liangpu597** [huiyadanli/RevokeMsgPatcher#324]
微信默认只是显示一段时间，对于每条消息不会显示，能否增加显示每条消息的发送时间戳功能？
这是它官方说的时间显示规则，一直需要知道每条聊天记录的发送时间，网上的做法都是合并转发（PS：没有找到其他方法），能否直接在每条消息上面直接显示时间，谢谢大佬！
![image](https://user-images.githubusercontent.com/23580110/167590525-d85229e6-40c6-4b8f-8162-e0672a32b624.png)

**Comment by huiyadanli** [comment]
也许能实现，但是我暂时没有找到如何实现这种操作

**Comment by liangpu597** [comment]
> 

好的，谢谢大佬！
