### ISSUE TITLE
[未支持版本]: 3.7.0.8

### ISSUE THREAD

**Issue by bootlegseahorse** [huiyadanli/RevokeMsgPatcher#329]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信测试版 3.7.0.8

### 对应版本的下载地址

https://www.aliyundrive.com/s/wQDNMVmtFED

### 软件提示了什么？

特征比对：当前特征码匹配数[1]和期望的匹配数[2]不一致。
![WindowClipping](https://user-images.githubusercontent.com/97839352/168417044-8f77ab9b-80cb-4394-9ad8-eacc86b5683f.png)

**Comment by huiyadanli** [comment]
[RevokeMsgPatcher.v1.4.beta.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/8693220/RevokeMsgPatcher.v1.4.beta.zip)

试试这个版本能否正常使用

**Comment by Tree-New-Beee** [comment]
> 

这包上传的对吗，下载了压缩包里显示的是1.3，也应用不了，提示特征码匹配不一致

**Comment by huiyadanli** [comment]
[RevokeMsgPatcher.v1.4.beta2.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/8693261/RevokeMsgPatcher.v1.4.beta2.zip)

上面那个打包有问题，还是老版本的，试试这个

**Comment by Tree-New-Beee** [comment]
可以安装补丁，但是微信打开弹出启动提示：由于环境异常，不能继续使用。打不开微信了

**Comment by Tree-New-Beee** [comment]
算了，先不搞了，毕竟是内测版本，内侧包应该有问题，谢谢啦

**Comment by huiyadanli** [comment]
[RevokeMsgPatcher.v1.4.beta3.去除校验.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/8693563/RevokeMsgPatcher.v1.4.beta3.zip)

加上了把校验去掉的功能

**Comment by kaixinsoft** [comment]
可以正常使用，谢谢。
