### ISSUE TITLE
v1.4微信patch无法获取功能

### ISSUE THREAD

**Issue by Howard20181** [huiyadanli/RevokeMsgPatcher#332]
![image](https://user-images.githubusercontent.com/40033067/168455896-122fca61-5f7e-445a-a59f-c05c8b6e6b7f.png)

**Comment by Howard20181** [comment]
QQ看起来是好的
![image](https://user-images.githubusercontent.com/40033067/168455915-d68cae9c-c4a3-47c8-a97f-c5d5f99552e1.png)
Tim
![image](https://user-images.githubusercontent.com/40033067/168455921-a66ab42f-ed97-4d71-a168-d3b4c6b27a49.png)

**Comment by huiyadanli** [comment]
看样子是没兼容好。。。

现在1.4加了个新的微信特征点替换后，3.7.08 以前的版本都不支持了

**Comment by huiyadanli** [comment]
修复了，重新下载试试

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.4

**Comment by Howard20181** [comment]
看起来没问题了
