### ISSUE TITLE
微信 对方正在输入 功能

### ISSUE THREAD

**Issue by Lvbuqing** [huiyadanli/RevokeMsgPatcher#333]
是否能去掉我本地的输入功能

pc微信端，别人发消息过来 我看的时候 回复别人，打字中，对方微信会显示 对方正在输入...

能否让对方不显示这个  对方正在输入...

**Comment by huiyadanli** [comment]
小技巧：收到消息后10s再打字输入，就不会有这个显示了

我能力有限，不准备做太多额外的feature，专心做防撤回。
