### ISSUE TITLE
1.4版本无法检测到微信应用

### ISSUE THREAD

**Issue by ATAKing1023** [huiyadanli/RevokeMsgPatcher#334]
微信版本：3.3.0.115
![image](https://user-images.githubusercontent.com/26701496/168559708-7bac8135-e355-4f83-a237-4036d97eb5a6.png)

**Comment by ATAKing1023** [comment]
> 1.3版本也检测不到吧。。
> 
> 原因应该是你没有使用安装版的微信，注册表种没有微信的安装路径信息，导致这种情况。
> 
> 手动选择目录即可

@huiyadanli 回退到1.3试了一下能检测到，是安装版的。另外我用1.4发现TIM的补丁安装状态也是错误的（显示未安装补丁 但是已经安装了）

**Comment by huiyadanli** [comment]
你当前使用的微信版本是什么？微信 3.5 版本后 目录有变化，1.4版本貌似没兼容老版本的目录判断。。

**Comment by ATAKing1023** [comment]
> 你当前使用的微信版本是什么？微信 3.5 版本后 目录有变化，1.4版本貌似没兼容老版本的目录判断。。

@huiyadanli 3.3.0.115

**Comment by ATAKing1023** [comment]
> 

@huiyadanli 启动报错：
![image](https://user-images.githubusercontent.com/26701496/168963316-f882421d-102b-4438-be8c-6d59000c385e.png)

**Comment by zty2019** [comment]
遇到了同样的问题，您提供的release版本也一样启动报错，微信版本3.6.0.18，用1.3版本成功安装补丁，1.4版本识别不到微信

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2353054650

试试这个版本

**Comment by ATAKing1023** [comment]
@huiyadanli 这个版本没有问题了，感谢
