### ISSUE TITLE
[未支持版本]: 3.7.0.19

### ISSUE THREAD

**Issue by yaosj2k** [huiyadanli/RevokeMsgPatcher#336]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

微信测试版 3.7.0.19

### 对应版本的下载地址

https://pan.baidu.com/s/1P4QWL82YcbHzVnFfsi9uHQ?pwd=nmsf

### 软件提示了什么？

![2022-05-18_143240](https://user-images.githubusercontent.com/260167/168972835-6340505d-bc8a-4163-a9bc-a7ae02e0e7c1.png)

**Comment by kaixinsoft** [comment]
![image](https://user-images.githubusercontent.com/8220003/168988862-c991c4cb-93d1-4381-aa6e-b5b41f63c3a6.png)

**Comment by Michaelxia6** [comment]
3.7.0.8开始就不支持了

**Comment by yaosj2k** [comment]
> 3.7.0.8开始就不支持了

1.4是支持3.7.0.8这个版本的

**Comment by huiyadanli** [comment]
看样子是去除校验这个特征变化了

**Comment by xiaoxinqqtang** [comment]
所以有解决的办法了吗？

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2358778505

这个版本支持了。。

补丁热加载的地址有点问题，只能下新版本了

**Comment by yaosj2k** [comment]
> https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2358778505
> 
> 这个版本支持了。。
> 
> 补丁热加载的地址有点问题，只能下新版本了

可以用了， 多谢！
