### ISSUE TITLE
[未支持版本]: 3.7.0.23

### ISSUE THREAD

**Issue by fdj94** [huiyadanli/RevokeMsgPatcher#341]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信PC端正式版 3.7.0.23

### 软件提示了什么？

今天早上，微信提示升级，手贱的点了升级，结果发现无论是防撤回1.3，还是1.4都安装不了了，1.3的没有截图，但一开始尝试的就是1.3的版本，确实是无法安装，错误也是特征码不匹配

![1](https://user-images.githubusercontent.com/22268635/169737038-81cf80bb-fca3-4d17-9e53-b29b23b8fbaa.png)
![2](https://user-images.githubusercontent.com/22268635/169737041-92b0e3f0-805b-48df-b476-e57c6cb03f39.png)

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2358778505

用这个版本试试

**Comment by fdj94** [comment]
可以了，十分感谢，虽然说微信的3.7.0.23的bug已经把我强制劝退了，但还是要感谢作者

**Comment by Michaelxia6** [comment]
卧槽，你哪里来的3.7.0.23安装包，可以发我一份吗谢谢
