### ISSUE TITLE
RevokeMsgPatcher 已停止工作

### ISSUE THREAD

**Issue by 972579171** [huiyadanli/RevokeMsgPatcher#342]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

972579171

### 对应版本的下载地址

https://github.com/huiyadanli/RevokeMsgPatcher

### 软件提示了什么？

![QQ图片20220524145954](https://user-images.githubusercontent.com/106140949/169968618-ef5dc615-99d5-4063-81ba-23016535175e.png)
一打开就停止是砸回事啊？

**Comment by huiyadanli** [comment]
软件版本是1.3 吗？

**Comment by huiyadanli** [comment]
大部分人都没有遇到你这个情况。。。
暂时没回复的话，我先close issue了。

建议通过windows事件查看器查看具体停止工作的报错，把报错贴上来。
