### ISSUE TITLE
1.5版本无法安装补丁

### ISSUE THREAD

**Issue by cnguu** [huiyadanli/RevokeMsgPatcher#344]
![image](https://user-images.githubusercontent.com/10758182/170426416-0b0dcdc1-1e2c-4e9e-b66e-892074883eff.png)

操作流程：
1、下载解压
2、右键管理员运行
3、点击安装补丁
4、弹出如图提示

**Comment by Mixlining** [comment]
你引进安装过补丁了，见我的issue：https://github.com/huiyadanli/RevokeMsgPatcher/issues/346

**Comment by cnguu** [comment]
@Mixlining 也就是说安装过的需要先还原，再更新新版打补丁

**Comment by huiyadanli** [comment]
> @Mixlining 也就是说安装过的需要先还原，再更新新版打补丁

你补丁实际已经打上了，只是界面按钮和点了以后的提示有问题。。。不影响实际使用，1.6版本会修复这个问题

这个bug是1.4版本的性能优化造成的。。。
