### ISSUE TITLE
可否更新下Wiki? 最新版本出错.

### ISSUE THREAD

**Issue by xx10n31y** [huiyadanli/RevokeMsgPatcher#345]
最新版本[3.7.0.26]跟着Wiki操作后, 替换掉原有的 `WeChatWin.dll` 后会出现

![image](https://user-images.githubusercontent.com/57975788/170505112-4c6a7a15-a662-4bd0-b8b7-e577ff41b648.png)

**Comment by huiyadanli** [comment]
Wechat.exe 加入了文件校验

关键词 show_verify_error

修改 jne -> jmp

![image](https://user-images.githubusercontent.com/15783049/170507328-7cffd961-f979-4e55-87eb-07d72eef6d72.png)

**Comment by xx10n31y** [comment]
感谢

**Comment by xx10n31y** [comment]
> Wechat.exe 加入了文件校验
> 
> 关键词 show_verify_error
> 
> 修改 jne -> jmp
> 
> ![image](https://user-images.githubusercontent.com/15783049/170507328-7cffd961-f979-4e55-87eb-07d72eef6d72.png)

好像最新版本又没有找到这个特征码了?

**Comment by huiyadanli** [comment]
应该还有的吧，因为我的特征没变化还能继续使用。。。

可以用winhex搜索 83C40884C0753F68 （注意勾选通配符3F），然后再在 x32dbg 通过对应的文件偏移位置进行定位

**Comment by xx10n31y** [comment]
> 应该还有的吧，因为我的特征没变化还能继续使用。。。
> 
> 可以用winhex搜索 83C40884C0753F68 （注意勾选通配符3F），然后再在 x32dbg 通过对应的文件偏移位置进行定位

是对 `wechatwin.dll` 用winhex打开后, 进行`hex`搜索吗, 我查找到后拿offset到x32dbg进行定位, 之后把上一个 `jne` 改成` jmp`, 还是会报环境异常. 

![image](https://user-images.githubusercontent.com/57975788/171318237-2b81da9f-3e1d-4bad-8615-1f641f31f4ff.png)

![image](https://user-images.githubusercontent.com/57975788/171318385-a8696549-4b47-4b3b-82d4-6128d0b3fbee.png)
![image](https://user-images.githubusercontent.com/57975788/171318522-251ef51c-fb5a-4850-b9a2-5eb3a5b39952.png)
