### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by Mixlining** [huiyadanli/RevokeMsgPatcher#346]
前提：已经安装过补丁
![image](https://user-images.githubusercontent.com/91776353/170691815-d368eaf7-4dc0-4e67-9c81-70746c2f4975.png)
然后随机点击一下QQ，TIM等后面的选项，再点回微信
![image](https://user-images.githubusercontent.com/91776353/170692024-8b7ff787-93b8-445d-b4bb-53acef9aa936.png)

**Comment by Mixlining** [comment]
不过无伤大雅

**Comment by AdminQQZ** [comment]
不改

**Comment by huiyadanli** [comment]
@Mixlining  感谢你详细的复现方法，帮助我快速定位了问题。

最新的编译版本已经修复了这个问题 https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2400699209

**Comment by huiyadanli** [comment]
已经替换了1.5版本的下载链接（懒得迭代新版本号了。。
