### ISSUE TITLE
【求助】由于环境异常，不能继续使用

### ISSUE THREAD

**Issue by onlyyou3166** [huiyadanli/RevokeMsgPatcher#347]
![rrr](https://user-images.githubusercontent.com/106523602/170959979-cbd6b191-09f5-4f0d-a42a-c420c34d4453.jpg)
 使用1.5版本安装补丁后，启动微信（版本3.7.0.23）提示“由于环境异常，不能继续使用，请从官方渠道重新下载安装后使用”。

**Comment by huiyadanli** [comment]
对应的安装包有没有，我试试。应该是去校验的功能没生效

**Comment by rffanlab** [comment]
微信的问题吧。。。

**Comment by huiyadanli** [comment]
@rffanlab 微信在 3.7 版本加入了文件校验功能

**Comment by shydyl** [comment]
您好，请问我就是3.7.0.26版本，还是有这个启动提示，这是怎么回事呢？

**Comment by huiyadanli** [comment]
> 您好，请问我就是3.7.0.26版本，还是有这个启动提示，这是怎么回事呢？

下载最新的1.5补丁安装上去校验的功能，或者直接微信官网下载最新的3.7.0.29吧，官方已经去掉这个校验了
