### ISSUE TITLE
对wechatwin.dll的访问被拒绝

### ISSUE THREAD

**Issue by excper** [huiyadanli/RevokeMsgPatcher#348]
![image](https://user-images.githubusercontent.com/21673620/171044283-7faf1fd8-bab6-4294-b511-eab7909ea231.png)
win10x64版本
3个功能任选一个都是如此
以管理员身份运行也是如此
微信已关
unlocker微信文件夹无任何占用情况
![image](https://user-images.githubusercontent.com/21673620/171044520-83ebc031-6365-4216-8496-1f228bdff902.png)

**Comment by huiyadanli** [comment]
提示这个错误不是文件被占用，而是文件的权限级别的问题

1. 以管理员权限启动补丁软件
2. 打开 WeChatWin.dll 的属性界面，确认取消勾选”只读“。在安全选项卡下，确认当前Windows登录用户有对这个文件的读写权限

**Comment by excper** [comment]
解决了，谢谢大佬。可否考虑在后续版本中加入自动解除只读的命令。包括wechat.exe wechatwin.dll都勾选了只读。

> 提示这个错误的原因不是文件被占用，而是文件的权限级别的问题
> 
> 1. 以管理员权限启动补丁软件
> 2. 打开 WeChatWin.dll 的属性界面，确认取消勾选”只读“。在安全选项卡下，确认当前Windows登录用户有对这个文件的读写权限
