### ISSUE TITLE
微信最新3.7.0.26检测到环境异常无法使用

### ISSUE THREAD

**Issue by 295480035** [huiyadanli/RevokeMsgPatcher#351]
![image](https://user-images.githubusercontent.com/20810427/171163209-1d788ea1-21b5-4d4d-bf28-10384b366094.png)

**Comment by huiyadanli** [comment]
提供一个3.7.0.26的版本的下载链接或者打包

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/171207321-933a58f5-27f8-49ee-bde8-69ff96fdad54.png)

我测试没有问题，不过多开好像失效了。

回到你的问题上。

3.5 以后的微信本体文件都在这个目录下 `\WeChat\[3.7.x.xx]` ，而你的 `\WeChat` 目录下也能被识别到微信（3.7.0.26）， 说明升级安装可能存在问题。

解决方法也很简单，三种方法任选其一：

1. 重装微信
2. 删除 `\WeChat` 目录下的 `WeChatWin.dll`
3. 手动修改补丁的应用目录，指向正确的目录`\WeChat\[3.7.0.26]`

**Comment by jdinosaur** [comment]
我也遇到了同样的问题
<img width="442" alt="image" src="https://user-images.githubusercontent.com/37896505/171308498-6d9dd15c-e0c1-4252-83ad-7f3756f33d53.png">

**Comment by larrylinli** [comment]
我早上刚发现系统自动更新了（3.7.0.26）。重新下载的1.5版。一切正常
![微信截图_20220601091938](https://user-images.githubusercontent.com/46351803/171309121-0357f93e-b521-4397-ae60-0555a4bb21c6.png)
。

**Comment by huiyadanli** [comment]
@jdinosaur 去除校验的选项必须勾选

**Comment by huiyadanli** [comment]
你这个版本好奇怪，没见过这种情况。。。重新下载一个版本安装试试？
