### ISSUE TITLE
大佬，52上有大神出了一个.dll文件，可以有撤回提示。

### ISSUE THREAD

**Issue by ccccerr** [huiyadanli/RevokeMsgPatcher#352]
[测试过3.7.0.26是可以用的，大佬研究下？也给咱们更新下？

**Comment by ccccerr** [comment]
![微信图片_20220531231204](https://user-images.githubusercontent.com/89056765/171208349-3cbbf07a-110a-4801-b186-2687031053d4.png)

**Comment by huiyadanli** [comment]
工作原理不一样，人家的是hook的，能做的事情可多了，同时风险也高一些。

我这个只是存粹的辅助16进制修改器，能做到事情十分局限，其中核心的修改特征也不一定是我发现并提供的，你可以直接看作是两种不同的工具。曾经能够保留防撤回提示的修改点暂时找不到了:joy:

**Comment by ccccerr** [comment]
是会有封号的风险吗？

**Comment by yaosj2k** [comment]
00000001        0.00000000        [9092] [云在天吾爱破解论坛52PoJie.cn，禁止转载！！！禁止某些网站修改！！！]       
00000002        0.01290770        [9092] LoadHook Entry.       
00000003        1.01456308        [9092] WeChatWin.dll=62060000.       
00000004        1.01463759        [9092] CodeSectionSize=01CE6200. dwBaseOfCode=00001000       
00000005        1.24955189        [9092] pHookTipsCode SearchCode ok [6248D762].       
00000006        1.24959528        [9092] HookRevokemsgCode SearchCode ok [6248D880].       
00000007        1.25072742        [9092] HookRevokemsgCode Ok        
00000008        1.25076509        [9092] LoadHook End.       
00000009        1.31532037        [10892] RecursiveDirectoryCreate( C:\Users\xxx\AppData\Roaming\Tencent\WeChat\xweb\crash directory exists )       
00000010        10.90072060        [10892] ############ OnBeforeBrowse url=weixin://resourceid/prepare/app.html        
00000011        21.13088608        [10892] ############ OnBeforeBrowse url=https://channels.weixin.qq.com/web/pages/home?is_preload=1&xlab_enable_finder_home=1&preload_id=5xxxxxxxxxxxx658&exportkey=nxxxxxxxxxxmrxY&pass_ticket=lVkxxxxxxxH8z82L93TwJXdI2rzBH2OKAHDo&wx_header=0        
00000012        21.78934097        [10892] ############ OnBeforeBrowse url=https://channels.weixin.qq.com/web/pages/feed?is_preload=1&xlab_enable_finder_home=1&preload_id=12834243&exportkey=n_Caaaazohf%2Fkyaaaaassdfdasfadsf2FHfdasf&wx_header=0        
00000013        34.17996597        [9092] <sysmsg type="revokemsg"><revokemsg><session>wxxxxxxxxx2</session><msgid>1ssss7</msgid><newmsgid>7534021005949429111</newmsgid><replacemsg><![CDATA[銆宮s1111銆嶅凡鍥炴敹涓?鍓囪▕鎭痌]></replacemsg></revokemsg></sysmsg>       
00000014        34.17998886        [9092] [Msg] name=6ssss8 session=wxxxxxxxxx2 name=       
00000015        41.90501785        [14956] XWeb createBrowser        
00000016        41.94222260        [14956] XWebBrowserDelegate getBrowserHwnd        
00000017        41.94259644        [14956] XWebBrowserDelegate loadUrl =http://servicewechat.com/preload/0/page-frame.html       
00000018        41.97482681        [14956] XWeb createBrowser        
00000019        41.99008942        [14956] XWebBrowserDelegate getBrowserHwnd        
00000020        41.99020004        [14956] XWebBrowserDelegate loadUrl =http://servicewechat.com/preload/0/page-frame.html       

好像大致原理是这样， 不知风险有多大

**Comment by saizo-zhao** [comment]
这款会失效，不知道毛病在哪儿

**Comment by serfend** [comment]
或许可以尝试找到weak_msg对应的函数，在data段填充一个汇编，在原revoke_msg的jmp跳转到该汇编中执行，然后再跳回原逻辑
```assembly
lea rdi,b'{user}撤回了一条消息:{link_to_msg}'
...
call weak_msg_tip
...
ret
```

**Comment by 10fun** [comment]
不一定要撤回提示，在撤回的对话中加个标识也可以

**Comment by troublewind** [comment]
lz能丢个链接吗，都搜不到相关帖子

**Comment by 6Tom** [comment]
链接
[www.52pojie.cn/thread-1640295-1-1.html](url)

**Comment by huiyadanli** [comment]
当前最新的 3.7 以上版本（3.7.0.30、3.7.5.23）重新开始支持撤回提示。
