### ISSUE TITLE
微信正式版3.7.0.27无法使用

### ISSUE THREAD

**Issue by Michaelxia6** [huiyadanli/RevokeMsgPatcher#353]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.7.0.27

### 软件提示了什么？

![Snipaste_2022-06-01_13-29-51](https://user-images.githubusercontent.com/86915639/171334529-621a267f-458a-4510-aca9-4547b94c3d3a.png)

**Comment by huiyadanli** [comment]
你这个 3.7.0.27 版本是怎么来的。。有无安装包？

官网下载的正式版 3.7.0.26 是支持的
#351

**Comment by Leakless** [comment]
> 你这个 3.7.0.27 版本是怎么来的。。有无安装包？
> 
> 官网下载的正式版 3.7.0.26 是支持的 #351

微信今天官网提供的版本就是3.7.0.27
![image](https://user-images.githubusercontent.com/6134641/171343666-da4b5a6d-6596-4a64-8c51-883a9b9b430e.png)
![image](https://user-images.githubusercontent.com/6134641/171343760-cafbdaa4-6be0-4d2e-8fdd-ba2c3ae28ce9.png)

**Comment by Pluto974** [comment]
3.7.0.27，实测不勾选去除校验可以

**Comment by MarkLily** [comment]
> 😂其实又更新了一个版本，晚上我看看
> 
> 你看3.7.0.26 -> 3.7.0.27 是官方自己把胆怯的逻辑给干掉了？

现在都变成 3.7.0.29啦！！！太快了！
