### ISSUE TITLE
微信3.7.0.26安装防撤回后不能打开

### ISSUE THREAD

**Issue by ChangGuo6716** [huiyadanli/RevokeMsgPatcher#354]
![image](https://user-images.githubusercontent.com/35018286/171342089-9e01f452-7bdd-438c-8193-885932998b9f.png)
提示：由于环境异常，不能继续使用
而且刚刚下载的最新版防撤回软件也没有去校验的选项

**Comment by dejiesd** [comment]
应该是WechatWin.dll文件损坏了，去官网下载安装程序修复一下就好

**Comment by ChangGuo6716** [comment]
最新进展，从官网下载重新安装后，勾选去校验会有错误提示，不勾选之后可以正常运行但是没有撤回提示，如图
![image](https://user-images.githubusercontent.com/35018286/171350622-08f24714-6233-48c6-b3a9-32b736a99f0e.png)

**Comment by huiyadanli** [comment]
#351 一个和你一样情况的用户。。。

你们的微信不知道为啥和我这边安装的微信，整个目录结构都不一样。。重新下载最新版本微信安装试试？

**Comment by xx10n31y** [comment]
> #351 一个和你一样情况的用户。。。
> 
> 你们的微信不知道为啥和我这边安装的微信，整个目录结构都不一样。。重新下载最新版本微信安装试试？

其实就是旧文件的问题, 我重命名已存在版本的文件夹然后重新安装就可以了. #345

**Comment by dejiesd** [comment]
2022.6.1新安装的微信把校验取消勾选就可以

**Comment by huiyadanli** [comment]
@ChangGuo6716 撤回提示很久以前就没了。。

**Comment by dejiesd** [comment]
> > 2022.6.1新安装的微信把校验取消勾选就可以
> 
> 我就是这样操作的，但是进去以后没有撤回提示了，看我上面新发的图片

撤回提示已经没有了

**Comment by Michaelxia6** [comment]
> > 2022.6.1新安装的微信把校验取消勾选就可以
> 
> 我就是这样操作的，但是进去以后没有撤回提示了，看我上面新发的图片

撤回提示早就没了
