### ISSUE TITLE
连续收到官方的安全提醒

### ISSUE THREAD

**Issue by reason84** [huiyadanli/RevokeMsgPatcher#357]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

3.6.018

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/59996188/171532200-fabdc609-41b3-433b-b942-1fb72ca71ae5.png)
小白请问，是否真的有被第三方读取的可能？还是官方过于敏感了呢？

**Comment by huiyadanli** [comment]
先放这里看看有没有类似的反馈。

官方这么提醒你肯定是有原因的，不过大概率不是本补丁造成的。

**Comment by reason84** [comment]
感谢回复，请问有没有什么办法排查一下，是哪个软件或者插件影响的呢？

**Comment by huiyadanli** [comment]
我也不知道，因为没遇到过这种情况。

可以先换台电脑登录试试，看看还有没有持续的提示。没有的话可以确认是你电脑上程序的问题，如果还有持续提示，那可能就是你的账号有问题了。。

1. 可以重点关注下有没有什么程序或者插件在hook微信。一些微信辅助之类的工具。
2. 关注下有没有什么奇怪的常驻进程。

**Comment by xx10n31y** [comment]
没有遇到
