### ISSUE TITLE
去除校验 检测的问题

### ISSUE THREAD

**Issue by xchsdo** [huiyadanli/RevokeMsgPatcher#359]
安装全部补丁后，再次打开软件依旧显示  去除校验  可使用，又或者是每次打开软件的时候 都会有  去除校验，然后切换下其他应用，在回到微信，去除校验的选项又没有了，要修复下这个  去除校验 的检测方法了

微信版本：3.7.0.29
软件版本：1.5

**Comment by huiyadanli** [comment]
最新编译版本已经修复这个问题

https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2448013916

**Comment by xchsdo** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by xchsdo** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
