### ISSUE TITLE
不知道哪条消息被对方撤回

### ISSUE THREAD

**Issue by wanqiuluoye** [huiyadanli/RevokeMsgPatcher#36]
不知道哪条消息是被对方撤回的消息，这样很不友好，可以知道是哪条消息是已撤回的最好。

**Comment by guozc09** [comment]
我也有同样的问题。看了一下源码，貌似只是修改了微信 revokeMsg 那里的跳转指令，je --> jmp，不让其进入防撤回的流程就没有后续的操作了，可参考 https://www.cnblogs.com/meowv/p/11428772.html 。如果需要提示的话可能需要一些其他操作才可以，比如在 “revokeMsg” 的地方想办法执行一下“xxx 撤回了一条消息的提示”，然后再跳转回来。期待各位大佬们的完善版本。

**Comment by wanqiuluoye** [comment]
看不懂……新入编程大军，初学者。期待完善版本。

**Comment by DearBo7** [comment]
+1,期待大佬们完善版本。

**Comment by Varorbc** [comment]
期待加入这个功能

**Comment by Dragon-Yu** [comment]
可以参考WechatTweak，这个mac 微信的防撤回是有撤回标识的

**Comment by Weenie** [comment]
> 
> 
> 我也有同样的问题。看了一下源码，貌似只是修改了微信 revokeMsg 那里的跳转指令，je --> jmp，不让其进入防撤回的流程就没有后续的操作了，可参考 https://www.cnblogs.com/meowv/p/11428772.html 。如果需要提示的话可能需要一些其他操作才可以，比如在 “revokeMsg” 的地方想办法执行一下“xxx 撤回了一条消息的提示”，然后再跳转回来。期待各位大佬们的完善版本。

中间加一步jmp到撤回提示，在提示后jmp到修改所指的指令处

**Comment by Weenie** [comment]
> 
> 
> > 我也有同样的问题。看了一下源码，貌似只是修改了微信 revokeMsg 那里的跳转指令，je --> jmp，不让其进入防撤回的流程就没有后续的操作了，可参考 https://www.cnblogs.com/meowv/p/11428772.html 。如果需要提示的话可能需要一些其他操作才可以，比如在 “revokeMsg” 的地方想办法执行一下“xxx 撤回了一条消息的提示”，然后再跳转回来。期待各位大佬们的完善版本。
> 
> 中间加一步jmp到撤回提示，在提示后jmp到修改所指的指令处

关键是，还得去找提示在是第几步

**Comment by huiyadanli** [comment]
> 我也有同样的问题。看了一下源码，貌似只是修改了微信 revokeMsg 那里的跳转指令，je --> jmp，不让其进入防撤回的流程就没有后续的操作了，可参考 https://www.cnblogs.com/meowv/p/11428772.html 。如果需要提示的话可能需要一些其他操作才可以，比如在 “revokeMsg” 的地方想办法执行一下“xxx 撤回了一条消息的提示”，然后再跳转回来。期待各位大佬们的完善版本。

@guozc09 @Varorbc  @Weenie 

最近看到了一种思路，可以做到防撤回并保留撤回提示。最近更换修改点来做到同样的效果
https://www.52pojie.cn/thread-1082540-1-1.html
https://www.52pojie.cn/thread-1048634-1-1.html

**Comment by huiyadanli** [comment]
[0.8版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/0.8) 已经 Release，微信将从 2.8.0.112 开始支持显示撤回提示。

有一个小缺点就是无法精准的看到具体撤回了哪一条。

**Comment by Varorbc** [comment]
@huiyadanli 能把原理发出来看看嘛，链接没有权限看

**Comment by zzqxztc** [comment]
andorid基于一些注入的框架模块，如微x模块，支持防撤回。
而且，还有提示，对方撤回了上一条信息，已经阻止。
不知道，是什么思路
但微信 PC 和 android版的 架构可能有区别。

**Comment by huiyadanli** [comment]
> @huiyadanli 能把原理发出来看看嘛，链接没有权限看

具体原理作者也没说，也是成果向的给出了修改的位置。

个人理解：原先修改的地方是在触发到撤回方法时，直接跳出。现在修改的地方是在撤回方法已经执行，撤回提示已经显示，然后要删除聊天记录的时刻直接跳出。

**Comment by whc2001** [comment]
请问QQ和TIM有可能也支持吗，现在日常用电脑版TIM，还得开着手机版

**Comment by c704501026** [comment]
希望出个制作撤回后有提示的教程，不知道撤回了后是哪条消息就很头疼。

**Comment by Githubbili** [comment]
大佬，还是没有显示撤回该消息
![Snipaste_2022-11-29_18-13-16](https://user-images.githubusercontent.com/21958998/204501802-8a87401c-5c7d-4ae1-ae21-45b4dca64cc3.png)

![微信图片_20221129181250](https://user-images.githubusercontent.com/21958998/204501744-5222817c-4359-4daf-87f9-12b2fe9dd4f0.png)

**Comment by 3234374354** [comment]
> 大佬，还是没有显示撤回该消息 ![Snipaste_2022-11-29_18-13-16](https://user-images.githubusercontent.com/21958998/204501802-8a87401c-5c7d-4ae1-ae21-45b4dca64cc3.png)
> 
> ![微信图片_20221129181250](https://user-images.githubusercontent.com/21958998/204501744-5222817c-4359-4daf-87f9-12b2fe9dd4f0.png)

好像是你的微信版本不支持提示功能

**Comment by magihub** [comment]
![image](https://user-images.githubusercontent.com/77531918/219921968-64b60355-c4de-4384-9b02-6c59d0ff7eee.png)
3.9版本的微信，看起来也不支持撤回提示呀。我看到52pojie上的贴图，貌似3.7的支持撤回提示。
![image](https://user-images.githubusercontent.com/77531918/219921992-f9ea90de-76c1-4745-914e-4f92652b61f6.png)

**Comment by tutdahai** [comment]
微信最新版仍然不支持防撤回带提示吗

**Comment by CatStarBubble** [comment]
每个版本特征码不一样,怎么快读定位特征码啊？现在是3.9 版本了。

**Comment by Regina-y** [comment]
希望微信撤回能在对应消息下添加已撤回的标记

**Comment by Caijiqwq** [comment]
现在3.9.11.17无法看到提示

**Comment by hjqs0605** [comment]
4.0版本，对方撤回没提示呢？

**Comment by l794** [comment]
我这目前（2025年8月5日19点03分）微信最新版（4.0.6.33），防撤回功能能正常用，就是别人已经撤回了消息，但没有提示，无法知道到底撤回了哪条消息

<img width="734" height="403" alt="Image" src="https://github.com/user-attachments/assets/ac4e77fe-b422-458a-9cd7-7c948629ba41" />

**Comment by l794** [comment]
> 我这目前（2025年8月5日19点03分）微信最新版（4.0.6.33），防撤回功能能正常用，就是别人已经撤回了消息，但没有提示，无法知道到底撤回了哪条消息

<img width="734" height="403" alt="Image" src="https://github.com/user-attachments/assets/d8ca7793-4104-4100-b36f-86731c99c152" />
![Image](https://github.com/user-attachments/assets/4ca0c98f-ef4a-4cff-8fd9-52d8c579cee8)

**Comment by l794** [comment]
> 我这目前（2025年8月5日19点03分）微信最新版（4.0.6.33），防撤回功能能正常用，就是别人已经撤回了消息，但没有提示，无法知道到底撤回了哪条消息
> 
> <img alt="图像" width="734" height="403" src="https://private-user-images.githubusercontent.com/224773898/474473919-ac4e77fe-b422-458a-9cd7-7c948629ba41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQzOTI0NzEsIm5iZiI6MTc1NDM5MjE3MSwicGF0aCI6Ii8yMjQ3NzM4OTgvNDc0NDczOTE5LWFjNGU3N2ZlLWI0MjItNDU4YS05Y2Q3LTdjOTQ4NjI5YmE0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNVQxMTA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGEyZTJlYjc2ZmE0OTRiNjdkYWVmYTE0NjA2N2NhNjIzNjRjYjEwNTBhMjM2NGFlM2Y0ZDU4YzI5MDFhMDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.akw6UP-OWhKP5HC41XPYczdoLo4RMzl1klJoiGOJKzk">

![Image](https://github.com/user-attachments/assets/0f71938d-4d65-40e0-bd0f-2fafe916902e)

**Comment by ZenoLeee** [comment]
希望可以出一个教程, 还有就是可以显示撤回了哪条信息
