### ISSUE TITLE
特征比对:当前特征码匹配数[0] 和期望的匹配数2不一致

### ISSUE THREAD

**Issue by yinzhenkun** [huiyadanli/RevokeMsgPatcher#361]
![image](https://user-images.githubusercontent.com/41945280/172743947-2e690451-e8ac-465f-adc6-8a26f9bb9af4.png)

Windows 微信版本3.7.0.29

**Comment by huiyadanli** [comment]
请下载最新版本 
https://github.com/huiyadanli/RevokeMsgPatcher/releases

https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2448013916
