### ISSUE TITLE
[未支持版本]: 1.5

### ISSUE THREAD

**Issue by CaufieldZ** [huiyadanli/RevokeMsgPatcher#363]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

3.7.0.30

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/32790971/173237819-b213c366-7b1c-4eba-b438-0e23019fbd39.png)
对路径\wechatwin.dll的访问被拒绝

**Comment by huiyadanli** [comment]
参考：https://github.com/huiyadanli/RevokeMsgPatcher/issues/348

**Comment by sixsix12** [comment]
推出WeChat用管理员启动
