### ISSUE TITLE
防撤回功能没有起作用

### ISSUE THREAD

**Issue by tjubuntu** [huiyadanli/RevokeMsgPatcher#367]
问题描述：
![Snipaste_2022-06-16_16-20-49](https://user-images.githubusercontent.com/5626367/174026358-832eb361-52f0-4021-adce-95764b35603d.png)
微信版本：
![image](https://user-images.githubusercontent.com/5626367/174026431-747f282b-29f1-41c3-8e92-fe890f87e20b.png)
防撤回软件版本：
![image](https://user-images.githubusercontent.com/5626367/174026500-5b771f21-5c91-425f-acf3-0a303e0cee74.png)

**Comment by wyDuang** [comment]
我的也没生效
微信版本：3.7.0.30

**Comment by huiyadanli** [comment]
测试 3.7.0.29 和 3.7.0.30 都可以正常防撤回

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/174490422-40a51d40-635e-4da9-b919-fd7e5858138a.png)

登录完微信之后.... 再运行

![image](https://user-images.githubusercontent.com/18187177/174490436-0855f30b-aa5e-40af-a3cf-392754c4f0f6.png)

**Comment by huiyadanli** [comment]
> ![image](https://user-images.githubusercontent.com/18187177/174490422-40a51d40-635e-4da9-b919-fd7e5858138a.png)
> 
> 登录完微信之后.... 再运行
> 
> ![image](https://user-images.githubusercontent.com/18187177/174490436-0855f30b-aa5e-40af-a3cf-392754c4f0f6.png)

当前版本的小bug，切换下微信、QQ就会去掉这个选项了

**Comment by mpfans** [comment]
但是现在确实是不工作....  撤回的消息直接消失...

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/174513346-bd9c2fc0-60f2-425b-a31d-0ff91ecb6766.png)

**Comment by wyDuang** [comment]
刚刚试发现生效了，但没有提示，看手机才发现撤回了😂

**Comment by huiyadanli** [comment]
> 我知道原因了,是因为微信更新了,但是他没有自动定位到新的目录....
> 
> ![image](https://user-images.githubusercontent.com/18187177/174700336-676ad4c9-32cb-4829-8249-9be94cc23f3a.png)

我记得补丁会自动选择版本号最高的目录，可能是bug

**Comment by tjubuntu** [comment]
> > 我知道原因了,是因为微信更新了,但是他没有自动定位到新的目录....
> > ![image](https://user-images.githubusercontent.com/18187177/174700336-676ad4c9-32cb-4829-8249-9be94cc23f3a.png)
> 
> 我记得补丁会自动选择版本号最高的目录，可能是bug

我反馈问题的时候，微信还没更新到3.7.0.30的版本

**Comment by tjubuntu** [comment]
> ![image](https://user-images.githubusercontent.com/18187177/174490422-40a51d40-635e-4da9-b919-fd7e5858138a.png)
> 
> 登录完微信之后.... 再运行
> 
> ![image](https://user-images.githubusercontent.com/18187177/174490436-0855f30b-aa5e-40af-a3cf-392754c4f0f6.png)

微信在登陆运行状态下是无法正常安装补丁的
