### ISSUE TITLE
无法找到关键文件

### ISSUE THREAD

**Issue by hoah2333** [huiyadanli/RevokeMsgPatcher#368]
微信更新到3.7.0.30后无法安装反撤回，提示“无法找到此应用的关键文件，请选择正确的安装路径！”但在此前可以安装反撤回并可确认生效
![image](https://user-images.githubusercontent.com/17213700/174435474-b1cf0d0a-d458-4db2-b425-f43fafab8cfa.png)
![image](https://user-images.githubusercontent.com/17213700/174435477-ea2869e7-0e39-48d7-823b-91dcdebf6a88.png)
![image](https://user-images.githubusercontent.com/17213700/174435478-7383c587-0e89-4bc7-9382-6ce6a55f40e4.png)
![image](https://user-images.githubusercontent.com/17213700/174435479-3f07a90f-30de-4a4b-ad84-d649ee7db7d9.png)

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/174478081-a2a6a6cb-7ff5-4191-8189-e9d18864e897.png)

测试正常


![image](https://user-images.githubusercontent.com/15783049/174478116-4bd3a8f9-e129-4c48-8861-c7e611648d77.png)

你可能需要选择到这一级
