### ISSUE TITLE
访问被拒绝

### ISSUE THREAD

**Issue by huixchen** [huiyadanli/RevokeMsgPatcher#369]
![微信截图_20220624121316](https://user-images.githubusercontent.com/28719793/175460889-6381609c-33f6-41bb-992d-52c59094797f.png)

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2523795387

**Comment by huixchen** [comment]
> https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2523795387
> 
> 最新编译版本已经解决了这个问题#348

OK了
