### ISSUE TITLE
防撤回插件安装后，不支持电脑回车键多开微信，现在版本2.7.1.65

### ISSUE THREAD

**Issue by Zheng-XianSheng** [huiyadanli/RevokeMsgPatcher#37]

**Comment by huiyadanli** [comment]
[版本支持](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81)

微信从 2.7.1.74 版本开始支持多开

2.7.1.65不支持多开，如果想要多开可以参考https://github.com/huiyadanli/RevokeMsgPatcher/issues/8
