### ISSUE TITLE
最新版本："无法找到此应用的关键文件，请选择正确的安装路径！"

### ISSUE THREAD

**Issue by liAndJack** [huiyadanli/RevokeMsgPatcher#374]
### WeChat地址是这个：
![sp20220629_084112_326](https://user-images.githubusercontent.com/62865942/176327459-05c42913-c66a-4730-97a4-c31bc82ccceb.png)
### 使用的是1.5，输入路径后不允许点击安装补丁：
![sp20220629_084053_441](https://user-images.githubusercontent.com/62865942/176327565-2fa80f88-598e-4e7e-a633-4190e2816c86.png)
### 然后我就手动选择路径，结果弹出来一个弹窗：
![sp20220629_084201_831](https://user-images.githubusercontent.com/62865942/176327635-5540fe9e-ed68-45ca-bf86-b8516444502c.png)

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/176339606-9a38be1c-86ac-415d-ab4b-d7780bba9604.png)

需要选择到下一级目录

**Comment by liAndJack** [comment]
这样确实可以，原来时被[README.md里的截图](https://github.com/huiyadanli/RevokeMsgPatcher#%E6%88%AA%E5%9B%BE)误导了
谢谢帮助
