### ISSUE TITLE
微信文件混乱

### ISSUE THREAD

**Issue by CHuaLi** [huiyadanli/RevokeMsgPatcher#376]
正常文件应该集中且按月区分存放在file文件夹，但是开了MsgAttach后收到文件后会存到MsgAttach文件夹里，而且不同时间段或者不同聊天对象的文件会分开存，且存的文件夹名是乱码，请问怎么解决

**Comment by yaosj2k** [comment]
3.7.1.7开始又恢复到原来的存放方式了
