### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by pigjio** [huiyadanli/RevokeMsgPatcher#377]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ正式版9.6.1（287732）

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/PCQQ9.6.2/QQ9.6.2.28755.exe

### 软件提示了什么？

qq自动给我更新到9.6.1版本后，防撤回失效，麻烦作者更新下这个版本的qq吧，谢谢！

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/177354745-51bc5e6b-da59-4ee6-a890-b49b24cf9681.png)

9.6.1（28732） 测试没问题
