### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by SSS7887** [huiyadanli/RevokeMsgPatcher#378]
提示应用程序无法正常启动0xc000007b

**Comment by huiyadanli** [comment]
是Win10吗？是否有安装 [.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642) 或更高版本

**Comment by SSS7887** [comment]
> 是Win10吗？是否有安装 [.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642) 或更高版本

已经解决啦，谢谢大佬
