### ISSUE TITLE
请问一下只用防撤回功能，会被系统封号吗？像确保一下娱乐的同时不被封号

### ISSUE THREAD

**Issue by AndyCao1125** [huiyadanli/RevokeMsgPatcher#380]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

正式版

### 对应版本的下载地址

最新版

### 软件提示了什么？

无

**Comment by huiyadanli** [comment]
不会。

至今没有由本补丁引发的封号、警告的反馈
