### ISSUE TITLE
安装后频道更新时报错

### ISSUE THREAD

**Issue by HadwinOFE** [huiyadanli/RevokeMsgPatcher#381]
**QQ版本：QQ9.6.2.28756**
![4](https://user-images.githubusercontent.com/102217417/179017140-28ec2dac-3bd6-4e24-9f47-589e142597a5.png)
**对应下载地址：https://dldir1.qq.com/qqfile/qq/PCQQ9.6.2/QQ9.6.2.28756.exe**
我使用的防撤回下载地址：https://wwn.lanzouf.com/b00ppm2pa
触发报错流程：
![1](https://user-images.githubusercontent.com/102217417/179016950-bff1de34-560f-40f0-9fca-9331973c3df6.png)
![2](https://user-images.githubusercontent.com/102217417/179017093-56c3a75f-4ca1-4965-879c-6e184bfdbe82.png)
![3](https://user-images.githubusercontent.com/102217417/179017116-c13b5445-af7a-46f8-9f2b-6853741e57cb.png)

**Comment by huiyadanli** [comment]
两者应该是毫无关系的（验证方法：备份还原后，重试更新QQ频道。）。QQ频道完全可以算作一个独立软件。。

建议直接重装QQ。

**Comment by HadwinOFE** [comment]
> 两者应该是毫无关系的（验证方法：备份还原后，重试更新QQ频道。）。QQ频道完全可以算作一个独立软件。。
> 
> 建议直接重装QQ。

确实重装QQ之后就不会出现启动错误了，但是过一会又会出现更新频道的按钮，然后是同样的结果，如果还原备份就不会有启动过程错误的问题，再次安装补丁又是启动过程错误。。。
