### ISSUE TITLE
好像对视频不生效了

### ISSUE THREAD

**Issue by leeemo** [huiyadanli/RevokeMsgPatcher#382]
大佬，今天发现我聊天群里别人发的视频撤回后，我想去点开却显示已被清理，我记得以前的话还是可以直接加载观看的呀。wx版本3.7.5.23
![23](https://user-images.githubusercontent.com/98966550/179387238-cf67955f-903c-44ec-b9b0-3e7203190da8.jpg)

**Comment by huiyadanli** [comment]
我测试了下，的确和你说的一样。老的防撤回方法视频是不会被清理的

**Comment by canbingzt** [comment]
图片也显示”被清理“

**Comment by huiyadanli** [comment]
#385
