### ISSUE TITLE
[微信3.7.5.23]:更新后发现1.5不支持新版本微信 

### ISSUE THREAD

**Issue by StarSpark** [huiyadanli/RevokeMsgPatcher#383]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.7.5.23

### 对应版本的下载地址

https://12660249950d5142f146b6521d49fe33.dlied1.cdntips.net/dldir1.qq.com/weixin/Windows/WeChatSetup.exe?mkey=62d3d0b66fc1f006&f=0af0&proto=https

### 软件提示了什么？

官网正常下载的最新版本微信，就是1.5.fix1版本防撤回不生效了~消息能正常撤回了~

**Comment by huiyadanli** [comment]
当前最新的 3.7 以上版本（3.7.0.30、3.7.5.23）重新开始支持撤回提示。

测试是能够正常防撤回的

**Comment by kakudesu** [comment]
我的防撤回也失效，跟issue发起人一样的版本

**Comment by kakudesu** [comment]
> 我的防撤回也失效，跟issue发起人一样的版本

不好意思，刚刚重新测试了，防撤回没有失效，失效的人在安装补丁的时候请看一下路径最后对不对，默认可能是`\Tencent\WeChat\[3.7.0.29]`, 手动选择一下你的本地最新微信版本路径，例如目前最新的是`\Tencent\WeChat\[3.7.5.23]`

**Comment by kartyl** [comment]
和issue发起人一样的版本，打开微信pc版之前撤回的消息，防撤回失效了。也就是说现在想要防撤回需要微信pc版一直开着，以前我手机上看到撤回提示再开微信pc版也能查到撤回的消息

**Comment by StarSpark** [comment]
> > 我的防撤回也失效，跟issue发起人一样的版本
> 
> 不好意思，刚刚重新测试了，防撤回没有失效，失效的人在安装补丁的时候请看一下路径最后对不对，默认可能是`\Tencent\WeChat\[3.7.0.29]`, 手动选择一下你的本地最新微信版本路径，例如目前最新的是`\Tencent\WeChat\[3.7对对对，确实这样搞一下就可以了，微信给你生成一个高版本的文件夹，好狗~

**Comment by StarSpark** [comment]
> > 我的防撤回也失效，跟issue发起人一样的版本
> 
> 不好意思，刚刚重新测试了，防撤回没有失效，失效的人在安装补丁的时候请看一下路径最后对不对，默认可能是`\Tencent\WeChat\[3.7.0.29]`, 手动选择一下你的本地最新微信版本路径，例如目前最新的是`\Tencent\WeChat\[3.7.5.23]`


>对对对，确实这样搞一下就可以了，微信给你生成一个高版本的文件夹，好狗~

**Comment by jonozw** [comment]
我这边3.7.5.23, 目录没错, 但是patch了以后依然不行. 
最开始Patch的时候给了一个警告信息, 但我没留神, 现在没了

**Comment by huiyadanli** [comment]
> 我这边3.7.5.23, 目录没错, 但是patch了以后依然不行. 最开始Patch的时候给了一个警告信息, 但我没留神, 现在没了

还原后重新patch试试

**Comment by jonozw** [comment]
1. 恢复Wechatwin.dll from wechatwin.dll.h.bak
![图片](https://user-images.githubusercontent.com/30031941/179456820-99aa3b2a-7df8-4889-a166-429dd4e41ab3.png)
2. patch
3. 显示patch OK
4. 好像还是不行...

**Comment by huiyadanli** [comment]
@jonozw 不要勾选去除校验试试

**Comment by jonozw** [comment]
> 

还是不行, 等下一个版本您更新吧, 反正也不是很着急的事情:)

非常感谢持续的沟通.

**Comment by MarkLily** [comment]
咩咩咩？防撤回提示那句话回归啦？？？我的最新版本没得呀

**Comment by MarkLily** [comment]
大佬 我刚才重装了官网的新版本，然后打上后，发现是有了那句撤回的提示了，但是不是在对话聊天窗口里，而是在左边的列表中。

**Comment by huiyadanli** [comment]
> 大佬 我刚才重装了官网的新版本，然后打上后，发现是有了那句撤回的提示了，但是不是在对话聊天窗口里，而是在左边的列表中。

有撤回提示的版本，暂时有以下问题：

1. 如果正在和对方聊天时，对方撤回了消息，那撤回提示依然不会显示，只有在左侧预览窗有显示撤回，需要切换到和别人的聊天窗再切回来才能看到撤回提示，如果是把聊天拉出单独窗口，一直不会有撤回提示。
2. 视频消息撤回后会被删除
3. 部分历史消息无法防撤回

**Comment by MarkLily** [comment]
大佬 我刚才切回窗口看了一下 验证了第一点 确实是看到了！！！优秀啊！

**Comment by 789qaz** [comment]
我发现现在这个版本如果撤回的是图片或者文件，那么会显示已被清理，打不开了

**Comment by MarkLily** [comment]
发现一个小问题，就是自己发了消息后，撤回，然后再切回来看 出现了两条撤回的提示语

**Comment by smile5231** [comment]
为什么 1.2 以后的版本我下载下来 都打不开呢？点击打开没反应。。.net是4.8版本的

**Comment by huiyadanli** [comment]
@smile5231 尝试安装下老版本的 [.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642)

**Comment by Lstoryc** [comment]
关闭微信后再开就GG了

**Comment by popokcn** [comment]
试试这个斑竹做的hook版本，我试用了下挺完美的。5月份的东西，现在最新版一样可以用。

还带撤回提示，图片和视频都能完美防撤回

https://www.52pojie.cn/thread-1640295-1-1.html

**Comment by sorgs** [comment]
发现自己发的消息，测回了，还是会显示，不看手机都不知道自己已经测回了

**Comment by rendongwei** [comment]
我这撤回看不到了 3.7.5.23版本

**Comment by Ivresse-gex** [comment]
我的一直提示获取最新补丁失败

**Comment by huiyadanli** [comment]
@Ivresse-gex 1.6 版本已经修复了这个问题
