### ISSUE TITLE
目前新版微信，对方撤回文件，微信会把文件从本地删除。能看到对方发的文件，但是点进去会显示文件已被

### ISSUE THREAD

**Issue by Mrlie** [huiyadanli/RevokeMsgPatcher#385]
![image](https://user-images.githubusercontent.com/25104962/181194326-c9f9275b-d7ba-4ff8-9a0d-07898ef0978e.png)
微信3.7.5.23

**Comment by JasonLeeForOnly** [comment]
![image](https://user-images.githubusercontent.com/47520063/181467625-6922840f-07c5-4e9b-8fff-bc9a4a70b85f.png)
会出现这种提示~

**Comment by huiyadanli** [comment]
已知问题。

当前防撤回补丁换成了有撤回提示的版本，相比较以前无撤回提示的版本有以下问题：

* 如果正在和对方聊天时，对方撤回了消息，那撤回提示依然不会显示，只有在左侧预览窗有显示撤回，需要切换到和别人的聊天窗再切回来才能看到撤回提示，如果是把聊天拉出单独窗口，一直不会有撤回提示。
* 视频/图片消息撤回后会被删除
* 部分历史消息无法防撤回

近期会提供一个新版本，供用户自行选择那种类型防撤回

**Comment by Lstoryc** [comment]
> 已知问题。
> 
> 当前防撤回补丁换成了有撤回提示的版本，相比较以前无撤回提示的版本有以下问题：
> 
> * 如果正在和对方聊天时，对方撤回了消息，那撤回提示依然不会显示，只有在左侧预览窗有显示撤回，需要切换到和别人的聊天窗再切回来才能看到撤回提示，如果是把聊天拉出单独窗口，一直不会有撤回提示。
> * 视频/图片消息撤回后会被删除
> * 部分历史消息无法防撤回
> 
> 近期会提供一个新版本，供用户自行选择哪种类型防撤回

大佬 最近发现重启下微信 就会导致功能失效，重新安装又好了 这该如何解决？

**Comment by harryas** [comment]
3.7.5.23版本的防撤回效果应该是失效了

**Comment by ekkoin** [comment]
一样，点大图显示已被清理

**Comment by huiyadanli** [comment]
1.6 版本已经把两种防撤回做成可选项了，选择老的特征码就不会出现这种情况了（当然也就不会出现撤回提示了）

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6

**Comment by BlingRbt** [comment]
现在最新版是用新的还是老的好？
能全部防撤回

**Comment by huiyadanli** [comment]
@BlingRbt 两个都装了，老版本的断的更加前面（优先级更高），也就是说对用户而言，两个都装就意味着只有老的生效

**Comment by Panaoxuan** [comment]
请问所以是老版的比较好吗，没有上述的问题，唯一的缺点就是没有撤回提示？（毕竟手机端可以看到提示）

**Comment by huiyadanli** [comment]
@Panaoxuan 是的（唯一的缺点就是没有撤回提示

**Comment by Panaoxuan** [comment]
好的好的，感谢~

**Comment by chenzhaokun** [comment]
![image](https://user-images.githubusercontent.com/88467902/187366317-cbbab824-219f-4921-9483-64f229b9a601.png)
我下载的1.6版本没有新版的防撤回选项，请问下这是什么情况呢

**Comment by Sodaly1318** [comment]
> ![image](https://user-images.githubusercontent.com/88467902/187366317-cbbab824-219f-4921-9483-64f229b9a601.png) 我下载的1.6版本没有新版的防撤回选项，请问下这是什么情况呢，现在对方撤回也没有提示

可以看一下这个 #415
