### ISSUE TITLE
对WeChatWin.dl的访问被拒绝

### ISSUE THREAD

**Issue by yq2020** [huiyadanli/RevokeMsgPatcher#386]
![image](https://user-images.githubusercontent.com/61315135/182017704-375d6e61-69b3-4179-9d14-ad46a978e25c.png)

**Comment by huiyadanli** [comment]
参考 #348 解决

或者直接下载最新版本：https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/2681542487
