### ISSUE TITLE
QQ无法显示图片

### ISSUE THREAD

**Issue by CODE-7z** [huiyadanli/RevokeMsgPatcher#388]
安装补丁后绝大部分图片（含表情包以及文件图片）无法正常显示
![未标题-1](https://user-images.githubusercontent.com/49109184/182129354-45dc81a7-55de-4cc3-9a45-6a481449f050.png)

**Comment by huiyadanli** [comment]
建议还原后再看。。
据我所知补丁不会产生这种问题
