### ISSUE TITLE
最新版微信(3.7.5.23)无法支持视频撤回后查看

### ISSUE THREAD

**Issue by fxxisme** [huiyadanli/RevokeMsgPatcher#390]
![image](https://user-images.githubusercontent.com/39211654/182764506-adcff37a-f528-409b-b281-aea7467ee470.png)

如果视频先浏览过，之后再被撤回可以观看
视频未浏览过，之后被撤回就显示已被清理
![image](https://user-images.githubusercontent.com/39211654/182764694-d5dbe263-0be4-48f8-bc62-3ea7238ec225.png)

**Comment by huiyadanli** [comment]
已知问题 #385

**Comment by huiyadanli** [comment]
1.6 版本已经把两种防撤回做成可选项了，选择老的特征码就不会出现这种情况了

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6
