### ISSUE TITLE
微信3.7.5.23获取最新补丁信息失败

### ISSUE THREAD

**Issue by Hamiltoncheung** [huiyadanli/RevokeMsgPatcher#392]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.7.5.23

### 软件提示了什么？

不知道为什么突然防撤回就用不了了，大佬帮忙看看，感谢感谢
![image](https://user-images.githubusercontent.com/110689251/183132458-b64f9a37-cd31-4724-b425-d031552af857.png)

**Comment by scalpelx** [comment]
同样遇到这个问题有两天了

**Comment by W4J1e** [comment]
我也是这样，然后没选多开和去除校验，只安装防撤回，提示安装成功。

**Comment by huiyadanli** [comment]
又一个源被干掉了。。。可能以后只能用外网的源了

**Comment by huiyadanli** [comment]
1.6 版本已经替换新的补丁源

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6

**Comment by Hamiltoncheung** [comment]
> 1.6 版本已经替换新的补丁源
> 
> https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6

解决啦，谢谢大佬

**Comment by Constaline** [comment]
或者看下以下源能否使用

- https://cdn.jsdelivr.net/gh/huiyadanli/RevokeMsgPatcher@master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json
- https://ghproxy.com/https://raw.githubusercontent.com/huiyadanli/RevokeMsgPatcher/master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json

**Comment by huiyadanli** [comment]
@Constaline 
第一个jsdelivr不太稳，
第二个也是国内用爱发电的，不敢薅太狠。

不过都可以作为备用源，感谢提供❤
