### ISSUE TITLE
微信3.7.5.31获取最新补丁信息失败

### ISSUE THREAD

**Issue by glutermjx** [huiyadanli/RevokeMsgPatcher#393]
如题
![image](https://user-images.githubusercontent.com/110708178/183232690-404d1a70-68bb-4d2d-954e-0849e5ea6637.png)

**Comment by huiyadanli** [comment]
1.6 版本已经替换新的补丁源，修复了这个问题

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6

**Comment by glutermjx** [comment]
邮件已收到，软件已下载，问题已经解决。谢谢！







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyadanli/RevokeMsgPatcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月6日(星期六) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] 微信3.7.5.31获取最新补丁信息失败 (Issue #393)





 
1.6 版本已经替换新的补丁源，修复了这个问题
 
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6
