### ISSUE TITLE
微信PC端登录，卡+黑

### ISSUE THREAD

**Issue by MarkLily** [huiyadanli/RevokeMsgPatcher#394]
微信PC端登录，手机点了确认后，发现会假死一会 黑框。过一会就好了，感觉像是微信同步消息出现了问题，之前看有人反应过，但是我的没问题，现在慢慢的公司电脑、家里电脑都陆陆续续出现了！问大家有么？目前最新版本：3.7.5.31

**Comment by StarryDreamm** [comment]
这应该是微信的问题

**Comment by MarkLily** [comment]
> 这应该是微信的问题

是的 我也是这么觉得呢 微信做得越来越拉垮了！

**Comment by huiyadanli** [comment]
具以前用户的反馈来看，我猜测是由于微信临时文件过多的原因造成的，可以尝试清理下聊天记录、接收文件文件夹等内容。

**Comment by MarkLily** [comment]
> 具以前用户的反馈来看，我猜测是由于微信临时文件过多的原因造成的，可以尝试清理下聊天记录、接收文件文件夹等内容。

OK 多谢大佬 我试试先！
