### ISSUE TITLE
README.md 中超链接有误

### ISSUE THREAD

**Issue by CuiaCuiSha** [huiyadanli/RevokeMsgPatcher#396]
![image](https://user-images.githubusercontent.com/32769735/183387573-0f0d9511-fcb6-413c-8506-998ed6e96a1e.png)

README.md 中超链接有误
红框里的链接为：https://github.com/huiyadanli/RevokeMsgPatcher/releases/download/1.5/RevokeMsgPatcher.v1.6.zip
正确链接应该是：https://github.com/huiyadanli/RevokeMsgPatcher/releases/download/1.6/RevokeMsgPatcher.v1.6.zip

**Comment by huiyadanli** [comment]
感谢提醒！的确是写错了...
