### ISSUE TITLE
QQ异常

### ISSUE THREAD

**Issue by CODE-7z** [huiyadanli/RevokeMsgPatcher#397]
QQ在打完补丁后变得巨卡无比，而且登录时有几率显示60011的错误而无法登录

**Comment by huiyadanli** [comment]
清空个人临时文件试试

**Comment by CODE-7z** [comment]
还是不行，显示60010
![无标题](https://user-images.githubusercontent.com/49109184/183817974-dbfedbfe-a3b7-49c8-a9d9-c3811599b1a7.png)
