### ISSUE TITLE
无法找到此应用的关键文件，请选择正确的安装路径!

### ISSUE THREAD

**Issue by Chobohoo** [huiyadanli/RevokeMsgPatcher#398]
微信版本：3.7.5.23
RevokeMsgPather版本：1.6 

问题描述：选择微信的安装文件夹后，提示“无法找到此应用的关键文件，请选择正确的安装路径!” QQ则不会有这个问题。

**Comment by huiyadanli** [comment]
参考 #374

**Comment by Chobohoo** [comment]
> 参考 #374

可以了..感谢回答...
