### ISSUE TITLE
[未支持版本]: 微信PC版3.7.6.22

### ISSUE THREAD

**Issue by yaosj2k** [huiyadanli/RevokeMsgPatcher#399]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

微信测试版 3.7.6.22

### 对应版本的下载地址

https://pan.baidu.com/s/1U9ploRe1VwieRAyr0j9MXA?pwd=w8bj 

### 软件提示了什么？

![2022-08-10_161354](https://user-images.githubusercontent.com/260167/183850935-71b52694-0fed-40f9-aafd-fdb5624680b0.png)

**Comment by huiyadanli** [comment]
直接更新了正式版本
