### ISSUE TITLE
有个小的建议,,发布新的版本的时候,能不能把最新的微信和qq也发上来?

### ISSUE THREAD

**Issue by a909042793** [huiyadanli/RevokeMsgPatcher#40]
是这样的,我再官网下载微信和qq,TIM的时候,并不知道他们的版本号,也就没法知道最新的补丁是否可用,所以希望,发布补丁的时候,能把适配的最新版的软件也一起发上来,这样安装对应的软件直接打上补丁就能用了!

**Comment by huiyadanli** [comment]
建议不错，下次会带上

**Comment by huiyadanli** [comment]
[版本支持](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81)中已经添加我收集的部分安装包
