### ISSUE TITLE
[未支持版本]: WeChat 3.7.6.24

### ISSUE THREAD

**Issue by MiTuYouZi** [huiyadanli/RevokeMsgPatcher#402]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.7.6.24

### 软件提示了什么？

显示版本支持，弹窗提示失败
![image](https://user-images.githubusercontent.com/103876902/185539555-2307bf99-ea16-488a-9f8e-545ee5ad2d3f.png)

![image](https://user-images.githubusercontent.com/103876902/185278782-2cdcbf72-552f-44e7-a588-78c9902d3d46.png)

**Comment by huiyadanli** [comment]
已更新
