### ISSUE TITLE
[未支持版本]: 3.7.6.24

### ISSUE THREAD

**Issue by cc19264997** [huiyadanli/RevokeMsgPatcher#404]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.7.6.24

### 对应版本的下载地址

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6

### 软件提示了什么？

不显示【防撤回带提示(新)】，或可能是无法支持【防撤回带提示(新)】

**Comment by cc19264997** [comment]
![12](https://user-images.githubusercontent.com/25716656/185772281-cee9150e-0545-4bd7-b28c-757db9c64121.png)

**Comment by huiyadanli** [comment]
暂不支持 防撤回带提示(新) 😂

**Comment by cc19264997** [comment]
> 暂不支持 防撤回带提示(新) 😂

好的明白，期待更新，谢谢解答~

**Comment by MarkLily** [comment]
今早也发现了 那个新标不见了 等大佬修改
