### ISSUE TITLE
微信不支持防撤回文件

### ISSUE THREAD

**Issue by super-github** [huiyadanli/RevokeMsgPatcher#407]
![image](https://user-images.githubusercontent.com/18386008/186309644-3f932c25-89f5-4cb9-997f-5e0ec932e9d2.png)
单独安装新版补丁，可防撤回消息，但是对文件无效。
安装旧版本的可防撤回文件，但无提示

**Comment by huiyadanli** [comment]
软件提示中已经说明过这种情况了

#385
