### ISSUE TITLE
[未支持版本]: 3.7.6.29

### ISSUE THREAD

**Issue by cbisuper** [huiyadanli/RevokeMsgPatcher#410]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

WX3.7.6.29

### 软件提示了什么？

当前特征码匹配数0与期望的匹配数1不一致

**Comment by huozaiwuli** [comment]
+1 微信今天更新了3.7.6.29之后更新补丁就出现这个了 
![image](https://user-images.githubusercontent.com/69556861/186595128-c6157412-e4eb-42c8-a5e4-a09252a11d75.png)

**Comment by hihop-kc** [comment]
3.7.6.27也不行

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by scalpelx** [comment]
用最新的1.6版本就可以了

**Comment by luoxigod** [comment]
今天刚刚自动更新的3.7.6.29版本的微信，软件用的也是最近的1.6版本，重新安装了补丁，但是不起作用。

**Comment by shakespearesnow** [comment]
> 用最新的1.6版本就可以了

你好我像问下是怎么用的呢,我更新了1.6还是用不了

**Comment by scalpelx** [comment]
> > 用最新的1.6版本就可以了
> 
> 你好我像问下是怎么用的呢,我更新了1.6还是用不了

用不了的具体表现是什么呢，我这里正常，微信3.7.6.29

**Comment by shakespearesnow** [comment]
> 

好吧，我这也是一样但是用不了

**Comment by scalpelx** [comment]
> > 
> 
> 好吧，我这也是一样但是用不了

所以说具体表现是什么呢，报错？

**Comment by shakespearesnow** [comment]
> 

好吧，我这也是一样但是用不了


> > > 
> > 
> > 
> > 好吧，我这也是一样但是用不了
> 
> 所以说具体表现是什么呢，报错？

显示的是成功了
，但是软件上显示的是防撤回（老），然后微信里也可以撤回

**Comment by 3jichi** [comment]
大佬这个版本防撤回插件显示是旧的不是新的

**Comment by huiyadanli** [comment]
请使用最新的[1.6版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases)

3.7.6+的版本又不支持带撤回提示的特征了

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
