### ISSUE TITLE
特征比对：当前特征码匹配数[0]和期望的匹配数[1]不一致

### ISSUE THREAD

**Issue by wandelfor** [huiyadanli/RevokeMsgPatcher#413]
特征比对：当前特征码匹配数[0]和期望的匹配数[1]不一致。
出现此种情况的一般有如下可能：
1. 你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
2. 如果当前版本为最新版本，特征码可能出现变化（可能性比较低），请联系作者处理。
3. PC微信版本是3.7.6.29

**Comment by udbbbn** [comment]
我的是 期望的匹配数[2] 不一致

**Comment by BiuZero** [comment]
补丁最新版是1.6，如果你用1.5就会提示这个

**Comment by milu223** [comment]
![image](https://user-images.githubusercontent.com/40411049/187001298-8fe2673a-a172-468d-aa33-c57cc0a513a8.png)

**Comment by milu223** [comment]
微信3.7.6.29，补丁版本1.6~😭
![image](https://user-images.githubusercontent.com/40411049/187001349-548a5873-e0e9-48c5-b039-8afdfbb05f31.png)

**Comment by huiyadanli** [comment]
请使用1.6版本 https://github.com/huiyadanli/RevokeMsgPatcher/releases
