### ISSUE TITLE
请求去掉微信自动更新

### ISSUE THREAD

**Issue by iOSreverse** [huiyadanli/RevokeMsgPatcher#414]
勾选了去除检查微信新版本功能，但是还是会自动更新。请求增加去掉自动更新的功能

**Comment by bancrogft** [comment]
微信有提示
[安全补丁等重要更新仍会自动安装]

**Comment by skyformat99** [comment]
> 勾选了去除检查微信新版本功能，但是还是会自动更新。请求增加去掉自动更新的功能

需要这个功能啊
屏蔽得了啊
