### ISSUE TITLE
v1.6选项没有新版防撤回选项

### ISSUE THREAD

**Issue by djmee** [huiyadanli/RevokeMsgPatcher#415]
![image](https://user-images.githubusercontent.com/93442627/187055269-bee0ceaa-9e7c-4d73-8af5-384cb28fbdf6.png)
新版防撤回是删掉了吗，在更新介绍里看到可以选择新版或者旧版，我这个怎么不一样
微信3.7.6.29

**Comment by FlechazoPh** [comment]
我也没有，最新的3.7版本

**Comment by huiyadanli** [comment]
暂时又不支持了:joy:

**Comment by ytkunkun** [comment]
如果有撤回提示 似乎会更加友好一点

**Comment by jonozw** [comment]
咨询一下, 3.7.xx的微信, 旧版本补丁工作正常吗? 

好确认一下升不升级微信, 谢谢

**Comment by huiyadanli** [comment]
@jonozw  

3.7.0.~3.7.5.（含3.7），有 带防撤回提示 的特征补丁，3.7.6.*就只有以前没提示的防撤回补丁了

只要程序版本是1.6，微信版本都有防撤回补丁可用

**Comment by jayjayleung** [comment]
这个提示什么时候能修复

**Comment by jayjayleung** [comment]
请问有没有3.7.0.~3.7.5的版本下载吗

**Comment by loveless277** [comment]
现在撤回自己的消息都还在，都怀疑自己有没有撤回成功了😂

**Comment by loveless277** [comment]
感谢您的来信！我已收到，等我看到就会回复！

**Comment by tglf** [comment]
> @jonozw
> 
> 3.7.0.~3.7.5.（含3.7），有带防滴回复提示的特征补丁，3.7.6.*就只有以前没有提示的防滴回补丁了
> 
> 只要程序版本是1.6，微信版本都有防滴回补丁可用
大佬我想问下带提示的防撤回和老版本那种撤回有什么区别嘛，撤回了不都有提示的嘛

**Comment by quarkape** [comment]
> @jonozw
> 
> 3.7.0.~3.7.5.（含3.7），有 带防撤回提示 的特征补丁，3.7.6.*就只有以前没提示的防撤回补丁了
> 
> 只要程序版本是1.6，微信版本都有防撤回补丁可用

3.7.5.19绿色版测试也不支持撤回提示~

**Comment by loveless277** [comment]
感谢您的来信！我已收到，等我看到就会回复！

**Comment by as88866920** [comment]
新版的微信不能搞撤回提示了。。。坐等大佬找到方法~

**Comment by as88866920** [comment]
> 暂时又不支持了😂

大佬什么时候能更新一下，坐等大佬找到方法~

**Comment by huiyadanli** [comment]
20230225：

微信 3.9.9.43 又支持带撤回提示了（可能很短暂吧）

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/0b616b0a-5a9f-4a65-8635-dfbb935fc4ac)

**Comment by loveless277** [comment]
感谢您的来信！我已收到，等我看到就会回复！
