### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by he734613955** [huiyadanli/RevokeMsgPatcher#416]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.7.6.29

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/55093891/187327558-00e0a170-9fe3-4b18-ab52-1ac12b17290d.png)

**Comment by huiyadanli** [comment]
请使用最新的[1.6版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases)

3.7.6+的版本又不支持带撤回提示的特征了

#410
