### ISSUE TITLE
[未支持版本]: 3.7.6.29

### ISSUE THREAD

**Issue by UI20114** [huiyadanli/RevokeMsgPatcher#417]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.7.6.29

### 对应版本的下载地址

https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

### 软件提示了什么？

特征比对:当前特征码匹配数[0]和期望的匹配数[2]不一致。出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
⒉如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作者处理。

**Comment by huiyadanli** [comment]
请使用最新的[1.6版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases)
