### ISSUE TITLE
[未支持版本]: QQ-NT

### ISSUE THREAD

**Issue by SekiBetu** [huiyadanli/RevokeMsgPatcher#418]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ 6.8.5.4200 exp

### 对应版本的下载地址

https://im.qq.com/macqq/index.shtml

### 软件提示了什么？

![ZE1TLD8HCO8H 9DBUY%HEM4](https://user-images.githubusercontent.com/38283893/187678403-a2f85d1b-15d4-48d1-b8f7-50ecb346df9c.png)
![image](https://user-images.githubusercontent.com/38283893/187679271-ef79f069-3d9d-4865-88dd-e0b530fb9df7.png)

这是QQ正在开发的跨平台统一版本，因为其使用了electron框架，所以未来可能会支持windows和linux，我先开个issue在这里，未来出了windows版再请求作者支持这一新框架的防撤回

**Comment by huiyadanli** [comment]
如果是js写的，感觉可以做到更多的事情，完全可以新开个坑来做。。。

可惜我的js水平稀烂。。。

**Comment by SekiBetu** [comment]
> 如果是js写的，感觉可以做到更多的事情，完全可以新开个坑来做。。。
> 
> 可惜我的js水平稀烂。。。

![image](https://user-images.githubusercontent.com/38283893/187681137-08017b5c-6465-419d-a8e0-fb378e9bb8eb.png)
目前的QQ频道就是electron框架，可以拿来练手

**Comment by callng** [comment]
@SekiBetu 请问这个QQ-NT如何申请内测呢，还是只限内部使用？

**Comment by callng** [comment]
@SekiBetu 请问这个QQ-NT如何申请内测呢，还是只限内部使用？

**Comment by SekiBetu** [comment]
> @SekiBetu 请问这个QQ-NT如何申请内测呢，还是只限内部使用？

需要加入内测群，内测群已经停止收人了，等下次扩大内测规模了估计会有别的渠道的，等吧

**Comment by SekiBetu** [comment]
> @SekiBetu 请问这个QQ-NT如何申请内测呢，还是只限内部使用？

已经公开测试了
https://im.qq.com/macqq/index.shtml

**Comment by callng** [comment]
ok

> > @SekiBetu 请问这个QQ-NT如何申请内测呢，还是只限内部使用？
> 
> 已经公开测试了 https://im.qq.com/macqq/index.shtml

**Comment by Deathef** [comment]
有没有支持的计划呢

**Comment by taozhiyu** [comment]
如果没记错，ntqq好像是全局转bytecode了

**Comment by buiawpkgew1** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/552
重复问题

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
