### ISSUE TITLE
[未支持版本]: TIM 3.4.0.22054

### ISSUE THREAD

**Issue by Noisyfox** [huiyadanli/RevokeMsgPatcher#419]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

TIM 正式版 3.4.0.22054

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/TIM3.4.0/TIM3.4.0.22054.exe

### 软件提示了什么？

选择安装补丁后提示特征码匹配数不一致：
![image](https://user-images.githubusercontent.com/1537155/187822200-50d583a1-9f7b-4a24-94d7-ab32c00fab59.png)

**Comment by Q-jun** [comment]
刚好就是昨天下的 现在上来才看到 哈哈哈 希望尽快可以

**Comment by DirXyz** [comment]
我也是这样

**Comment by DirXyz** [comment]
老版本好像可以，我重装系统前Tim可用，重装完系统下了个新Tim就不行了

**Comment by Lw520Y** [comment]
+1 之前是上一个版本 是可以用的 然后今天更新了3.4.0.22054这个版本就gg了

**Comment by huiyadanli** [comment]
已经支持

**Comment by DirXyz** [comment]
> 已经支持

哪个呀，没找到啊

**Comment by DirXyz** [comment]
> 已经支持

成功了

**Comment by Q-jun** [comment]
> 已经支持

感谢作者
