### ISSUE TITLE
运行后windows defender检测到木马，请问正常吗

### ISSUE THREAD

**Issue by Hanson13** [huiyadanli/RevokeMsgPatcher#42]
![image](https://user-images.githubusercontent.com/26969122/68988265-83920b80-086f-11ea-964e-976fe9127a72.png)

**Comment by huiyadanli** [comment]
我的 windows defender 不会有报毒提示。

如果是从 GitHub 上下载的可以放心使用。看提示疑似是我的程序申请UAC提升至管理员权限引发的警告，但是一般这项行为是不会触发警告的。

**Comment by Hanson13** [comment]
谢谢回复，发现是我没有以管理员权限打开，以管理员权限打开就不报错了
