### ISSUE TITLE
[未支持版本]: 微信3.7.6.44

### ISSUE THREAD

**Issue by ambertong52** [huiyadanli/RevokeMsgPatcher#422]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.7.6.44

### 对应版本的下载地址

https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe 

### 软件提示了什么？

![Snipaste_2022-09-03_09-10-52](https://user-images.githubusercontent.com/35869597/188250020-b3e5c48e-9a62-434c-b169-7b3793a82698.png)

**Comment by huiyadanli** [comment]
请使用最新的[1.6版本](https://github.com/huiyadanli/RevokeMsgPatcher/releases)

**Comment by lingting** [comment]
用的 1.6版本, 无效. 

![image](https://user-images.githubusercontent.com/59352063/190941046-b09d4028-c34a-40f9-bfa8-0ad815f49b9b.png)

**Comment by fivenull** [comment]
一样，windows微信PC端 3.7.6.44防撤回失效
