### ISSUE TITLE
[未支持版本]: tim3.4——

### ISSUE THREAD

**Issue by FHForget** [huiyadanli/RevokeMsgPatcher#426]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

Tim 3.4.0.22054

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/112800414/188304775-c35117b1-2769-413e-b185-b8e1bf7e2ff9.png)

**Comment by star-picker** [comment]
问题同上

**Comment by huiyadanli** [comment]
已支持

**Comment by FHForget** [comment]
👌🏻 一会儿试试哈



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月24日 17:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [huiyadanli/RevokeMsgPatcher] [未支持版本]: tim3.4—— (Issue #426) |

已支持
