### ISSUE TITLE
手机微信APP  安卓，小米手机[未支持版本]: 

### ISSUE THREAD

**Issue by SugerWin** [huiyadanli/RevokeMsgPatcher#428]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 8.0.27

### 软件提示了什么？

手机微信APP  安卓，小米手机

**Comment by huiyadanli** [comment]
手机端防撤回早就有了，关键词 xposed、太极、微x模块 。自行研究。
