### ISSUE TITLE
[未支持版本]: TIM 3.4.0.22055

### ISSUE THREAD

**Issue by SkipM4** [huiyadanli/RevokeMsgPatcher#429]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

3.4.0.22055

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/TIM3.4.0/TIM3.4.0.22055.exe

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/40311581/189289468-9bded42f-2cda-49c0-9cde-a13672ecbd63.png)

**Comment by JiJiang233** [comment]
一样

**Comment by nirbusan** [comment]
the same problem

**Comment by boyliuxiaopeng** [comment]
请求支持！
![image](https://user-images.githubusercontent.com/28186929/190836629-f264e27e-8d5e-42d3-96f0-3d14eaa2770a.png)

**Comment by wuhulqs** [comment]
me too

**Comment by huiyadanli** [comment]
已经支持
