### ISSUE TITLE
qq版本更新到9.2.0.26456了，希望能更新

### ISSUE THREAD

**Issue by Ad-Bean** [huiyadanli/RevokeMsgPatcher#43]

**Comment by jyh111** [comment]
+1

**Comment by Xpangh** [comment]
+1

**Comment by huiyadanli** [comment]
我收到了更新，但是im.dll的版本并没有变化。。。能否提供一个对应版本的dll

另外今天QQ更新了最新的版本 9.2.1.26546 ，已经支持该版本

https://im.qq.com/

**Comment by Xpangh** [comment]
> 
> 
> 我收到了更新，但是im.dll的版本并没有变化。。。能否提供一个对应版本的dll
> 
> 9.2另外今天qq更新了最新的版本。1.26546已经支持该版本，
> 
> https://im.qq.com/

软件获取最新补丁获取不到怎么弄

**Comment by Kiritomo** [comment]
emmm.我记得前几天把9.2.1版本发过去了

**Comment by Xpangh** [comment]
> 
> 
> emmm.我记得前几天把9.2.1版本发过去了

RevokeMsgPatcher.exe v0.6的 右下角自动获取版本还是失败

**Comment by huiyadanli** [comment]
@Kiritomo 你那个貌似是测试版本。。9.2.1.26503

@Xpangh coding的pages服务挂了。。。如果不恢复的话，我只能升级整个程序使用新的服务托管补丁信息了

**Comment by Xpangh** [comment]
> 
> 
> @Kiritomo 你那个貌似是测试版本。。9.2.1.26503
> 
> @Xpangh coding的pages服务挂了。。。如果不恢复的话，我只能升级整个程序使用新的服务托管补丁信息了

 我的QQ 今早去官方 下载新版的的了 不管怎么点都是不兼容的

**Comment by huiyadanli** [comment]
@Xpangh 因为获取最新补丁的服务挂了（昨晚就挂了），只能先等 coding 恢复，到晚上还不行的话，我会升级一个最新版本。

**Comment by huiyadanli** [comment]
@Xpangh 已恢复

**Comment by Xpangh** [comment]
> 
> 
> @Xpangh 已恢复

 好的  已收到

**Comment by Ad-Bean** [comment]
> 
> 
> @Xpangh 已恢复
版本是写错了吗，我这显示支持2.0.26546？

**Comment by Kiritomo** [comment]
> > @Xpangh 已恢复
> > 版本是写错了吗，我这显示支持2.0.26546？

先操作备份还原，再点我防撤回

**Comment by Xpangh** [comment]
> 
> 
> > @Xpangh 已恢复
> > 版本是写错了吗，我这显示支持2.0.26546？

你看的是当前版本吧 软件我都更新了补丁

**Comment by Ad-Bean** [comment]
> 
> 
> > > @Xpangh 已恢复
> > > 版本是写错了吗，我这显示支持2.0.26546？
> 
> 先操作备份还原，再点我防撤回

已解决，谢谢！
