### ISSUE TITLE
如果删除了此软件，，补丁会跟着一起删除吗？？还是说需要先还原 才可以

### ISSUE THREAD

**Issue by BethPerry845** [huiyadanli/RevokeMsgPatcher#430]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

3.6

### 软件提示了什么？

如题，或者说程序移动了位置，补丁是否还生效

**Comment by huiyadanli** [comment]
1. 补丁不会删除，需要你使用备份还原功能，或者直接重装微信。

2. 程序移动位置不影响补丁是否生效，因为修改的是微信的文件
