### ISSUE TITLE
请问针对撤回的txt文档和图片有效吗

### ISSUE THREAD

**Issue by BethPerry845** [huiyadanli/RevokeMsgPatcher#431]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

3.6.4

### 软件提示了什么？

请问针对撤回的txt文档和图片有效吗？

**Comment by huiyadanli** [comment]
有效

**Comment by Nerders** [comment]
> 有效

大佬，软件近期有更新吗？
Tim最近更新不适配了，微信也只有旧版本防撤回了。
