### ISSUE TITLE
[未支持版本]: TIM 3.4.0.22055

### ISSUE THREAD

**Issue by fzlzjerry** [huiyadanli/RevokeMsgPatcher#436]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [ ] 我确认当前使用的是最新版

### 微信/QQ 版本

TIM正式版3.4.0.22055

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/TIM3.4.0/TIM3.4.0.22055.exe

### 软件提示了什么？

![屏幕截图 2022-09-22 231254](https://user-images.githubusercontent.com/100508620/191785384-aaaa4612-eb46-4905-95b1-ea0679ca8a22.png)
无法加入补丁

**Comment by huiyadanli** [comment]
已经支持
