### ISSUE TITLE
[未支持版本]: Tim 3.4.1.22056

### ISSUE THREAD

**Issue by davidwushi1145** [huiyadanli/RevokeMsgPatcher#437]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

Tim 3.4.1.22056

### 对应版本的下载地址

https://office.qq.com/download.html

### 软件提示了什么？

![捕获](https://user-images.githubusercontent.com/88446549/192093374-ed7775e0-c86f-42f0-b0aa-a843386ebe5a.PNG)

**Comment by huiyadanli** [comment]
你再试试？刚刚更新了最新补丁，我测试没问题。
