### ISSUE TITLE
[未支持版本]: QQ v9.6.6.28796

### ISSUE THREAD

**Issue by douxy1994** [huiyadanli/RevokeMsgPatcher#438]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ 9.6.6.28796

### 软件提示了什么？

软件无法识别QQ，选择路径也识别不到。
![image](https://user-images.githubusercontent.com/58248905/192126655-9f7800e5-d440-4e8f-b644-4626f695b996.png)

![image](https://user-images.githubusercontent.com/58248905/192126679-a49ad09c-ea49-42df-95d2-198afbb2babc.png)

**Comment by huiyadanli** [comment]
手动选择你QQ的安装路径就行了

**Comment by douxy1994** [comment]
> 手动选择你QQ的安装路径就行了

哦哦，原来是定位到QQ目录下而不是bin目录下
