### ISSUE TITLE
微信最新的已经2.7.1.88了，希望能支持一下

### ISSUE THREAD

**Issue by fan0424** [huiyadanli/RevokeMsgPatcher#44]
pc版的微信 设置里关了升级 但是还是被强制偷偷更新到2.7.1.88了，希望能够适配

**Comment by huiyadanli** [comment]
这个版本早就已经适配了，关注左下角**获取最新补丁信息以后**再打补丁就行了

**Comment by fan0424** [comment]
> 这个版本早就已经适配了，关注左下角**获取最新补丁信息以后**再打补丁就行了

好的  谢谢 我找一下

**Comment by huiyadanli** [comment]
打错字了，是右下角。点击右下角的字符可以看到当前支持哪些版本，以这个为准
[版本支持](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81) 页面也忘记更新了:joy:

**Comment by fan0424** [comment]
> 打错字了，是右下角。点击右下角的字符可以看到当前支持哪些版本，以这个为准
> [版本支持](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81) 页面也忘记更新了

恩 我刚才下载试了 可以用
