### ISSUE TITLE
电脑端可以加上阻止撤回成功的提示吗？这样才能知道对方想撤回哪条消息

### ISSUE THREAD

**Issue by MarcoHoo** [huiyadanli/RevokeMsgPatcher#446]
电脑端可以加上阻止撤回成功的提示吗？这样才能知道对方想撤回哪条消息，不然也不知道对方原来撤回了某条消息
像这样
![微信图片_20221012100032](https://user-images.githubusercontent.com/22971812/195231782-26d99f28-8e80-438e-8ce0-53bab547f9db.png)

**Comment by MarcoHoo** [comment]
关了吧，我发出去才看到原来有讨论了，不好意思

**Comment by huiyadanli** [comment]
现在的本防撤回从原理层面来讲，很难做到这种复杂的操作（但是会安全些。

如果有这方面的需求可以选择其他方式防撤回的补丁（比如hook）。

**Comment by linhongjun** [comment]
还是以安全为前提考虑吧  不然被封号就麻烦了
