### ISSUE TITLE
[未支持版本]: TIM 3.4.1.22056

### ISSUE THREAD

**Issue by h7ml** [huiyadanli/RevokeMsgPatcher#450]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

TIM 3.4.1.22056

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/TIM3.4.2/TIM3.4.2.22058.exe

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/55233292/196238982-80935360-fd79-4711-abce-9c801d77c176.png)
![image](https://user-images.githubusercontent.com/55233292/196247313-f1933543-7684-4abf-af02-42715c66396a.png)

**Comment by h7ml** [comment]
> 

我只是修改了文件存储位置

**Comment by huiyadanli** [comment]
我全新安装测试没有这个问题
