### ISSUE TITLE
当前特征匹配数0与期望匹配数1不一致

### ISSUE THREAD

**Issue by bykarina** [huiyadanli/RevokeMsgPatcher#451]
1.更新到最新的微信版本，但是无法安装补丁成功

**Comment by fangxiaomin** [comment]
+1

**Comment by lhcheerup** [comment]
+1

**Comment by huiyadanli** [comment]
更新补丁为最新版本。

请补充微信版本。

**Comment by fangxiaomin** [comment]
3.7.6.44


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyadanli/RevokeMsgPatcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] 当前特征匹配数0与期望匹配数1不一致 (Issue #451)





 
更新补丁为最新版本。
 
请补充微信版本。

**Comment by huiyadanli** [comment]
3.7.6.44 已支持的 请下载最新版本https://github.com/huiyadanli/RevokeMsgPatcher/releases

**Comment by fangxiaomin** [comment]
好的 感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyadanli/RevokeMsgPatcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] 当前特征匹配数0与期望匹配数1不一致 (Issue #451)





 
3.7.6.44 已支持的 请下载最新版本https://github.com/huiyadanli/RevokeMsgPatcher/releases

**Comment by bykarina** [comment]
已安装并且试用成功，谢谢




karina
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyadanli/RevokeMsgPatcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] 当前特征匹配数0与期望匹配数1不一致 (Issue #451)





 好的 感谢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "huiyadanli/RevokeMsgPatcher"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年11月3日(星期四) 下午3:52 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [huiyadanli/RevokeMsgPatcher] 当前特征匹配数0与期望匹配数1不一致 (Issue #451) 
 
 
 
 
 
   
 3.7.6.44 已支持的 请下载最新版本https://github.com/huiyadanli/RevokeMsgPatcher/releases
