### ISSUE TITLE
微信3.8.0.18版本无法进行双开

### ISSUE THREAD

**Issue by jokeliu1** [huiyadanli/RevokeMsgPatcher#453]
微信3.8.0.18版本无法进行双开

**Comment by huiyadanli** [comment]
怎么突然就3.8版本了，有无下载地址

**Comment by SivanWWW** [comment]
> 怎么突然就3.8版本了，有无下载地址

我有安装包 微信官方群里的 如何发给你

**Comment by huiyadanli** [comment]
直接上传或者通过奶牛快传、文叔叔之类的临时文件分享方式分享给我

**Comment by SivanWWW** [comment]
> 直接上传或者通过奶牛快传、文叔叔之类的临时文件分享方式分享给我

 https://cowtransfer.com/s/a16af684090d4f 点击链接查看 [ WeChat3.8.0.18.exe ] ，
或访问奶牛快传 cowtransfer.com 输入传输口令 udzqvx 查看；

**Comment by Jackamy** [comment]
已经更新到[3.8.0.20]了

**Comment by huiyadanli** [comment]
3.8.0 + 多开已经支持
