### ISSUE TITLE
[未支持版本]: 3.8.0.20

### ISSUE THREAD

**Issue by Jackamy** [huiyadanli/RevokeMsgPatcher#454]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.8.0.20

### 对应版本的下载地址

https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

### 软件提示了什么？

微信已自动更新到 [3.8.0.20]

**Comment by Eddie2860** [comment]
最新3.8.0.25

**Comment by Jackamy** [comment]
> 最新3.8.0.25

主要是看到文件夹里面更新了，我一直没重启微信，就没更新还在用18.没想到更新的20又已经听说强制更新到25 了。

**Comment by liuzengwei** [comment]
最新3.8.0.27啦

**Comment by BlingRbt** [comment]
最新3.8.0.27啦
多开好像不成功了
防撤回还行

**Comment by Jackamy** [comment]
> 最新3.8.0.27啦 多开好像不成功了 防撤回还行

不能多开先不升级了，就怕强制升级

**Comment by hu62521** [comment]
最新3.8.0.29也不支持多开

**Comment by yaosj2k** [comment]
已经到30了

**Comment by Gensiss** [comment]
自动更新到了3.8.0.29，不能多开

**Comment by jekey2000** [comment]
自动更新到了3.8.0.31，不能多开

**Comment by yoder** [comment]
自动更新到了3.8.0.33，不能多开

**Comment by huiyadanli** [comment]
3.8.0 + 多开已经支持
