### ISSUE TITLE
多开有问题

### ISSUE THREAD

**Issue by ONLYLOVELYKISS** [huiyadanli/RevokeMsgPatcher#457]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.8.0.20

### 软件提示了什么？

<img width="369" alt="image" src="https://user-images.githubusercontent.com/88222714/200776445-55ae934f-8ebf-4e66-b8ba-13d545a9c665.png">
多开补丁安装失败

**Comment by prophet233** [comment]
3.8.0.31多开安装失败

**Comment by ONLYLOVELYKISS** [comment]
啊？3.8.0.20呢

**Comment by huiyadanli** [comment]
3.8.0 + 多开已经支持
