### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by TF123456789** [huiyadanli/RevokeMsgPatcher#461]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.8.0.33

### 软件提示了什么？

特征码不匹配

**Comment by huiyadanli** [comment]
3.8.0 + 多开已经支持，重试下
