### ISSUE TITLE
[未支持版本]: 3.8.0.33

### ISSUE THREAD

**Issue by China74ya** [huiyadanli/RevokeMsgPatcher#463]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.8.0.33

### 对应版本的下载地址

自动更新

### 软件提示了什么？

特征比对:当前特征码匹配数[O]和期望的匹配数[1]不一致。出现此种情况的一般有如下可能:

如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作者处理。

**Comment by lyhrtb** [comment]
跟帖，遇到同样问题，向大佬求助~~~Orz

**Comment by LeonLyon** [comment]
我也跟帖，我也遇到同样问题，向大佬求助

**Comment by prophet233** [comment]
+1，微信更新了之后多开安装不上了。只有防撤回能用

**Comment by yoder** [comment]
我也跟帖，我也遇到同样问题，向大佬求助

**Comment by Mivimcrs** [comment]
+1，多开无效了

**Comment by jp1017** [comment]
+1

**Comment by huiyadanli** [comment]
3.8.0 + 多开已经支持

**Comment by xuanxiaoxiaoxiao** [comment]
为什么找应用路径里面只有一个桌面 没有其他别的安装路径可以找到啊

**Comment by jp1017** [comment]
> 3.8.0 + 多开已经支持

# 哪里下载呢？1.6版本可以吗

**Comment by huiyadanli** [comment]
@jp1017 1.6 版本重试即可

**Comment by jp1017** [comment]
> @jp1017 1.6 版本重试即可

重试后，**成功**启用了多开功能，感恩，

### 南无大乘妙法莲华经！！！
### 天地万法皆一人一念之所变现！

**Comment by coder-xc** [comment]
不支持防撤回的话，把之前的文件删掉，然后重新下载解压，就可以了，亲测有效

**Comment by Kimi-zhang** [comment]
日常催更

**Comment by yoder** [comment]
> 日常催更

已经支持了哦

**Comment by sorgs** [comment]
防撤回最大的问题是，自己的消息测回了，还是在显示，不知道自己是否测回成功

**Comment by coder-xc** [comment]
> 防撤回最大的问题是，自己的消息测回了，还是在显示，不知道自己是否测回成功

这个确实是大问题，有时候会引用别人已经撤回的消息，就很尴尬

**Comment by scottchen123** [comment]
请问在哪里下载补丁
