### ISSUE TITLE
大佬，微信又更新了，1.6现在用不了了

### ISSUE THREAD

**Issue by 213shensou** [huiyadanli/RevokeMsgPatcher#466]

**Comment by jp1017** [comment]
# 具体说说看，哪个地方用不了？

**Comment by 213shensou** [comment]
![QQ截图20221112194859](https://user-images.githubusercontent.com/89138842/201472602-1f12ef3f-e36a-4fe1-81ee-7e86e19d7dd6.png)

**Comment by 213shensou** [comment]
不能多开了只能防撤回

**Comment by huiyadanli** [comment]
3.8.0 多开已经添加支持，不用更新版本，重新试试
