### ISSUE TITLE
微信3.8.0.33找不到安装路径

### ISSUE THREAD

**Issue by xuanxiaoxiaoxiao** [huiyadanli/RevokeMsgPatcher#467]
微信3.8.0.33，安装路径手动选择里面只有一个桌面可以选择
TIM QQ都能正常安装

**Comment by hdw0504** [comment]
> 微信3.8.0.33，安装路径手动选择里面只有一个桌面可以选择 TIM QQ都能正常安装

需要自己手动选择，找到微信安装路径下的`[3.8.0.33]`
![image](https://user-images.githubusercontent.com/56396696/201508407-1b70d6ce-571d-4cde-bea6-b965ddd5b78a.png)

**Comment by wakichen** [comment]
大佬，该更新了

**Comment by xuanxiaoxiaoxiao** [comment]
![image](https://user-images.githubusercontent.com/118063986/201516598-456ec0b1-5004-4ab5-8233-9ee1b60d8f28.png)
![image](https://user-images.githubusercontent.com/118063986/201516600-949e35ee-4bb2-49c2-bb8f-edd98209a705.png)

**Comment by huiyadanli** [comment]
@wakichen 当前 1.6 支持最新微信

**Comment by xuanxiaoxiaoxiao** [comment]
@huiyadanli 好的 已解决，复制了软件路径过去已安装成功

**Comment by huiyadanli** [comment]
@xuanxiaoxiaoxiao 你这种情况第一次见，跟本软件无关，你所有使用同类型浏览文件夹的功能应该都会出现这个问题，本来就是直接调用的系统API。

如果说只是防撤回键入的话，参考三楼的文件夹路径，手动复制粘贴路径吧。
或者直接重装微信，这样软件能够自动读取到微信的目录

搜索了下，出现的这种情况可能原因是：

当桌面文件夹、文件总数超过一定数量时（具体个数不详，猜测可能跟系统架构或内存有关），点击应用程序中“浏览”按钮时，就会出现你这种情况。

**Comment by huiyadanli** [comment]
> @huiyadanli 好的 已解决，复制了软件路径过去已安装成功

已经学会抢答了....
刚写完答案你已经解决了
