### ISSUE TITLE
更新微信后每次开机必须手动开启多开

### ISSUE THREAD

**Issue by TomaYoshitaka** [huiyadanli/RevokeMsgPatcher#469]
升级微信到3.8.0.33后，每次开机微信的多开插件默认关闭，必须手动打开RevokeMsgPatcher.MultiInstance.exe开启多开

**Comment by huiyadanli** [comment]
重新打补丁即可

**Comment by TomaYoshitaka** [comment]
测试过重新打补丁，还是不行，必须要手动启用

**Comment by huiyadanli** [comment]
补丁打上了但是不能多开？

**Comment by TomaYoshitaka** [comment]
是的，我刚又检查时发现，不是关机后再开机需要手动启动，而是只要把打开的微信多开小工具v0.1点X关掉后，就失效了，再次打开微信多开小工具v0.1时，即使登录的有微信（上一次开启多开时开的两个），也会显示当前数量为0而且必须手动启动多开
![多开](https://user-images.githubusercontent.com/7340168/201814971-d343507e-d0ce-48b9-9b25-fbb650b1767e.png)

**Comment by huiyadanli** [comment]
嗯，这个工具确实是这么使用的。

补丁打上了但是不能多开的问题，应该是由于本地微信安装目录下存在多个版本的文件。补丁并没有打在你正在使用的版本上，你可以打开微信安装目录截图看下
