### ISSUE TITLE
开启防撤回之后，似乎自己发送的消息也不能撤回重新编辑了

### ISSUE THREAD

**Issue by dcl409310085** [huiyadanli/RevokeMsgPatcher#471]
首先感谢大佬辛苦提供的软件
言归正传，如题，能否支持自己的消息可以撤回重新编辑？
能优化的话最好，暂不支持也没关系，不胜感激

**Comment by luojianxhlxt** [comment]
> 

求生欲好高的issue。。。

**Comment by huiyadanli** [comment]
我测试来看是支持的，不影响自己撤回。。

**Comment by dcl409310085** [comment]
> 我测试来看是支持的，不影响自己撤回。。

![Video_2022-11-16_113422](https://user-images.githubusercontent.com/59494558/202078037-97dfaf38-6695-4190-a0f0-8257271fd9da.gif)
可以看一下这个录屏，PS：微信版本，3.8.0.33

**Comment by MarkLily** [comment]
3.8.0.41 也是一样的问题哈~

**Comment by CooperZhuang** [comment]
我也用的3.8.0.41,同样存在这个问题

**Comment by arsenalpoll** [comment]
那我还是先不打补丁了

**Comment by Pieces94** [comment]
> 我也用的3.8.0.41,同样存在这个问题

确实如此，所以我暂时先不打补丁了。希望大佬早日更新一下

**Comment by xzxiaoshan** [comment]
同样的问题，坐等更新

**Comment by Ku-M** [comment]
有没有一种可能，你可以直接复制然后再修改

**Comment by mengxinyizhui** [comment]
> 有没有一种可能，你可以直接复制然后再修改

没有

**Comment by Ri-Yue** [comment]
3.8.0.41 win11
pc端消息撤回不了 点了撤回后手机端并没有撤回 重新打补丁也是一样

**Comment by yisqiu** [comment]
确实存在以上问题

**Comment by jp1017** [comment]
> 不影响自己实际撤回，但是表面上看是没撤回的。

👍 是这样的呀，实际是撤回的，要更新的话，复制一下，再编辑就好了，打到了你的目的了。

win11 微信版本3.8.1.26。

## 所以不知道大家还有什么问题！
