### ISSUE TITLE
麻烦屏蔽升级的提示

### ISSUE THREAD

**Issue by skyformat99** [huiyadanli/RevokeMsgPatcher#475]
微信隔一段时间就升级；
这个时候，如果不升级，会经常收到提示。

看着恶心
能不能把这个提示关闭了。或者屏蔽了？

**Comment by YPR2021** [comment]
这个是微信里面设置的  关这个软件什么事....

**Comment by linhongjun** [comment]
自己关闭更新就行

**Comment by skyformat99** [comment]
不想升级，不要那个升级提示，屏蔽了最好

**Comment by linhongjun** [comment]
自己设置就行了
![1](https://user-images.githubusercontent.com/16095518/209739157-f9ebc2a8-c33c-46a5-b845-c54704dec4f2.jpg)
