### ISSUE TITLE
 微信安装不了

### ISSUE THREAD

**Issue by DanielIsOP** [huiyadanli/RevokeMsgPatcher#476]
![image](https://user-images.githubusercontent.com/34736270/202432708-47040cc9-383d-4d66-b098-ad6573e6b278.png)
这是我选择了我的微信文件夹路径之后
![image](https://user-images.githubusercontent.com/34736270/202432785-ec5f22bc-aa4a-436e-83f2-e19c3725e77d.png)

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/202454373-5073cc46-16fe-4115-954c-9ad9b7bb8eba.png)


参考选择这个目录

**Comment by 727729853** [comment]
感谢
