### ISSUE TITLE
微信电脑版升级为最新版本[3.8.0.41]使用补丁后有卡顿

### ISSUE THREAD

**Issue by zzarking** [huiyadanli/RevokeMsgPatcher#477]
微信电脑版升级为最新版本[3.8.0.41]使用补丁后有卡顿，比如在微信里输入@ ，然后微信就卡顿了，界面也消失了一下，能否升级一下补丁，谢谢。

**Comment by huiyadanli** [comment]
微信本身的问题，清理微信的临时文件试试
