### ISSUE TITLE
0.6版本不支持微信2.7.1.88

### ISSUE THREAD

**Issue by Dddota** [huiyadanli/RevokeMsgPatcher#48]
![image](https://user-images.githubusercontent.com/28125380/69908320-91c05a00-1421-11ea-961f-8e2e5e9572e9.png)

**Comment by huiyadanli** [comment]
最新补丁无法获取导致，正在修复中...

**Comment by huiyadanli** [comment]
服务已经恢复，请关注右下角获取最新补丁的提示。等获取到最新补丁之后再防撤回就可以了
