### ISSUE TITLE
微信电脑版[3.8.0.41]安装补丁后，电脑端撤回不了消息

### ISSUE THREAD

**Issue by mengxinyizhui** [huiyadanli/RevokeMsgPatcher#482]
电脑端撤回消息后，该消息还显示在列表里，其实已经撤回了，但是自己列表里还有

**Comment by mengxinyizhui** [comment]
https://user-images.githubusercontent.com/59494558/202078037-97dfaf38-6695-4190-a0f0-8257271fd9da.gif
这个录屏

**Comment by BigBigBIgMan** [comment]
盲猜一下，他的意思是，点撤回后，自己的聊天页还是显示，其实，对方收到的消息已经撤回了

**Comment by huiyadanli** [comment]
不影响实际撤回效果
