### ISSUE TITLE
3.8.1.19无法安装多开

### ISSUE THREAD

**Issue by CaufieldZ** [huiyadanli/RevokeMsgPatcher#484]
3.8.1.19无法安装多开

**Comment by TomaYoshitaka** [comment]
+1，防撤回可以正常安装，但多开只能手动启用

![image](https://user-images.githubusercontent.com/7340168/206937961-35956427-444f-4325-bd2e-6e036198cd29.png)

**Comment by jp1017** [comment]
> 多开只能手动启用

怎么手动打开呢

**Comment by xiegoudan** [comment]
手动多开微信很简单，退出所有微信，鼠标单击微信图标，然后按多少次enter键就弹出多少个登录，记住，要在微信弹出登录界面前多按几次。

**Comment by q2119990** [comment]
> 来个这个版本的打包，我这边没法自动更新到这个版本

https://cloud.189.cn/web/share?code=qmqUnmzMVVJj（访问码：6pjy）

**Comment by starscen** [comment]
3.8.1.26同样无法多开
![image](https://user-images.githubusercontent.com/44452287/208034487-4d0e8795-84a3-45dd-9ba3-45ac047bb1e0.png)

**Comment by huiyadanli** [comment]
3.8.1.* 已经支持，试试

**Comment by jp1017** [comment]
> 3.8.1.* 已经支持多开，试试

+ 可以了，cooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo……l
