### ISSUE TITLE
Tim最新版 期望值 不一致

### ISSUE THREAD

**Issue by 123114** [huiyadanli/RevokeMsgPatcher#485]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

TIM   3.4.3.22064   正式版本

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/TIM3.4.3/TIM3.4.3.22064.exe

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/40789222/206847252-0cfdd15f-682f-47b6-8ace-b7f9e5f32caa.png)
特征码 不一致  匹配数【0】 与 期望 【3】 不一致

**Comment by huiyadanli** [comment]
请使用最新的1.6版本
