### ISSUE TITLE
无法获得最新补丁信息

### ISSUE THREAD

**Issue by Mo0546** [huiyadanli/RevokeMsgPatcher#49]
已用管理员身份打开，没有设置代理，0.6 版提示不支持微信 2.7.1.88，无法获得最新补丁消息
![20191201160344](https://user-images.githubusercontent.com/42494601/69911329-c8fc2e80-1454-11ea-9b5f-640091a7457c.png)

**Comment by huiyadanli** [comment]
coding 的pages服务挂了。。

**Comment by Mo0546** [comment]
已经可以用了，大佬辛苦了

**Comment by wzshuang** [comment]
获取最新的补丁信息失败
