### ISSUE TITLE
[未支持版本]:请求来个MAC版本的

### ISSUE THREAD

**Issue by ohnoa** [huiyadanli/RevokeMsgPatcher#490]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

mac微信

### 软件提示了什么？

请来个MAC版本的

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues?q=mac
