### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by Ten-G** [huiyadanli/RevokeMsgPatcher#491]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.8.1.26

### 对应版本的下载地址

https://pc.weixin.qq.com/

### 软件提示了什么？

刚刚微信更新了一个小版本，重新安装补丁显示特征码不匹配，经测试未安装成功

**Comment by Stpehen-Hito** [comment]
![屏幕截图 2022-12-28 203909](https://user-images.githubusercontent.com/121556648/209813695-cc22a02d-a2f5-4129-bfba-c2d0609ca5d0.png)
同样

**Comment by qjx378** [comment]
![image](https://user-images.githubusercontent.com/2217077/209819604-441327d5-86f0-49cf-9a85-7a2d5681411b.png)

**Comment by ring0li** [comment]
我也是呢，奇怪

**Comment by huiyadanli** [comment]
最新补丁信息的存储欠费了:joy: 已经恢复，重试即可

**Comment by qwertyue** [comment]
> 最新补丁信息的存储欠费了😂 已经恢复，重试即可

请问作者大大，微信3.7.5.23应该支持这个防撤回带提示吗？
我的3.7.5.23的微信好像不支持

**Comment by huiyadanli** [comment]
@qwertyue 3.7.5.23 支持带提示的防撤回

**Comment by qwertyue** [comment]
> @qwertyue 3.7.5.23 支持带提示的防撤回

难道是因为我之前用过老版本的防撤回 我再试试
