### ISSUE TITLE
[未支持版本]: 3.8.1.26

### ISSUE THREAD

**Issue by LanRenLan** [huiyadanli/RevokeMsgPatcher#493]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.8.1.26

### 对应版本的下载地址

弹出窗口更新

### 软件提示了什么？

![微信截图_20221229085120](https://user-images.githubusercontent.com/112599739/209984255-6992b638-97b2-4c95-9a30-378575b18efb.png)
![image](https://user-images.githubusercontent.com/112599739/209984303-f3af6e1e-962d-4656-9002-951d7413767b.png)
微信更新完成后，打开RevokeMsgPatcher，并未提示需要安装插件，随后防撤回功能失效。还原后重新安装旧版防撤回也无效

**Comment by huiyadanli** [comment]
请确认是否能够访问这个地址 ： https://hui-config.oss-cn-hangzhou.aliyuncs.com/1.6/patch.json

出现这种情况的原因是未获取到最新的补丁信息

**Comment by zhuanshulz** [comment]
确认能够访问后重启补丁软件即可。
