### ISSUE TITLE
安装补丁后提示“未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by pcfaq** [huiyadanli/RevokeMsgPatcher#496]
Windows 11 专业版       版本	22H2      操作系统版本	22621.963
微信版本 2.8.0.112
点击安装补丁后出现以下提示，不知道是哪里的问题？
<img width="587" alt="image" src="https://user-images.githubusercontent.com/122148328/211141183-e0668371-5f4c-4b42-851c-87e2183f03cd.png">

**Comment by huiyadanli** [comment]
额，你这个版本有点太老了吧。

应该是迭代中老的补丁模式逻辑出现了bug

报错详情的内容（异常文本）能完整贴过来吗？

**Comment by huiyadanli** [comment]
#511
