### ISSUE TITLE
[未支持版本]: 3.9.0.22

### ISSUE THREAD

**Issue by hecarli555** [huiyadanli/RevokeMsgPatcher#497]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.9.0.22

### 软件提示了什么？

已经无法多开了，希望大佬修复

**Comment by kanbaopeng** [comment]
附议

**Comment by fatcatsk** [comment]
附议

**Comment by Hiikki** [comment]
+1

**Comment by defix** [comment]
+1

**Comment by cddehsy** [comment]
支持的啊

**Comment by JRGavin** [comment]
附议

**Comment by CaufieldZ** [comment]
同样的情况，求修复

**Comment by levie-vans** [comment]
+1

**Comment by Fthrepublic** [comment]
此版本经测试，不支持多开。等作者修复

**Comment by bravolover520** [comment]
附议

**Comment by apull-zy** [comment]
多开不支持了，临时用批处理多开。

**Comment by medico4949** [comment]
> 

请问 如何使用批处理多开

**Comment by medico4949** [comment]
> 多开不支持了，临时用批处理多开。

请问 如何使用批处理多开

**Comment by mzmang** [comment]
以下多开批处理（保存为bat文件直接执行，记得路径更换为自己的）
@echo off
start /d "D:\Program Files (x86)\Tencent\WeChat\" WeChat.exe
start /d "D:\Program Files (x86)\Tencent\WeChat\" WeChat.exe
exit

**Comment by huiyadanli** [comment]
3.9.0.22 多开已经支持

**Comment by medico4949** [comment]
> 以下多开批处理（保存为bat文件直接执行，记得路径更换为自己的） @echo off start /d "D:\Program Files (x86)\Tencent\WeChat" WeChat.exe start /d "D:\Program Files (x86)\Tencent\WeChat" WeChat.exe exit

感谢，已成功
