### ISSUE TITLE
QQ频道支持

### ISSUE THREAD

**Issue by zgzyh** [huiyadanli/RevokeMsgPatcher#498]
可不可以支持QQ频道防撤回

**Comment by EmiyaNiu** [comment]
QQ频道应该很难吧，感觉是独立开的。

**Comment by huiyadanli** [comment]
QQ频道聊天功能寄了hhh

**Comment by zgzyh** [comment]
没有啊



发自我的iPad


------------------ 原始邮件 ------------------
发件人: 辉鸭蛋 ***@***.***&gt;
发送时间: 2024年2月25日 12:14
收件人: 2738226109 ***@***.***&gt;
主题: Re: [huiyadanli/RevokeMsgPatcher] QQ频道支持 (Issue #498)





 
QQ频道聊天功能寄了hhh
