### ISSUE TITLE
出现消息丢失问题

### ISSUE THREAD

**Issue by ineac** [huiyadanli/RevokeMsgPatcher#499]
![image](https://user-images.githubusercontent.com/111550029/212905234-a2b35d26-777c-4433-8d35-209334f20e62.png)
出现有  **首条未读消息** ，点击跳转后，重新回到最新消息位置，会只出现几天前的消息，最新的消息丢失了。
qq重新下载了还原补丁，也还是这样。
如果有空可以麻烦说一下，解决办法吗？

**Comment by e4je** [comment]
你这个问题很奇怪啊，你都说还原了补丁了那就跟作者的软件没关系了吧，为什么不去问腾讯客服跑来这里提这种问题。

**Comment by ineac** [comment]
> 

我是用了补丁才会出现这种情况的，并且也有其他人也反映过有这个问题。

而且我说的是开了补丁才会出现消息丢失的情况（没有用之前都不会有这种问题），并且还原补丁了以后消息还是没有回来，那就代表这个问题是永久性的。

我也不确定是不是补丁和qq版本不兼容或者之类的什么问题，我只是提出有这种情况出现而已，并不是针对作者，并且我用了10多年的qq了，我现在的qq版本也用了很久没更新了，从来都没有出现过这种情况。只有用补丁才会出现这种情况。

**Comment by ineac** [comment]
> 你这个问题很奇怪啊，你都说还原了补丁了那就跟作者的软件没关系了吧，为什么不去问腾讯客服跑来这里提这种问题。

我是用了补丁才会出现这种情况的，并且也有其他人也反映过有这个问题。

而且我说的是开了补丁才会出现消息丢失的情况（没有用之前都不会有这种问题），并且还原补丁了以后消息还是没有回来，那就代表这个问题是永久性的。

我也不确定是不是补丁和qq版本不兼容或者之类的什么问题，我只是提出有这种情况出现而已，并不是针对作者，并且我用了10多年的qq了，我现在的qq版本也用了很久没更新了，从来都没有出现过这种情况。只有用补丁才会出现这种情况。

**Comment by huiyadanli** [comment]
我测试不打补丁的情况下，群消息多到一定程度的情况下，会出现类似的情况
