### ISSUE TITLE
微信发了个支持小程序的内测版2.7

### ISSUE THREAD

**Issue by aliofwind** [huiyadanli/RevokeMsgPatcher#5]
https://developers.weixin.qq.com/miniprogram/dev/devtools/pc-dev.html
有点心动想升级，防撤回能不能更新上

https://dldir1.qq.com/weixin/Windows/WeChat2.7.0_beta.exe
直链

**Comment by huiyadanli** [comment]
已经支持 2.7.0.65

**Comment by 17637462979** [comment]
牛皮，剛想著。支不支持就看到了

**Comment by Tanler** [comment]
> 已经支持 2.7.0.65

你好，我这里安装最新测试版的版本号是2.7.0.70，提示微信版本不支持。

**Comment by huiyadanli** [comment]
@Tanler 2.7.0.70 已经支持
