### ISSUE TITLE
QQ10多年的聊天记录和Tim6年的聊天记录都丢失了，做好聊天记录的备份。

### ISSUE THREAD

**Issue by kaixinsoft** [huiyadanli/RevokeMsgPatcher#502]
QQ10多年的聊天记录和Tim6年的聊天记录都丢失了，不知道和使用这个有关吗？
一个是22年11月份丢失的，一个是刚刚丢失的。登录的时候都有提示说什么文件损坏，忘记截图了。
QQ和Tim都是最新版本，是不是QQ在程序里增加了对QQ软件本身文件的校验，从而做了某些处理。
聊天记录丢失了，感觉损失很大。希望大家做好聊天记录的备份。
本开源软件很好，仅是猜测，可能也有其他原因造成的聊天记录丢失。
谢谢作者带来这么好的软件。

**Comment by huiyadanli** [comment]
暂时作为问题挂在这边，看看有没有类似的情况发生。

补丁造成聊天记录丢失的概率不大
