### ISSUE TITLE
微信不显示撤回的提示

### ISSUE THREAD

**Issue by cattle891240** [huiyadanli/RevokeMsgPatcher#507]
自从3.8xxxx版本后的微信好像就不显示防撤回的提示了。曾经有一段时间补丁版本有显示新版本和老版本的防撤回，但是随着微信的更新，我在windows10和windows11电脑版微信上就只能看见老版本的防撤回补丁，这个是基于什么原因呢？有没有办法解决显示防撤回的提示？有时候人家都撤回了我还在引用消息并回复对方。

**Comment by huiyadanli** [comment]
因为新的方式找不到了:joy:   

所以只有老的方式了

**Comment by cattle891240** [comment]
那有办法可以说新原理的思路让大家摸索？

**Comment by huiyadanli** [comment]
思路见wiki的一些引用，基本都差不多。
