### ISSUE TITLE
关于微信安装路径 [3.9.0.28]  的问题

### ISSUE THREAD

**Issue by Joey-zy1024** [huiyadanli/RevokeMsgPatcher#509]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.9.0.28

### 软件提示了什么？

不知道什么时候开始 安装使用了 RevokeMsgPatcher软件 之前1.X版本的时候使用过 中间有段时间没用过
后来再使用的时候发现用不了了 获取的微信安装路径 居然 是 D:\SoftwareCommon\Tencent\WeChat\[3.9.0.28] 这样格式的
请问下各位大佬有遇到过这样的问题吗？怎么解决呢？

**Comment by huiyadanli** [comment]
新版本微信的目录结构变更过

**Comment by Joey-zy1024** [comment]
感谢大佬的回复！！！但是我的问题是怎么变更回以前正常的微信安装目录呢？感觉现在的安装路径目录很怪
求告知 谢谢大佬



在 2023-02-13 11:59:02，"辉鸭蛋" ***@***.***> 写道：

新版本微信的目录结构变更过

**Comment by huiyadanli** [comment]
这个是微信官方的更新，正常情况下肯定没法变回去了。除非一直用老版本。
