### ISSUE TITLE
补丁获取失败了

### ISSUE THREAD

**Issue by ZORfree** [huiyadanli/RevokeMsgPatcher#51]
![image](https://user-images.githubusercontent.com/26847215/70765509-fa9ac100-1d95-11ea-9adb-058f9adbf6cd.png)

**Comment by ZORfree** [comment]
![image](https://user-images.githubusercontent.com/26847215/70765631-48172e00-1d96-11ea-903d-3063a5fe5c48.png)

**Comment by huiyadanli** [comment]
coding的pages服务又双叒叕挂了，下个版本会切换到其他静态资源存放的地方。

按照之前的经验，1天左右的时间会自动恢复。
