### ISSUE TITLE
收到的word、excel、PPT文档都成了只读模式

### ISSUE THREAD

**Issue by asprin51** [huiyadanli/RevokeMsgPatcher#510]
收到的word、excel、PPT文档都成了只读模式，不能直接便捷了，需要先改属性为可读可写模式，最新版的微信，最新版的防撤回

**Comment by huiyadanli** [comment]
与补丁无关，还原后试试

**Comment by syuraking** [comment]
腾讯加的脑残机制，PC版的微信3.9以上版本存在，接收的文件自动修改为只读属性。
如果不想被这样，用3.8版本，屏蔽更新
