### ISSUE TITLE
[特征对比不一致] 安装Windows 微信补丁时发生错误

### ISSUE THREAD

**Issue by AlanduzzZ** [huiyadanli/RevokeMsgPatcher#512]
微信版本：
3.9.0.28

OS 版本：
Windows 10 企业版 22H2 19045.2604

防撤回补丁版本：
v1.6，且右下角已经提示为最新

期望结果：
正常安装微信防撤回补丁，实现微信防撤回功能

现状：
无论是选择老版本补丁还是新版本补丁，亦或者两个都选，然后在跳出来的弹窗选是，最终结果都提示特征对比不一致，具体报错如下：
![image](https://user-images.githubusercontent.com/10544715/220057430-e5ec68c4-6464-4d3c-adb7-69b24c98bd57.png)

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/220062914-24420303-dbb9-4fef-871d-54c1bb07e59d.png)

正常的界面是这样的，可选功能不会有(新)的补丁。。是不是你下载的某个版本有问题。。

试试 https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.6  这里的版本

**Comment by AlanduzzZ** [comment]
看起来并不是版本的问题
![image](https://user-images.githubusercontent.com/10544715/220075263-a7a3e4db-de4f-448f-b679-4c5e71b8b8aa.png)

如果两个版本都勾选，中间会有这个确认框
![image](https://user-images.githubusercontent.com/10544715/220075092-86b05c43-3d43-439f-9b2f-529f04221235.png)

**Comment by AlanduzzZ** [comment]
中间有过这么一个操作：

1、因为换电脑了，就把旧电脑的微信数据目录copy了一份到新电脑上

2、安装微信后，重新登陆账号

3、在微信设置中重新指定了微信数据目录到旧电脑的数据目录。

然后就发现这个问题了

**Comment by AlanduzzZ** [comment]
前面把微信卸载了(不保留本地数据)，重新安装，仍然是这个问题

**Comment by AlanduzzZ** [comment]
我找到问题了。

前面看了下代码，发现RevokeMsgPatcher还需要在打补丁时下载某些静态资源，而且这些看起来有些放在对象存储里面，但是我们公司最近上了AC，劫持了诸多网盘及对象存储的HTTPS证书，导致RevokeMsgPatcher在下载的时候HTTPS连接错误，无法下载静态文件，应该是有些静态文件缺失导致程序异常。

感觉可以输出点log在本地，不然调试起来也挺难受，总之解决了！

感谢这个伟大的项目！

**Comment by huiyadanli** [comment]
可以下载action中的最新编译版本，内置补丁信息的就是最新的。 https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/3922143775

我就好奇为啥显示的内置补丁已经是最新的，release里面的内置补丁文件应该是很久的一个版本了。正常应该会显示“获取成功”。


![image](https://user-images.githubusercontent.com/15783049/220083456-03b2391a-5a8c-4690-ba62-422c29acd7f0.png)


不过看上去现在软件可能也存在，被劫持的情况下应该是会抛出错误显示获取补丁信息失败的。

**Comment by AlanduzzZ** [comment]
但是我这边就是被劫持之后没有报错。

在已经正确安装了补丁之后，正常来说应该是"备份还原"按钮是可以点的，"安装补丁！"是灰色的。

但是获取资源失败的情况下这两个按钮都是可以点的，只不过点了“安装补丁！”之后就会是我这个报错

下次我去action里面下载吧。

但是有个疑问，为什么资源下载失败还是会显示获取成功呢？

**Comment by huiyadanli** [comment]
"https://hui-config.oss-cn-hangzhou.aliyuncs.com/1.6/patch.json",
            "https://cdn.jsdelivr.net/gh/huiyadanli/RevokeMsgPatcher@master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json",
            "https://ghproxy.com/https://raw.githubusercontent.com/huiyadanli/RevokeMsgPatcher/master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json",
            "https://raw.fastgit.org/huiyadanli/RevokeMsgPatcher/master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json",
            "https://huiyadanli.coding.net/p/RevokeMsgPatcher/d/RevokeMsgPatcher/git/raw/master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json",
            "https://raw.githubusercontent.com/huiyadanli/RevokeMsgPatcher/master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json"

**Comment by AlanduzzZ** [comment]
[https://hui-config.oss-cn-hangzhou.aliyuncs.com/1.6/patch.json](url) 被劫持，提示证书错误
[https://huiyadanli.coding.net/p/RevokeMsgPatcher/d/RevokeMsgPatcher/git/raw/master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json](url) 提示连接被重置
[https://raw.githubusercontent.com/huiyadanli/RevokeMsgPatcher/master/RevokeMsgPatcher.Assistant/Data/1.6/patch.json](url) 被墙

当前坐标：上海
