### ISSUE TITLE
希望QQ微信反撤回能看到“对方撤回了这条消息”的提示

### ISSUE THREAD

**Issue by GreatAden** [huiyadanli/RevokeMsgPatcher#513]
如题，希望QQ微信的反撤回能加入这个功能，不然我甚至不知道对方撤回了这条消息，还得拿手机去看。如果能添加这个功能，那么谢谢大佬，插件目前看已经很不错了
![000F74F8](https://user-images.githubusercontent.com/89302318/220792864-72732976-7588-40b2-a49b-d3a97d99e511.png)

**Comment by pawn-sxy** [comment]
+1

**Comment by sadboy-cn** [comment]
+1

**Comment by sfc9982** [comment]
现在是直接删掉撤回相关汇编，我觉得加入提示还得使用新方法，可以看下第三方客户端，很多支持你所说的提示功能。

**Comment by cnvoa** [comment]
+1

**Comment by wky114** [comment]
> 现在是直接删掉撤回相关汇编，我觉得加入提示还得使用新方法，可以看下第三方客户端，很多支持你所说的提示功能。

请问是什么第三方客户端？

**Comment by huiyadanli** [comment]
#243
