### ISSUE TITLE
.Net框架高于4.5+， 但是也打不开

### ISSUE THREAD

**Issue by Corgile** [huiyadanli/RevokeMsgPatcher#514]
> [.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642) 或更高版本。低于此版本在打开程序时可能无反应，或者直接报错。

如题，我的.NET版本

![image](https://user-images.githubusercontent.com/48396880/220941147-1a4204cb-baa5-4947-8d87-c3d7aed5837f.png)

**Comment by huiyadanli** [comment]
打开时有无报错提示？

没有的话，直接下载安装 [.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642) 试试

**Comment by Corgile** [comment]
试过，低版本安装不了。如图

![image](https://user-images.githubusercontent.com/48396880/221091805-ce4a1ea5-d3dc-4c4d-ad87-c668df5b1b41.png)

**Comment by huiyadanli** [comment]
以管理员权限打开了吗，是否存在安全软件的静默拦截。

**Comment by Corgile** [comment]
> 以管理员权限打开了吗，是否存在安全软件的静默拦截。
> 
> 深入研究的方式：可以打开windows事件管理器找下软件启动时的报错

都试过了，时事件查看器里没有AntiRevoke相关的日志。

**Comment by huiyadanli** [comment]
等等，AntiRevoke？

应该是 RevokeMsgPatcher 或者 .net 相关的内容
