### ISSUE TITLE
[未支持版本]: 3.9.2.6

### ISSUE THREAD

**Issue by uvips** [huiyadanli/RevokeMsgPatcher#516]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信测试版3.9.2.6

### 对应版本的下载地址

https://www.aliyundrive.com/s/RhKwhFsgoBu

### 软件提示了什么？

补丁安装已经成功，实际防撤回测试是失效的

**Comment by huiyadanli** [comment]
微信 3.9.2.23 防撤回已经更新 https://github.com/huiyadanli/RevokeMsgPatcher/issues/535
