### ISSUE TITLE
[未支持版本]: 3.9.2.12

### ISSUE THREAD

**Issue by aoguai** [huiyadanli/RevokeMsgPatcher#517]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信测试版 3.9.2.12

### 软件提示了什么？

多开、撤回失效

特征比对:当前特征码匹配数[0]和期望的匹配数[1]不一致。出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
⒉如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作者处理。

**Comment by qq17854** [comment]
+1

**Comment by q2119990** [comment]
3.9.2.15   显示支持，实际防撤回无效，多开无效

**Comment by huiyadanli** [comment]
微信 3.9.2.23 防撤回已经更新 https://github.com/huiyadanli/RevokeMsgPatcher/issues/535
