### ISSUE TITLE
你好作者我问一下最新版的QQ9能不能用

### ISSUE THREAD

**Issue by fgr178707** [huiyadanli/RevokeMsgPatcher#519]
你好作者我问一下最新版的QQ9能不能用

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/223728006-ddaf7afa-0085-4b0d-a9f7-97978a947205.png)

我测试可以

**Comment by fgr178707** [comment]
好的谢谢
