### ISSUE TITLE
微信2.7.2.76不支持

### ISSUE THREAD

**Issue by kimihiro233** [huiyadanli/RevokeMsgPatcher#52]
微信2.7.2.76，提示不支持该版本

**Comment by huiyadanli** [comment]
这个版本应该是测试版，能提供一个下载链接吗？

**Comment by xx10n31y** [comment]
[打补丁教程](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E5%BE%AE%E4%BF%A1%E9%98%B2%E6%92%A4%E5%9B%9E%E4%B8%8E%E5%A4%9A%E5%BC%80%E6%95%99%E7%A8%8B)

跟着大佬的教程自己打的补丁,可用,不放心可以跟着大佬教程操作




[WeChatWin.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/3987687/WeChatWin.zip)

**Comment by mrchzh** [comment]
微信自动更新了...今早给我自动更新了！现在不行了 防撤回  我已经关掉了

**Comment by whwnow** [comment]
我的也自动更新了，没防撤回还好，没了多开很难受，求更新

**Comment by huiyadanli** [comment]
@xx10n31y @mrchzh @whwnow 
能否提供一个新版本微信目录的打包，我接受不到这个更新

**Comment by huiyadanli** [comment]
@whwnow 关于多开，最近开发了微信通用多开的小工具（未发布），通杀所有版本，你可以试试

[微信通用多开.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/3994848/default.zip)

**Comment by whwnow** [comment]
@huiyadanli 是不是只提供`WeChatWin.dll`就够了？

**Comment by huiyadanli** [comment]
@whwnow 最好提供整个微信目录的打包，这样可以验证最终结果。建议通过邮件发送 huiyadanli@126.com

**Comment by whwnow** [comment]
> @whwnow 最好提供整个微信目录的打包，这样可以验证最终结果。建议通过邮件发送 [huiyadanli@126.com](mailto:huiyadanli@126.com)

查收一下

**Comment by huiyadanli** [comment]
@kimihiro233 @mrchzh @whwnow 已经更新支持
