### ISSUE TITLE
微信刚更新了，重新安装补丁后无法多开

### ISSUE THREAD

**Issue by mrchengcheng** [huiyadanli/RevokeMsgPatcher#522]
如题

**Comment by mrchengcheng** [comment]
微信最新版本是3.9.2.20

**Comment by crydear** [comment]
> 微信最新版本是3.9.2.20

我这个版本防撤回也失效了

**Comment by jet0duqiqi** [comment]
+1

**Comment by miaowu001** [comment]
![image](https://user-images.githubusercontent.com/78711864/224945792-ea5337dc-af47-4284-abf6-05cdde98e018.png)

**Comment by se7enalways** [comment]
求大大更新脚本, 嘻嘻, 已經離不開多開, 還有賤兮兮的防撤回;D
