### ISSUE TITLE
管理员身份打开只加载一会儿就没反应了，也没新的窗口

### ISSUE THREAD

**Issue by Jang1221** [huiyadanli/RevokeMsgPatcher#524]
1

**Comment by huiyadanli** [comment]
请使用[.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642) 或更高版本。低于此版本在打开程序时可能无反应，或者直接报错。

如果确认.NET Framework 4.5.2已经安装，尝试以管理员权限打开。观察是否存在安全软件的静默拦截。

如果以上操作都没反应，可以打开windows事件管理器找下软件启动时软件本体或者.NET相关的报错。

**Comment by Jang1221** [comment]
> 请使用[.NET Framework 4.5.2](https://www.microsoft.com/en-us/download/details.aspx?id=42642) 或更高版本。低于此版本在打开程序时可能无反应，或者直接报错。
> 
> 如果确认.NET Framework 4.5.2已经安装，尝试以管理员权限打开。观察是否存在安全软件的静默拦截。
> 
> 如果以上操作都没反应，可以打开Windows事件管理器找下软件启动时软件本体或者.NET相关的报错。

请问如果是NET相关的报错需要怎么解决呢
