### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by forever11eleven** [huiyadanli/RevokeMsgPatcher#526]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.9.2.20

### 对应版本的下载地址

3.9.2.20

### 软件提示了什么？

发出去可以撤回了，防撤回失效了
![捕获](https://user-images.githubusercontent.com/75199923/225180969-ad76a596-08d9-4a87-81a9-010066108b6d.PNG)

**Comment by Jackamy** [comment]
没出现这个，提示成功，但不能多开。

**Comment by JovanFeng** [comment]
只能先到官网安装旧版本用了，屏蔽自动更新
