### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by lolofivewx** [huiyadanli/RevokeMsgPatcher#527]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.9.0.28

### 对应版本的下载地址

https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

### 软件提示了什么？

补丁安装成功后，撤回消息未拦截成功。

**Comment by huiyadanli** [comment]
3.9.0.28一直是支持的，请确认你使用的补丁软件是最新的
