### ISSUE TITLE
Win微信3.9.2.20防撤回失效

### ISSUE THREAD

**Issue by fuchengxin** [huiyadanli/RevokeMsgPatcher#528]
![image](https://user-images.githubusercontent.com/15795966/225568989-e3d705b9-1177-4214-a7fc-255fd2c0a6ac.png)
已经下载了最新版本，防撤回还是没有生效
![image](https://user-images.githubusercontent.com/15795966/225569418-624bdda4-f091-4050-b30d-6512e0e858ff.png)

**Comment by fuchengxin** [comment]
![image](https://user-images.githubusercontent.com/15795966/225569706-906a0ab9-12ba-46d4-a186-6eb67f936f7f.png)
点击安装补丁会提示不匹配

**Comment by gejiawei007** [comment]
加1  而且多开也使用不了了

**Comment by xiangxingze** [comment]
芜湖，要等作者更新了哦

**Comment by tiger-do** [comment]
俺也是，要等更新了

**Comment by AlanduzzZ** [comment]
可以看看是不是我这个问题 #512

**Comment by huiyadanli** [comment]
这个版本确实是不支持的，最近工作太忙了。防撤回找新的方案。

**Comment by xiaodu33603** [comment]
> Owner

什么时候更新呀

**Comment by ououming123** [comment]
今天忽然更新已经变成3.9.2.22了    比你这个issue又更新了..

**Comment by shanyoumuxi-1** [comment]
期待更新，感谢

**Comment by zyfwq** [comment]
3.9.2.22不能用了，防撤回没关注，就是多开不行了

**Comment by zyfwq** [comment]
最新的微信版本是3.9.2.23不能用

**Comment by yaofeng2688** [comment]
期待更新，感谢

**Comment by haoyu-lab** [comment]
期待更新，感谢

**Comment by popokcn** [comment]
最新微信发神经病了，一直疯狂更新。又看不出更新了什么垃圾

**Comment by AdeSpike** [comment]
微信3.9.23也是无法用了，多开显示特征码不匹配

**Comment by fuchengxin** [comment]
想要多开手动运行文件里面的RevokeMsgPatcher.MultiInstance.exe 应该也可以

**Comment by Cterry0516** [comment]
我把微信版本还原到3.9.0.28 😄 终于可以用了

**Comment by qingshuangyixia** [comment]
> 
大佬怎么退级的

**Comment by qingshuangyixia** [comment]
> 我把微信版本还原到3.9.0.28 😄 终于可以用了

大佬怎么还原的能说说方法吗？

**Comment by Alleninggx** [comment]
> > 我把微信版本还原到3.9.0.28 😄 终于可以用了
> 
> 大佬怎么还原的能说说方法吗？

https://github.com/tom-snow/wechat-windows-versions

**Comment by fuchengxin** [comment]
#543 已经有了补丁，可用

**Comment by huiyadanli** [comment]
微信 3.9.2.23 防撤回已经更新 https://github.com/huiyadanli/RevokeMsgPatcher/issues/535
