### ISSUE TITLE
微信2.8.0.82目前不支持

### ISSUE THREAD

**Issue by peshxx** [huiyadanli/RevokeMsgPatcher#53]
今天更新了2.8.0.82版本，求大佬支持

**Comment by huiyadanli** [comment]
可以提供一份安装包或者微信目录的打包吗？
暂时接受不到测试版的更新

**Comment by Kiritomo** [comment]
我通过抓包获取到了更新文件，但是没法解密安装，大佬有兴趣的话可以研究一下
https://dldir1.qq.com/weixin/Windows/WeChat_2.7.1_update88_ex.xml
https://dldir1.qq.com/weixin/Windows/WeChat_2.7.1_update88_ex.dat

**Comment by Kiritomo** [comment]
> 可以提供一份安装包或者微信目录的打包吗？
> 暂时接受不到测试版的更新

我通过抓包获取到了更新文件，但是没法解密安装，大佬有兴趣的话可以研究一下
https://dldir1.qq.com/weixin/Windows/WeChat_2.7.1_update88_ex.xml
https://dldir1.qq.com/weixin/Windows/WeChat_2.7.1_update88_ex.dat

**Comment by huiyadanli** [comment]
@Kiritomo 感谢提供信息，这两个 url 的东西已经几乎等同于安装包了。不过要切分文件，有点麻烦:joy:

我通过拼 url 得到了一份 2.8.0.78 的安装包
https://dldir1.qq.com/weixin/Windows/WeChat2.7.2_beta.exe

**Comment by Kiritomo** [comment]
> @Kiritomo 感谢提供信息，这两个 url 的东西已经几乎等同于安装包了。不过要切分文件，有点麻烦
> 
> 我通过拼 url 得到了一份 2.8.0.78 的安装包
> https://dldir1.qq.com/weixin/Windows/WeChat2.7.2_beta.exe

我记得我是20号看到IT之家的新闻说微信测试版更新到了2.7.2.76版本，但是当时通过WeChat2.7.2_beta.exe这个链接无法请求到文件，所以通过抓包和拼url得到了上面的那两个文件，没想到今天居然可以了，也是没太搞懂微信实际的版本号与下载链接里的版本号有啥关联

**Comment by huiyadanli** [comment]
有热心网友邮箱发了一个2.8.0.82 版本微信的打包，现在已经支持该版本的防撤回

**Comment by Kiritomo** [comment]
> 有热心网友邮箱发了一个2.8.0.82 版本微信的打包，现在已经支持该版本的防撤回

现在却有一个问题，安装2.8.0.82版本之后，WeChatWin.dll的里的信息却是2.7.2.82，导致识别为未支持的版本

**Comment by huiyadanli** [comment]
> 现在却有一个问题，安装2.8.0.82版本之后，WeChatWin.dll的里的信息却是2.7.2.82，导致识别为未支持的版本

先“还原”后“点我防撤回”试试，相当于直接使用老版本的dll，一般是可以用的。
