### ISSUE TITLE
若出现安装补丁失败，一个解决办法

### ISSUE THREAD

**Issue by YuetKaka15** [huiyadanli/RevokeMsgPatcher#531]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.3

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/108283159/227082240-150edce1-f140-494b-92bd-a5c09ab77093.png)

若出现此问题，可适用微信版本3.3，卸载新版微信后安装
可适用网上的安装包，此处提供我使用的版本以及下载网址，自行安装https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_faq_list&head=true

**Comment by huiyadanli** [comment]
微信 3.9.2.23 防撤回已经更新 https://github.com/huiyadanli/RevokeMsgPatcher/issues/535
