### ISSUE TITLE
[未支持版本]: 3.9.2.23多开不支持

### ISSUE THREAD

**Issue by mrdijj** [huiyadanli/RevokeMsgPatcher#533]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

正式版3.9.2.23

### 软件提示了什么？

提示是成功，但无法多开

**Comment by hugh-qiu** [comment]
无法防撤回了，可以多开，但是要打开多开器。

**Comment by Jackamy** [comment]
> 

多开器在哪有？

**Comment by MarkLily** [comment]
> > 
> 
> 多开器在哪有？
RevokeMsgPatcher.MultiInstance.exe 这个就是吧

**Comment by byweibo** [comment]
![image](https://user-images.githubusercontent.com/7714894/227715978-7ba52a4e-8276-4313-842e-25415c54e38e.png)
无法注入多开

**Comment by huiyadanli** [comment]
多开已经处理，防撤回暂时没方案
