### ISSUE TITLE
[未支持版本]: 微信 3.9.2.23 防撤回失效

### ISSUE THREAD

**Issue by hugh-qiu** [huiyadanli/RevokeMsgPatcher#535]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信3.9.2.23

### 软件提示了什么？

提示安装成功，微信登录防撤回功能失效，并且无法直接进行多开操作，只能启动多开软件进行多开；

**Comment by ZeroCreate999** [comment]
同 3.9.2.23 也是失效

**Comment by MarkLily** [comment]
一样了 好像这次更新 被针对了

**Comment by linhongjun** [comment]
早晨更新后 同失效。
![1](https://user-images.githubusercontent.com/16095518/227667365-bbe7a22b-79bd-4694-a199-873545603982.jpg)

**Comment by lyhrtb** [comment]
目前重新安装补丁提示持征比对:当前特征码匹配数[0]和期望的匹配数[1]不一致。

**Comment by lyhrtb** [comment]
![QQ截图20230325143238](https://user-images.githubusercontent.com/51842628/227701133-e21871b9-7cd7-4b4a-9ca6-fbb0bdcefd0b.png)

**Comment by BioinfoCat** [comment]
我也碰到了，刚刚更新，更新完想安装补丁，发现不成功了

**Comment by Eric-the-Red-00** [comment]
只能等待作者更新了

**Comment by xmhwws** [comment]
怎么回退旧版本？

![image](https://user-images.githubusercontent.com/42903751/227706290-439f41e7-63d8-43fd-a232-7cc3074cdd76.png)

**Comment by muteX4** [comment]
离谱呀

**Comment by zss823158062** [comment]
特征码变了吧，坐等作者更新

**Comment by nasaboy** [comment]
确实是失效了

**Comment by jinuosiboshi** [comment]
等待更新

**Comment by baikexiaotian** [comment]
失效了

**Comment by iamcaopanpan** [comment]
等更新

**Comment by BlingRbt** [comment]
确实 多开失效了 防撤回看着是安装成功了 实际没测试

**Comment by wuzhengqiang** [comment]
我的是升级[微信 3.9.2.23后，再来打开1.6版本的程序时，发现防撤回按钮都没有了！只有个多开按钮。。。亲测，防撤回功能的确也失效了。之前也是，每次升级微信了都要重装，之前的版本至少可以重装，这下完犊子了，没防撤回选项了！

**Comment by d407565739** [comment]
坐等更新 希望加入解除只读

**Comment by s19293949** [comment]
坐等更新

**Comment by s19293949** [comment]
万人血书请求作者更新最新版！

**Comment by Lkhongsen** [comment]
等作者大大更新

**Comment by Damon-Yo** [comment]
坐等作者爸爸更新。

**Comment by Ruling95** [comment]
同等，这个版本，打开就显示，撤回已经处理过了。
![image](https://user-images.githubusercontent.com/49261119/227897755-cea130c8-efd7-4a3d-99c2-28571e6bd5bb.png)

**Comment by douxy1994** [comment]
万人血书求更新

**Comment by SPECIALTIGER-007** [comment]
+1

**Comment by Kurasa632** [comment]
您好，您的邮件我已收到！

**Comment by whatqiu** [comment]
如果需要撤回的话，回退下面这个版本，测试可以用，先把原来的卸载掉，卸载时保留数据就好了，一般聊天记录不会删。:smiley:
[v3.8.1.26](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.8.1.26)

**Comment by Ruling95** [comment]
https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_faq_list&head=true

管网历史版本可下载。

**Comment by macyoyo** [comment]
目前3.9.0.28版本还能正常使用补丁，新版本的3.9.2.23版本就是更新了特征码，现在的补丁已经不支持了，等待更新

**Comment by macyoyo** [comment]
> https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_faq_list&head=true
> 
> 管网历史版本可下载。

这个只是历史办的日志，下载链接除了安卓版以外，像Windows版本的都是最新版，没有历史版本

**Comment by d407565739** [comment]
> > https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_faq_list&head=true
> > 管网历史版本可下载。
> 
> 这个只是历史办的日志，下载链接除了安卓版以外，像Windows版本的都是最新版，没有历史版本

https://github.com/tom-snow/wechat-windows-versions

**Comment by huiyadanli** [comment]
3.9.2.* 暂时没可用的防撤回方案，等大佬的方案了

**Comment by FLYFLY0** [comment]
还有别的方法吗？

**Comment by CoderDai** [comment]
![image](https://user-images.githubusercontent.com/38967259/228222621-160d9b6b-686a-41ce-9084-5d9296eaa802.png)
我这个更离谱，直接没有防撤回选项了

**Comment by huiyadanli** [comment]
> ![image](https://user-images.githubusercontent.com/38967259/228222621-160d9b6b-686a-41ce-9084-5d9296eaa802.png) 我这个更离谱，直接没有防撤回选项了

因为防撤回失效了，这个补丁信息我暂时去掉了。。。

**Comment by Jack800109** [comment]
求更新

**Comment by CoderDai** [comment]
> > ![image](https://user-images.githubusercontent.com/38967259/228222621-160d9b6b-686a-41ce-9084-5d9296eaa802.png) 我这个更离谱，直接没有防撤回选项了
> 
> 因为防撤回失效了，这个补丁信息我暂时去掉了。。。

同求作者大大更新

**Comment by DearBo7** [comment]
同求作者大大更新

**Comment by mygitnb** [comment]
刚刚更新，更新安装补丁成功，防撤回失效了 3.9.2.23

**Comment by 1044650112** [comment]
可以下载历史版本的地方，下载3.9.0.28实测可用https://mydown.yesky.com/pcsoft/44417133/versions/?t=1502372866803

**Comment by huiyadanli** [comment]
微信 3.9.2.23 防撤回已经更新，特征来自 #543

**Comment by jinzezhi** [comment]
> 微信 3.9.2.23 防撤回已经更新，特征来自 #543

是需要自己编译更新后的代码吗

**Comment by huiyadanli** [comment]
> > 微信 3.9.2.23 防撤回已经更新，特征来自 #543
> 
> 是需要自己编译更新后的代码吗

不需要，会自动获取最新的补丁信息的

**Comment by alllllllllli** [comment]
试过好多版本了，全部不行😭😭😭

**Comment by popokcn** [comment]
我在这里喊一声“张小龙我操你妈”，大家都没啥意见吧？
