### ISSUE TITLE
最新版微信防撤回插件失效，腾讯软件中心微信最新版本为3.9.0.28，可下载旧安装包降级安装

### ISSUE THREAD

**Issue by m55614903** [huiyadanli/RevokeMsgPatcher#538]
等了几天作者大大还没更新防撤回插件，只能降级微信，但是又不知道对应的微信安装包的md5，不想乱下，意外发现腾讯软件中心的微信安装包不是最新的。
https://pc.qq.com/detail/8/detail_11488.html
发布时间：2023-02-08 大小：165.21MB 版本：3.9.0.28
文件太大了，上传不了，有需要的可以自行下载

**Comment by ououming123** [comment]
可惜了   现在去看已经是
发布时间：2023-03-23大小：167.78MB版本：3.9.2.23

**Comment by vipnetant** [comment]
### **声明：本人3月1日在官网下载，请自行选择，不放心的不要下载。本人不承担任何责任及回答。**
`Size: 173240032 bytes
File Version: 3.9.0.1000
Modified: 2023年3月1日, 12:59:43
MD5: 3EFD527EE04C027F401E3B0A460242C2
SHA1: 12421DAAEDFE434A7981650FAE836BB0E84A69B5
CRC32: D267A980`
```
WeChatSetup3.9.0.28.exe
https://www.aliyundrive.com/s/j7X6u9wnn3p
提取码: 39028
```

**Comment by Ruling95** [comment]
https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=weixin_faq_list&head=true

这里可以下载历史版本的。

**Comment by Alleninggx** [comment]
https://github.com/tom-snow/wechat-windows-versions

**Comment by m55614903** [comment]
> 等了几天作者大大还没更新防撤回插件，只能降级微信，但是又不知道对应的微信安装包的md5，不想乱下，意外发现腾讯软件中心的微信安装包不是最新的。 https://pc.qq.com/detail/8/detail_11488.html 发布时间：2023-02-08 大小：165.21MB 版本：3.9.0.28 文件太大了，上传不了，有需要的可以自行下载

这个是我前两天在腾讯软件中心下载的微信安装包，这位朋友的网盘文件可以用的，下载之后记得确认下MD5
C:\Users\Mixer\Downloads>certutil -hashfile WeChatSetup_3.9.0.28.exe md5
MD5 的 WeChatSetup_3.9.0.28.exe 哈希:
3efd527ee04c027f401e3b0a460242c2
CertUtil: -hashfile 命令成功完成。

C:\Users\Mixer\Downloads>certutil -hashfile WeChatSetup_3.9.0.28.exe sha1
SHA1 的 WeChatSetup_3.9.0.28.exe 哈希:
12421daaedfe434a7981650fae836bb0e84a69b5
CertUtil: -hashfile 命令成功完成。

**Comment by m55614903** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/538#issuecomment-1484451078

> 等了几天作者大大还没更新防撤回插件，只能降级微信，但是又不知道对应的微信安装包的md5，不想乱下，意外发现腾讯软件中心的微信安装包不是最新的。 https://pc.qq.com/detail/8/detail_11488.html 发布时间：2023-02-08 大小：165.21MB 版本：3.9.0.28 文件太大了，上传不了，有需要的可以自行下载

腾讯软件中心的微信也更新了
这位朋友的网盘资源可以用的，下载后记得确认下MD5 https://github.com/huiyadanli/RevokeMsgPatcher/issues/538#issuecomment-1484451078

这是我前两天在腾讯软件中心下载的
C:\Users\Mixer\Downloads>certutil -hashfile WeChatSetup_3.9.0.28.exe md5
MD5 的 WeChatSetup_3.9.0.28.exe 哈希:
3efd527ee04c027f401e3b0a460242c2
CertUtil: -hashfile 命令成功完成。

C:\Users\Mixer\Downloads>certutil -hashfile WeChatSetup_3.9.0.28.exe sha1
SHA1 的 WeChatSetup_3.9.0.28.exe 哈希:
12421daaedfe434a7981650fae836bb0e84a69b5
CertUtil: -hashfile 命令成功完成。

**Comment by mencall** [comment]
我记得腾讯软件中心上的QQ还是微信，只要知道版本号，参照以前的地址链接修改版本号，就能直接下载的，包括历史版本，就是说腾讯不删的（毕竟这些并不大）。
刚试了下，这个地址或保存目录（或策略）是变了吧，找到以前的下载链接，修改下，3.9.0的官网下载地址如下：
https://webcdn.m.qq.com/spcmgr/download/WeChatSetup_3.9.0.28.exe
