### ISSUE TITLE
微信测试版2.8.0.88不支持

### ISSUE THREAD

**Issue by rabbit-cat** [huiyadanli/RevokeMsgPatcher#54]
电脑重启后发现更新了2.8.0.88测试版，用最新版本备份还原后防撤回，然后微信开始闪退，直接不能使用，不知道是测试版问题还是防撤回问题

**Comment by rabbit-cat** [comment]
无奈回退版本了

**Comment by rabbit-cat** [comment]
感觉是不支持防撤回，旧版本有点丑，检查更新还是.88版本的，更新后没有用防撤回发现正常

**Comment by huiyadanli** [comment]
**备份还原后防撤回，实际就是直接用了老版本的dll，这种用法不是很推荐使用，容易出现问题，尽量等我更新对应防撤回版本的支持后直接点防撤回按钮**

额。。备份还原后用的是旧版本的dll，和新版本实际是不匹配的，可能会出现闪退的问题。。



我搞完 2.8.0.88 防撤回的支持之后，

给你一个2.8.0.88版本的dll你手动替换下一下，就应该就不会出现闪退问题了

**Comment by rabbit-cat** [comment]
copy,感谢大佬

**Comment by huiyadanli** [comment]
2.8.0.88 版本已经支持

对应防撤回的dll如下，你直接覆盖微信目录下的`WeChatWin.dll`就可以恢复正常了
[WeChatWin.zip](https://github.com/huiyadanli/RevokeMsgPatcher/files/4013960/WeChatWin.zip)

**Comment by jsxyhyj** [comment]
看release那写支持2.8.0.88版本，但是release那下载的，还是0.6版本是11月3日的。不是1月1日的。

**Comment by huiyadanli** [comment]
> 看release那写支持2.8.0.88版本，但是release那下载的，还是0.6版本是11月3日的。不是1月1日的。

补丁是联网获取的最新版本，主程序无需更新
