### ISSUE TITLE
如果需要防撤回的话，回退下面这个版本，测试可以用，先把原来的卸载掉，卸载时保留数据就好了，一般聊天记录不会删。:smiley:

### ISSUE THREAD

**Issue by whatqiu** [huiyadanli/RevokeMsgPatcher#541]
如果需要撤回的话，回退下面这个版本，测试可以用，先把原来的卸载掉，卸载时保留数据就好了，一般聊天记录不会删。:smiley:
[v3.8.1.26](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.8.1.26)

_Originally posted by @whatqiu in https://github.com/huiyadanli/RevokeMsgPatcher/issues/535#issuecomment-1485062156_

**Comment by su998** [comment]
感谢好心人

**Comment by scalpelx** [comment]
[3.9.0.28](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.0.28)就可以

**Comment by scalpelx** [comment]
> > [3.9.0.28](https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.0.28)就可以
> 
> 我下载了这个装了几次还是会安装3.9.23的，我就换了更低的。

在设置里关闭自动升级就好，要不你装老版本，照样也会给你升级

**Comment by zilianglei** [comment]
3.9.0.28会提示哪条消息是撤回的吗

**Comment by scalpelx** [comment]
> 3.9.0.28会提示哪条消息是撤回的吗

不会

**Comment by huiyadanli** [comment]
微信 3.9.2.23 防撤回已经更新 https://github.com/huiyadanli/RevokeMsgPatcher/issues/535
