### ISSUE TITLE
[未支持版本]: 微信 3.9.0.29

### ISSUE THREAD

**Issue by hayden7c** [huiyadanli/RevokeMsgPatcher#542]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.0.29

### 软件提示了什么？

安装了补丁包，提示安装成功了，但是多开还是失效了

**Comment by huiyadanli** [comment]
#535

**Comment by JJJoie** [comment]
www.53taoka.com   这个是代理开钻的淘宝平台，你点进去就知道了      注册一下，然后填写上级帐号11871，然后联系我，我免费帮你开。。

**Comment by huiyadanli** [comment]
这个版本没遇到过，issue先挂着，不知道现有特征能不能兼容
