### ISSUE TITLE
3.9.2.23的防撤回补丁

### ISSUE THREAD

**Issue by DoYmL8c** [huiyadanli/RevokeMsgPatcher#543]
多开+防撤回
https://www.lanzout.com/i3pmq0rehlvg

仅防撤回
https://www.lanzout.com/iSRKx0rehmbc

**Comment by xiaoyuzz** [comment]
测试了一下 不行的 覆盖了会提示损坏 直接跳到微信官网让你下载  无奈回退到3.9.0.28了

**Comment by zss823158062** [comment]
试过了，可行，没问题

**Comment by xiaoyuzz** [comment]
> 

我重装试一下。。。。。。。。。。。。。。

**Comment by xiaoyuzz** [comment]
> 多开+防撤回 https://www.lanzout.com/i3pmq0rehlvg
> 
> 仅防撤回 https://www.lanzout.com/iSRKx0rehmbc

重装能用了 谢谢

**Comment by MarkLily** [comment]
哈哈哈 这个是吾爱破解那个么

**Comment by xiaoyuzz** [comment]
> 哈哈哈 这个是吾爱破解那个么

压缩包是那么写的 吾爱破解。。。。。。。

**Comment by MarkLily** [comment]
> > 哈哈哈 这个是吾爱破解那个么
> 
> 压缩包是那么写的 吾爱破解。。。。。。。

这个可以用的，吾爱里面还有个，可以提示防撤回的信息，不过这次版本更新后，就没了。旧版本是可以的

**Comment by sanchez0623** [comment]
可以！感谢

**Comment by MrSToneX** [comment]
防撤回确实可以！

**Comment by fuchengxin** [comment]
试了，可行，感谢！

**Comment by tiger-do** [comment]
> > 多开+防撤回 https://www.lanzout.com/i3pmq0rehlvg
> > 仅防撤回 https://www.lanzout.com/iSRKx0rehmbc
> 
> 重装能用了 谢谢

大佬，这个怎么使用啊

**Comment by lucy-dog** [comment]
刚刚试了，可行非常感谢！

**Comment by MarkLily** [comment]
> > > 多开+防撤回 https://www.lanzout.com/i3pmq0rehlvg
> > > 仅防撤回 https://www.lanzout.com/iSRKx0rehmbc
> > 
> > 
> > 重装能用了 谢谢
> 
> 大佬，这个怎么使用啊

WeChatWin.dll 文件覆盖版本号目录下的WeChatWin.dll即可

**Comment by tiger-do** [comment]
> 

貌似需要重新安装微信哦

**Comment by MarkLily** [comment]
> > 
> 
> 貌似需要重新安装微信哦

需要安装官方的最新版本exe包，直接官网下载，安装覆盖就行，聊天记录在的。不放心的话就备份一下聊天记录再安装！

**Comment by tiger-do** [comment]
> 

好的，多谢大佬

**Comment by lzyssg** [comment]
防撤回可以用

**Comment by Shimiankang** [comment]
> > 多开+防撤回 https://www.lanzout.com/i3pmq0rehlvg
> > 仅防撤回 https://www.lanzout.com/iSRKx0rehmbc
> 
> 重装能用了 谢谢

是不是要重新安装微信

**Comment by MK-320** [comment]
感谢感谢 3.9.2.23 有用

**Comment by huiyadanli** [comment]
查了下补丁来自：https://www.52pojie.cn/thread-1743409-1-2.html

已经基于该补丁信息更新特征码。

**Comment by Mcdull0921** [comment]
可以用，感谢大佬

**Comment by d-denglei** [comment]
> 多开+防滴回 https://www.lanzout.com/i3pmq0rehlvg
> 
> 只防滴回 https://www.lanzout.com/iSRKx0rehmbc
感谢大佬 可以使用

**Comment by iamcaopanpan** [comment]
可以用了

**Comment by iamxiaoyuge** [comment]
3.9.2.23 做到防撤回，但是没办法做到防撤回提醒。
请问哪个版本能做到防撤回提醒？

**Comment by iamxiaoyuge** [comment]
> > 3.9.2.23 做到防撤回，但是没办法做到防撤回提醒。 请问哪个版本能做到防撤回提醒？
> 
> https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81 从 2.8.0.112 开始支持带提示的防撤回，3.3.5.15版本后暂时不支持显示撤回提示

谢谢您的回答。

**Comment by MarkLily** [comment]
> 3.9.2.23 做到防撤回，但是没办法做到防撤回提醒。 请问哪个版本能做到防撤回提醒？

上个版本（3.9.0.28）就可以做到！参考https://www.52pojie.cn/thread-1750880-1-1.html

**Comment by wtzlyf** [comment]
可以防撤回，也可多开，期待出防撤回提醒版本。

**Comment by popokcn** [comment]
> > 3.9.2.23 做到防撤回，但是没办法做到防撤回提醒。 请问哪个版本能做到防撤回提醒？
> 
> 上个版本（3.9.0.28）就可以做到！参考https://www.52pojie.cn/thread-1750880-1-1.html
这是某个52pojie的大佬写的hook版本，大佬最近应该没空更新。
我们这个是修改微信撤回的逻辑，只能简单的让撤回失效。
