### ISSUE TITLE
本地 tmp 缓冲文件回退「3.9.0.29」之前版本的方法参考

### ISSUE THREAD

**Issue by xcbyao** [huiyadanli/RevokeMsgPatcher#545]
分享一个 Windows 上有**本地 tmp 缓冲目录**的回退版本方法，实测可用，尚未发现不妥之处，有大佬懂其中利弊欢迎指出。

## 方法如下：

1. 找到 WeChat 安装目录，如下图结构，红色部分弃用，选用绿色部分的版本之一。（红色部分可删可不删，目测没啥大影响）

![image](https://user-images.githubusercontent.com/40726291/229102017-535068f7-c411-4c42-9f4c-a8f70032d272.png)

2. 将桌面等微信快捷键的**属性目标**手动更改到选用目录下的 **exe 文件**。

![image](https://user-images.githubusercontent.com/40726291/229102505-ab8863fa-9c8a-475f-a079-afe99f3a220a.png)

3. 再把 RevokeMsgPatcher 应用的微信路径，手动选择**上一步路径**或直接**复制到空白框**中，检测到微信版本，安装补丁。

![image](https://user-images.githubusercontent.com/40726291/229102981-46985ad0-a0b1-4432-b237-aa5972e09757.png)

4. 最后，**防撤回，多开测试，成功回退。**

5. 或者找到上述路径的最新版本，替换该 issue #543 中的补丁文件。

**Comment by huiyadanli** [comment]
微信正常情况下，这些tmp文件夹是会自动删除的。不删除的情况比较少见。。

另，3.9.2.23 已经支持防撤回了。

**Comment by xcbyao** [comment]
对，不知道什么原因本地还有 tmp 版本。

主要提供一个思路，在特征码未更新出来之前的迂回策略。

或者，可能有人存有更早的版本需要回退，比如能提取视频号的未加密链接等相关旧版功能。

当然，后者不在本项目讨论范围了，仅作分享参考。

**Comment by qingshuangyixia** [comment]
我是也看到有上个版本临时文件，但是重装了3.0第一个版本就可以了
