### ISSUE TITLE
3.9.2.23 防撤回会同时影响拍一拍

### ISSUE THREAD

**Issue by AnzhiZhang** [huiyadanli/RevokeMsgPatcher#547]
打上防撤回补丁后无法接收到拍一拍

**Comment by Damon-Yo** [comment]
同问题，PC不显示拍一拍信息

**Comment by AnzhiZhang** [comment]
补充：在手机上拍他人同样无法收到，只有在电脑端发出拍一拍可以正常显示

**Comment by alllllllllli** [comment]
防撤回在哪啊？

**Comment by MarkLily** [comment]
同问题，别人拍我，PC端看不到；还有个问题不知道是微信同步的问题，每次登录PC端的时候，那些公众号的推送消息，我在登录之前手机上都不显示聊天记录了，怎么PC端同步出来了，每次都手动再删。大佬们有遇到过么

**Comment by StoneForests** [comment]
3.9.2.26 pc端仍然显示不了别人对我的 拍一拍
