### ISSUE TITLE
[常见问题]更换新配置时异常

### ISSUE THREAD

**Issue by djmee** [huiyadanli/RevokeMsgPatcher#548]
防撤回版本v1.6 windows11 22H2
长达一个星期提示更换新配置时异常，没有防病毒程序，尝试过重新安装、关闭梯子等
![image](https://user-images.githubusercontent.com/93442627/230076431-2bc86ada-89cb-4518-a683-717cf09bf5cc.png)
![image](https://user-images.githubusercontent.com/93442627/230076521-0abbf430-1461-42cd-a38c-818ff2aaa509.png)

**Comment by huiyadanli** [comment]
补丁实际地址： https://hui-config.oss-cn-hangzhou.aliyuncs.com/1.6/patch.json

你手动访问下看看是否能正常访问。

**Comment by djmee** [comment]
可以的

**Comment by huiyadanli** [comment]
直接在这个页面下载最新编译版本吧，内置了最新的补丁信息，https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/4565259364

**Comment by djmee** [comment]
解决了，非常感谢您的耐心帮助🥰
