### ISSUE TITLE
最新版微信安装补丁后无法登录

### ISSUE THREAD

**Issue by ventzx** [huiyadanli/RevokeMsgPatcher#549]
最新版微信（3.9.2.23）安装补丁后无法扫码登录微信，并显示以下内容：

_**文件默认保存位置无法使用，将不能正常使用微信，请更改位置。**_

备份还原后恢复正常。

安装补丁前我已经关闭了微信，并用管理员权限打开安装程序，获取成功后进行安装，不知道问题出现在哪里

**Comment by huiyadanli** [comment]
看下微信目录的截图，估计是同时存在了多个版本的微信了

**Comment by ventzx** [comment]
以下分别是插件中识别到的微信目录、微信根目录和带版本号的目录
![QQ图片20230420233713](https://user-images.githubusercontent.com/40136577/233416970-7d96a0c5-b4f6-4b6d-a816-4ad0a9952d57.png)
![QQ图片20230420233720](https://user-images.githubusercontent.com/40136577/233416973-a5b8673f-a410-4032-8850-d0ca62b969c2.png)
![QQ图片20230420233724](https://user-images.githubusercontent.com/40136577/233416975-5d705be8-af33-46d0-9262-690723027422.png)

**Comment by huiyadanli** [comment]
目录没问题，这种情况没遇到过。

“文件默认保存位置无法使用，将不能正常使用微信，请更改位置。”

这个“默认保存位置”应该是保存微信用户相关文件的地方，应该和补丁没啥关系

**Comment by ventzx** [comment]
更换另一台电脑后问题解决，原因不明
