### ISSUE TITLE
PCQQ9.2.2.26569不支持

### ISSUE THREAD

**Issue by wysnxzm** [huiyadanli/RevokeMsgPatcher#55]

**Comment by huiyadanli** [comment]
[版本支持说明](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81)

9.2.2.26569 前段时间已经支持

最新版本的支持需要耐心等待最新补丁的获取，请关注右下角提示

当前软件支持的版本信息可以点击软件右下角获取补丁信息的相关文字进行查看

**Comment by wysnxzm** [comment]
> [版本支持说明](https://github.com/huiyadanli/RevokeMsgPatcher/wiki/%E7%89%88%E6%9C%AC%E6%94%AF%E6%8C%81)
> 
> 9.2.2.26569 前段时间已经支持
> 
> 最新版本的支持需要耐心等待最新补丁的获取，请关注右下角提示
> 
> 当前软件支持的版本信息可以点击软件右下角获取补丁信息的相关文字进行查看

找到问题了,是获取支持的版本过慢导致的开代理获取就ok
