### ISSUE TITLE
Releases 还是2022年的，跪求更新。

### ISSUE THREAD

**Issue by Ruling95** [huiyadanli/RevokeMsgPatcher#550]
![image](https://user-images.githubusercontent.com/49261119/231953751-49cefff3-71a7-47c1-a369-b51a77ee8eb7.png)

**Comment by huiyadanli** [comment]
最新的编译版本可以从 https://github.com/huiyadanli/RevokeMsgPatcher/actions 中获取

主要是没什么大改动需要发布新版本:joy:
