### ISSUE TITLE
安装防撤回后不停弹出后台项目已添加提示

### ISSUE THREAD

**Issue by 48038411** [huiyadanli/RevokeMsgPatcher#554]
![image](https://user-images.githubusercontent.com/44643400/232713595-268a47b4-f1c8-4179-9d83-85c05c4f904e.png)
如图所示

**Comment by huiyadanli** [comment]
发错项目了吧，本项目是Win下的防撤回

**Comment by 48038411** [comment]
> 

秒发现秒关闭，实在是不好意思
