### ISSUE TITLE
给一个通杀特征思路

### ISSUE THREAD

**Issue by bigsinger** [huiyadanli/RevokeMsgPatcher#555]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

1.0

### 软件提示了什么？

看了下源码里的特征每个版本一个，工作量太大，实际上可以提取一个通用的特征，通杀全部（或大部）版本。

参见：https://zhupite.com/sec/ida-modify-wechat-to-prevent-revoke-message.html 的思路，在定位到特征后，往后面去定位patch点就方便多了。

特征的结构可以设计为：
通用特征：粗粒度定位
精细特征：精细定位

大概形式为：
{
  通用特征：" AA BB CC 00 12 ?? 34"
  精细特征组：{
     ......
    ......
  }
}

**Comment by huiyadanli** [comment]
实际2022至今防撤回其实就两组特征反复横跳。（所以软件更新频次不高）

多的变更基本都是为了兼容测试版本，或者是新的防撤回点实现不同的效果。

不过这篇文章还是很有参考价值的，感谢分享。
