### ISSUE TITLE
校验WeChatApp.exe失败

### ISSUE THREAD

**Issue by MosesFu** [huiyadanli/RevokeMsgPatcher#56]
### Version: 

WeChat Beta 2.7.1.85 for Windows 10

### Action: 

* 打开Windows电脑端的微信上任意小程序时()
* 登录微信时

### Alert msg: 

“校验WeChatApp.exe失败!”

### Result(/Affect): 
* 无法使用小程序
* 不影响登陆使用

**Comment by huiyadanli** [comment]
看一下防撤回补丁里面显示的微信版本是不是 2.7.1.85？如果是 2.7.1.85 并且点击防撤回后提示“已经安装此补丁”，那应该不是防撤回补丁的问题。

建议官网重新下载微信PC版并覆盖安装 https://pc.weixin.qq.com/

**Comment by MosesFu** [comment]
> 看一下防撤回补丁里面显示的微信版本是不是 2.7.1.85？如果是 2.7.1.85 并且点击防撤回后提示“已经安装此补丁”，那应该不是防撤回补丁的问题。
> 
> 建议官网重新下载微信PC版并覆盖安装 https://pc.weixin.qq.com/

微信安装包是从官网下载后升级的，防撤回补丁是2.7.1.88版本。

卸载(保留数据/不保留数据均尝试过)、安装后问题仍未解决，
推测是本机系统问题或微信安装包兼容问题，
不是防撤回补丁的问题，谢谢。
