### ISSUE TITLE
3.9.5.22版本

### ISSUE THREAD

**Issue by Tree-New-Beee** [huiyadanli/RevokeMsgPatcher#560]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信3.9.5.22版本

### 对应版本的下载地址

https://423down.lanzouo.com/iLwXA0u283yd

### 软件提示了什么？

![image](https://user-images.githubusercontent.com/67086459/235273518-702150c9-2066-44dc-8168-658158db3492.png)

**Comment by huiyadanli** [comment]
已经支持
