### ISSUE TITLE
麻烦问一下，有人遇到这个问题了吗，借这个问题反馈区询问一下。

### ISSUE THREAD

**Issue by qingshuangyixia** [huiyadanli/RevokeMsgPatcher#561]
上一次不是3.9.2.23更新了，但是以前的防撤回很久没更新，所以不支持，一两周左右看到还不支持，就网上找了上个版本的微信下载重装了，今天电脑一打开就显示微信自动更新了，我都没让他自动更新，设置里看了一下把更新的按钮取消了，但是还强制更新了，是不是过多长时间没升级到可以使用的版本微信就会自动更新/强制更新一次？有没有解决这个问题的方法，麻烦说一声，谢谢。
借楼问一下，谢谢这个软件的作者一直更新着版本支持。我刚升完级还看到新的版本，有小红点。

**Comment by kkxg** [comment]
可能是他自己强制更新的？
![image](https://user-images.githubusercontent.com/20535377/235287118-4408ba31-407a-4408-afc0-d7b13c4c9433.png)

**Comment by huiyadanli** [comment]
会强制更新
