### ISSUE TITLE
3.9.5.26  新老版本安装都提示 当前特征与期待不一致

### ISSUE THREAD

**Issue by JustinZBY** [huiyadanli/RevokeMsgPatcher#562]
是需要作者更新 新版本嘛 礼貌求问

**Comment by JustinZBY** [comment]
![QQ截图20230430090132](https://user-images.githubusercontent.com/36722018/235330620-ffcf9862-7fcc-43dc-8c88-847eb827c9b0.png)

**Comment by lonee6** [comment]
补丁特征码又变了，52pj上有新的。

**Comment by JustinZBY** [comment]
> 补丁特征码又变了，52pj上有新的。

52pj只有25的 现在已经26了 懒得降级= =

**Comment by AromaMemory** [comment]
3.9.5.25 新老版本安装都提示 当前特征与期待不一致

**Comment by AromaMemory** [comment]
> 补丁特征码又变了，52pj上有新的。
哪里可以看到

**Comment by huiyadanli** [comment]
已经支持了，微信3.9.5居然直接是64位版本，难得。
