### ISSUE TITLE
新版本多少有点问题, 建议直接回退到旧版本吧

### ISSUE THREAD

**Issue by xx10n31y** [huiyadanli/RevokeMsgPatcher#564]
回退到3.9.0版本, https://web.archive.org/web/20230209071724/https://pc.weixin.qq.com/

**Comment by huiyadanli** [comment]
新版本有啥问题可以发出来看看，虽然不一定能解决hhh

**Comment by FuGuiLiu** [comment]
最新版本的微信好像不支持了 我试过两个设备了

**Comment by huiyadanli** [comment]
@FuGuiLiu 发下具体版本号，现在最新的都是支持的

**Comment by FuGuiLiu** [comment]
> @FuGuiLiu 发下具体版本号，现在最新的都是支持的

卧槽我刚卸载![image](https://user-images.githubusercontent.com/63985387/236417684-c7e6f5ae-ac5f-4662-a2bc-644b04b86476.png)![正在上传 236417686...]

**Comment by Qian119lsj** [comment]
3.9.2.26 刚打开自动更新就不行了,有没有办法让他不更新,设置里已经关了自动更新了

**Comment by StoneForests** [comment]
> 

我试了下3.9.2.26可以用呀

**Comment by huiyadanli** [comment]
3.9.2.26 我测试没问题

**Comment by vipnetant** [comment]
3.9.2.26实测没问题，可以防撤回。
