### ISSUE TITLE
3.9.5.25 撤回一直转圈

### ISSUE THREAD

**Issue by MarkLily** [huiyadanli/RevokeMsgPatcher#566]
3.9.5.25版本，一撤回，就显示转圈，如果鼠标移到别的地方，再跳回来就好了。

**Comment by huiyadanli** [comment]
挂着看看有没有人遇到相同问题的

**Comment by broeeee** [comment]
![图片](https://github.com/huiyadanli/RevokeMsgPatcher/assets/18160411/01abc300-28b4-4ecb-93ec-4c69f719f9b1)
手机撤回电脑上不会有显示转圈圈，PC端仅PC端有转圈圈，手机上显示已正常撤回。
