### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by xiaoxinfen** [huiyadanli/RevokeMsgPatcher#567]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.9.2.26

### 软件提示了什么？

不能有效地防止撤回

**Comment by huiyadanli** [comment]
这个版本已经支持了，不行的话可以试试这个最新编译的版本

https://github.com/huiyadanli/RevokeMsgPatcher/suites/12609999292/artifacts/674855366
