### ISSUE TITLE
被撤回的消息看不出是哪条

### ISSUE THREAD

**Issue by xiaoceziv50** [huiyadanli/RevokeMsgPatcher#568]
可以支持被撤回的消息下方添加已撤回的提示么
win10 微信版本3.9.0.28，

**Comment by luoshuinifengxiangxi** [comment]
+1现在看不出来哪条是撤回的信息 很不方便

**Comment by saozimian** [comment]
不显示撤回的哪一条信息，希望修复一下

**Comment by luuunnn** [comment]
这个功能个人感觉非常实用，且必要，作者大大采纳采纳采纳

**Comment by liweiBingo** [comment]
赞同 跪求大佬增加功能，mac版本的防撤回还有个功能就是 可以把撤回的内容同时发送给自己

**Comment by G0dShit** [comment]
+10086

**Comment by jiangzhangpu** [comment]
希望作者可以看到这个，撤回的消息能给个提示

**Comment by NJXS-cho** [comment]
+1 3.9.5.81 不支持所谓的“新版撤回提示”

**Comment by jiandan5997** [comment]
自己撤回的信息 也没有提示了，这个问题可以解决吗？

**Comment by momoblydblk** [comment]
我现在是手机没装防撤回但电脑装了，然后通过对比手机和电脑的聊天记录来确定撤回了啥的

**Comment by yearnxiao** [comment]
自己去手机聊天记录看下不就知道了，还要啥自行车！

**Comment by NJXS-cho** [comment]
本身这里就是反馈优化使软件越来越好，作者能增加最好，不增加也感谢分享。什么自行车不自行车的，是不是学了一句梗把你能得？再如，比如反应BUG,你是不是也会来一句：能用就行，要啥自行车？ 你需要就反馈，不需要个别就安于现状就行，别找存在感好吗，

**Comment by huiyadanli** [comment]
#243
