### ISSUE TITLE
希望增加个去取文件只读的功能。

### ISSUE THREAD

**Issue by 928882650** [huiyadanli/RevokeMsgPatcher#570]
另外说一句 张小龙 操你妈！

**Comment by MarkLily** [comment]
附议！这个功能很实用！！！另外说一句 张小龙日常没马！

**Comment by MarkLily** [comment]
目前看到这个解决办法：
微信文件管理的那个文件夹先获取管理员权限，然后你再把这个文件夹只读取消，并将更改应用于此文件夹、子文件夹和文件！

**Comment by nljxlove** [comment]
张小龙 操你妈！

**Comment by yearnxiao** [comment]
没明白文件只读是什么，什么文件不可编辑了？

**Comment by huiyadanli** [comment]
这个问题，新版本微信自己已经去除了

**Comment by yearnxiao** [comment]
用了这么多年微信，接收了无数文件没发现哪里的文件是只读的
