### ISSUE TITLE
[微信3.9.5.41]: 不支持防撤回功能

### ISSUE THREAD

**Issue by c17abab** [huiyadanli/RevokeMsgPatcher#572]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.9.5.41

### 软件提示了什么？

![小Q截图-20230512141431](https://github.com/huiyadanli/RevokeMsgPatcher/assets/16625444/56f9843c-f9dc-4c74-b7b0-d73b0dc6cdd8)

**Comment by huiyadanli** [comment]
多开有问题

**Comment by huiyadanli** [comment]
已经支持多开，试试

**Comment by qiaobai28** [comment]
来个对应版本的下载地址，谢谢。

**Comment by ASAProger** [comment]
3.9.6版的多开好像不起作用了

**Comment by snomgq** [comment]
是不是该更新了
