### ISSUE TITLE
求适配新版QQ防撤回

### ISSUE THREAD

**Issue by miaowu001** [huiyadanli/RevokeMsgPatcher#573]
求适配新版QQ防撤回
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/78711864/5d64712c-68f7-484e-a1bf-a57db8db31a9)

**Comment by huiyadanli** [comment]
没测试资格

**Comment by buiawpkgew1** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/418
