### ISSUE TITLE
防撤回失效

### ISSUE THREAD

**Issue by gjx2116557388** [huiyadanli/RevokeMsgPatcher#574]
大佬您好，就是您开源的这个防撤回现在微信的新版本已经失效了，我看您的源码还在更新但是软甲已经是1.6很久没更新了，您还在维护这个项目不

**Comment by buiawpkgew1** [comment]
能用啊

**Comment by gjx2116557388** [comment]
> 能用啊

现在新版本的微信失效了吧好像

**Comment by huiyadanli** [comment]
最新的 3.9.5.* 微信都是支持的

**Comment by gjx2116557388** [comment]
> 提供下实体版本号，如果有安装包就更好了

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/67618391/30385b13-e6e1-4475-b9d1-6bc7ff30b076)
老哥我的微信是这个版本的

**Comment by gjx2116557388** [comment]
不好意思啊是我搞错了 没失效没失效 泪目 不好意思 @huiyadanli @buiawpkgew1

**Comment by pdg666** [comment]
> 不好意思啊是我搞错了没失效没失效泪目不好意思@huiyadanli @buiawpkgewwei
你用的新撤回还是老撤回？？
