### ISSUE TITLE
为什么 打完补丁之后  打开微信链接 微信窗口会独立出来  这是怎么做到的

### ISSUE THREAD

**Issue by itcast-e** [huiyadanli/RevokeMsgPatcher#575]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/64728445/aef99617-e670-4491-9c75-00b92c7abe6d)

**Comment by itcast-e** [comment]
正常来说都是 微信内置的窗口  但是用了防撤回之后 这个窗口就被独立出来了 很想知道 这是怎么做到的

**Comment by huiyadanli** [comment]
这是微信的功能，和补丁无关
