### ISSUE TITLE
最新版的插件好像不支持最新版的微信

### ISSUE THREAD

**Issue by wenrouyue** [huiyadanli/RevokeMsgPatcher#576]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/69041830/8ca174fe-dbe4-4f9f-9959-88a3df177d62)
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/69041830/445f58f8-efc8-4ce1-abeb-cf30973bded5)
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/69041830/eb62b776-9737-414f-90b8-992373646b71)

**Comment by linkooOOO** [comment]
你的1.6版为啥有带提示的
