### ISSUE TITLE
请教关于防撤回对未登录时收到的消息也能生效

### ISSUE THREAD

**Issue by lkyu-ly** [huiyadanli/RevokeMsgPatcher#577]
发现pc微信用完本工具之后，即使在没有登录的情况下，这个时候收到的消息也能防撤回，即在登录之后是可以被看见的。
但是QQ和Tim似乎不然，没有登录的时候收到的被撤回的消息，在软件上既不会显示已被撤回，也不能防撤回。请问对于这个问题有解决方案吗？可否做到像微信一样，这样可以免去需要一直登陆pc的困扰。

**Comment by huiyadanli** [comment]
理论上微信未登录情况下，历史撤回消息肯定是看不到的。要不你再确认试试？

**Comment by lkyu-ly** [comment]
起因是之前多次都是手机上看到别人撤回消息，才打开电脑登录微信，确确实实是能对未登录时接收到的消息起作用的，我也觉得很疑惑（），遂来请教一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月22日(周一) 上午10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huiyadanli/RevokeMsgPatcher] 请教关于防撤回对未登录时收到的消息也能生效 (Issue #577)




 
理论上微信未登录情况下，历史撤回消息肯定是看不到的。要不你再确认试试？

**Comment by Ressler-Git** [comment]
> 理论上微信未登录情况下，历史撤回消息肯定是看不到的。要不你再确认试试？

这个我也遇到过，确实在PC端未登录的情况下，手机端接收消息被撤回，然后再登录PC端能够看到已经被撤回的消息。

**Comment by betterdoitnow** [comment]
我也证实过，是这样的。

**Comment by betterdoitnow** [comment]
反过来证实，微信服务器是保留所有的聊天记录的。

**Comment by wozaitianwai** [comment]
如果撤回本身也是个消息，应该所有消息都是才cdn上有存的，感觉像是这么个逻辑

**Comment by huiyadanli** [comment]
经测试确实能够收到历史撤回消息，以前是不行的，

可能的原因：
1. 3.9版本的防撤回点位变更过导致的
2. 漫游消息的推送机制变过

对于1L的问题，本工具防撤回本质是反汇编破坏微信本身的撤回功能，没法做更多建设性功能。也就是本工具没有解决方案。

（如果要实现各类自定义功能也只能hook微信实现，此类工具还是存在的，你可以自行搜索下）

**Comment by lkyu-ly** [comment]
> 经测试确实能够收到历史撤回消息，以前是不行的，
> 
> 可能的原因：
> 
> 1. 3.9版本的防撤回点位变更过导致的
> 2. 漫游消息的推送机制变过
> 
> 对于1L的问题，本工具防撤回本质是反汇编破坏微信本身的撤回功能，没法做更多建设性功能。也就是本工具没有解决方案。
> 
> （如果要实现各类自定义功能也只能hook微信实现，此类工具还是存在的，你可以自行搜索下）

感谢您。这个被发现的额外“功能”还是挺有意思的。

**Comment by Cyanogens** [comment]
所以QQ/TIM在未登录时撤回的消息在pc端无法复现吗？
