### ISSUE TITLE
[未支持版本]: 3.9.5.55

### ISSUE THREAD

**Issue by wangzheooo** [huiyadanli/RevokeMsgPatcher#578]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.5.55

### 软件提示了什么？

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/55420071/9e011454-ce0c-45e5-83c8-28750af6a89f)

**Comment by huiyadanli** [comment]
现在都1.6版本了，你从哪下的1.2版本。。。

请下载最新版本 https://github.com/huiyadanli/RevokeMsgPatcher/releases
