### ISSUE TITLE
可不可以支持Microsoft Store的版本的QQ？

### ISSUE THREAD

**Issue by Howard20181** [huiyadanli/RevokeMsgPatcher#58]
版本如图
![image](https://user-images.githubusercontent.com/40033067/71764556-3869b000-2f24-11ea-8139-d99a2ab7a2b0.png)
位置：
C:\Program Files\WindowsApps\903DB504.46618D74B1ECA_9.1.6.0_x86__a99ra4d2cbcxa\QQ\Bin

**Comment by LuohuaRain** [comment]
还有Microsoft Store的微信

**Comment by scalpelliu** [comment]
同求

**Comment by ttimasdf** [comment]
Similar to #7. 支持商店版本需要一个稳定的权限支持机制。Store应用目录都是SYSTEM权限，只允许几个特殊的用户组修改。所以需要实现的功能包括，先获取所有权，然后把当前用户加到ACL里，修改文件，然后再把刚加入的条目删掉，再把所有者改回SYSTEM。

**Comment by reserveword** [comment]
我手动替换文件都有障碍，先取得WindowsApps文件夹和QQ所在包的文件夹的拥有权，然后添加允许自己用户所有权限的规则，但是还是没法修改里面的文件。我把权限改来改去，还把ACL翻出来和其他文件的ACL比对过，但都没用，只能删除里面的文件，不能修改
