### ISSUE TITLE
[未支持版本]: 微信3.9.2.26

### ISSUE THREAD

**Issue by achabuhecha** [huiyadanli/RevokeMsgPatcher#580]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.9.2.26

### 软件提示了什么？

![Snipaste_2023-05-26_09-27-13](https://github.com/huiyadanli/RevokeMsgPatcher/assets/34528397/44f3a389-b8a7-4a9d-9080-5c77458bf4cb)

**Comment by achabuhecha** [comment]
图片附着错误。请看本张。
![Snipaste_2023-05-26_09-29-04](https://github.com/huiyadanli/RevokeMsgPatcher/assets/34528397/8bbef80d-08e4-45ca-b839-d03d9c5bd417)

**Comment by huiyadanli** [comment]
应该是没获取到最新补丁信息导致的，试试最新的构建版本


https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/4965022495
