### ISSUE TITLE
我想问下从哪里下载补丁的最新版本啊？

### ISSUE THREAD

**Issue by qhlf78** [huiyadanli/RevokeMsgPatcher#581]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.2.23

### 软件提示了什么？

我想问下从哪里下载补丁的最新版本啊？

**Comment by huiyadanli** [comment]
releases 版本： https://github.com/huiyadanli/RevokeMsgPatcher/releases

最新的编译版本：https://github.com/huiyadanli/RevokeMsgPatcher/actions

如何下载最新编译版本：

1. 选择最新的提交记录
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/9a3db3ec-0b1a-4c9c-8658-c941cddc3674)

2. 滚动到最下面，点击下载
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/662ca800-1a16-455c-a820-23819571dad5)
