### ISSUE TITLE
TIM版本更新以后补丁安装不上了

### ISSUE THREAD

**Issue by lingkerio** [huiyadanli/RevokeMsgPatcher#584]
先前的版本安装了补丁，后来tim更新以后在要安装就会有下列提示
<img width="236" alt="image" src="https://github.com/huiyadanli/RevokeMsgPatcher/assets/112792583/4e59490d-2479-4618-9c9b-9bdbed61052a">
这是我的补丁程序界面视图
<img width="245" alt="image" src="https://github.com/huiyadanli/RevokeMsgPatcher/assets/112792583/3efdf23c-386c-40ca-be9d-3fd460e04ecc">
是不是需要卸载以前的补丁才能安装新的？但是备份还原功能也没法点

**Comment by huiyadanli** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/70456ae4-0ff3-4584-9e1c-ab442e67a79b)

我测试没问题。这个补丁信息2年没变过了，应该和软件版本也没关系。

假如是更新了TIM直接打补丁即可，原来打了补丁的文件会被TIM更新覆盖的
