### ISSUE TITLE
qq9.7.8经常崩溃，win11 22621.1702

### ISSUE THREAD

**Issue by MrLee980** [huiyadanli/RevokeMsgPatcher#586]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/128470614/efd7fb34-9839-4516-bcef-ad992e003d28)
应该是最近两个qq版本吧，老是崩溃，每天崩溃三次左右，挂着不用qq都崩溃，不知道是不是防撤回的问题

**Comment by MrLee980** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/128470614/29e3e5ee-cfe0-4316-b9d1-22794b6d129e)
[QQ113458b.txt](https://github.com/huiyadanli/RevokeMsgPatcher/files/11632438/QQ113458b.txt)
[QQ113458bFMD5.txt](https://github.com/huiyadanli/RevokeMsgPatcher/files/11632439/QQ113458bFMD5.txt)

**Comment by huiyadanli** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/ed2a6bf0-939b-49d4-906a-dc3e6bb44535)

我用着没问题，看看有没有类似反馈。

你本身电脑软件冲突的概率大一点

**Comment by AquaSimulacra** [comment]
并不是，我没装之前也会卡死
