### ISSUE TITLE
微信3.9.5.81

### ISSUE THREAD

**Issue by CMJNB** [huiyadanli/RevokeMsgPatcher#591]
貌似安装防撤回后，自己撤回会一直转圈圈，撤回不成功。

**Comment by wuzhengqiang** [comment]
而且别人撤回时也不提示，好久就这样了。转圈圈这个，你切换到别的窗口再回来，就不转圈圈了。自己是撤回不成功的，之前也是这样，我倒是希望增加别人撤回了的话，麻烦给个提示

**Comment by Amoystyle** [comment]
3.9.5.81
特征: 0F87F20000004883FA010F8462090000
替换: 9090909090904883FA090F8462090000

**Comment by xMaaster** [comment]
原谅小白没有看明白。请问，特征码如何替换？

**Comment by huiyadanli** [comment]
> 3.9.5.81 特征: 0F87F20000004883FA010F8462090000 替换: 9090909090904883FA090F8462090000

我测试了下这个特征也是会转圈圈。。

**Comment by huiyadanli** [comment]
表面转圈圈，实际自己撤回是成功的
