### ISSUE TITLE
无法撤回消息

### ISSUE THREAD

**Issue by zerosherd** [huiyadanli/RevokeMsgPatcher#592]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/45382820/49a65fe4-8079-4ab2-a34c-8487deed4436)
已Patch官方版本微信，确实实现了防撤回，但是无法撤回自己消息。

**Comment by maoshu08** [comment]
请问有支持3.9.5.81的版本吗？

**Comment by maoshu08** [comment]
可以试试3.9.5.81，这个版本可以撤回自己消息。但是电脑版还会看到自己的，手机版显示已经撤回了。

**Comment by huiyadanli** [comment]
测试了下，自己撤回自己的消息是无限转圈，但是实际是已经撤回了的

**Comment by huiyadanli** [comment]
#591
