### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by lm379** [huiyadanli/RevokeMsgPatcher#593]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQNT-9.8.3-13720

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/56c03ab0/QQ9.8.3.13720_x64.exe

### 软件提示了什么？

请求增加基于NT架构的windows qq的防撤回支持

**Comment by huiyadanli** [comment]
#552
