### ISSUE TITLE
[未支持版本]: QQNT

### ISSUE THREAD

**Issue by LazilyCat** [huiyadanli/RevokeMsgPatcher#595]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQNT 9.8.3-13720 (x64)

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/56c03ab0/QQ9.8.3.13720_x64.exe

### 软件提示了什么？

QQNT是腾讯基于Electron的版本，俗称“QQ9”，虽然目前还是测试版，软件目前没有QQNT的防撤回，望作者更新

**Comment by buiawpkgew1** [comment]
#552

**Comment by shenuadm** [comment]
QQNT这界面我喜欢，希望作者能做个QQNT的防撤回

**Comment by NOWorEVER** [comment]
同求

**Comment by MiTuYouZi** [comment]
同求 +1

**Comment by buiawpkgew1** [comment]
> 同求 +1

#522

**Comment by buiawpkgew1** [comment]
> 同求+1

#552

**Comment by BoringHacker** [comment]
+1

**Comment by hugo-Miles** [comment]
顶一下，让作者看到😎

**Comment by Fthrepublic** [comment]
腾讯 QQ Windows 版本昨日上新 v9.9.0 

1、基于 QQ NT 技术，在桌面端是采用 C++ 和 Electron 的方式呈现，Electron 通过使用 Node.js 和 Chromium 的渲染引擎完成桌面GUI开发。这可能使用更多的内存，但比起 Edge WebView2 性能更优，且容易跨平台开发。

2、根据了解新 QQ Windows 版本是使用 Electron 25 版本（对应 Chromium 114），相对同类型 Electron 产品较新，如 Battle.net、Steam，且经特殊处理因此还可兼容 Windows 7 SP1 ，所以 Electron 相关程序你可能还会看到是 Chromium 108。

3、官网没介绍到的功能「QQ GAME」已经集成至最新版本，但部分用户还没有被灰度到，一旦出现目前将无法自定义隐藏，只有小世界和 QQ 频道可在移动端上设置隐藏。

4、支持原生 Windows 通知、窗口圆角与 Windows Acrylic 效果，目前来说隔壁微信都是不支持的，虽然 Windows Acrylic 效果是 Windows 10 的特性，但目前 QQ 并未开放给 Windows 10 用户，据悉因有内存泄漏的技术问题。所以基本上除通知外都是 Windows 11 独家支持。

5、沒有 QQ 安全防护进程(Q盾)。

新版下载地址： https://im.qq.com/pcqq/index.shtml

**Comment by Jimmy-506** [comment]
同求+1

**Comment by 3358329598** [comment]
同求+1

**Comment by lp123sun** [comment]
被微软teams遗弃的技术

**Comment by fgr178707** [comment]
> 同求+1



> 顶一下，让作者看到😎



> 同求+1



> 同求 +1



> 同求

#552

**Comment by Xiaohm6** [comment]
同求

**Comment by buiawpkgew1** [comment]
> 同求
> 

#552

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
