### ISSUE TITLE
[未支持版本]:

### ISSUE THREAD

**Issue by jason-liu475** [huiyadanli/RevokeMsgPatcher#596]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.2.26

### 软件提示了什么？

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/25763344/e58773ee-6df1-4bc5-89c9-5fa5a0c6d0d2)
安装补丁按钮禁用

**Comment by jason-liu475** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/25763344/c4de2137-ffca-4b38-bae8-77645b1b69c8)

**Comment by nsfw404** [comment]
这种情况下手动改成对应版本的微信目录就可以了。
