### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by 1481357572** [huiyadanli/RevokeMsgPatcher#597]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

qq正式版 9.7.9

### 对应版本的下载地址

https://im.qq.com/pcqq

### 软件提示了什么？

用管理员身份运行之后，到QQ的界面 安装补丁成功，但是防撤回不生效。

**Comment by 1481357572** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/45160488/e4072bee-78f3-4201-abb0-44fbf9683d80)

**Comment by huiyadanli** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/37eb7352-6da0-42dc-bce8-f2bf15c4b049)

测试可以防撤回

**Comment by 1481357572** [comment]
我刚试了下还是不行呢  重新安装防撤回也还是不行，这个要怎么排查下呢？

**Comment by huiyadanli** [comment]
看截图已经安装成功，你启动的QQ是软件显示中的目录的QQ吗？
