### ISSUE TITLE
[未支持版本]: NT架构QQ正式版已经发布了

### ISSUE THREAD

**Issue by study520x** [huiyadanli/RevokeMsgPatcher#599]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ9.9.0.14569

### 软件提示了什么？

看看能支持吗
64位：https://dldir1.qq.com/qqfile/qq/QQNT/bbabcfd7/QQ9.9.0.14569_x64.exe

32位：https://dldir1.qq.com/qqfile/qq/QQNT/b62fc715/QQ9.9.0.14569_x86.exe

**Comment by wushendutang** [comment]
俺也一样

**Comment by czruby** [comment]
俺也一样

**Comment by SplashCN123** [comment]
俺也一样。

**Comment by fgr178707** [comment]
#552

**Comment by cattle891240** [comment]
我今天下载了QQNT是不支持的

**Comment by Jingxu23** [comment]
防撤回目前不支持NTQQ，希望作者更新嘞

**Comment by fgr178707** [comment]
请查看此iss

> 我今天下载了QQNT是不支持的



> #552



> 我今天下载了QQNT是不支持的



> 防撤回目前不支持NTQQ，希望作者更新嘞

请查看Issues #552

**Comment by X-LSH** [comment]
俺也一样

**Comment by fgr178707** [comment]
> 俺也一样

#552

**Comment by ExcaliburQZ** [comment]
无法找到此应用的关键文件，请选择正确的安装路径

**Comment by fgr178707** [comment]
> 无法找到此应用的关键文件，请选择正确的安装路径

请查看 #552

**Comment by ExcaliburQZ** [comment]
> > 无法找到此应用的关键文件，请选择正确的安装路径
> 
> 请查看 #552

作者不准备更新NT版的意思？

**Comment by fgr178707** [comment]
> > > 无法找到此应用的关键文件，请选择正确的安装路径
> > 
> > 
> > 请查看 #552
> 
> 作者不准备更新NT版的意思？

字面意思 或者是你@一下作者

**Comment by KamenRevice** [comment]
俺也一样

**Comment by Dayanshifu** [comment]
俺也一样。

**Comment by ticmark** [comment]
me too

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
