### ISSUE TITLE
不支持2.7.0.64，系統windows 10企業版 LTSC

### ISSUE THREAD

**Issue by 17637462979** [huiyadanli/RevokeMsgPatcher#6]

**Comment by huiyadanli** [comment]
2.7.0.64....

https://dldir1.qq.com/weixin/Windows/WeChat2.7.0_beta.exe

尝试更新下2.7.0.65如何:joy:

**Comment by 17637462979** [comment]
@huiyadanli 好的，可以了。謝謝幫助
