### ISSUE TITLE
新版本的撤回提示不起作用。

### ISSUE THREAD

**Issue by wangjiwang** [huiyadanli/RevokeMsgPatcher#60]
我下载了微信2.8.0.112，覆盖安装原先的2.8.0.111。但是安装了最新的补丁，还是和之前一样，没有提示哪一条信息是撤回的。

**Comment by huiyadanli** [comment]
最新的0.8版本的补丁才能做到保留撤回提示，更新到2.8.0.112以后要重新打一次补丁。

如果以上两点都满足，可能是补丁有问题，晚上我重新测试下补丁效果。

**Comment by wangjiwang** [comment]
> 最新的0.8版本的补丁才能做到保留撤回提示，更新到2.8.0.112以后要重新打一次补丁。
> 
> 如果以上两点都满足，可能是防撤回有问题，晚上我重新测试下补丁效果。

是的，已经满足上面的两点。顺便问一下，【卸载】教程只是说删除相关文件，请问相关文件是什么？

**Comment by huiyadanli** [comment]
> > 最新的0.8版本的补丁才能做到保留撤回提示，更新到2.8.0.112以后要重新打一次补丁。
> > 如果以上两点都满足，可能是防撤回有问题，晚上我重新测试下补丁效果。
> 
> 是的，已经满足上面的两点。顺便问一下，【卸载】教程只是说删除相关文件，请问相关文件是什么？

这个【卸载】是指卸载补丁软件，它的相关文件只有软件本体（0.7以后的版本还带上了一个通用躲多开工具和一个说明文档）。。直接删就可以了。。不会在其他任何地方释放其他文件。。

**Comment by huiyadanli** [comment]
@wangjiwang  测试过了没有问题

![image](https://user-images.githubusercontent.com/15783049/72203305-f9e47000-34a4-11ea-8e92-05e3b29ca135.png)

![image](https://user-images.githubusercontent.com/15783049/72203311-108ac700-34a5-11ea-9151-05f778233d31.png)

**Comment by wangjiwang** [comment]
> @wangjiwang 测试过了没有问题
> 
> ![image](https://user-images.githubusercontent.com/15783049/72203305-f9e47000-34a4-11ea-8e92-05e3b29ca135.png)
> 
> ![image](https://user-images.githubusercontent.com/15783049/72203311-108ac700-34a5-11ea-9151-05f778233d31.png)

啊，打扰您了，可能是我理解错了意思。这个版本和之前的效果一样，看到大家都在留言“能不能加个撤回消息的提示”，我以为您在这个版本已经实现了。目前还是无法区分哪一条消息是对方撤回的。
![image](https://user-images.githubusercontent.com/20352069/72203478-18e40180-34a7-11ea-967c-9124c9e62ebb.png)，比如上面这张图，对方撤回了“测试”二字，插件虽然把两个字保留下来了，但是微信还是提醒“对方撤回一条消息”，我们就搞不清插件是否真的执行，因为目前而言效果和未使用插件显示效果是一样的。

**Comment by itaismile** [comment]
最有有个标记 撤回的字体颜色 不一样  或者  后面追加用（）表示撤回

**Comment by CPCer** [comment]
请问你们是在哪里下载的，，我官网下的最新的还是2.8.0.0

**Comment by huiyadanli** [comment]
@CPCer 安装以后可以看到具体版本
