### ISSUE TITLE
[未支持版本]: 3.9.6.22，不支持多开

### ISSUE THREAD

**Issue by freasen** [huiyadanli/RevokeMsgPatcher#602]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.6.22

### 对应版本的下载地址

3.9.5提示自动更新到3.9.6.22的，没有下载地址

### 软件提示了什么？

当前特征码匹配数[0]和期望的匹配数[1]不一致
不会附截图啊！没有上传扭，这面弄？
3.9.5提示自动更新到3.9.6.22的，没有下载地址

**Comment by freasen** [comment]
![微信图片_20230707192934](https://github.com/huiyadanli/RevokeMsgPatcher/assets/7367629/81c2d9ca-0c08-4dc0-9edc-1865f9fa8e98)

好吧，学废了如何双穿截图了！

**Comment by huiyadanli** [comment]
已修复

**Comment by Luoxin** [comment]
可否更新一下 Releases 的包关于修复这个问题的版本

**Comment by huiyadanli** [comment]
> 可否更新一下 Releases 的包关于修复这个问题的版本

老版本会自动获取最新特征的，不用更新
