### ISSUE TITLE
QQ NT架构的防撤回会提上日程吗

### ISSUE THREAD

**Issue by MemorXuxu** [huiyadanli/RevokeMsgPatcher#604]
新版NT架构的QQ 会有功能支持吗，由于不太懂技术，不太清楚难度，只能寄希望于诸位了！

**Comment by KamenRevice** [comment]
会支持NT架构的防撤回吗

**Comment by JunShine** [comment]
同问

**Comment by Ziang-Liu-95** [comment]
最近刚用QQNT新架构，感觉还挺好用的。不过现在还不支持防撤回，请问之后会考虑QQ新架构的防撤回吗？

**Comment by HansonXHC** [comment]
同问

**Comment by zhaoaaaaa5** [comment]
nt直接上插件就可以了

**Comment by KamenRevice** [comment]
> nt直接上插件就可以了

  什么插件啊

**Comment by buiawpkgew1** [comment]
> > nt直接上插件就可以了
> 
>   什么插件啊

#552

**Comment by zhaoaaaaa5** [comment]
> > ntdirect上插件就可以了
> 
> 什么插件啊

git搜下有很多，qq nt插件啥的

**Comment by Bixby0318** [comment]
求求求

**Comment by habacat** [comment]
同求

**Comment by fgr178707** [comment]
> 新版NT架构的QQ 会有功能支持吗，由于不太懂技术，不太清楚难度，只能寄希望于诸位了！

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
