### ISSUE TITLE
[未支持版本]: 微信 3.9.5.90

### ISSUE THREAD

**Issue by seayxu** [huiyadanli/RevokeMsgPatcher#605]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.9.5.90

### 软件提示了什么？

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/11575055/f5ecf594-63cf-4d7e-bb84-65584eff010d)

**Comment by huiyadanli** [comment]
这个理论上是支持的，你用的是最新版本的补丁吗

**Comment by seayxu** [comment]
是从Actions下载的最新的

**Comment by seayxu** [comment]
按照原理修改了 `je` 还是能撤销
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/11575055/ad4b22b3-1fb4-4acc-8705-ddc58d2b7bf3)
文件偏移量为：`BDE4CB`

**Comment by huiyadanli** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/47503bd6-28fa-4289-b291-cb26e3aa8ca9)

我测试了下最新的 3.9.5.91 是可以打上补丁的。

https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

看下你补丁安装到哪个微信目录了？

**Comment by huiyadanli** [comment]
> 按照原理修改了 `je` 还是能撤销 ![image](https://user-images.githubusercontent.com/11575055/252906662-ad4b22b3-1fb4-4acc-8705-ddc58d2b7bf3.png) 文件偏移量为：`BDE4CB`

这个方式3.9.5版本后失效了

**Comment by seayxu** [comment]
3.9.5.91 是可以， 3.9.5.910 微信软件内更新提示是最新版本
