### ISSUE TITLE
NT好像正式发布了，有可能支持防撤回吗？

### ISSUE THREAD

**Issue by Swinden** [huiyadanli/RevokeMsgPatcher#606]
🎉Windows新版本9.9.0正式发布，欢迎下载体验🎉
下载地址：https://im.qq.com/pcqq/index.shtml
1. 基于QQNT技术架构全面升级，使用操作更加流畅快捷。
2. 全新UI设计，界面更加简约轻盈。
3. 消息页面三栏式设计，查看信息更加流畅。
4. 多人语音视频聊天，沟通无极限。
5. 还有更多便捷小功能等待解锁哦！
6. 优化了启动速度和性能
7. 修复了若干个已知问题

> 
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/96880842/4f860213-0b1f-4634-96c1-607139d9aa1b)

**Comment by buiawpkgew1** [comment]
能不能别重复了
