### ISSUE TITLE
我安装后防撤回正常，但是没有撤回提示

### ISSUE THREAD

**Issue by wukm5123** [huiyadanli/RevokeMsgPatcher#608]
我安装后防撤回正常，但是没有撤回提示，搜了一圈也没找到相关的答案，是个例吗

**Comment by huiyadanli** [comment]
现在就是没撤回提示的

**Comment by as88866920** [comment]
> 现在就是没撤回提示的

大佬什么时候能更新一下，坐等大佬找到方法~

**Comment by kakudesu** [comment]
> > 现在就是没撤回提示的
> 
> 大佬什么时候能更新一下，坐等大佬找到方法~

带对方防撤回提醒的用v3.3.0以前的版本

**Comment by Fudge2000** [comment]
为什么不能支持撤回消息提示呢，这样就不会显得尴尬

**Comment by xcSlice** [comment]
没有撤回提示，对方都已经撤回了，自己还在傻傻的写回复。

**Comment by akFace** [comment]
没提示，什么时候出新版本噢

**Comment by srx00000** [comment]
同求，QQ回到別人已經撤回的消息太尷尬了

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/243

3.9.9.43 又可以带撤回提示了
