### ISSUE TITLE
[未支持版本]: 微信 3.5.9.30

### ISSUE THREAD

**Issue by LisonFan** [huiyadanli/RevokeMsgPatcher#610]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.5.9.30

### 对应版本的下载地址

https://dldir1.qq.com/weixin/Windows/WeChatSetup_x86.exe

### 软件提示了什么？

安装程序 SHA256： 4a9223ffa35c2a216389c1e988581e46ba90375a340c4633e60c7c1a558c922f

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/9424775/dee99481-d93f-4df0-a4c0-2ce5d79cd99a)
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/9424775/04c194b8-a7c7-428c-a2dc-305b38592167)

**Comment by huiyadanli** [comment]
#605

3.9.5.90 好像确实不支持，这个包我没获取到过
官网下载的 3.9.5.91 没问题
