### ISSUE TITLE
关于windows微信防撤回

### ISSUE THREAD

**Issue by 6pjj6** [huiyadanli/RevokeMsgPatcher#612]
可以使用防止别人撤回，但是自身不能撤回，一直转圈圈

**Comment by huiyadanli** [comment]
表面转圈圈，实际自己撤回是成功的

#591

**Comment by 6pjj6** [comment]
确实是撤回成功了，有没有办法可以把转圈圈去掉呢？或者是像微信的撤回一样，撤回了可以再编辑



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月23日(周日) 晚上9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [huiyadanli/RevokeMsgPatcher] 关于windows微信防撤回 (Issue #612)




 
表面转圈圈，实际自己撤回是成功的
 
#591

**Comment by huiyadanli** [comment]
等大佬找到新的防撤回点位
