### ISSUE TITLE
QQNT版 问一下 作者什么时候发布  他们老撤回看不到撤回消息！很麻烦

### ISSUE THREAD

**Issue by BJJCCC** [huiyadanli/RevokeMsgPatcher#614]
球球了  快发布吧

**Comment by buiawpkgew1** [comment]
重复 #552

**Comment by cerantes** [comment]
你都用QQNT了，直接用QQNT插件呗

**Comment by fgr178707** [comment]
> 球球了 快发布吧

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT

**Comment by XinYunNet** [comment]
同求啊，搞插件老感觉会被封号

**Comment by fgr178707** [comment]
> 同求啊，搞插件老感觉会被封号

俗话说的好，怕封号就别用

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
