### ISSUE TITLE
[未支持版本]: QQNT

### ISSUE THREAD

**Issue by BJJCCC** [huiyadanli/RevokeMsgPatcher#615]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQNT 版本: 9.9.1-15293

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/4ebc66b2/QQ9.9.1.15293_x86.exe

### 软件提示了什么？

没有防撤回很难受

**Comment by buiawpkgew1** [comment]
重复 #552

**Comment by qingshuangyixia** [comment]
9.7.1也不支持

**Comment by coder9029** [comment]
不知道啥时候支持QQNT

**Comment by 1273082756** [comment]
QQNT附议

**Comment by 21064321** [comment]
> ### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！
> * [x]  我确认当前使用的是最新版
> 
> ### 微信/QQ 版本
> QQNT 版本: 9.9.1-15293
> 
> ### 对应版本的下载地址
> https://dldir1.qq.com/qqfile/qq/QQNT/4ebc66b2/QQ9.9.1.15293_x86.exe
> 
> ### 软件提示了什么？
> 没有防撤回很难受

QQNT有插件，地址在https://github.com/mo-jinran/LiteLoaderQQNT

**Comment by Pinghaichuan** [comment]
QQNT附议

**Comment by HatsuneMikuZero** [comment]
ntQQ附议，想用深色QQ呜呜呜

**Comment by hawchou1995** [comment]
附议QQNT

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
