### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by tomcat-bj** [huiyadanli/RevokeMsgPatcher#619]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.6.29

### 对应版本的下载地址

微信是多年使用，自动升级上来的

### 软件提示了什么？

微信是多年使用，自动升级上来的。已使用管理员身份打开RevokeMsgPatcher，选择微信目录后，提示无法找到此应用的关键文件
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/23627776/abe64144-2060-4c9a-ae24-f0be30f09060)

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/23627776/90892fa7-cd1a-4f9a-a969-614ed4714689)

**Comment by huiyadanli** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/67e2828b-26a3-473d-b138-32506b8d512d)

选择这个目录打补丁就行

**Comment by tomcat-bj** [comment]
成功啦，谢谢！
