### ISSUE TITLE
wechat 3.9.6.33新版本在撤回的文字前边一直有个转圈圈的icon

### ISSUE THREAD

**Issue by macyoyo** [huiyadanli/RevokeMsgPatcher#621]
如题，一直使用3.9.0.28版本没升级，但是昨天（8月2日夜间）被TX强制给升级到了3.9.6.33新版本，发现打补丁后撤回消息，前边一直有个转圈的载入图标，但是自己的消息是可以正常撤回的，就是这个图标总是以为没法出去的消息在加载，这个能否解决？
补充：别人撤回的消息也能正常拦截，不显示圈圈图标，只有自己发的消息撤回前边带有图标。

使用环境：
Windows 10 22h2 x64 19045.3208中文专业版
联通1000兆宽带
补丁是github上的RevokeMsgPatcher.v1.6版本补丁

**Comment by macyoyo** [comment]
那好吧，能否换个图标代表，效果应该比这个图标要好很多，如果能换的话！

**Comment by huiyadanli** [comment]
本防撤回基于反汇编的，不是想干啥就能干啥的，可以说只能破坏一些关键程序节点，没法做建造。

**Comment by macyoyo** [comment]
那就是  MOV 移动  JMP 转移跳转 这些呗，不能再增加一些dll劫持啥的么？

**Comment by huiyadanli** [comment]
> 那就是 MOV 移动 JMP 转移跳转 这些呗，不能再增加一些dll劫持啥的么？

1. 有人做了，效果更好，你可以尝试搜索下
2. 本项目不会做hook相关的操作，高风险且违背本项目的初衷。

**Comment by macyoyo** [comment]
好的，感谢回复，我去找找！

**Comment by iamxiaojianzheng** [comment]
> 好的，感谢回复，我去找找！

有找到吗？
