### ISSUE TITLE
3.9.6 之后的x86 版本不支持了？

### ISSUE THREAD

**Issue by univert** [huiyadanli/RevokeMsgPatcher#626]
https://dldir1.qq.com/weixin/Windows/WeChatSetup_x86.exe
这个应该是最新的3.9.6.32 , x86的版本 ，不支持了

https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
这个应该是x64的3.9.6.33， x64的版本，是支持的。

**Comment by pgy866** [comment]
不支持啦吗

**Comment by pgy866** [comment]
![图片](https://github.com/huiyadanli/RevokeMsgPatcher/assets/28694676/0b4ad542-bfc4-4b12-acdf-8f08d1e6e4de)


3.9.5.90 也不支持

**Comment by pgy866** [comment]
![图片](https://github.com/huiyadanli/RevokeMsgPatcher/assets/28694676/b956dbd6-b33c-49d7-85a5-cd93ab568775)

3.9.5.80 也不支持

**Comment by huiyadanli** [comment]
请下载最新版本微信。
3.9.5之后官方都已经是x64了

**Comment by pgy866** [comment]
需要在DEEPIN  使用 https://bbs.deepin.org/post/262924,
WINE 微信64位目前无法使用，输入框无法输入消息，所以才考虑用32位的


能告知32位微信最后一个支持的版本号嘛？
谢谢你

**Comment by univert** [comment]
最新的微信x86和x64都有下载的，
https://dldir1.qq.com/weixin/Windows/WeChatSetup_x86.exe
x86是偶数版本，x64是奇数

**Comment by pgy866** [comment]
> > 请下载最新版本微信. 3.9.5之后官方都已经是x64了
> 
> 最新的微信x86和x64都有下载的, https://dldir1.qq.com/weixin/Windows/WeChatSetup_x86.exe x86是偶数版本,x64是奇数

是的 一直可以下载 希望作者更新支持。

现在谁知道最后一个支持的32位版本号是哪个啊？

**Comment by pgy866** [comment]
https://github.com/tom-snow/wechat-windows-versions/releases/download/v3.9.2.23/WeChatSetup-3.9.2.23.exe

v3.9.2.23 这个是目前 32位最后一个支持的版本 但是不提示

**Comment by manyhelp** [comment]
一路自动升级上来的3.9.8.15，今天也提示了这个特征比对的弹窗

**Comment by 404-pp** [comment]
> 一路自动升级上来的3.9.8.15，今天也提示了这个特征比对的弹窗

一样版本，发现一直在提示特征比对不一致，希望作者更新支持

**Comment by ldawson951** [comment]
3.9.8.15 不能用了：报错为：
特征比对:当前特征码匹配数[O]和期望的匹配数[3]不一致。出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
2.如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作者处理。

**Comment by goodjob321** [comment]
3.9.8.15 不能用，报错为：特征比对:当前特征码匹配数[O]和期望的匹配数[2]不一致。且一直获取最新补丁信息失败。
