### ISSUE TITLE
软件权限提示建议

### ISSUE THREAD

**Issue by Only-Code-A** [huiyadanli/RevokeMsgPatcher#628]
因公司电脑权限管控，C盘文件扫描及注册表可能无权限访问

打开v1.6版本程序时，后台无限重启，且无法根据进程强制关闭，导致电脑卡顿

建议作者如有权限问题时，可弹提示框即可，没必要无限疯狂重启程序

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/blob/master/RevokeMsgPatcher/Program.cs

确实有自启唤起UAC操作，不过这个方案很稳定暂时不会改。我无法对奇怪权限管控这种方式进行预判，也不知道如何改动才能解决你的问题。

不过Debug版本是不会进行权限提升操作，可以使用 [Action](https://github.com/huiyadanli/RevokeMsgPatcher/actions)下自动编译的[Debug版本](https://github.com/huiyadanli/RevokeMsgPatcher/suites/15548073405/artifacts/887259682)，应该能解决你的问题
