### ISSUE TITLE
[未支持版本]: LINUX QQ

### ISSUE THREAD

**Issue by pgy866** [huiyadanli/RevokeMsgPatcher#629]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

linuxqq_3.2.0-16605_amd64.deb

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/1776936e/linuxqq_3.2.0-16605_amd64.deb

### 软件提示了什么？

不支持

**Comment by huiyadanli** [comment]
暂不考虑win平台以外的系统。而且应该会有其他更好的方案
