### ISSUE TITLE
2.8.0.111版本微信安装RevokeMsgPatcher.v0.8 后不支持防撤回

### ISSUE THREAD

**Issue by zfy603206328** [huiyadanli/RevokeMsgPatcher#63]
2.8.0.111版本微信安装RevokeMsgPatcher.v0.8 后不支持防撤回

**Comment by huiyadanli** [comment]
可以提供下对应的微信目录下所有文件的打包吗

**Comment by zfy603206328** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"辉鸭蛋"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月21日(星期二) 晚上9:34
收件人:&nbsp;"huiyadanli/RevokeMsgPatcher"<RevokeMsgPatcher@noreply.github.com&gt;;
抄送:&nbsp;"兔子爱上猫"<603206328@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] 2.8.0.111版本微信安装RevokeMsgPatcher.v0.8 后不支持防撤回 (#63)




可以提供下对应的微信目录下所有文件的打包吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

WeChat.zip (120.14M, 2020年02月21日 08:18 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0c6138627bff4fcb8b53cc411130001c51030856000901561e565d52021d06515004155a5500031e57070b510f51575200040c53373a326456225003431e485a436105&code=3a8b7023

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/72880828-97a82c80-3d3a-11ea-841d-d9df06e5dce2.png)

![image](https://user-images.githubusercontent.com/15783049/72880974-dccc5e80-3d3a-11ea-9360-34e4dae6b564.png)

你提供的文件已经安装了补丁，我直接登录测试完全支持防撤回！

**Comment by zfy603206328** [comment]
好的谢谢，等过完年我再试试，新年快乐



---原始邮件---
发件人: "辉鸭蛋"<notifications@github.com&gt;
发送时间: 2020年1月22日(周三) 下午5:17
收件人: "huiyadanli/RevokeMsgPatcher"<RevokeMsgPatcher@noreply.github.com&gt;;
抄送: "zhaofy"<603206328@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [huiyadanli/RevokeMsgPatcher] 2.8.0.111版本微信安装RevokeMsgPatcher.v0.8 后不支持防撤回 (#63)




 

 
你提供的文件已经安装了补丁，我直接登录测试完全支持防撤回！

**Comment by SpaceEggs** [comment]
我也是这个版本，不支持防撤回。

会不会和系统语言有关，我的系统和微信都是英文的。

**Comment by huiyadanli** [comment]
和系统语言无关，建议找人具体测试下撤回效果，现在的防撤回会显示原来的撤回提示。

**Comment by LoongLoL** [comment]
自己撤回的消息是可以撤回的，别人撤回的消息依旧会提示微信的撤回提示，一个不太好的点是我不知道别人撤回的是那一条消息。

**Comment by huiyadanli** [comment]
> 自己撤回的消息是可以撤回的，别人撤回的消息依旧会提示微信的撤回提示，一个不太好的点是我不知道别人撤回的是那一条消息。

的确有这个问题，暂时没有更好的解决方案了，未来可能可以做到
