### ISSUE TITLE
[未支持版本]: 

### ISSUE THREAD

**Issue by shangliang186** [huiyadanli/RevokeMsgPatcher#631]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.6.32

### 对应版本的下载地址

https://github.com/huiyadanli/RevokeMsgPatcher

### 软件提示了什么？

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/144104896/6afaed1d-991d-42dd-85c9-c305c8b8a5ae)
提示当前匹配特征码0  和期望值不一样 而且可选功能哪里只有多开和防撤回

**Comment by huiyadanli** [comment]
你这个软件目录看着不对，新版本微信都有版本号的。

**Comment by shangliang186** [comment]
是要用默认安装路径么 我微信是装在D盘的  版本也是最新的啊 要不楼主给个微信的安装包呗
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/144104896/d625737f-5ed0-49ce-ab44-bd69e31c7731)
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/144104896/7cc763ee-c577-4225-b985-190420eba687)

**Comment by shangliang186** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/144104896/6e882952-b1b6-4d7d-80ef-341453f97ee1)
我启动了下多开 然后多开一直卡着不动 也没有启动成功 然后点击停止  又重复操作了一下多开的启动和停止 回来看防撤回就与版本号了  安装补丁也成功了

**Comment by shangliang186** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/144104896/6e882952-b1b6-4d7d-80ef-341453f97ee1)
我启动了下多开 然后多开一直卡着不动 也没有启动成功 然后点击停止  又重复操作了一下多开的启动和停止 回来看防撤回就与版本号了  安装补丁也成功了
