### ISSUE TITLE
怎么屏蔽PC微信更新提示？

### ISSUE THREAD

**Issue by kidzgy** [huiyadanli/RevokeMsgPatcher#634]
如果当前微信版本不是最新版本，会随机弹出更新提示的小窗，不知道怎么屏蔽这个？

是否可以用hosts屏蔽的话，不知道该指向哪个域名？

如果不能用hosts屏蔽，不知有逆向的解决方案吗？

**Comment by scalpelx** [comment]
好像用hosts屏蔽dldir1.qq.com可以，但是会影响腾讯其他软件的下载，不知道有没有更好的方案

**Comment by kidzgy** [comment]
zd423有个屏蔽升级提示的补丁：https://www.lanzoub.com/iytTg0u665qj

**Comment by scalpelx** [comment]
> zd423有个屏蔽升级提示的补丁：https://www.lanzoub.com/iytTg0u665qj

看着说是适用于3.9.5以上版本的，3.9.0.28可以正常用吗

**Comment by kidzgy** [comment]
> > zd423有个屏蔽升级提示的补丁：https://www.lanzoub.com/iytTg0u665qj
> 
> 看着说是适用于3.9.5以上版本的，[3.9.0.28](http://3.9.0.28)可以正常用吗
我自己没有用这些补丁，用的是最新版的微信，一直没机会弹出升级提示。

**Comment by scalpelx** [comment]
> > zd423有个屏蔽升级提示的补丁：https://www.lanzoub.com/iytTg0u665qj
> 
> 看着说是适用于3.9.5以上版本的，3.9.0.28可以正常用吗

用了几天发现还是会弹
