### ISSUE TITLE
[未支持版本]:  QQ9.4.6.0 WindowsStore版本 是否支持？

### ISSUE THREAD

**Issue by Camellia-zh** [huiyadanli/RevokeMsgPatcher#635]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ9.4.6.0 Windows商店版

### 对应版本的下载地址

https://www.123pan.com/s/eeU0Vv-5MBld

### 软件提示了什么？

![微信截图_2023](https://github.com/huiyadanli/RevokeMsgPatcher/assets/45528812/8e2dbf30-0d55-4f29-841c-2c2d694fc5a1)

是微软商店放开之前无QProtect的版本，安装包为appx格式，已授予安装目录的访问权限，显示不支持。

https://www.123pan.com/s/eeU0Vv-5MBld
提取：9471

**Comment by zhixia-shijian** [comment]
怎么关掉防撤回
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/140401485/5df76e62-66b3-49d7-8684-0583ef6851ff)

**Comment by Camellia-zh** [comment]
这是自动回复邮件。


    ---------------------------- 

您的邮件已投递到邮箱。


    ----------------------------

**Comment by huiyadanli** [comment]
不考虑支持商店版了

**Comment by Camellia-zh** [comment]
这是自动回复邮件。


    ---------------------------- 

您的邮件已投递到邮箱。


    ----------------------------
