### ISSUE TITLE
[未支持版本]: 3.9.7.25

### ISSUE THREAD

**Issue by xubo000** [huiyadanli/RevokeMsgPatcher#636]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版本3.9.7.25

### 软件提示了什么？

![捕获](https://github.com/huiyadanli/RevokeMsgPatcher/assets/134153398/d1603075-10cb-45a6-8141-ec538b17d578)
上图为截图

**Comment by luojianxhlxt** [comment]
今天更新到3.9.7.29了

**Comment by pjy612** [comment]
emmm release 里面下的 都没有 新 这东西 囧

**Comment by huiyadanli** [comment]
3.9.7.25 应该是没有【新】这个补丁的。。。

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/b5e327ed-09d2-45de-ab23-0761387b37e4)

你应该是没自动获取到最新补丁信息

可以在构建里面下载内置补丁信息最新的版本：
https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/5996105344/job/16260101001

**Comment by LangfordHsu** [comment]
@huiyadanli 大佬，具体应该是怎么做呢？下载哪个文件？然后怎么操作呢？感谢

**Comment by huiyadanli** [comment]
@LangfordHsu  
给你给直链：
https://github.com/huiyadanli/RevokeMsgPatcher/suites/15548073405/artifacts/887259685

**Comment by LangfordHsu** [comment]
还是不行哎 @huiyadanli 
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/33155648/8d36537a-fd1a-42e7-90f3-d35d2cc137b5)

**Comment by huiyadanli** [comment]
@LangfordHsu 你这不是已经安装成功了么，已经可以防撤回了

**Comment by LangfordHsu** [comment]
有点bug，这个微信3.9.7.25版我没有点过安装补丁，因为它一直显示灰色。然后在微信里也测试过，确实是没有防止撤回…… @huiyadanli 
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/33155648/4a4212a6-a894-42ce-83cc-50b1557f188a)

**Comment by fy520134** [comment]
> 3.9.7.25 应该是没有【新】这个补丁的。。。
> 
> ![image](https://user-images.githubusercontent.com/15783049/273487394-b5e327ed-09d2-45de-ab23-0761387b37e4.png)
> 
> 你应该是没自动获取到最新补丁信息
> 
> 可以在构建里面下载内置补丁信息最新的版本： https://github.com/huiyadanli/RevokeMsgPatcher/actions/runs/5996105344/job/16260101001

大佬，什么时候3.9.7.25防撤回版本支持提示呀？

**Comment by huiyadanli** [comment]
@LangfordHsu 我测试没问题，你实际启动的微信肯定和你打补丁的目录不一致，可以进微信安装目录看下。大概率是多个微信版本共存了

**Comment by huiyadanli** [comment]
@fy520134 没有新方案之前不会有带提示的防撤回了。当前的防撤回方案问题也挺多的
