### ISSUE TITLE
[未支持版本]: 最新的3.9.7.29不支持了吗？

### ISSUE THREAD

**Issue by qq1986114** [huiyadanli/RevokeMsgPatcher#638]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.7.29

### 软件提示了什么？

无法使用在最新版本微信？？

**Comment by huiyadanli** [comment]
支持的

**Comment by lelucermaire17** [comment]
我显示的是当前特征码匹配数[0]和期望的匹配数[1]不一致

**Comment by abandonstudy** [comment]
我这也是特征码不一致

**Comment by huiyadanli** [comment]
下载最新构建版本试试
https://github.com/huiyadanli/RevokeMsgPatcher/suites/15548073405/artifacts/887259685

最近好像部分地区获取补丁信息有问题

**Comment by lelucermaire17** [comment]
哇，谢谢，安装成功啦！

**Comment by espwong** [comment]
> 下载最新构建版本试试 https://github.com/huiyadanli/RevokeMsgPatcher/suites/15548073405/artifacts/887259685
> 
> 最近好像部分地区获取补丁信息有问题

更新了这个版本可以了
