### ISSUE TITLE
微信 更新 2.8.0.116版本

### ISSUE THREAD

**Issue by 474364707** [huiyadanli/RevokeMsgPatcher#64]
微信 更新 2.8.0.116版本

**Comment by huiyadanli** [comment]
0.8 版本的补丁支持所有新版本。你可以测试下是否能够成功打上补丁

**Comment by WarriorYu** [comment]
我试了几次，2.8.0.116防撤回无效。补丁提示成功了

**Comment by huiyadanli** [comment]
@474364707 @WarriorYu  现在新版本会显示对方撤回的信息，但信息实际是没有撤回的。
可以参考 #60

**Comment by 474364707** [comment]
好的 谢谢了
