### ISSUE TITLE
自己撤回一直转圈实际撤回成功，版本：3.9.7.29

### ISSUE THREAD

**Issue by Fabali** [huiyadanli/RevokeMsgPatcher#640]
之前的版本微信使用了撤回补丁就有这个问题，手动撤回自己的消息，会一直在转圈圈，一开始以为撤回失败了，后来才发现，手机端撤回成功了（手机没有使用防撤回补丁），才发现原来是电脑的问题

**Comment by huiyadanli** [comment]
#621

已知问题
