### ISSUE TITLE
微信[3.9.7.29]，自己撤回的时候能成功撤回，但是效果一直转圈

### ISSUE THREAD

**Issue by daizhichao** [huiyadanli/RevokeMsgPatcher#646]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/7709655/e0e3fc08-fe13-45be-a46d-744fe1ce37ee)

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/621

**Comment by jiahao6635** [comment]
自己撤回消息是否可以显示撤回成功

**Comment by mavisOK** [comment]
＋1

**Comment by lanlan1971** [comment]
会有提示的，请更新
![image](https://github.com/user-attachments/assets/17fd5042-2dbc-47dc-a0cf-6b976cb7c751)


> 自己撤回消息是否可以显示撤回成功

**Comment by 550783859** [comment]
看介绍里，有明确的说了这个情况，
