### ISSUE TITLE
[未支持版本]: 3.9.8.15

### ISSUE THREAD

**Issue by ldawson951** [huiyadanli/RevokeMsgPatcher#652]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.8.15

### 软件提示了什么？

特征比对:当前特征码匹配数[0]和期望的匹配数[3]不一致。出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装。
⒉如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作者处理。

**Comment by blacksr** [comment]
现在已经支持了，最新版本1.17

**Comment by huiyadanli** [comment]
测试1.7版本支持，理论上1.6也是支持的，不支持的唯一原因就是没有获取到最新补丁信息
