### ISSUE TITLE
v1.7不支持微信3.9.7.29版本撤回？

### ISSUE THREAD

**Issue by weixisheng** [huiyadanli/RevokeMsgPatcher#654]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/16042305/a68ff695-2935-47e8-b2ba-46122d8b9b8f)

**Comment by huiyadanli** [comment]
你这不是安装成功了么

**Comment by weixisheng** [comment]
> 你这不是安装成功了么

昨晚安装的，但是刚才微信消息还是撤回了

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/16042305/37dce26e-ea94-4724-a5b4-8bf811ee3239)

**Comment by huiyadanli** [comment]
你使用的微信的路径，大概率和你打补丁的微信路径不一样

**Comment by weixisheng** [comment]
> 你使用的微信的路径，大概率和你打补丁的微信路径不一样

ok，我检查下

**Comment by Young-people** [comment]
> 你使用的微信的路径，大概率和你打补丁的微信路径不一样

我卸载老版本，新版本可能路径不一样了  怎么修复，怎么删除已打的补丁

**Comment by huiyadanli** [comment]
> > 你使用的微信的路径，大概率和你打补丁的微信路径不一样
> 
> 我卸载老版本，新版本可能路径不一样了 怎么修复，怎么删除已打的补丁


手动选择正确的路径
