### ISSUE TITLE
[未支持版本]: 3.9.8.15

### ISSUE THREAD

**Issue by Liumda** [huiyadanli/RevokeMsgPatcher#658]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.8.15

### 软件提示了什么？

![Uploading 1701768166031.png…]()

**Comment by Liumda** [comment]
特征比对: 当前特征码匹配数[0]和期望的匹配数[2]不一致出现此种情况的一般有如下可能:
1.你可能已经安装了某个功能的补丁，请选择未安装功能进行安装请联系作2.如果当前版本为最新版本，特征码可能出现变化 (可能性比较低)
者处理。

**Comment by huiyadanli** [comment]
#657  1.7版本支持
