### ISSUE TITLE
2.8.0.116版本微信无法安装RevokeMsgPatcher.v0.8 的防撤回补丁

### ISSUE THREAD

**Issue by Jack6811** [huiyadanli/RevokeMsgPatcher#66]

**Comment by huiyadanli** [comment]
有无具体提示？‘
#64

**Comment by Jack6811** [comment]
![image](https://user-images.githubusercontent.com/57797431/74082503-90508500-4a95-11ea-904e-29dc0c859f70.png)

**Comment by huiyadanli** [comment]
@Jack6811 请使用最新的0.8版本

**Comment by tldzyx** [comment]
2.8.0.121版本微信也弹出类似的提示

**Comment by huiyadanli** [comment]
@tldzyx 我测试过这个版本，0.8可以正常使用
