### ISSUE TITLE
吾爱上这个支持3.9.0.28版本的防撤回，看看他咋实现的

### ISSUE THREAD

**Issue by gx0674** [huiyadanli/RevokeMsgPatcher#660]
帖子路径：
https://www.52pojie.cn/thread-1750880-1-1.html
![帖子](https://github.com/huiyadanli/RevokeMsgPatcher/assets/42225892/55b8d61d-d4de-4c89-aa05-39891537587a)

**Comment by gx0674** [comment]
> hook形式的，原理不同。
> 
> 这对这个项目而言可能是一条红线，跨过可能就无了，懂吧。
> 
> 暂时只会保持当前笨拙的方式。毕竟初衷也只是做一个16进制的查找替换。

哦哦，原来如此，就是hook方式容易被封号哈

**Comment by huiyadanli** [comment]
1. hook形式功能繁多容易被封号
2. 作者（我）的逆向水平很差，也无力进行长期维护
3. 项目用这种形式很容易被南山必胜客找上门

**Comment by gx0674** [comment]
> 1. hook形式功能繁多容易被封号
> 2. 作者（我）的逆向水平很差，也无力进行长期维护
> 3. 项目用这种形式很容易被南山必胜客找上门

懂了，是的，安全第一
