### ISSUE TITLE
微信3.9.8.15 打了防撤回补丁，一启动wx就直接崩溃

### ISSUE THREAD

**Issue by localurk** [huiyadanli/RevokeMsgPatcher#662]
微信3.9.8.15 打了防撤回补丁，一启动wx就直接崩溃，还原就可用。
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/13211756/24f3e162-a12a-4f52-8e05-0df849c03d43)

**Comment by huiyadanli** [comment]
测试没有遇到这种情况，建议覆盖安装微信后重试
