### ISSUE TITLE
似乎破坏了搜索功能？

### ISSUE THREAD

**Issue by 6LWa6ZKx** [huiyadanli/RevokeMsgPatcher#664]
windows微信最新版，无法正常使用搜索功能了。

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/61306859/728b5c3b-8718-4804-9481-c93e70080f0f)

**Comment by huiyadanli** [comment]
与补丁无关，请还原补丁重试

**Comment by 6LWa6ZKx** [comment]
> 与补丁无关，请还原补丁重试

我猜测是这一年来微信升级，不断的重复安装补丁，导致某些文件的损坏导致的？

或者说需要还原才能升级微信版本。

**Comment by huiyadanli** [comment]
大概率是微信本身的问题，我只是给你一个控制变量找到问题原因并解决问题的方案
