### ISSUE TITLE
每日10点PC端微信提示安全风险，被踢下线

### ISSUE THREAD

**Issue by juzq** [huiyadanli/RevokeMsgPatcher#666]
版本：1.7
微信版本：3.9.7.29

![img_v3_0263_923c86a0-fb48-45ea-a9a0-f029b0f40dbg](https://github.com/huiyadanli/RevokeMsgPatcher/assets/12960773/5878c605-91b9-4d26-8b78-b86ba4d9b4a1)

虽然不影响正常使用，但是每天都需要重新扫码登录，很不方便

**Comment by huiyadanli** [comment]
建议还原后继续观察，找到实际触发账号安全的原因。补丁应该不会触发这个提示。

**Comment by Lishy1535** [comment]
是公司的电脑把，有后台监控软件运行着，可以搜下ipguard了解

**Comment by makabaka33** [comment]
提示一下，ipguard是有2-3帧截屏功能的，相当于实时监控员工的上网行为，号称最恶心的管控软件，具体如何查看可以试着命令行输入netstat –an |find “8237”，看一下如果有进程，那就是实锤了，

**Comment by juzq** [comment]
实锤了，我是装了[ToDesk](https://www.todesk.com/solo)导致的，退出之后就没再出现了。
