### ISSUE TITLE
不支持QQ9吗

### ISSUE THREAD

**Issue by lhy1131599462** [huiyadanli/RevokeMsgPatcher#668]

**Comment by EmiyaNiu** [comment]
同问

**Comment by buiawpkgew1** [comment]
QQNT有插件，地址在https://github.com/mo-jinran/LiteLoaderQQNT

**Comment by wintrue** [comment]
> QQNT有插件，地址在https://github.com/mo-jinran/LiteLoaderQQNT

支持的版本太旧了

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
