### ISSUE TITLE
是否能支持QQ NT呢

### ISSUE THREAD

**Issue by EasonsVirus46786** [huiyadanli/RevokeMsgPatcher#669]

**Comment by hualin6** [comment]
同问 ，现在有新架构版的QQ，这个需要真正的更新一版
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/51294303/ea093c7d-c26e-428b-8329-8fa019c5179a)

**Comment by lovingzyz** [comment]
确实，QQ脑瘫版改更新下啦

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
