### ISSUE TITLE
新版本3.9.8.25不支持了

### ISSUE THREAD

**Issue by DIFF0815** [huiyadanli/RevokeMsgPatcher#670]
新版本3.9.8.25不支持了，大佬什么时候更新下

**Comment by zz80900** [comment]
闪退

**Comment by jason-liu475** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/25763344/67d1ae69-2190-407b-9aec-cd99703deda8)

**Comment by dreamtraveler-LiuQi** [comment]
你们都能用吗？😂

**Comment by xlh001** [comment]
不能

**Comment by huiyadanli** [comment]
测试 3.9.8.25 支持。请更新1.7版本
