### ISSUE TITLE
开启防撤回后 表情和新加的好友头像都不显示

### ISSUE THREAD

**Issue by andywang155** [huiyadanli/RevokeMsgPatcher#672]
开启防撤回后 表情和新加的好友头像都不显示

**Comment by huiyadanli** [comment]
没遇到过这种问题。。。

你要不先还原后测试下

**Comment by as88866920** [comment]
没注入时是能正常显示的
QQ 9.9.12-25765注入补丁后
QQ自带的表情不显示
![QQ20240717-225431](https://github.com/user-attachments/assets/ddd298ea-44cc-4eef-81af-0dc7df9f582a)

**Comment by as88866920** [comment]
9.9.11-24815 就不会这样
