### ISSUE TITLE
最新版3.9.9防撤回失效了

### ISSUE THREAD

**Issue by hm983763907** [huiyadanli/RevokeMsgPatcher#673]
麻烦开发大大适配下最新的微信版本

**Comment by MarkLily** [comment]
3.9.9.25没问题呀！

**Comment by jianchennn** [comment]
> 3.9.9.25没问题呀！

最新的不是3.9.9.13吗

**Comment by jianchennn** [comment]
![QQ截图20240112152214](https://github.com/huiyadanli/RevokeMsgPatcher/assets/64254217/59bb69b4-df14-45cd-80c8-86a198874718)

**Comment by MarkLily** [comment]
你这个试试 先安装官网的版本后 再安装插件

**Comment by jianchennn** [comment]
> 你这个试试 先安装官网的版本后 再安装插件

我刚刚从github重新下载了 现在可以用了

**Comment by GitHubacb** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/39853627/4ac655fa-b004-4606-8bef-8629eef75594)
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/39853627/d6cad599-5b76-4e9d-9985-73964ef7487d)

可以自己找到版本号填进去

**Comment by JRGavin** [comment]
> ![image](https://private-user-images.githubusercontent.com/39853627/302082576-4ac655fa-b004-4606-8bef-8629eef75594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxODQ4MTEsIm5iZiI6MTcwNzE4NDUxMSwicGF0aCI6Ii8zOTg1MzYyNy8zMDIwODI1NzYtNGFjNjU1ZmEtYjAwNC00NjA2LThiZWYtODYyOWVlZjc1NTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDAxNTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NTUzYTg0YmNmYzQ0MmQ5MGViNDlhMTNkZmMxMmE4Zjc2ZDc3NjlmNTE3YTI2Zjk2MTZkNTQwZmFhMjE1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILRgUXPRIrWbLcmsJeUoO2EoNvTPNgMnHpOBsNxuRJE) ![image](https://private-user-images.githubusercontent.com/39853627/302082605-d6cad599-5b76-4e9d-9985-73964ef7487d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxODQ4MTEsIm5iZiI6MTcwNzE4NDUxMSwicGF0aCI6Ii8zOTg1MzYyNy8zMDIwODI2MDUtZDZjYWQ1OTktNWI3Ni00ZTlkLTk5ODUtNzM5NjRlZjc0ODdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDAxNTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMzk3YmI3YTZkY2YwNDIyMWJkYzBkOTcwNTkxMjBiOTRhODlkY2EwMzEyOWU4N2Q4Y2JlOTBiZjFkNTdhYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YhQ1MI055X2nUbP6c-sr1O1wp2FVlm6L1pFEVb5C2zQ)
> 
> 可以自己找到版本号填进去

g这个方法可行！

**Comment by huiyadanli** [comment]
一直都是支持的
