### ISSUE TITLE
[未支持版本]: 由于公司装了监控，考虑到安全性，不想用防撤回了，应该怎么处理

### ISSUE THREAD

**Issue by vleyong** [huiyadanli/RevokeMsgPatcher#674]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.8.25

### 软件提示了什么？

没什么，很好

**Comment by huiyadanli** [comment]
还原补丁或者覆盖安装微信。

公司监控和你本地防撤回有个毛线关系。
