### ISSUE TITLE
微信 无法找到此应用的关键文件，请选择正确的安装路径

### ISSUE THREAD

**Issue by minorikawafuso** [huiyadanli/RevokeMsgPatcher#675]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/47047663/8952f3cb-ddb6-4fcf-b168-13eb3289165d)

我很确定我选择了正确的路径，WeChat.exe就在该目录下。QQ和TIM的补丁都可以正确自动识别到路径并安装，只有微信的不行。微信版本是3.9.8.25，是官网下载不是Microsoft Store版

**Comment by huiyadanli** [comment]
你打开对应目录截图。关键文件是 wechatwin.dll

**Comment by SamWang8888** [comment]
重装
