### ISSUE TITLE
[未支持版本]: QQ版本: 9.9.6-20201 (64位）

### ISSUE THREAD

**Issue by saucyjackme** [huiyadanli/RevokeMsgPatcher#676]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ正式版本: 9.9.6-20201 (64位)

### 对应版本的下载地址

https://github.com/huiyadanli/RevokeMsgPatcher/releases/download/1.7/RevokeMsgPatcher.v1.7.zip

### 软件提示了什么？

微信3.9.8.25能够生效，QQ版本: 9.9.6-20201 (64位）提示找不到关键文件

**Comment by DreamersPrime** [comment]
“对应版本的下载地址”应该是https://im.qq.com/pcqq
这个是nt架构的新版qq，目前版本号是9.9.7-20979；原版qq似乎已经停止更新了，截止目前已经一年零一天没更新了
希望大大能做一下适配🙏

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
