### ISSUE TITLE
更新微信,安装完插件后,重新登录微信,历史消息没了

### ISSUE THREAD

**Issue by cynen** [huiyadanli/RevokeMsgPatcher#680]
微信: 3.9.3 -->3.9.9 (升级微信)
版本:v1.7 (安装插件)
安装完,再登录微信后,发现历史消息没了. 检查发现文件保存位置自动变更了. 重新选择文件保存位置,再登录打开发现历史消息还是无法加载. 

咨询一下,是正常现象吗?

**Comment by cynen** [comment]
唉, 修了好久,准备放弃历史消息了.
防撤回是生效状态.

**Comment by huiyadanli** [comment]
和插件无关，建议咨询微信
