### ISSUE TITLE
微信更新版本后，会对多开+防撤回进行检测（最近两个版本的微信都这样）。多开/单开登录后一段时间，会强制掉线

### ISSUE THREAD

**Issue by zangbob** [huiyadanli/RevokeMsgPatcher#682]
微信更新版本后，会对多开+防撤回进行检测（最近两个版本的微信都这样）。多开/单开登录后一段时间，会强制掉线

使用版本：微信PC 3.9.9.35  +  RevokeMsgPatcher.v1.7

**Comment by huiyadanli** [comment]
防撤回完全没有感知到这个问题

**Comment by zangbob** [comment]
重新测试了一下，只开防撤回，不开多开，目前暂无强制掉线

**Comment by NotPeppa** [comment]
3.9.9.43 单防撤回也强制掉线了

**Comment by zangbob** [comment]
同楼上，3.9.9.43 只开防撤回，有时几分钟就强制掉线。有时坚持较长一段时间后再掉

**Comment by huiyadanli** [comment]
依旧无法复现，大概率和补丁无关

**Comment by Su-528** [comment]
> 3.9.9.43 单防撤回也强制掉线了

+1会提示环境错误，去掉防撤回就不会掉线
