### ISSUE TITLE
[未支持版本]: QQ NT 9.9.7-21159 (64位)

### ISSUE THREAD

**Issue by tutdahai** [huiyadanli/RevokeMsgPatcher#683]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ NT 9.9.7-21159 (64位)

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/395e339f/QQ9.9.7.21159_x64.exe

### 软件提示了什么？

QQ NT 已经更新了很多版本，不知道能不能支持，感谢大佬

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
