### ISSUE TITLE
[未支持版本]: QQ NT 9[QQNT 9.9.7-21159 (64位)]或者微软商店里的桌面版无法受支持[防撤回版本v1.7_2'v1.7'v1.6均尝试过]

### ISSUE THREAD

**Issue by FCXRDSS** [huiyadanli/RevokeMsgPatcher#684]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ9或者微软商店里的桌面版无法受支持

### 对应版本的下载地址

https://im.qq.com/pcqq/index.shtml

### 软件提示了什么？

QQ9或者微软商店里的桌面版最新版无法受支持
RevokeMsgPatcher无法找到安装路径
![屏幕截图 2024-01-26 171444](https://github.com/huiyadanli/RevokeMsgPatcher/assets/136197412/177115e0-acf0-4859-84a6-bd8d50958767)
![屏幕截图 2024-01-26 171427](https://github.com/huiyadanli/RevokeMsgPatcher/assets/136197412/959492b6-e035-4ebe-be93-f79f6b7a3a28)
![屏幕截图 2024-01-26 171436](https://github.com/huiyadanli/RevokeMsgPatcher/assets/136197412/5195052e-3c9b-4050-848f-2a69a651051c)

**Comment by FCXRDSS** [comment]
版本：9.9.7-21159 (64位)

**Comment by muteX4** [comment]
对啊，我也是这样，找不到qq路径，自动搜索的路径是没更新过的qq

**Comment by buiawpkgew1** [comment]
QQ NT 目前不支持

**Comment by diudiu199488** [comment]
什么时候可以支持QQNT呢？

**Comment by phtry** [comment]
请问什么时候支持QQnt v9.9.7 还有在更新嘛

**Comment by Reallywish** [comment]
希望支持QQnt版本，老版本群多了就卡的不行了

**Comment by JunShine** [comment]
QQnt需要使用LiteLoaderQQNT插件再安装防撤回补丁

**Comment by NOWorEVER** [comment]
有大佬做了一个https://github.com/xh321/LiteLoaderQQNT-Anti-Recall，刚刚才知道

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
