### ISSUE TITLE
 实际效果：对方撤回消息后，将在当前聊天记录最下方显示“xxxx 撤回了一条消息”，但是没有提示撤回信息

### ISSUE THREAD

**Issue by wenan110** [huiyadanli/RevokeMsgPatcher#685]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.9.27

### 软件提示了什么？

撤回之后并没有 ‘’xxxx 撤回了一条消息‘’撤回提示，跟没有撤回一样

**Comment by huiyadanli** [comment]
已经不支持这个撤回消息显示了
