### ISSUE TITLE
10w用户血书申请支持最新版微信！更新的功能对公众号文章阅读提升很大！

### ISSUE THREAD

**Issue by theblack6688** [huiyadanli/RevokeMsgPatcher#69]
https://s2.ax1x.com/2020/02/06/16rIYT.png

版本：2.8.0.111

万分感谢大佬！

**Comment by theblack6688** [comment]
![版本：2.8.0.111](https://s2.ax1x.com/2020/02/06/16rIYT.png)

万分感谢！

**Comment by huiyadanli** [comment]
这个版本一直都支持 #63

**Comment by theblack6688** [comment]
> 这个版本一直都支持 #63

嗯嗯  我用的是之前的老版本补丁，更新了微信后用了补丁使微信版本回退了，更新了补丁就OK了，谢谢！
