### ISSUE TITLE
识别不到最新版QQ的安装目录了

### ISSUE THREAD

**Issue by paradiseTT** [huiyadanli/RevokeMsgPatcher#691]
问题并不复杂，只是识别不到QQ的安装目录，微信和TIM是正常的
![1710126809294](https://github.com/huiyadanli/RevokeMsgPatcher/assets/129969499/3e1e79b1-d980-4b83-8e77-306c33104e5e)
![1710126791190](https://github.com/huiyadanli/RevokeMsgPatcher/assets/129969499/65c4ea84-bfc2-4532-8317-75c4e71ae8bd)
![1710126752577](https://github.com/huiyadanli/RevokeMsgPatcher/assets/129969499/ef364ae6-89de-4a23-a620-7ee3d1e051e0)
![1710126719649](https://github.com/huiyadanli/RevokeMsgPatcher/assets/129969499/e8c86349-4249-47d1-a9bf-4b409050efc1)
![1710126917121](https://github.com/huiyadanli/RevokeMsgPatcher/assets/129969499/b634cfa8-e813-4dba-a7ff-897d822ab4d2)

**Comment by Yu-Code666** [comment]
请问有解决办法了嘛

**Comment by paradiseTT** [comment]
我还在等

**Comment by 17726** [comment]
+1我也是

**Comment by regan79** [comment]
+1我也是

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
