### ISSUE TITLE
[未支持版本]: 9.9.7-21804

### ISSUE THREAD

**Issue by Andy0604** [huiyadanli/RevokeMsgPatcher#692]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

9.9.7-21804

### 对应版本的下载地址

qq里面自动检测更新的

### 软件提示了什么？

什么也没提示  防撤回也没生效

**Comment by John-Y-Wilson** [comment]
同微信9.9.7-21804,安装后没有效果.

**Comment by Hillter** [comment]
实测确实没用了， 啥时候能更新啊
