### ISSUE TITLE
3.9.10版本微信似乎已经重新支持带提示的防撤回

### ISSUE THREAD

**Issue by bootlegseahorse** [huiyadanli/RevokeMsgPatcher#693]
![截屏 微信_QQ_TIM防撤回补丁 v1 7 2024-3-14 (300)](https://github.com/huiyadanli/RevokeMsgPatcher/assets/97839352/90f2ce9b-b7e5-4016-bd5c-ef6a41fb51da)
![截屏 微信电脑版更新 2024-3-14 (299)](https://github.com/huiyadanli/RevokeMsgPatcher/assets/97839352/884e705a-c90b-457e-b0b3-d7839eb9cc91)

3.9.9还不行，3.9.10突然恢复支持了？不是真正的issue，但可喜可贺吧应该说是。

**Comment by huiyadanli** [comment]
3.9.9.43 开始支持的，具体看置顶issue
