### ISSUE TITLE
PC端部署防撤回后，同步手机消息后消息丢失

### ISSUE THREAD

**Issue by Contractscheng** [huiyadanli/RevokeMsgPatcher#695]
手机微信聊天消息，在PC端微信登录的时候会同步至PC端，安装完防撤回补丁后，PC端同步消息会和手机端有差异，PC端缺少一部分消息，，

**Comment by huiyadanli** [comment]
看上去和补丁无关

**Comment by Contractscheng** [comment]
> 从你的描述来看和补丁无关

我想逻辑也是这样，，但是我把补丁拿掉之后，，这个情况就消失了，，

**Comment by Contractscheng** [comment]
> > 从你的描述来看和补丁无关
> 
> 我想逻辑也是这样，，但是我把补丁拿掉之后，，这个情况就消失了，，

我可以再描述一下，有补丁的情况下，PC端登录同步手机的微信消息，会有部分消息丢失，，没有补丁，PC端登录就和手机端的消息是同步的，，  重装新版微信和重装补丁，我这边测试过，，不知道是不是个例

**Comment by supernova4869** [comment]
有没有可能你有很多电脑，同步的时候在另一个电脑上，而你测试的时候只专心用一个电脑，所以不会同步丢失

**Comment by YangZhaocool** [comment]
手机微信也装个防撤回
