### ISSUE TITLE
[未支持版本]: 9.9.8-22165

### ISSUE THREAD

**Issue by pdx9257** [huiyadanli/RevokeMsgPatcher#697]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ正式版9.9.8-22165

### 软件提示了什么？

软件识别不到QQ9版本以后的安装目录，安装旧版QQ会强制更新QQ，

**Comment by tagaga** [comment]
啥时候能够支持QQNT？

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
