### ISSUE TITLE
使用这个防撤回会被封吗

### ISSUE THREAD

**Issue by chrjojame** [huiyadanli/RevokeMsgPatcher#698]
这里有说到
![屏幕截图 2024-03-27 145820](https://github.com/huiyadanli/RevokeMsgPatcher/assets/119778455/1165ad02-6c52-4976-b7ab-c1316661c077)
https://www.landiannews.com/archives/103081.html?utm_sources=ourl.co&utm_medium=social&utm_campaign=none

**Comment by huiyadanli** [comment]
自行辨别
