### ISSUE TITLE
怎么关闭防撤回啊

### ISSUE THREAD

**Issue by zhixia-shijian** [huiyadanli/RevokeMsgPatcher#699]
打开防撤回之后不知道怎么**关闭**了
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/140401485/0ade2457-317d-447d-83bf-40427b199d21)

**Comment by huiyadanli** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/df2fcba6-0205-4adb-8537-c97d89cc2e52)

或者覆盖安装微信
