### ISSUE TITLE
[未支持版本]: 微信版本：3.9.10.19

### ISSUE THREAD

**Issue by JIUJIUs** [huiyadanli/RevokeMsgPatcher#705]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版：3.9.10.19

### 软件提示了什么？

防撤回失效了

**Comment by huiyadanli** [comment]
测试时支持的

**Comment by JIUJIUs** [comment]
> 我测试是支持的

DAMN ，我再试下~
