### ISSUE TITLE
防撤回提示位置问题

### ISSUE THREAD

**Issue by zcb321** [huiyadanli/RevokeMsgPatcher#707]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/37659598/08f281c7-131f-4399-b3f1-88df146bb5ff)
如果在撤回之前发送了其他消息，那撤回提醒会显示在最后一条消息之后，无法分辨撤回的具体是那一条信息，建议优化一下

**Comment by huiyadanli** [comment]
当前的原理只能搞破坏，无法做创造

简单的说就是做不到
