### ISSUE TITLE
[未支持版本]: 3.9.10.19

### ISSUE THREAD

**Issue by L4v3nder** [huiyadanli/RevokeMsgPatcher#708]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.9.10.19

### 软件提示了什么？

新老防撤回都能正常安装，但无法防撤回

**Comment by 838104105** [comment]
支持的，需要手动调整微信安装路径，因为这个版本微信安装路径改了

**Comment by TDD404** [comment]
> 支持的，需要手动调整微信安装路径，因为这个版本微信安装路径改了

请问在哪个路径下呢，我这边显示没有变化安装路径

**Comment by L4v3nder** [comment]
路径没问题，手动选择路径就好了
