### ISSUE TITLE
微信多开功能使用背景问题

### ISSUE THREAD

**Issue by BananaMan666** [huiyadanli/RevokeMsgPatcher#713]
想要在pc端登录的微信a和b是不是要在两部手机上都登录，才能在一个pc上实现微信多开？手机微信app切换登录两个微信，虽然开了多开功能，但是仍然会自动退出切换失效的那个微信。

**Comment by YangZhaocool** [comment]
微信app切换登录两个微信 实际被你切换掉的已经掉了
如果你没有两个手机 你就在手机上安装微信多开 
github都能正常评论 怎么安装多开不用我多说了吧

**Comment by BananaMan666** [comment]
是的，拿了俩手机分别登录微信就可以登录了。不过问题来了，多开微信登录有可能会对钉钉产生影响。待我验证一下。

**Comment by YangZhaocool** [comment]
不用那么麻烦 你如果是安卓 就去找多开微信下载
你如果是iOS 就去弄个证书 找多开微信下载 一个手机就可以了

**Comment by huiyadanli** [comment]
我无法处理这个问题
