### ISSUE TITLE
打开软件，无法识别QQ，也无法手动选择QQ路径

### ISSUE THREAD

**Issue by 123qwer123** [huiyadanli/RevokeMsgPatcher#714]
QQ版本：9.9.9.22578 
出现问题：无法自动识别QQ路径，通过手动选择也无法识别QQ应用程序
本机安装的QQ版本如下：
![QQ版本——Snipaste_2024-05-10_17-40-43](https://github.com/huiyadanli/RevokeMsgPatcher/assets/37107690/dae1de48-e745-44c3-9b01-bee012c4ea29)

本机安装QQ路径如下，及无法自动识别QQ路径
![软件路径为null——Snipaste_2024-05-10_17-42-11](https://github.com/huiyadanli/RevokeMsgPatcher/assets/37107690/b364d3bd-6555-4ac8-9642-f5ac6df3fd3c)

手动选择也无法识别QQ应用程序
![手动选择路径找不到应用程序——Snipaste_2024-05-10_17-44-01](https://github.com/huiyadanli/RevokeMsgPatcher/assets/37107690/b62d187e-bcdd-4c3a-8172-5dc946feb1f0)

**Comment by Fllly** [comment]
同现此问题，版本号为 9.9.9.23424

**Comment by ko1004u** [comment]
QQNT版没支持呢

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
