### ISSUE TITLE
[未支持版本]: 微信 3.9.9.34 32位版本

### ISSUE THREAD

**Issue by jianhun9527** [huiyadanli/RevokeMsgPatcher#715]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信 3.9.9.34

### 对应版本的下载地址

https://dldir1.qq.com/weixin/Windows/WeChatSetup_x86.exe

### 软件提示了什么？

特征对比：当前特征码比对数【0】和期望的匹配数【2】不一致

**Comment by 1282814653** [comment]
微信 3.9.10.19 版本  撤回的内容也不显示了  只提醒 对方撤回了信息

**Comment by qq690712575** [comment]
+1

**Comment by cherub0507** [comment]
32位版本好像都不支持

**Comment by cherub0507** [comment]
> 微信 3.9.10.19 版本 撤回的内容也不显示了 只提醒 对方撤回了信息

64位的3.9.10.19的话，这个好使
https://wwl.lanzout.com/iIS7g1w6lg7e    密码: 52pj

**Comment by huiyadanli** [comment]
不再考虑支持32位版本
