### ISSUE TITLE
[未支持版本]:微信3.9.10.19

### ISSUE THREAD

**Issue by chenzhenpeng** [huiyadanli/RevokeMsgPatcher#718]
可以正常安装补丁，但是防撤回失效

**Comment by lalaxiao1258** [comment]
微信3.9.11.3内测版不支持，麻烦作者更新一下，万分感谢

**Comment by Young-people** [comment]
可以正常安装补丁，但是防撤回失效

**Comment by chenzhenpeng** [comment]
微信3.9.10.27已经可以了

**Comment by huiyadanli** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/ad2d6e62-6363-4800-9d03-1ee5a58cdd62)
