### ISSUE TITLE
[未支持版本]: 安装后chrome闪退

### ISSUE THREAD

**Issue by m1m1cat** [huiyadanli/RevokeMsgPatcher#719]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

3.9.10.19

### 对应版本的下载地址

https://github.com/huiyadanli/RevokeMsgPatcher/releases/download/1.7/RevokeMsgPatcher.v1.7.zip

### 软件提示了什么？

安装防撤回后，chrome闪退

**Comment by huiyadanli** [comment]
？？？？

**Comment by m1m1cat** [comment]
不确定，我正在看崩溃日志
