### ISSUE TITLE
微信莫名退出，然后弹框让重登

### ISSUE THREAD

**Issue by HorseXInsectCoder** [huiyadanli/RevokeMsgPatcher#72]
如题。我的微信版本是2.8.0.121

**Comment by huiyadanli** [comment]
我也在用这个版本，没有出现你说的问题。

如果不频繁出现，应该是微信本身的问题

**Comment by huiyadanli** [comment]
个人怀疑是你在微信更新之后使用备份还原功能，然后新版本微信用着老版本DLL可能会出现闪退的问题，重装微信即可
