### ISSUE TITLE
[未支持版本]: 微信3.9.11.7版本不支持，麻烦作者更新一下，万分感谢

### ISSUE THREAD

**Issue by zxx-gu** [huiyadanli/RevokeMsgPatcher#721]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信3.9.11.7

### 对应版本的下载地址

https://pc.weixin.qq.com/

### 软件提示了什么？

特征比对:当前特征码匹配数[1]和期望的匹配数[2]不一致。

**Comment by sun90581737** [comment]
微信3.9.11.7版本不支持，麻烦作者更新一下，谢谢~~

**Comment by huiyadanli** [comment]
**1. 3.9.11.x 多开不支持，已经更新特征码支持，重试即可**
2. 多开不支持的情况下可以使用通用的多开工具，没必要一直等补丁
3. 新老防撤回在 3.9.11.x 下测试均没有问题

另外两周前的微信灰度更新我压根收不到，没包催更也没啥用hhh
