### ISSUE TITLE
[未支持版本]: 微信正式版 3.9.11.8

### ISSUE THREAD

**Issue by yxdym** [huiyadanli/RevokeMsgPatcher#722]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.9.11.8

### 软件提示了什么？

特征比对:当前特征码匹配数[1]和期望的匹配数[2]不一致。
![1](https://github.com/huiyadanli/RevokeMsgPatcher/assets/171526177/9fb5cccd-8344-4e95-9ca5-54d9a1bdbcba)

**Comment by lalaxiao1258** [comment]
是否可以提供下安装包，谢谢！

**Comment by yxdym** [comment]
> 是否可以提供下安装包，谢谢！

微信自己更新的

**Comment by lalaxiao1258** [comment]
> > 是否可以提供下安装包，谢谢！
> 
> 微信自己更新的

好的，感谢

**Comment by huiyadanli** [comment]
**1. 3.9.11.x 多开不支持，已经更新特征码支持，重试即可**
2. 多开不支持的情况下可以使用通用的多开工具，没必要一直等补丁
3. 新老防撤回在 3.9.11.x 下测试均没有问题
