### ISSUE TITLE
[未支持版本]: 3.9.10.27

### ISSUE THREAD

**Issue by pdx9257** [huiyadanli/RevokeMsgPatcher#724]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版3.9.10.27

### 软件提示了什么？

微信自动更新了，然后就多开和撤回都失效了

**Comment by pdx9257** [comment]
![1717558169037](https://github.com/huiyadanli/RevokeMsgPatcher/assets/165118989/46184af9-76f0-4cb7-8e48-656cbf8229a8)

**Comment by pdx9257** [comment]
![1717558208355](https://github.com/huiyadanli/RevokeMsgPatcher/assets/165118989/11bb11ef-a9b4-4535-86a5-c8d121a599ae)

**Comment by huiyadanli** [comment]
你选的路径和你实际运行的微信不一致

**Comment by pdx9257** [comment]
搞定了，不知道为啥，前面安装没把旧版本覆盖，就变成2个微信了，现在删了其中一个就可以用了

**Comment by lalaxiao1258** [comment]
> 搞定了，不知道为啥，前面安装没把旧版本覆盖，就变成2个微信了，现在删了其中一个就可以用了

有没有安装包？
