### ISSUE TITLE
[未支持版本]: 微信正式版 3.9.10.27

### ISSUE THREAD

**Issue by ThekingMX1998** [huiyadanli/RevokeMsgPatcher#725]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版 3.9.10.27

### 对应版本的下载地址

https://d063a3bbc4a807eab7f720e972a2d8d0.dlied1.cdntips.net/dldir1v6.qq.com/weixin/Windows/WeChatSetup.exe

### 软件提示了什么？

開啟wechat後彈出窗口顯示,但功能基本都可以使用
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/79040577/66c0a62a-4027-45a7-941a-85aa276422c6)

**Comment by huiyadanli** [comment]
![8f30c9c2b63ffc7bfb17ac05728d5157](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/5fb507d8-3358-4345-92ce-5cf31897dc62)
支持的，是你微信的问题，建议重新覆盖安装微信
