### ISSUE TITLE
3.9.11.9 不支持

### ISSUE THREAD

**Issue by MarkLily** [huiyadanli/RevokeMsgPatcher#726]
大佬，新版测试版，3.9.11.9新的不支持，但是旧的防撤回可以安装，但是还没试效果！
https://423down.lanzouo.com/itgkb211uwna 下载安装包

**Comment by MarkLily** [comment]
发现了，不勾选前面的多开，后面的旧和新 就可以安装成功！试过了有提示撤回

**Comment by lalaxiao1258** [comment]
> 发现了，不勾选前面的多开，后面的旧和新 就可以安装成功！试过了有提示撤回

多开没发用。期待大佬后续更新

**Comment by huiyadanli** [comment]
**1. 3.9.11.x 多开不支持，已经更新特征码支持，重试即可**
2. 多开不支持的情况下可以使用通用的多开工具，没必要一直等补丁
3. 新老防撤回在 3.9.11.x 下测试均没有问题
