### ISSUE TITLE
不支持QQNT版，无法识别，也无法手动选择QQ路径

### ISSUE THREAD

**Issue by wxs77133338** [huiyadanli/RevokeMsgPatcher#727]
QQ版本：版本: 9.9.11-24568 (64位)
![66e66f9d-2b9e-46fb-8a4a-dcc54d09c484](https://github.com/huiyadanli/RevokeMsgPatcher/assets/149324070/197d53a2-854d-45c8-86fc-385f5ed4fc54)
<img width="379" alt="微信图片_20240609183735" src="https://github.com/huiyadanli/RevokeMsgPatcher/assets/149324070/0cb8d270-ce8f-42a9-a203-21d7c4046b8d">

**Comment by ssboy9527** [comment]
me too @huiyadanli

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
