### ISSUE TITLE
最新版本微信已经无法使用,可以安装补丁,但多开功能未生效

### ISSUE THREAD

**Issue by duzidengdaizz** [huiyadanli/RevokeMsgPatcher#728]
如题..大佬啥时候给更新下.补丁方式提示安装成功,但是无法多开,撤回的时候一直转圈.

**Comment by Jack800109** [comment]
防撤回貌似也不能用了

**Comment by esbylan** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/729#issuecomment-2167361178

**Comment by huiyadanli** [comment]
**1. 3.9.11.x 多开不支持，已经更新特征码支持，重试即可**
2. 多开不支持的情况下可以使用通用的多开工具，没必要一直等补丁
3. 新老防撤回在 3.9.11.x 下测试均没有问题
