### ISSUE TITLE
3.9.11.15不支持了

### ISSUE THREAD

**Issue by xjock** [huiyadanli/RevokeMsgPatcher#729]
3.9.11.15不支持了

**Comment by sofs2005** [comment]
刚刚我升级了也发现了，只有老版防撤回可以打上去，多开和新版防撤回不行

**Comment by aikeqin** [comment]
微信3.9.11.15已不支持防撤回和多开

**Comment by yearnxiao** [comment]
我也遇到了，希望大佬能支持修复

**Comment by you-xn** [comment]
大佬，3.9.11.15版本微信多开不好使了，能麻烦看下吗

**Comment by Yidk12** [comment]
旧版本多开第三个不行，要求更新，更新后发现都不能用了

**Comment by Yidk12** [comment]
> 旧版本多开第三个不行，要求更新，更新后发现都不能用了

已经回退3.9.8.25了，完美解决

**Comment by lalaxiao1258** [comment]
你们上传安装包啊

**Comment by Jasperben** [comment]
这个版本可以用
https://f.ws59.cn/f/ecgo6a07bzh 复制链接到浏览器打开

**Comment by Jasperben** [comment]
> 这个版本可以用
> https://f.ws59.cn/f/ecgo6a07bzh

**Comment by mpfans** [comment]
用新防撤回 ,不勾选多开.. 然后自己用压缩包里面自带的多开助手开就好了

**Comment by esbylan** [comment]
> 用新防撤回 ,不勾选多开.. 然后自己用压缩包里面自带的多开助手开就好了

有效

**Comment by cherub0507** [comment]
多开功能不生效

**Comment by esbylan** [comment]
> 多开功能不生效

你看上面人说的呀，只能先用压缩包那个多开工具了

**Comment by huiyadanli** [comment]
**1. 3.9.11.x 多开不支持，已经更新特征码支持，重试即可**
2. 多开不支持的情况下可以使用通用的多开工具，没必要一直等补丁
3. 新老防撤回在 3.9.11.x 下测试均没有问题

**Comment by zhuyd8414** [comment]
> **1. 3.9.11.x 多开不支持，已经更新特征码支持，重试即可** 2. 多开不支持的情况下可以使用通用的多开工具，没必要一直等补丁 3. 新老防撤回在 3.9.11.x 下测试均没有问题

收到，谢谢大佬指点。
