### ISSUE TITLE
大大大佬！新包不会安装了

### ISSUE THREAD

**Issue by MarkLily** [huiyadanli/RevokeMsgPatcher#732]
---------------------------
警告
---------------------------
LiteLoaderQQNT文件夹不存在，仅安装QQNT去验证补丁
---------------------------
确定   
---------------------------
这个提示过后，然后又弹出安装成功！
最后QQ里面去验证 也是没有看到放撤回的效果。
由于QQNT需要加载软件目录下的 LiteLoaderQQNT，所以请不要在压缩包内直接双击运行本软件！
这句话貌似我没看懂

**Comment by huiyadanli** [comment]
是bug，已经修复

文件下载包已经替换为 1.8.1 版本

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8

**Comment by MarkLily** [comment]
下载下来 提示报毒了 大佬！忽略不

**Comment by huiyadanli** [comment]
忽略，这玩意会报毒？

多引擎查杀就一个没过
https://www.virscan.org/report/af327a6c8d8f088f4b043d02ea395a61a00c444d600541bbe7a4723622728b8b

**Comment by Gavin-zht** [comment]
请问大佬，应该如何使用呢？
我安装了软件，并安装了插件，但是没有看到防撤回的效果啊。
由于QQNT需要加载软件目录下的 LiteLoaderQQNT，所以请不要在压缩包内直接双击运行本软件！ 这句话我有点没看懂，请问应该如何使用呢？
