### ISSUE TITLE
新版防撤回可以防止图片/视频被撤回了吗

### ISSUE THREAD

**Issue by czm708033** [huiyadanli/RevokeMsgPatcher#733]
记得之前有一次弹窗提示说，如果选择新版，图片和视频就无法防撤回。刚才没有找到这个信息，请问现在解决这个问题了吗？或者同时安装新版和老版可以吗？麻烦了。

**Comment by huiyadanli** [comment]
请自行测试

**Comment by lanlan1971** [comment]
亲测，已经支持了
1.9版本配合3.9.12.17微信
![屏幕截图 2024-10-04 104810](https://github.com/user-attachments/assets/204a3d3a-291e-43f3-a908-6f6a742c39e6)
![image](https://github.com/user-attachments/assets/bf7b5a73-1586-400d-a6eb-0a30470e229a)

**Comment by lanlan1971** [comment]
> 记得之前有一次弹窗提示说，如果选择新版，图片和视频就无法防撤回。刚才没有找到这个信息，请问现在解决这个问题了吗？或者同时安装新版和老版可以吗？麻烦了。

可以了
