### ISSUE TITLE
新版微信3.9.11.17补丁打不上

### ISSUE THREAD

**Issue by Johnny-liux** [huiyadanli/RevokeMsgPatcher#734]
![Uploading 1718589668507.jpg…]()
后期会有补丁更新吗？

**Comment by Johnny-liux** [comment]
![Uploading 1718589668507.jpg…]()

**Comment by huiyadanli** [comment]
你的图没传上来

现阶段补丁是支持3.9.11.17的

**Comment by Johnny-liux** [comment]
我重新选择安装目录后，可以了，谢谢！！！！
________________________________
发件人: 辉鸭蛋 ***@***.***>
发送时间: 2024年6月17日 6:45
收件人: huiyadanli/RevokeMsgPatcher ***@***.***>
抄送: Johnny-liux ***@***.***>; Author ***@***.***>
主题: Re: [huiyadanli/RevokeMsgPatcher] 新版微信3.9.11.17补丁打不上 (Issue #734)


你的图没传上来

现阶段补丁是支持3.9.11.17的

―
