### ISSUE TITLE
[未支持版本]: QQ'NT-9.9.11-24815(32位)

### ISSUE THREAD

**Issue by Starbroke** [huiyadanli/RevokeMsgPatcher#737]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQNT 9.9.11-24815(32位)

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.11_240617_x86_01.exe

### 软件提示了什么？

[图片](https://github.com/huiyadanli/RevokeMsgPatcher/assets/51042230/cfdaecb3-38c1-416c-a070-0e7b1c7c2e9c)

**Comment by huiyadanli** [comment]
换64位

**Comment by Starbroke** [comment]
> 换64位

好的，了解
