### ISSUE TITLE
新版本微信无法使用防撤回

### ISSUE THREAD

**Issue by XIAXIACC** [huiyadanli/RevokeMsgPatcher#741]
3.9.11.17版本安装新的补丁之后无法使用防撤回

**Comment by huiyadanli** [comment]
我测试没问题

**Comment by XIAXIACC** [comment]
但是我这边没办法使用了，这个有什么解决办法吗
&nbsp;


叶涵
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月3日(星期三) 上午10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huiyadanli/RevokeMsgPatcher] 新版本微信无法使用防撤回 (Issue #741)















我测试没问题

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***和&gt;

**Comment by huiyadanli** [comment]
你的提问让我无法判断你具体遇到的问题，我只能猜测是微信多版本共存的情况，请参考 #734 。

如何提问？
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15783049/05ba9e93-46d5-46f8-9792-2118db0d6f31)

**Comment by DemosHume** [comment]
微信版本更新有补丁失效的情况，重新安装补丁可能可以解决。

**Comment by ozwalter225** [comment]
检查一下根目录，根目录中很可能有两个版本号的文件夹。

**Comment by klcb2010** [comment]
你说的转圈问题吧？ 不影响
