### ISSUE TITLE
是不是被微信关注了

### ISSUE THREAD

**Issue by safebaseline** [huiyadanli/RevokeMsgPatcher#743]
最近好像微信官方提示登录环境异常了

**Comment by huiyadanli** [comment]
大概率是你本身环境的问题

**Comment by safebaseline** [comment]
有可能，最近在测试不用这个工具看看，目前还没复现


------------------ 原始邮件 ------------------
发件人: 辉鸭蛋 ***@***.***&gt;
发送时间: 2024年7月15日 18:05
收件人: huiyadanli/RevokeMsgPatcher ***@***.***&gt;
抄送: safebaseline ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [huiyadanli/RevokeMsgPatcher] 是不是被微信关注了 (Issue #743)





 
大概率是你本身环境的问题

**Comment by kartyl** [comment]
这个问题感觉有半年了吧，3.9.9和3.9.10都隔几天就提示异常，退回3.9.8一个月了没事

**Comment by bootlegseahorse** [comment]
应该不会，我从来没遇到过

**Comment by xxhhlk** [comment]
我这里是加好友（好像加群也会）时候会掉线、提示“系统环境异常”，要重新登录，不知道大家是不是

**Comment by safebaseline** [comment]
已收到

**Comment by pjy612** [comment]
> 我这里是加好友（好像加群也会）时候会掉线、提示“系统环境异常”，要重新登录，不知道大家是不是

没用远程桌面啥的么？
我只有远程桌面啥的时候 才随机出现这个 ╮(￣▽￣")╭

**Comment by xxhhlk** [comment]
> > 我这里是加好友（好像加群也会）时候会掉线、提示 “系统环境异常”，要重新登录，不知道大家是不是
> 
> 没用远程桌面啥的么？ 我只有远程桌面啥的时候 才随机出现这个 ╮(￣▽￣")╭

用，但是大部分时间是作为主控端，被控时也不会用微信，直接在手机上操作了

**Comment by xxhhlk** [comment]
> 我这里是加好友（好像加群也会）时候会掉线、提示 “系统环境异常”，要重新登录，不知道大家是不是

我把微信扔沙盒里面，半个月没出现过了，供参考。刚放进去要过几天才有效果。也不知道是检测到什么了。
