### ISSUE TITLE
发现似乎有人在用这个软件卖钱，而且连GitHub链接都没去掉

### ISSUE THREAD

**Issue by ohohlev** [huiyadanli/RevokeMsgPatcher#745]
![微信截图_20240710113734](https://github.com/huiyadanli/RevokeMsgPatcher/assets/156192701/135b89c1-4f99-477d-9879-9e7be41e56a9)
网址是https://shop.licran.com/index/detail/168e10f5-c0a9-4993-9fe3-aa6484f68ab5.html

**Comment by huiyadanli** [comment]
界面上已经有开源免费字样了，被倒卖我也很无奈

**Comment by GeniusShiki** [comment]
这种是真恶心啊。

**Comment by 593496637** [comment]
此人的网站与联系方式：https://licran.com/
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15769004/f358c706-ef98-431e-987c-7758ec046bc3)
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15769004/54a9f4c6-af45-4cb2-9b80-d24aa236e124)

**Comment by 593496637** [comment]
![image](https://github.com/huiyadanli/RevokeMsgPatcher/assets/15769004/048443d4-9c65-475f-ab0c-115ae68df267)
