### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by mangojiumu** [huiyadanli/RevokeMsgPatcher#75]
![TIM截图20200221091720](https://user-images.githubusercontent.com/48395727/74995182-18b62900-548b-11ea-88cd-6174e4e1a7d6.png)
Win7 旗舰版 2.7。1.88微信

**Comment by huiyadanli** [comment]
请安装[.NET Framework 4.5](https://www.microsoft.com/zh-cn/download/details.aspx?id=30653) 或者更高版本

**Comment by mangojiumu** [comment]
感谢！
