### ISSUE TITLE
QQNT9.9.12-25765 版本中图片防撤回失效

### ISSUE THREAD

**Issue by Baofen** [huiyadanli/RevokeMsgPatcher#750]
新版qq有个问题，就是如果说你的窗口在一个群上面，那么里面的图是可以防撤回并且可以看见的，但是如果你一旦离开了，那么别人发的图就不会加载，而如果别人在你点回去之前撤回了，虽然显示防撤回但是你依旧看不到发了什么东西。之前的老版本你去别的群聊天，切回来还是可以看到之前撤回的图片的。关于配置我我开了将撤回消息存入数据库，没开防撤回自己的消息，内存缓存1w，清理500，样式配置全开了

**Comment by huiyadanli** [comment]
RevokeMsgPatcher 只是辅助安装了 [LiteLoaderQQNT](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT) 以及 [LiteLoaderQQNT-Anti-Recall](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall) 

具体问题请在对应插件 repo 的 issue 下提问。

个人认为这种情况类似 QQ接到消息时已经被撤回（只接到了撤回的消息），无法看到内容是正常现象，因为你本地从未下载过这张图片，当然无法防撤回。

**Comment by Baofen** [comment]
好的谢谢，在那里已经找到了相同的问题。另外我觉得是新版qq的问题，因为老版qq即使没点开聊天框，对于图片的防撤回也是同样生效的（可能是已经预加载的原因？）
