### ISSUE TITLE
[未支持版本]: 3.9.11.23版本的微信不支持了，可以更新吗

### ISSUE THREAD

**Issue by chenxu-george** [huiyadanli/RevokeMsgPatcher#752]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

正式版3.9.11.23

### 对应版本的下载地址

自动更新的

### 软件提示了什么？

提示安装成功
![微信截图_20240723112752](https://github.com/user-attachments/assets/677ec15d-3dec-4fda-8687-f235debaae4e)
但是防撤回没有效果

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/8dcd75bb-df1d-4c51-8562-6cf40f321b0d)

是不是微信目录下存在多个版本的微信了，需要手动选择下

**Comment by lyhrtb** [comment]
大佬，实测确实功能失效，微信版本3.9.11.25

**Comment by lyhrtb** [comment]
> 大佬，实测确实功能失效，微信版本3.9.11.25

![Uploading 微信截图_20240908213654.png…]()

**Comment by huiyadanli** [comment]
实测有效
