### ISSUE TITLE
新版QQ只有在在线时的撤回才能拦截，有办法能获取到离线时的撤回吗？有考虑新增Mac-QQ的防撤回吗

### ISSUE THREAD

**Issue by Egoista7** [huiyadanli/RevokeMsgPatcher#753]
新版QQ
版本: 9.9.11-24815 (64位)
补丁为1.8最新版本

一、如图所示，因为是Mac+Windows台式的办公分离组合，出门在外的mac是无法看到撤回内容的，但是回到家后的撤回不会像以前一样继续保留了。依稀记得以前的补丁是可以保留离线状态的撤回的。现在能否有其他的解决方法？

二、或者是否有考虑过Mac的QQ防撤回呢？

**Comment by huiyadanli** [comment]
mac自行搜索，有很多的
