### ISSUE TITLE
同步更新 LiteLoaderQQNT 版本

### ISSUE THREAD

**Issue by YttriumWillow** [huiyadanli/RevokeMsgPatcher#756]
目前已有 LiteLoaderQQNT 内核新版本

![图片](https://github.com/user-attachments/assets/7d2b93c3-6c39-41f3-bd5f-b8bd4e63930e)

手动更新是否可以直接替换目录下的 `LiteLoaderQQNT` 文件夹

**Comment by huiyadanli** [comment]
可以直接替换

**Comment by Ruling95** [comment]
还好我先来翻issues了。  不然就提了一个和这个差不多的了。
![image](https://github.com/user-attachments/assets/5ae5562d-9864-40e5-ace4-a43265e68c4c)
新版本解决了。替换掉后。表情正常展示。

**Comment by YttriumWillow** [comment]
我也试了试应该没啥问题。谢谢 :D
