### ISSUE TITLE
QQ找不到路径

### ISSUE THREAD

**Issue by qg89** [huiyadanli/RevokeMsgPatcher#759]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ版本: 9.9.12-25765 (64位)

### 软件提示了什么？
![1722827728669](https://github.com/user-attachments/assets/f9e8fc4e-43bb-48c4-8866-bc0c258e8471)

找不到应用路径，是QQ版本太高了么

**Comment by huiyadanli** [comment]
用1.8版本
