### ISSUE TITLE
新版本QQ未支持

### ISSUE THREAD

**Issue by nextleafzhao** [huiyadanli/RevokeMsgPatcher#76]
如图

![Snipaste_2020-02-22_12-17-45](https://user-images.githubusercontent.com/18350016/75086294-8fc3ee00-556d-11ea-8960-b578f0dfb8fc.png)

QQ版本：9.2.3（26662）
![image](https://user-images.githubusercontent.com/18350016/75086335-dd405b00-556d-11ea-902b-43238fad6bb4.png)

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/75111454-fda70d00-5674-11ea-879b-0e05d2a9321d.png)

我测试没有问题，这个有点奇怪。。。你是不是先点了备份还原？建议重新安装QQ试试

**Comment by wolf-ajson** [comment]
重新应用后可以了，应该是我微信自动更新后dll被覆盖回去，非常感谢
