### ISSUE TITLE
如果qq版本更新过，虽然之前能看到撤回的消息，更新以后是不是看不到了？

### ISSUE THREAD

**Issue by Towards-future** [huiyadanli/RevokeMsgPatcher#760]
如果qq版本更新过，虽然之前能看到撤回的消息，更新以后是不是看不到了？
很久以前装的防撤回插件，当时看到了某条被撤回的消息。qq版本更新以后看不到了，还是显示被撤回。
想问下qq版本更新以后，每次之前防撤回的消息，是不是都看不到了。还是显示撤回。

**Comment by huiyadanli** [comment]
具体看插件功能

**Comment by huiyadanli** [comment]
QQNT 的插件支持设置记录历史撤回信息的，当然前提是你确实收到过这条消息
