### ISSUE TITLE
新版NTQQ的撤回补丁造成截图工具无法使用

### ISSUE THREAD

**Issue by macyoyo** [huiyadanli/RevokeMsgPatcher#762]
如题，以前的版本还行，前几天NTQQ被自动升级了，升到了9.9.12.26466版本x64的，然后发现群截图功能点击后卡死，按下esc退出正常。吧撤回补丁撤销，恢复原版登录截图正常。

**Comment by huiyadanli** [comment]
你可以手动更新 LiteLoaderQQNT  #756

后续程序会加入自动获取最新版本的 LiteLoaderQQNT
