### ISSUE TITLE
建议在软件内注明插件仓库地址和作者说明

### ISSUE THREAD

**Issue by xh321** [huiyadanli/RevokeMsgPatcher#766]
我是QQNT防撤回插件作者，建议在软件界面内注明捆绑插件的仓库地址和作者信息，以便用户直接点击查看原始仓库（同时方便用户直接前往提交issue）。
原因是我有一个朋友跟我说防撤回的问题，他以为防撤回是你做的，不注明容易导致混淆。

**Comment by huiyadanli** [comment]
好的，这就加上

**Comment by huiyadanli** [comment]
新版已添加仓库地址和作者信息 https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.9

感谢你们提供这么好用的插件
