### ISSUE TITLE
QQnt在选择安装路径后始终提示无法找到关键文件。

### ISSUE THREAD

**Issue by raevoioj** [huiyadanli/RevokeMsgPatcher#767]
![image](https://github.com/user-attachments/assets/a100202e-277f-46c2-80d3-8da0fca6988a)
QQnt在选择安装路径后始终提示无法找到关键文件，不论是从9.9.11更新到最新版，还是卸载重装都没用。选择的路径没错，是自定义安装的D:\\qqnt\。

**Comment by OumaWu** [comment]
如图，微信也有同样的问题，更新到3.9.11.25版本后打开防撤回无法查询到安装路径，手动选择后显示无法找到安装文件
![微信图片_20240817062050](https://github.com/user-attachments/assets/5e7423fb-55a1-4e66-a58a-27456bee3486)
![1723846708541](https://github.com/user-attachments/assets/df56b700-9d11-4e56-8c9c-e2d5a092adf4)

**Comment by huiyadanli** [comment]
> ![image](https://private-user-images.githubusercontent.com/132725598/358476728-a100202e-277f-46c2-80d3-8da0fca6988a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTc0NzIsIm5iZiI6MTcyMzg1NzE3MiwicGF0aCI6Ii8xMzI3MjU1OTgvMzU4NDc2NzI4LWExMDAyMDJlLTI3N2YtNDZjMi04MGQzLThkYTBmY2E2OTg4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMTEyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzQwYmY2MWJkNGZjZmEzNjRiNDNhMzgxNTIzMWQ5YTAzYmVjZjczOTA0NjlhYzc3NGMzMTJmZWM0NzBhY2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JX0cLR5kFb7ghA03DyhtruxdXqh60BjJTpTu1VdO9Ak) QQnt在选择安装路径后始终提示无法找到关键文件，不论是从9.9.11更新到最新版，还是卸载重装都没用。选择的路径没错，是自定义安装的D:\qqnt\。

请确保 D:\qqnt\QQ.exe存在

**Comment by raevoioj** [comment]
> > ![image](https://private-user-images.githubusercontent.com/132725598/358476728-a100202e-277f-46c2-80d3-8da0fca6988a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTc0NzIsIm5iZiI6MTcyMzg1NzE3MiwicGF0aCI6Ii8xMzI3MjU1OTgvMzU4NDc2NzI4LWExMDAyMDJlLTI3N2YtNDZjMi04MGQzLThkYTBmY2E2OTg4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMTEyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzQwYmY2MWJkNGZjZmEzNjRiNDNhMzgxNTIzMWQ5YTAzYmVjZjczOTA0NjlhYzc3NGMzMTJmZWM0NzBhY2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JX0cLR5kFb7ghA03DyhtruxdXqh60BjJTpTu1VdO9Ak) QQnt在选择安装路径后始终提示无法找到关键文件，不论是从9.9.11更新到最新版，还是卸载重装都没用。选择的路径没错，是自定义安装的D:\qqnt\。
> 
> 请确保 D:\qqnt\QQ.exe存在

![image](https://github.com/user-attachments/assets/73096fff-322b-40bf-ad68-c54296ef58a2)
存在的

**Comment by huiyadanli** [comment]
请使用1.8版本，1.7版本不支持QQNT

https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8

另外注意1.8版本自带的 [LiteLoaderQQNT](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT) 需要自行更新到最新版本

**Comment by raevoioj** [comment]
> 请使用1.8版本，1.7版本不支持QQNT
> 
> https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
> 
> 另外注意1.8版本自带的 [LiteLoaderQQNT](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT) 需要自行更新到最新版本

解决了。大佬code页“点我下载最新版本”链接仍然是1.7版本，下载完没注意版本号

**Comment by huiyadanli** [comment]
因为1.8版本还有些问题，没彻底放出去
