### ISSUE TITLE
微信推出新版本，放撤回已失效

### ISSUE THREAD

**Issue by wolf-ajson** [huiyadanli/RevokeMsgPatcher#77]
微信近期更新了2.8.0.121版本，原有0.8版本插件已失效，请求更新新版本

**Comment by huiyadanli** [comment]
0.8版本支持微信的最新版本 #74

**Comment by wolf-ajson** [comment]
> 0.8版本支持微信的最新版本 #74
> 
> 如果出现类似 #76 的提示，你是否在微信更新后点击了备份还原？

重新应用后可以了，应该是我微信自动更新后dll被覆盖回去，非常感谢

**Comment by huiyadanli** [comment]
每次更新以后都要重新打补丁。。
