### ISSUE TITLE
重新登陆qqnt后，防撤回的消息就不再显示了

### ISSUE THREAD

**Issue by SakuraSora** [huiyadanli/RevokeMsgPatcher#771]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQNT9.9.11-24815 (64位)

### 软件提示了什么？

如题，在重新登陆QQNT之后，之前被防止撤回的消息全都无法显示，取而代之的是“对方撤回了一条消息”

**Comment by bootlegseahorse** [comment]
设置里有是否保存撤回消息，自己找找就行

**Comment by huiyadanli** [comment]
这个是插件的能力，我只是直接自带了别人的插件，请自行设置 https://github.com/xh321/LiteLoaderQQNT-Anti-Recall
