### ISSUE TITLE
[未支持版本]: QQ 9.9.15.27333

### ISSUE THREAD

**Issue by gdd111** [huiyadanli/RevokeMsgPatcher#772]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ 9.9.15.27333

### 软件提示了什么？
win7系统，刚下了最新的QQ，
![image](https://github.com/user-attachments/assets/e6bb8fd1-4734-448f-b210-fb95cce7c693)

**Comment by bootlegseahorse** [comment]
这个是LiteQQNT的问题，暂时无法解决，建议回滚9.9.12

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/396
