### ISSUE TITLE
无法自动搜索路径也没有办法识别路径中的软件

### ISSUE THREAD

**Issue by Tigee-postmodernist-version** [huiyadanli/RevokeMsgPatcher#773]
![17f19d12d8cd8c06b1937f31a39c8b5c](https://github.com/user-attachments/assets/01877ef2-1a03-45a0-aeaf-77c239a47e9f)
如图为qq目前版本
![image](https://github.com/user-attachments/assets/e840c964-fea4-428e-83f5-a7078e12ccb5)
无法自动识别路径
![image](https://github.com/user-attachments/assets/429182ad-a44e-4b2c-a2fd-462fd2426547)
手动添加
![image](https://github.com/user-attachments/assets/5c05ecd3-1842-41be-85c4-904e7975bc52)
出现错误
望大佬给出解决方案！非常感谢

**Comment by huiyadanli** [comment]
请使用1.8版本

**Comment by Tigee-postmodernist-version** [comment]
问题已经解决，不过希望作者可以更新主页的下载连接，readme中的最新版本的下载连接仍然为1.8，具有误导性
