### ISSUE TITLE
QQNT使用防撤回后，截图功能失效

### ISSUE THREAD

**Issue by Lyq1668** [huiyadanli/RevokeMsgPatcher#774]

**Comment by huiyadanli** [comment]
自行更新 [LiteLoaderQQNT](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT) 插件即可

**Comment by nidonglin** [comment]
> 自行更新 [LiteLoaderQQNT](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT) 插件即可

怎么更新啊？我把LiteLoaderQQNT源码覆盖不行呢

**Comment by qinfen180** [comment]
我也遇到了，把这个zip解压替换上去就可以了。
[LiteLoaderQQNT.zip](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/releases/download/1.2.1/LiteLoaderQQNT.zip)

**Comment by Lyq1668** [comment]
谢谢指点啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月23日 11:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [huiyadanli/RevokeMsgPatcher] QQNT使用防撤回后，截图功能失效 (Issue #774) |

我也遇到了，把这个zip解压替换上去就可以了。
LiteLoaderQQNT.zip
