### ISSUE TITLE
QQNT 9.9.15-26909 (64位)图片和视频撤回后无法显示

### ISSUE THREAD

**Issue by nidonglin** [huiyadanli/RevokeMsgPatcher#775]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQNT 9.9.15-26909

### 软件提示了什么？

文字和表情都可以防撤回成功，但是图片只有在当前对话框并显示过接收图片后才可以防撤回，如果当前不在这个此对话框未看到过图片则无法接收到撤回的图片

**Comment by Ruling95** [comment]
版本: 9.9.12-25765 (64位)   也是一样的。  消息撤回前，未打开对应的对话框。  等打开对话框时，就只显示一图裂信息。

**Comment by huiyadanli** [comment]
这是插件方相关问题，可以在 https://github.com/xh321/LiteLoaderQQNT-Anti-Recall 这边提问。

我只是安装了  LiteLoaderQQNT 和相关插件
