### ISSUE TITLE
提示特征码不一致怎么解决啊

### ISSUE THREAD

**Issue by haydenyip** [huiyadanli/RevokeMsgPatcher#776]
![6800a29ce32be5f1c619b626fa878e01](https://github.com/user-attachments/assets/983d7831-8504-464e-8727-5ef0fb64bc35)
z之前没有下载过类似的插件 但是现在提示这个 不太理解

**Comment by huiyadanli** [comment]
请使用  https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.8
