### ISSUE TITLE
[未支持版本]: QQNT 9.9.15.28060

### ISSUE THREAD

**Issue by KATAFANG** [huiyadanli/RevokeMsgPatcher#779]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [x] 我确认当前使用的是最新版

### 微信/QQ 版本

QQNT 9.9.15.28060

### 对应版本的下载地址

https://im.qq.com/pcqq/index.shtml

### 软件提示了什么？

![image](https://github.com/user-attachments/assets/479d504c-ec17-4f6f-83b3-68570ef3999f)

**Comment by FLYFLY0** [comment]
一样

**Comment by MarkLily** [comment]
我也提示这样

**Comment by heeroyuyj** [comment]
same isuess here

**Comment by duoremi** [comment]
一样

**Comment by betterdoitnow** [comment]
一样的问题

**Comment by KellyWasTaken** [comment]
我这里也是

**Comment by heeroyuyj** [comment]
手动更新 LiteLoaderQQNT 到最新版了, 还是不支持

**Comment by huiyadanli** [comment]
我直接使用了 [LiteLoaderQQNT-PatcherNFixer](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer) 的修补方式。

等待 LiteLoaderQQNT 相关更新吧，我这边也会跟进

**Comment by BHBhh** [comment]
期待更新，今天手欠更新了QQ新版本，防撤回失效了。

**Comment by as88866920** [comment]
> 我直接使用了 [LiteLoaderQQNT-PatcherNFixer](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer) 的修补方式。
> 
> 等待 LiteLoaderQQNT 相关更新吧，我这边也会跟进

2Q版本:9.9.15.28131不能修复
![Uploading 微信截图_20240923165026.png…]()

**Comment by huiyadanli** [comment]
1.9 版本已经更新相关支持 https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.9

**Comment by supernova4869** [comment]
喜报！终于更新了！

**Comment by dmarkdmark** [comment]
> 1.9 版本已经更新相关支持 https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.9

芜湖，赶紧抛弃老板QQ，去QQ官网下最新版QQNT去，用1.9体验下

**Comment by wzgrx** [comment]
安装 LiteLoaderQQNT 时出现异常:mscorlib
在System.Collections.Comparer.Compare(Object a, Object b)在System.Collections.Generic.ObjectComparer1.Compare(T x,T y)在System.Ling.EnumerableSorter2.CompareKeys(Int32 index1, Int32index2)
在System.Ling.EnumerableSorter`1.QuickSort(Int32l] map, Int32 left, Int32right)
在System.Ling.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)在System.Ling.OrderedEnumerable`1.<GetEnumerator>d 1.MoveNext()在System.Ling.Enumerable.FirstOrDefault[TSource](lEnumerable~1 source)在RevokeMsgPatcher.Forms.FormLiteLoaderQQNT.GetAppPath(StringinstallPath)在RevokeMsgPatcher.Forms.FormLiteLoaderQQNT.btnPath Click(Objectsender, EventArgs e)
必须至少有一个对象实现 IComparable。
