### ISSUE TITLE
[未支持版本]: QQ NT 9.9.15-28131

### ISSUE THREAD

**Issue by HuangSmith** [huiyadanli/RevokeMsgPatcher#781]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ NT（正式版） 9.9.15.28131

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.15_240919_x64_01.exe

### 软件提示了什么？

打开程序-选择QQNT-安装
![image](https://github.com/user-attachments/assets/4f9aaa14-d025-4896-bdea-1f1d2f4875ba)
![image](https://github.com/user-attachments/assets/8e9f8d51-268b-42e1-b5a8-929e61784930)

**Comment by fomodj** [comment]
所遇相同，盼望适配

**Comment by zcqzcq** [comment]
qqnt有别的可用

**Comment by hand50** [comment]
> qqnt有别的可用

请问是哪个版本？用哪个渠道下的啊？现在用QQ官网下版本的是版本是9.9.15-28327 (64位)

**Comment by Itzamana** [comment]
> > qqnt有别的可用
> 
> 请问是哪个版本？用哪个渠道下的啊？现在用QQ官网下版本的是版本是9.9.15-28327 (64位)

补丁等更新，这几天先用旧版吧，27597可以正常用

**Comment by hand50** [comment]
谢谢
&nbsp;


飞鸿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月26日(星期四) 晚上8:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huiyadanli/RevokeMsgPatcher] [未支持版本]: QQ NT 9.9.15-28131 (Issue #781)














   
qqnt有别的可用
  
请问是哪个版本？用哪个渠道下的啊？现在用QQ官网下版本的是版本是9.9.15-28327 (64位)
  
补丁等更新，这几天先用旧版吧，27597可以正常用

**Comment by bin20941314** [comment]
> > qqnt有别的可用
> 
> 请问是哪个版本？用哪个渠道下的啊？现在用QQ官网下版本的是版本是9.9.15-28327 (64位)

https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.10_240520_x64_01.exe,亲测可以

**Comment by hand50** [comment]
可以了，谢谢分享

**Comment by hand50** [comment]
谢谢
&nbsp;


飞鸿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月27日(星期五) 下午5:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huiyadanli/RevokeMsgPatcher] [未支持版本]: QQ NT 9.9.15-28131 (Issue #781)














   
qqnt有别的可用
  
请问是哪个版本？用哪个渠道下的啊？现在用QQ官网下版本的是版本是9.9.15-28327 (64位)
  
https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.10_240520_x64_01.exe
 亲测，可以

**Comment by nickzhang1102** [comment]
用了别的，可以了
![Uploading 8ccac272-8198-427c-a613-0d328bde1744.png…]()

**Comment by nickzhang1102** [comment]
![8ccac272-8198-427c-a613-0d328bde1744](https://github.com/user-attachments/assets/c3eacc74-4a75-4c62-832f-695caad64f36)
用了别的可以了

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/779
