### ISSUE TITLE
【BUG】release1.8版本同时勾选下述方框的内容，点击安装补丁，点击取消，后没有安装按钮

### ISSUE THREAD

**Issue by idle147** [huiyadanli/RevokeMsgPatcher#782]
# 复现流程
![image](https://github.com/user-attachments/assets/a48bbd3e-e258-4339-8a84-655cae965184)
![image](https://github.com/user-attachments/assets/3c4eb466-6d46-4a80-8259-a3d60656f658)
![image](https://github.com/user-attachments/assets/3f552f92-2cd7-4289-b27f-a41d8bf18aeb)

# 原因推测
返回后按钮状态没有更新

**Comment by huiyadanli** [comment]
感谢如此详细的复现流程，确实没更新按钮状态
