### ISSUE TITLE
[未支持版本]: 特征对比不一致

### ISSUE THREAD

**Issue by TokisakiKuru3** [huiyadanli/RevokeMsgPatcher#784]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ9版本: 9.9.15-28060 (64位)

### 软件提示了什么？

![f5a61a4ccf497d046bcbc41dcc920842](https://github.com/user-attachments/assets/454783bd-009c-4b05-bb50-4292bc695c12)

**Comment by huiyadanli** [comment]
#779
