### ISSUE TITLE
最新QQNT版本支持吗

### ISSUE THREAD

**Issue by dmarkdmark** [huiyadanli/RevokeMsgPatcher#786]
我用的最新QQNT版本，用RevokeMsgPatcher提示我找不到路径
害的我直接找9.7.23（29392）这个版本用了
用NT的用惯了，用原来的有点不适应
再次希望大佬能RevokeMsgPatcher支持最新版的NT的QQ

PS：

QQ已扫码登录过，已退出

QQ版本

![Clip_2024-09-25_15-13-26](https://github.com/user-attachments/assets/5f79abbb-7c04-47dc-a08d-430f871299f5)

启动RevokeMsgPatcher

![Clip_2024-09-25_15-14-54](https://github.com/user-attachments/assets/be1b1abd-626a-40d1-b376-276bab90a5d4)

管理员运行，选QQ

![Clip_2024-09-25_15-16-15](https://github.com/user-attachments/assets/0a9e36b7-b0fe-4b64-818d-4878e067ec3c)

我自己选QQNT路径

![Clip_2024-09-25_15-17-12](https://github.com/user-attachments/assets/5596c974-8483-4e20-822a-e1000907e66e)

**Comment by wbsds** [comment]
下载最新版1.8

**Comment by dmarkdmark** [comment]
> 下载最新版1.8
> 
> 下载最新版1.8

![Clip_2024-09-26_11-12-48](https://github.com/user-attachments/assets/9cda1b18-5316-4752-b3ed-3f21ef71478c)
1.8在哪，我点这里只有1.7

**Comment by huiyadanli** [comment]
最新版本又不支持了，1.8只能在release下载

https://github.com/huiyadanli/RevokeMsgPatcher/releases

**Comment by as88866920** [comment]
> 最新版本又不支持了，1.8只能在release下载
> 
> https://github.com/huiyadanli/RevokeMsgPatcher/releases

好像是路径变了，所也你这个不能用了

**Comment by huiyadanli** [comment]
已支持 https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.9

README.md 由于1.8版本不完善所以一直没更新
