### ISSUE TITLE
我更新了版本之后运行就报这个错误怎么办解决呀

### ISSUE THREAD

**Issue by Nexolanta** [huiyadanli/RevokeMsgPatcher#787]
![image](https://github.com/user-attachments/assets/b95243cb-df0d-47a9-b420-b1004ffac752)

**Comment by HyggeBo7** [comment]
+1 我也是哎

**Comment by huiyadanli** [comment]
使用 https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.9 版本
