### ISSUE TITLE
[未支持版本]: 9.9.15_240925

### ISSUE THREAD

**Issue by yiborui** [huiyadanli/RevokeMsgPatcher#790]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

QQ正式版9.9.15_240925

### 对应版本的下载地址

https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.15_240925_x64_01.exe

### 软件提示了什么？

当前特征码匹配数[0]和期望的匹配数[1]不一致
![s](https://github.com/user-attachments/assets/897d6b1d-6330-453c-87cb-b7dc5d5ffbb9)

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/issues/779
