### ISSUE TITLE
[未支持版本]: 9.9.15-28327 (64位)

### ISSUE THREAD

**Issue by supernova4869** [huiyadanli/RevokeMsgPatcher#792]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

9.9.15-28327 (64位)

### 对应版本的下载地址

https://github.com/huiyadanli/RevokeMsgPatcher/releases/download/1.9/RevokeMsgPatcher.v1.9.zip

### 软件提示了什么？

安装补丁后，手机端测试撤回，电脑端无法拦截
![image](https://github.com/user-attachments/assets/59cf0590-3c22-4310-9881-04024c1df5b2)

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/3bb7b9c3-e956-4315-bdc6-861faeefae6c)
