### ISSUE TITLE
显示安装成功，却没显示

### ISSUE THREAD

**Issue by hand50** [huiyadanli/RevokeMsgPatcher#793]
![image](https://github.com/user-attachments/assets/fee8dc98-6b0e-4c41-a274-67e8d911b46f)
![image](https://github.com/user-attachments/assets/520c0645-9aea-4205-a1ce-845c4f9623c3)

**Comment by hand50** [comment]
![image](https://github.com/user-attachments/assets/f6db9cb8-953e-4370-9c2a-a75b8c63b76a)
版本是官网下的最新版，求助

**Comment by huiyadanli** [comment]
看下 QQNT 安装目录下的 `QQNT\versions\` 文件夹内是否存在多个版本

**Comment by hand50** [comment]
![image](https://github.com/user-attachments/assets/a2c850cb-e189-4359-bc38-94f2753ef8c0)
****

**Comment by hand50** [comment]
好像没有

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/2174f893-fa8c-4643-9454-30393534da02)

本质是将红框内容进行了自动化操作，逐一检查即可

**Comment by hand50** [comment]
![image](https://github.com/user-attachments/assets/1a35ef43-cbec-4553-b409-34dae08cacfc)
![image](https://github.com/user-attachments/assets/c9f7555e-fca8-457e-97fa-1418db2766f9)

**Comment by hand50** [comment]
![image](https://github.com/user-attachments/assets/a5b008b5-cbbb-4558-916c-d53dfd840adf)

**Comment by hand50** [comment]
![image](https://github.com/user-attachments/assets/86c385f7-9619-4465-8dd6-b821ac715a9d)

**Comment by hand50** [comment]
请问问题在哪儿？

**Comment by huiyadanli** [comment]
不是让你自己修改，很明显你安装的QQ位置和你现在的QQ位置不是一个

**Comment by hand50** [comment]
![image](https://github.com/user-attachments/assets/760cce0c-0355-4bd8-97e3-5247b42ceadc)
请问这个不是一个位置吗？我是自定义到E盘，设置的文件夹名是QQNT

**Comment by hand50** [comment]
我把我自己改的都还原了，虽然能正常打开，但还是设置界面依旧没有插件的内容

**Comment by huiyadanli** [comment]
奥，是一个，关键文件已经写入了。

![image](https://github.com/user-attachments/assets/97122e56-4d25-42b9-b7d5-18db95a69fc9)

你既然直接手动修改了就自己手动到底吧

![image](https://github.com/user-attachments/assets/713add6f-1329-4ca0-bad0-2e3a13197efa)

左边括号写成了中文括号，右边缺失括号

**Comment by hand50** [comment]
![image](https://github.com/user-attachments/assets/cf64288e-30fb-4bf6-9ece-3311b9bcc5ee)

**Comment by huiyadanli** [comment]
https://liteloaderqqnt.github.io/guide/install.html

**Comment by lieincode** [comment]
<img width="249" alt="Snipaste_2024-10-05_01-18-29" src="https://github.com/user-attachments/assets/35181f32-0d62-4332-8709-64473fce935b">

不知道问题有没有解决，我是全程看着官网发的链接做的，结果也是安装成功没反应

**Comment by lieincode** [comment]
<img width="988" alt="Snipaste_2024-10-05_01-16-13" src="https://github.com/user-attachments/assets/ca1e2db5-3013-47f0-9e76-736e87cc1d58">
