### ISSUE TITLE
安装成功了，但是好像防撤回没有生效。

### ISSUE THREAD

**Issue by 9bugaosu1** [huiyadanli/RevokeMsgPatcher#794]
![image](https://github.com/user-attachments/assets/0c31eed8-fe75-40e9-86b7-a4ea2215ef84)
![image](https://github.com/user-attachments/assets/7cf5a7a3-7be3-4cd6-ac45-ed29f15f4787)
![image](https://github.com/user-attachments/assets/0182a754-5c1c-4e6c-bef6-c36943a1e69c)

**Comment by huiyadanli** [comment]
安装成功的情况下，这个问题需要去 https://github.com/xh321/LiteLoaderQQNT-Anti-Recall 提问

**Comment by 9bugaosu1** [comment]
> 安装成功的情况下，这个问题需要去 https://github.com/xh321/LiteLoaderQQNT-Anti-Recall 提问

好的 谢谢。
