### ISSUE TITLE
QQNT可有闪图保存功能，今天看群，有个撤回的图片裂开了，一看就是闪图

### ISSUE THREAD

**Issue by dmarkdmark** [huiyadanli/RevokeMsgPatcher#795]
![Clip_2024-09-30_10-27-10](https://github.com/user-attachments/assets/17b9401b-6c6f-40da-96dd-7f59d5b78868)

**Comment by huiyadanli** [comment]
请在 https://github.com/xh321/LiteLoaderQQNT-Anti-Recall 相关仓库提问
