### ISSUE TITLE
关于v1.9LiteLoaderQQ安装器被拒绝访问

### ISSUE THREAD

**Issue by user-newfiles** [huiyadanli/RevokeMsgPatcher#796]
![image](https://github.com/user-attachments/assets/9e51f0ca-317d-44ff-a829-a774b090bcc0)

我尝试过使用提权工具，仍然拒绝访问。

**Comment by NAGATOYUKl** [comment]
复现，用1.8的正常。在1.8还原后安装1.9依旧失效。

**Comment by user-newfiles** [comment]
> 复现，用1.8的正常。在1.8还原后安装1.9依旧失效。

那我应该怎么做呢？

**Comment by huiyadanli** [comment]
关闭QQNT后重试
