### ISSUE TITLE
微信使用BUG

### ISSUE THREAD

**Issue by chun32101** [huiyadanli/RevokeMsgPatcher#797]
将任务栏处的微信窗口关闭后（不是退出），再次点击任务栏的微信
<img width="188" alt="6ea42126b58813884a52916fa80e9a8" src="https://github.com/user-attachments/assets/02704e41-177a-42b5-9317-3af80c25805a">
出现的是登录界面而不是微信的聊天界面

**Comment by chun32101** [comment]
<img width="1248" alt="98f2861dd99bc7fdf05a3e799ae3d44" src="https://github.com/user-attachments/assets/1d150080-29e4-434f-876a-b6b2111f774c">

**Comment by huiyadanli** [comment]
别安装多开就行

**Comment by chun32101** [comment]
这个多开安装后如何卸载呀

**Comment by huiyadanli** [comment]
备份还原
