### ISSUE TITLE
撤回提示正常显示，能不能增加一个对内容的引用？

### ISSUE THREAD

**Issue by xinxinenjoy** [huiyadanli/RevokeMsgPatcher#799]
群聊的时候会弹出来撤回提示，但不知道具体是哪条信息被撤回了，回复了不该回复的信息就很尴尬

**Comment by huiyadanli** [comment]
微信当前方式做不到

**Comment by suibianlook** [comment]
> 微信当前方式做不到

在3.7.5.23版本中可以实现这个功能，今天自动更新了最新版本3.9.12.17版本后就不能了，是微信修改了代码的原因吗，希望作者能回复下，如何可以实现的话，我就等等，要不然就退版本回去了（3.7.5.23版本群聊撤回信息会在那条信息下显示两次撤回 特别显眼，能快速看到是哪一条撤回hhh）
