### ISSUE TITLE
希望添加多开功能

### ISSUE THREAD

**Issue by niluanxy** [huiyadanli/RevokeMsgPatcher#8]
如果能再集成个多开功能就好了，另外撤回如果加个提示就完美了

**Comment by twolier** [comment]
> 如果能再集成个多开功能就好了，另外撤回如果加个提示就完美了

多开很简单啊
到安装目录执行 start WeChat.exe&WeChat.exe
想开几个追加 WeChat.exe

**Comment by huiyadanli** [comment]
新版本已经开始支持多开
