### ISSUE TITLE
建议将撤回的消息发送到文件传输助手, 不然找起来停费时间的

### ISSUE THREAD

**Issue by JayaHuang** [huiyadanli/RevokeMsgPatcher#80]
当前的功能虽然挺好.  但如果没有留意微信消息, 是不知道有什么消息撤回了. 所以建议将所有的撤回消息都发送到自己的文件传输助手, 这样就一目了然了. 是哪个群的谁谁谁, 撤回了什么内容

**Comment by KermitLee** [comment]
有保留撤回的消息吗？我怎么找不到对方撤回的内容

**Comment by huiyadanli** [comment]
想法很好，但是臣妾做不到 😂

**Comment by hideonbush-cell** [comment]
hhhhhhhhhhh想法很美好

**Comment by fsnhljz** [comment]
Mac版的可以做到呀，是什么原因做不到呢？
