### ISSUE TITLE
好久没启动QQNT，今天启动发现无法启动

### ISSUE THREAD

**Issue by dmarkdmark** [huiyadanli/RevokeMsgPatcher#800]
![Clip_2024-10-05_21-52-56](https://github.com/user-attachments/assets/0df7f78a-bb49-4ad2-8525-f4f3d288929a)

![Clip_2024-10-05_21-55-35](https://github.com/user-attachments/assets/aac935d0-eb5f-4f9e-a606-4913a15dc5e7)

启动桌面QQNT

![Clip_2024-10-05_21-56-22](https://github.com/user-attachments/assets/c5df28fc-7a1f-4609-8504-d0bf9b3cea86)

PS：之前好像发了个PDF文件给一个新添加的QQ好友，然后直接退出

今天来启动QQNT，发现有问题了

**Comment by dmarkdmark** [comment]
备份还原也不行，不是干嘛了

**Comment by huiyadanli** [comment]
关闭QQNT后重新安装补丁

**Comment by dmarkdmark** [comment]
> 关闭QQNT后重新安装补丁
> 
> 关闭QQNT后重新安装补丁

奥利给，把QQ进程给关了，然后重新运行下，又好了
