### ISSUE TITLE
[未支持版本]: 不支持的文件：名称 QQ.exe 版本 9.9.15.28418！

### ISSUE THREAD

**Issue by iTanken** [huiyadanli/RevokeMsgPatcher#801]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

- QQNT 正式版 9.9.15-28327 (64位)
- QQNT 正式版 9.9.15-28418 (64位)

### 软件提示了什么？

- 不支持的文件：名称 QQ.exe 版本 9.9.15.28327！
- 不支持的文件：名称 QQ.exe 版本 9.9.15.28418！

**Comment by huiyadanli** [comment]
请使用1.9版本

**Comment by iTanken** [comment]
> 请使用1.9版本

![image](https://github.com/user-attachments/assets/4a127893-d235-4d51-bf1f-e2b86efb880d)
![image](https://github.com/user-attachments/assets/d6dff4c2-20e4-4f29-b13d-4bc00330c905)

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/55174ebd-507e-430a-8384-e7a1a6158faa)

安装器安装

**Comment by wenhuang0913** [comment]
![微信图片_20241009134905](https://github.com/user-attachments/assets/4372ad58-b699-4e02-a238-0c5bd8ba36f1)
还是不好使呢？
