### ISSUE TITLE
Windows 微信 3.9.12.15版本，更新1.9版本防撤回后，防撤回功能无法生效。请问下要怎么解决？

### ISSUE THREAD

**Issue by March689** [huiyadanli/RevokeMsgPatcher#802]
![image](https://github.com/user-attachments/assets/c4ed19dd-581e-43c3-8376-88ecba1ce769)
![微信图片_20241008100234](https://github.com/user-attachments/assets/7d1eb314-2e76-4e1d-b03c-17d3a0d8b13e)

**Comment by mrjeye** [comment]
官网下载最新版本微信重装后再安装补丁即可

**Comment by fsxde** [comment]
官网下了3.9.12.16版本的，还是安装不起来防撤回
![image](https://github.com/user-attachments/assets/899b1bda-f25f-4740-806d-5910bd4e8b3e)

**Comment by fsxde** [comment]
> 官网下了3.9.12.16版本的，还是安装不起来防撤回 
![image](https://github.com/user-attachments/assets/6a28929f-3dce-4572-bdf2-b03781151cbe)
