### ISSUE TITLE
[未支持版本]: 3.9.12.16 32位版本

### ISSUE THREAD

**Issue by fsxde** [huiyadanli/RevokeMsgPatcher#803]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信32位正式版3.9.12.16

### 对应版本的下载地址

https://dldir1v6.qq.com/weixin/Windows/WeChatSetup_x86.exe

### 软件提示了什么？

卸载了。重装在D盘还是一样![image](https://github.com/user-attachments/assets/3eebdf85-d21b-400d-ade6-53f992fa7569)

**Comment by fsxde** [comment]
另一台电脑64位版本的自动更新微信后可以安装补丁

**Comment by ZW310** [comment]
![30493](https://github.com/user-attachments/assets/f556722b-6b2d-44a3-aa8c-2e825db6f500)

64位系统微信3.9.12.17    补丁识别不出来，更新不了

**Comment by fsxde** [comment]
> ![30493](https://private-user-images.githubusercontent.com/123850482/375931118-f556722b-6b2d-44a3-aa8c-2e825db6f500.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTQ3OTQsIm5iZiI6MTcyODcxNDQ5NCwicGF0aCI6Ii8xMjM4NTA0ODIvMzc1OTMxMTE4LWY1NTY3MjJiLTZiMmQtNDRhMy1hYThjLTJlODI1ZGI2ZjUwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNjI4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODQ2ZTdkMWEwOGU4Mzg1N2VmNDAyM2ZlYWIzNzg0NjE0MDgxYjEyYzQ2MDk2Y2Q0NmU4NjU2ZGZkYWNiZjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kk0HJ12nT8D7puY0a5lKro_QIzBlfz7hkvBI1i-ILpg)
> 
> 64位系统微信3.9.12.17 补丁识别不出来，更新不了

我3.9.12.19的都可以
![image](https://github.com/user-attachments/assets/2aa9bd21-1a40-4d2d-9370-dab6d63cb0a0)

**Comment by huiyadanli** [comment]
> ![30493](https://private-user-images.githubusercontent.com/123850482/375931118-f556722b-6b2d-44a3-aa8c-2e825db6f500.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTU2ODEsIm5iZiI6MTcyODcxNTM4MSwicGF0aCI6Ii8xMjM4NTA0ODIvMzc1OTMxMTE4LWY1NTY3MjJiLTZiMmQtNDRhMy1hYThjLTJlODI1ZGI2ZjUwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNjQzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQyOGI0NWEyMTZhMWFkMTZkODQ5NDg2MjlmNjY4NzUyZGE0ZGRlMjFhNjA2YTJiNGVlMjZlNWYxNWQ5NGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3M7RXoCE4cgwraYqWp2zsYkxn74u97Rj36j2K6GelI4)
> 
> 64位系统微信3.9.12.17 补丁识别不出来，更新不了

你的微信文件夹下存在多个版本，手动选择正确的路径

**Comment by ZW310** [comment]
> > ![30493](https://private-user-images.githubusercontent.com/123850482/375931118-f556722b-6b2d-44a3-aa8c-2e825db6f500.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTU2ODEsIm5iZiI6MTcyODcxNTM4MSwicGF0aCI6Ii8xMjM4NTA0ODIvMzc1OTMxMTE4LWY1NTY3MjJiLTZiMmQtNDRhMy1hYThjLTJlODI1ZGI2ZjUwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNjQzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQyOGI0NWEyMTZhMWFkMTZkODQ5NDg2MjlmNjY4NzUyZGE0ZGRlMjFhNjA2YTJiNGVlMjZlNWYxNWQ5NGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3M7RXoCE4cgwraYqWp2zsYkxn74u97Rj36j2K6GelI4)
> > 64位系统微信3.9.12.17 补丁识别不出来，更新不了
> 
> 你的微信文件夹下存在多个版本，手动选择正确的路径

谢谢大佬   我测试下

**Comment by Barry04** [comment]
今天我也不行，3.9.12.17，安装成功了，但是撤回还是撤回的，看不到的，咋解决的

**Comment by huiyadanli** [comment]
不支持32位微信
