### ISSUE TITLE
请问在Virustotal中，为什么有一个报毒？

### ISSUE THREAD

**Issue by seanwang0209** [huiyadanli/RevokeMsgPatcher#805]
DeepInstinct
MALICIOUS
Acronis (Static ML)
Undetected
<img width="1010" alt="Snipaste_2024-10-11_08-07-08" src="https://github.com/user-attachments/assets/383a178f-4c8b-4783-9d53-dcbefc0f5402">

**Comment by huiyadanli** [comment]
你应该去问杀毒软件而不是问我。。。我咋知道他怎么命中特征的
