### ISSUE TITLE
[未支持版本]: 微信pc端4.0.13测试版，是否可以研究下

### ISSUE THREAD

**Issue by lalaxiao1258** [huiyadanli/RevokeMsgPatcher#806]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信测试版4.0.13

### 对应版本的下载地址

https://www.123pan.com/s/ea99-y4AnH

### 软件提示了什么？

大佬有空研究下最新的内测版本

**Comment by LanceCXW** [comment]
内测需要资格，填写问卷提交即可，我是昨天晚上填写的，今天上午才可以登录
https://wj.qq.com/s2/479617/ce78/

**Comment by bootlegseahorse** [comment]
> 内测需要资格，填写问卷提交即可，我是昨天晚上填写的，今天上午才可以登录 https://wj.qq.com/s2/479617/ce78/

需要吗？我反正啥措施也没做就直接顺利登录了，PC和Mac都可以。可能我很久以前就申请过内测吧我也不清楚

**Comment by douxy1994** [comment]
附议，大而丑的最新测试版希望能一揽子支持了。

**Comment by blucegoh** [comment]
4.0版本，bat文件方式也不能多开了。

**Comment by 886899** [comment]
现在全员开放内测了

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/2.0
