### ISSUE TITLE
别人撤回的图片，裂开了

### ISSUE THREAD

**Issue by dmarkdmark** [huiyadanli/RevokeMsgPatcher#807]
这是什么原因

![Clip_2024-10-12_16-52-55](https://github.com/user-attachments/assets/f1cbd0c6-348b-44cd-b82c-7a8943a4efe3)

这是被清理了吗

![Clip_2024-10-12_16-53-35](https://github.com/user-attachments/assets/f399285b-fb07-447a-a90c-a9244e726a99)

还是撤回功能有问题了。

**Comment by nanxi666** [comment]
我也是一样，图片防撤回不了

**Comment by dmarkdmark** [comment]
> 我也是一样，图片防撤回不了

这是QQNT9+消息时，我翻聊天记录，然后看到这个图片裂开了
如果是刚撤回不久的，还是可以看到的
听说有个明文数据库，不知道有啥工具查看这个裂开图片不

**Comment by Ruling95** [comment]
俺也一样。

**Comment by dmarkdmark** [comment]
日常滴滴

**Comment by nanxi666** [comment]
> 日常滴滴

哈哈，日常催作者。不过听说好像降级能图片能防撤回

**Comment by dmarkdmark** [comment]
> > 日常滴滴
> 
> 哈哈，日常催作者。不过听说好像降级能图片能防撤回

辛苦来个亲测可用的QQNT版本
感谢

**Comment by dmarkdmark** [comment]
> > 日常滴滴
> 
> 哈哈，日常催作者。不过听说好像降级能图片能防撤回

![Clip_2024-10-18_15-24-25](https://github.com/user-attachments/assets/04ecc35c-4e71-41e9-9c5e-021d48beeec0)
这是我目前使用的版本

**Comment by huiyadanli** [comment]
QQNT我这边只是辅助安装防撤回插件

此问题参考 https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/issues/94

**Comment by dmarkdmark** [comment]
> QQNT我这边只是辅助安装防撤回插件
> 
> 此问题参考 [xh321/LiteLoaderQQNT-Anti-Recall#94](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/issues/94)

大佬，能找到9.9.7QQNT安装包不，我降级得了

**Comment by nanxi666** [comment]
> > QQNT我这边只是辅助安装防撤回插件
> > 此问题参考 [xh321/LiteLoaderQQNT-Anti-Recall#94](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/issues/94)
> 
> 大佬，能找到9.9.7QQNT安装包不，我降级得了

https://forum.itzdrli.cc/d/9-zi-yuan-qqntjia-gou-an-zhuang-bao-han-quan-bu-li-shi-ban-ben/2

**Comment by dmarkdmark** [comment]
已去tg找到9.9.7安装包，正在使用，看是否还会出现该问题

![Clip_2024-10-21_10-14-59](https://github.com/user-attachments/assets/83421dd3-9b1c-4917-a139-7046fe1b8fd6)

**Comment by dmarkdmark** [comment]
G，用1.9安装，QQNT没有撤回插件了
QQNT版本：
9.9.7-20667

**Comment by dmarkdmark** [comment]
日常滴滴
