### ISSUE TITLE
新版本 TIM (3.0.0) 未支持

### ISSUE THREAD

**Issue by solstice23** [huiyadanli/RevokeMsgPatcher#81]
![screenshot](https://i.loli.net/2020/03/27/AJ67WaDGx4byn2F.png)

TIM 3.0.0 : https://c-t.work/s/648195c1040c4f

**Comment by huiyadanli** [comment]
TIM居然复活了:joy: ，我去下载新版试试

**Comment by qqq7586025** [comment]
想要加1

**Comment by EDTmagiclab** [comment]
想要+2，新版TIM真香

**Comment by huiyadanli** [comment]
看了下消息撤回模块和QQ完全一致。。。

TIM 3 以及更加新的版本已经支持。 https://github.com/huiyadanli/RevokeMsgPatcher/commit/8fe154393984ec84f31c77b0e0f27dde2e9f37f6

**Comment by solstice23** [comment]
感谢啦！

**Comment by qqq7586025** [comment]
感谢啦！
