### ISSUE TITLE
QQNT 频繁退登

### ISSUE THREAD

**Issue by Smiog** [huiyadanli/RevokeMsgPatcher#811]
只安装了 QQNT 的防撤回。

QQ 版本：9.9.15-28060
插件版本：1.9

一天能自动退登好几次，并且退登后必须重新输入密码才能重进 QQ。

**Comment by huiyadanli** [comment]
没遇到这种情况，建议在 https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/ 提问

**Comment by MushroomScript** [comment]
我也是 你解决了吗

**Comment by MushroomScript** [comment]
> 我也是 你解决了吗

我的QQ版本是 9.9.12-25765  所以我觉得跟QQ版本应该关系不大, 我安装了LLNT, 并且我同时登录了3个QQ, 都是常用的大号已经在线很多年的, 有一个号开启了LLNT的HTTP服务和反向WebSocket服务, 对接了机器人, 但是我机器人什么消息都没处理, 大概几个小时QQ就会退掉, 另外两个没开启LLNT的就没掉

**Comment by Smiog** [comment]
我查看了设备记录没有盗号迹象，并且删除补丁后 QQ 恢复正常，用旧版 QQ 也不会掉登，考虑仍是 LiteLoader 与 QQNT 兼容性问题。
