### ISSUE TITLE
安装路径为空

### ISSUE THREAD

**Issue by XlonLeo** [huiyadanli/RevokeMsgPatcher#819]
win系统刚降级的，微信是安在D盘的就没动，等到微信更新版本之后重新安装防撤回，安装路径为空，并且手动选择安装路径也会显示无法找到此应用的关键文件
![Snipaste_2024-10-21_09-55-57](https://github.com/user-attachments/assets/1790dbf0-4962-4e02-a8a2-b08e7ae114a3)

**Comment by huiyadanli** [comment]
说明你路径选错了，微信目录下面还有个以版本号命名的目录，选它

**Comment by XlonLeo** [comment]
没有选错, 依旧为空
![image](https://github.com/user-attachments/assets/a252a631-48bf-4868-8f59-54c32c99246e)


> 说明你路径选错了，微信目录下面还有个以版本号命名的目录，选它

**Comment by XlonLeo** [comment]
注册表添加相应安装路径，已解决

**Comment by westmood1219** [comment]
> 注册表添加相应安装路径，已解决

能说说具体怎么操作吗

**Comment by dmarkdmark** [comment]
麻烦关下issue
