### ISSUE TITLE
qq轻聊版变成qq极速版了，更新啦

### ISSUE THREAD

**Issue by zengxiyao** [huiyadanli/RevokeMsgPatcher#82]
qq轻聊版变成qq极速版了，更新啦

**Comment by huiyadanli** [comment]
这个只有安卓版本吧，没看到有这个PC版本

**Comment by zengxiyao** [comment]
哦哦，是的

**Comment by xiahongyang123** [comment]
不如我讲个故事给你







01




&nbsp; &nbsp;&nbsp;“在一片蔚蓝的海洋里，生活着无数的生物。

&nbsp; &nbsp; &nbsp;人鱼是这片海里最特别的存在。所有生物都爱它。





&nbsp; &nbsp; &nbsp;它有粉色的纤长的鱼尾巴。

&nbsp; &nbsp; &nbsp;还有在这片海上呼风唤雨的至高能力。




&nbsp; &nbsp; &nbsp;它温柔善良，正义友好，

&nbsp; &nbsp; &nbsp;笑起来的时候脸上总有个鱼涡。













02




&nbsp; &nbsp; &nbsp;人鱼无聊的时候会悄悄上岸去逛集市，但它永远

&nbsp; &nbsp; &nbsp;记得黄昏前回到海里。

&nbsp; &nbsp; &nbsp;父亲说这是这片海洋的规矩。




&nbsp; &nbsp; &nbsp;它向来听话。

&nbsp; &nbsp; &nbsp;直到有一天。




&nbsp; &nbsp; &nbsp;“妈妈，我想留在岸上看黄昏。”

&nbsp; &nbsp; &nbsp;“不行啊，孩子。你父亲说你看了人间的黄昏就没

&nbsp; &nbsp; &nbsp; 有机会再回到这片海了。”

&nbsp; &nbsp; &nbsp;“那我便不看了。”













03




&nbsp; &nbsp;&nbsp;&nbsp;鲨鱼躲在一个巨大的水草下面，试图偷偷消化掉

&nbsp; &nbsp; &nbsp;它听到的对话。




&nbsp; &nbsp; “它回来的时候总不开心是因为它想看黄昏吗。”

&nbsp; &nbsp; &nbsp;鲨鱼想也许我能替它前去探探路。







04




&nbsp; &nbsp;&nbsp;&nbsp;鲨鱼是在一个晴天出海的，它佩戴上所有需要战

&nbsp; &nbsp; &nbsp;斗时才穿的铠甲，颇有一去不复返的决心。




&nbsp; &nbsp; &nbsp;于是这天。




&nbsp; &nbsp; &nbsp;它看到太阳落山时映在海面上的光芒，一片紫色。

&nbsp; &nbsp; &nbsp;原来这就是黄昏。

&nbsp; &nbsp; &nbsp;有颜色，透明。













05




&nbsp; &nbsp;&nbsp;“快看，大白鲨！它真的来了。”

&nbsp; &nbsp; &nbsp;捕猎者躲在一棵大树的背后和同伴窃窃私语。




&nbsp; &nbsp; “不枉费我们这么久的心思。”

&nbsp; &nbsp; “可你看它手头上的兵器，我们不一定能成功。”

&nbsp; &nbsp; “那就智取。”







06




&nbsp; &nbsp; &nbsp;“大白鲨，你知道为什么你的人鱼公主总想要看

&nbsp; &nbsp; &nbsp; 黄昏吗？”

&nbsp; &nbsp; &nbsp; 英俊的人类来到鲨鱼的面前。




&nbsp; &nbsp; &nbsp;“因为我告诉它，如果它看到了其它生物都看不

&nbsp; &nbsp; &nbsp; 到的黄昏，我就会带它回家。”

&nbsp; &nbsp; &nbsp;“你每天悄悄跟在它身后。难道不知道它也想和

&nbsp; &nbsp; &nbsp; 美人鱼一样把尾巴换成腿，为了和我在一起吗？“







07




&nbsp; &nbsp; &nbsp;它知道。

&nbsp; &nbsp; &nbsp;当然知道。




&nbsp; &nbsp; &nbsp;鲨鱼爱人鱼公主，

&nbsp; &nbsp; &nbsp;人鱼公主想和面前的这个人类生活在一起。













08




&nbsp; &nbsp;&nbsp;&nbsp;“不如，把你的獠牙给我，

&nbsp; &nbsp; &nbsp; 我便有方法成全你的感情。”




&nbsp; &nbsp; &nbsp;“我不需要。”

&nbsp; &nbsp; &nbsp;“我的獠牙给你，你能成全它吗。”




&nbsp; &nbsp; &nbsp;“当然。”




&nbsp; &nbsp; &nbsp; 捕猎者用手中的剑轻而易举取走了它最锋利的

&nbsp; &nbsp; &nbsp; 牙齿。血腥味弥漫在整个岸边。













09




&nbsp; &nbsp; &nbsp;捕猎者没有食言。

&nbsp; &nbsp; &nbsp;人鱼公主很快就恢复了往日的欢笑，

&nbsp; &nbsp; &nbsp;还时常露出它脸上的鱼涡。




&nbsp; &nbsp; &nbsp;它只是不知道有一个爱它的鲨鱼已经失去了獠牙。

&nbsp; &nbsp; &nbsp;而失去了獠牙的鲨鱼几乎丢了半条鱼命。













10




&nbsp; &nbsp;&nbsp;&nbsp;后来，人鱼公主发现它爱着的人类其实是个捕猎

&nbsp; &nbsp; &nbsp;者， 甚至在他的家中发现了无数和它生活在同一

&nbsp; &nbsp; &nbsp;片海洋中的同伴的器官。




&nbsp; &nbsp; &nbsp;鲨鱼赶到的时候，捕猎者正拿起利剑去砍人鱼的

&nbsp; &nbsp; &nbsp;尾巴。




&nbsp; &nbsp; &nbsp;那条粉色的纤长的鱼尾巴。

&nbsp; &nbsp; &nbsp;在紫色的霞光中一点点幻灭，然后几近消逝。




&nbsp; &nbsp; &nbsp;它绝望的呜咽起来。然后向面前的人类冲撞过去。

&nbsp; &nbsp; &nbsp;但是很快，它便伤痕累累，用自己仅剩的力气游

&nbsp; &nbsp; &nbsp;到人鱼身边。




&nbsp; &nbsp; &nbsp;它只能托着它，如同一块珍宝。













11




&nbsp; &nbsp; &nbsp;它说:“我没有人类英俊的外貌，

&nbsp; &nbsp; &nbsp;没有镶着宝石的利剑，

&nbsp; &nbsp; &nbsp;我只有锋利的獠牙，

&nbsp; &nbsp; &nbsp;和一个对血腥味敏感的鼻子。”




&nbsp; &nbsp; “没有动物喜欢我，你是第一个对我讲话的。”




&nbsp; &nbsp; “你送了我一颗海螺，我常在里面听见你的笑声。”




&nbsp; &nbsp; “我看到你不开心的时候会想，

&nbsp; &nbsp; &nbsp;要是你开心就好了。

&nbsp; &nbsp; &nbsp;看到你开心的时候又想，

&nbsp; &nbsp; &nbsp;要是是我让你开心的就好了。”




&nbsp; &nbsp; “我总幻想自己陪你去看黄昏，你看紫色的霞光，

&nbsp; &nbsp; &nbsp;我就看你。”




&nbsp; &nbsp; “其实我是不懂辨别颜色的，你说黄昏是紫色的，

&nbsp; &nbsp; &nbsp;我便觉得是。”




&nbsp; &nbsp; “如果有一天能托着你，听你唱歌，

&nbsp; &nbsp; &nbsp;那就是我最大的梦想了。”




&nbsp; &nbsp; “在我心里，你是整个海洋歌声最动听的人鱼，

&nbsp; &nbsp; &nbsp;它们都比不上你，

&nbsp; &nbsp; &nbsp;你是公主。”













12




&nbsp; &nbsp;&nbsp;&nbsp;“后来呢，后来呢，你梦到结局了吗？”




&nbsp; &nbsp; &nbsp;“后来，鲨鱼用剩下的牙齿咬断了岸上的人类。

&nbsp; &nbsp; &nbsp; 它实现了自己的梦想。”

&nbsp; &nbsp; &nbsp;“大概就是，大家都死了，这是一个悲剧。”




&nbsp; &nbsp; &nbsp;“我觉得不是。

&nbsp; &nbsp; &nbsp; 也许人鱼公主开始爱上的就是鲨鱼呢。

&nbsp; &nbsp; &nbsp; 它想帮不能辨别色彩的鲨鱼去看看黄昏的样子。

&nbsp; &nbsp; &nbsp; 它想做它的第一个朋友。

&nbsp; &nbsp; &nbsp; 它其实不爱笑，却把笑声都藏进一颗小海螺里。

&nbsp; &nbsp; &nbsp; 直到有一天，

&nbsp; &nbsp; &nbsp; 捕猎者给它看了它最爱的鲨鱼的獠牙，

&nbsp; &nbsp; &nbsp; 于是它崩溃了。”













13




&nbsp; &nbsp;&nbsp;&nbsp;“或许吧。”

&nbsp; &nbsp; &nbsp;“或许不是一个悲剧。”

**Comment by xiahongyang123** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"辉鸭蛋"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午4:34
收件人:&nbsp;"huiyadanli/RevokeMsgPatcher"<RevokeMsgPatcher@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [huiyadanli/RevokeMsgPatcher] qq轻聊版变成qq极速版了，更新啦 (#82)





 
Closed #82.
