### ISSUE TITLE
qqnt防撤回对折叠到群助手的群没有用？

### ISSUE THREAD

**Issue by lulvxiu** [huiyadanli/RevokeMsgPatcher#820]
刚刚看别人撤回后还是看不见

**Comment by lulvxiu** [comment]
版本9.9.15-28498 (64位)，撤回工具也是最新的

**Comment by lulvxiu** [comment]
好像有了，不知道是不是之前没打开过群聊的原因

**Comment by dmarkdmark** [comment]
关下issue谢谢，看到好几天了
(#^.^#)

**Comment by huiyadanli** [comment]
在  https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/issues 提问。

这里只是安装了相关插件
