### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by dmarkdmark** [huiyadanli/RevokeMsgPatcher#821]
起因：最新版QQNT成功安装插件，无法查看撤回图片（图片是裂开的），然后去tg找到一个QQNT低版本安装包

![Clip_2024-10-21_18-25-28](https://github.com/user-attachments/assets/af53223e-3c01-4398-adb2-dba7738f562d)

使用1.9，管理员运行

![Clip_2024-10-21_18-25-58](https://github.com/user-attachments/assets/994296c9-fc57-4717-a438-3f3134d7ce42)

![Clip_2024-10-21_18-26-26](https://github.com/user-attachments/assets/e46fdc12-65a2-4122-9e9d-d9fe14606f7b)

点击，更新所有按钮
点击，安装

![Clip_2024-10-21_18-27-45](https://github.com/user-attachments/assets/9423ece9-ca1a-4c4f-9683-cb437f8127fb)

启动QQNT，查看QQNT设置

![Clip_2024-10-21_18-28-28](https://github.com/user-attachments/assets/ba3cf30b-455b-4cd8-babf-bbdd08234ab8)

无插件模块

PS：附上QQNT安装包和撤回工具

通过百度网盘分享的文件：撤回插件问题
链接：https://pan.baidu.com/s/1dZhU0Un7uWae1Cbl9ClQ1w?pwd=a5lu 
提取码：a5lu

**Comment by dmarkdmark** [comment]
日常滴滴

**Comment by huiyadanli** [comment]
无力测试，可以尝试使用1.8版本。应该是支持的

**Comment by dmarkdmark** [comment]
> 无力测试，可以尝试使用1.8版本。应该是支持的

我1.7 1.8都用过，似乎不行，我再试下

**Comment by dmarkdmark** [comment]
> 无力测试，可以尝试使用1.8版本。应该是支持的

![Clip_2024-10-22_16-53-50](https://github.com/user-attachments/assets/83bc8baa-3e85-4ba5-931d-bbf1492472c4)

我擦，不给支持了，我是因为最新版QQNT查看撤回图片会裂开，我才降级到9.9.7，这下1.8.1不支持9.9.7QQNT了

**Comment by dmarkdmark** [comment]
咋子搞，最新QQNT撤回有问题，会图片裂开
降级，补丁不支持

**Comment by huiyadanli** [comment]
你按照 LiteLoaderQQNT 的教程手动安装，或者换其他安装器

**Comment by dmarkdmark** [comment]
> 你按照 LiteLoaderQQNT 的教程手动安装，或者换其他安装器

那我去看看那边的教程，太难搞了，已经晕了
本意：还是想最新版QQNT使用大佬这个的，可惜最新版QQNT查看图片会裂开
