### ISSUE TITLE
QQNT 版本: 9.9.16-28788 (64位) 防撤回安装失败

### ISSUE THREAD

**Issue by qq1176914912** [huiyadanli/RevokeMsgPatcher#823]
防撤回之前是可以用的，今天更新了QQNT版本到 9.9.16-28788 (64位)，我想着是不是需要再安装一下防撤回，关闭了qq，在安装器安装时后报错了：
![image](https://github.com/user-attachments/assets/77352c61-0fc7-4991-ae24-92b85012da95)
![image](https://github.com/user-attachments/assets/e8dbcac8-8b59-4db6-acef-b493bd8bdcfe)

**Comment by dfnone** [comment]
同版本我这里安装没问题

**Comment by qq1176914912** [comment]
> 同版本我这里安装没问题 ![image](https://private-user-images.githubusercontent.com/111632883/379510010-8fcc79eb-9f3e-4051-92c1-d5bd48c55216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzMxNDYsIm5iZiI6MTcyOTczMjg0NiwicGF0aCI6Ii8xMTE2MzI4ODMvMzc5NTEwMDEwLThmY2M3OWViLTlmM2UtNDA1MS05MmMxLWQ1YmQ0OGM1NTIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMTIwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWY3MjY3OTk3MTM2NmQzOWVlNDUyZDQwNjdhYzQ3ODQ2NzgxZGUxODk2YjNjODUzMDdjMmM0NjNmZjdhMzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KYwEP8lnevsgLfnGCpxLfZd4gaDoPu9eyzxFHWq2YAQ)

我又试了一下，又可以了 不知道之前是什么问题 ,之前可能是没关干净0.0
