### ISSUE TITLE
[未支持版本]: Weixin4.0.0.22

### ISSUE THREAD

**Issue by wgetnz** [huiyadanli/RevokeMsgPatcher#827]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

测试版本 4.0.0.22

### 软件提示了什么？

提示请输出正确的路径

附件为测试版本，无需账号内测，直接可登陆

下载地址
阿里云盘：https://www.alipan.com/s/xjhGXVkj7sR

百度云盘：https://pan.baidu.com/s/1PazTPT2aHK1S6xdblVnJvg?pwd=anwn

**Comment by ViCrack** [comment]
微信官网现在就能直接下载了

**Comment by RUANRUI1995** [comment]
微信NT版希望可以支持

**Comment by RUANRUI1995** [comment]
现在最新4.0.0.26

**Comment by blucegoh** [comment]
Windows：https://dldir1v6.qq.com/weixin/Universal/Windows/WeChatWin.exe

**Comment by zetaloop** [comment]
> 现在最新4.0.0.26

4.0.0.26 可用的防撤回特征 -> [#832 (comment)](https://github.com/huiyadanli/RevokeMsgPatcher/issues/832#issuecomment-2453503225)

**Comment by huiyadanli** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/2.0
