### ISSUE TITLE
[未支持版本]: 3.9.12.17

### ISSUE THREAD

**Issue by XXXLLi0213** [huiyadanli/RevokeMsgPatcher#830]
### 请先确认当前使用的 微信/QQ/TIM防撤回补丁 是最新版本！

- [X] 我确认当前使用的是最新版

### 微信/QQ 版本

微信正式版：3.9.12.17

### 对应版本的下载地址

https://pc.weixin.qq.com/

### 软件提示了什么？

WeChat官网和华为应用市场下载的最新版（3.8.12.17），安装提示都一样（看截图)

![image](https://github.com/user-attachments/assets/ea16b8fc-bf39-44cb-a62a-1575c322cadf)
特征比对:当前特征码匹配数[0)和明望的西配数(2]不一致，
应用别
出现此种情况的一般有如下可能:1,你可能已经安装了某个功能的补丁，请选择来安美功能进行安装,2.如果当前版本为最新版本，特征码可能出现变化(可能性比较低)，请联系作者处理，

**Comment by huiyadanli** [comment]
![image](https://github.com/user-attachments/assets/f0c2d98e-10ba-430b-a59d-5fece5aa4cb9)
------------------------
![image](https://github.com/user-attachments/assets/aef9baa3-8f01-469b-9220-1d1b7dde5d00)
------------------
![image](https://github.com/user-attachments/assets/fca7cade-ef5d-4a71-b74c-5dbdd07b5d4a)
