### ISSUE TITLE
QQ9.9.16-29271新版本 安装后一直循环登录

### ISSUE THREAD

**Issue by MarkLily** [huiyadanli/RevokeMsgPatcher#834]
如题！

**Comment by EddyLee88** [comment]
![image](https://github.com/user-attachments/assets/6a8deef3-ec07-425b-a87a-bb7cd5ff6417)
9.9.16-29271 (64位)
一样的情况

**Comment by Cheng-02** [comment]
一样的的情况

**Comment by Young522488690** [comment]
加一，盼修复

**Comment by fakejadelee** [comment]
+·1

**Comment by 18215569765** [comment]
一样

**Comment by huiyadanli** [comment]
等待 LiteLoaderQQNT 发布新版本后，更新 LiteLoaderQQNT 就能解决

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/10d5ccd12f56ac96d420db62831ed1ae90ce0b1f

**Comment by mo-jinran** [comment]
修好发布了

**Comment by MarkLily** [comment]
验证过了 是修复好了！感谢大佬 感谢各位！
