### ISSUE TITLE
是否可选不使用管理员权限打开

### ISSUE THREAD

**Issue by amorphobia** [huiyadanli/RevokeMsgPatcher#837]
我的微信是使用 [scoop](https://github.com/ScoopInstaller/Scoop) 安装的，因此不在 `Program Files` 里，修改其中的 exe 或者 dll 不需要管理员权限。

目前 RevokeMsgPatcher 不能使用普通权限打开，因此在拿不到管理员权限的电脑上无法使用。

请问技术上能否实现不需要管理员权限？

**Comment by huiyadanli** [comment]
#663
