### ISSUE TITLE
qq更新后，下载2.0插件，无法处理防撤回。

### ISSUE THREAD

**Issue by Ruling95** [huiyadanli/RevokeMsgPatcher#838]
点击报错信息。
![image](https://github.com/user-attachments/assets/4d1a7458-edf3-41bd-8a97-615035426523)

QQNT版本。
![image](https://github.com/user-attachments/assets/9f408c54-60a0-4bac-a9d2-d719691c4060)

qq更新后，下载2.0插件，无法处理防撤回。

**Comment by dmarkdmark** [comment]
> 点击报错信息。 ![image](https://private-user-images.githubusercontent.com/49261119/385104284-4d1a7458-edf3-41bd-8a97-615035426523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTAwMDgsIm5iZiI6MTczMTQ4OTcwOCwicGF0aCI6Ii80OTI2MTExOS8zODUxMDQyODQtNGQxYTc0NTgtZWRmMy00MWJkLThhOTctNjE1MDM1NDI2NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5MjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZmQwYzQzYzIxMTZhZmYyMTJhODliYTM5ZWU5MTBiY2Y0NDAyYzUyNWI0MGY1NTYzOWFmOTdlZTcxOTE0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YmjGAdmnRlWUmWV_K1_k5CoyZrgsO2QAB_ZR9kyGUQc)
> 
> QQNT版本。 ![image](https://private-user-images.githubusercontent.com/49261119/385104326-9f408c54-60a0-4bac-a9d2-d719691c4060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTAwMDgsIm5iZiI6MTczMTQ4OTcwOCwicGF0aCI6Ii80OTI2MTExOS8zODUxMDQzMjYtOWY0MDhjNTQtNjBhMC00YmFjLWE5ZDItZDcxOTY5MWM0MDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5MjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNGNjMTA4MzJiMmI3YjljZjBmNGQwYWYxNDUwOGFkZTNjZGRjMzNkMjAxNjllZjBiMmViZWYyNjBhMTZhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y0HMpFphPGFz-p1zeWBOvvYh6Je0QIIfxr516yXE7eE)
> 
> qq更新后，下载2.0插件，无法处理防撤回。

那你下1.9试试，2.0就是给微信内测用的，你降级试下

**Comment by Ruling95** [comment]
降级到1.9了。还是报错。這难道要重装一下qq。
![image](https://github.com/user-attachments/assets/c2e61cc9-a420-46b3-8fc6-0f57409d954a)

**Comment by Ruling95** [comment]
妥活了。   把QQ重装了。然后就可以了。。。。
