### ISSUE TITLE
会不会有植入

### ISSUE THREAD

**Issue by jaxling** [huiyadanli/RevokeMsgPatcher#84]
打不开dll文件，打开了也看不懂到底干了啥，所以有此一问

**Comment by byyxx128** [comment]
软件是开源的，不放心的自己编译，还不放心的就不要用了……

**Comment by huiyadanli** [comment]
1. 使用 Beyond Compare 的16进制文件对比功能，可以看到修改前后的dll区别。

2. 程序是开源的也可以看到做出了哪些修改，具体修改的内容可以参考：
https://github.com/huiyadanli/RevokeMsgPatcher/blob/master/RevokeMsgPatcher.Assistant/JsonData.cs
