### ISSUE TITLE
NTQQ防撤回安装失败

### ISSUE THREAD

**Issue by lzspain** [huiyadanli/RevokeMsgPatcher#844]
今天将NTQQ更新到9.9.16.29456后，用2.0插件安装防撤回模块，但几个模块都提示mscorlib异常，必须至少有一个对象实现IComparable，是什么原因呢？
![微信截图_20241119091201](https://github.com/user-attachments/assets/906a491c-7780-4fdb-aa78-90b918140906)

**Comment by 517986804** [comment]
2.0插件压缩包解压出来安装防撤回模块，解压出来的文件不能删，删了就会mscorlib异常

**Comment by lzspain** [comment]
> 2.0插件压缩包解压出来安装防撤回模块，解压出来的文件不能删，删了就会mscorlib异常

没有删过，之前使用都正常，就今天用电脑管家更新QQ后就这样。奇怪的是，QQ自己又更新了一次，再安装补丁又正常了。

**Comment by lzspain** [comment]
> 2.0插件压缩包解压出来安装防撤回模块，解压出来的文件不能删，删了就会mscorlib异常

还有个问题，这两天QQNT频繁出现登录失效，需要重新登录的问题，是这个插件导致的，还是腾讯自己的原因呢？

**Comment by 517986804** [comment]
> > 2.0插件压缩包解压出来安装防撤回模块,解压出来的文件不能删,删了就会mscorlib异常
> 
> 没有删过,之前使用都正常,就今天用电脑管家更新即时通信软件后就这样。奇怪的是，QQ自己又更新了一次,再安装补丁又正常了。

说明你电脑管家更新的版本不对，至少不是最新版，我一般都是官网下载最新版

**Comment by 517986804** [comment]
> > 2.0插件压缩包解压出来安装防撤回模块,解压出来的文件不能删,删了就会mscorlib异常
> 
> 还有个问题,这两天QQNT频繁出现登录失效,需要重新登录的问题,是这个插件导致的,还是腾讯自己的原因呢？

目前不清楚，我的QQNT也是，打补丁的和不打补丁的两台电脑都有这情况

**Comment by dmarkdmark** [comment]
我今天老是登着就自动退出,我直接更新QQNT,再次使用撤回,发现一样的问题,我直接删除电脑的撤回,然后重新下载2.0就行了
