### ISSUE TITLE
关于“pc版防撤回微信”和“手机版官方微信”之间进行聊天记录“迁移”的疑问。

### ISSUE THREAD

**Issue by neatgz** [huiyadanli/RevokeMsgPatcher#849]
电脑PC版微信，已打防撤回补丁。
手机版微信，官方版。
使用微信的“聊天记录迁移功能”，从电脑上迁移到手机上，会不会出现冲突？因为聊天记录其实一个是有撤回，一个没撤回，迁移和合并的过程中，会不会有冲突？谢谢。

**Comment by huiyadanli** [comment]
我无法给出回答，建议用其他账号自行尝试
