### ISSUE TITLE
qqnt更新安装出现异常：mscorlib

### ISSUE THREAD

**Issue by 1onelyman** [huiyadanli/RevokeMsgPatcher#857]
更新qqnt插件后安装报错，关闭qq、管理员模式运行、切换更新代理都不行
![image](https://github.com/user-attachments/assets/9f65151d-8ee6-45ce-9517-5aea6caa7480)

**Comment by huiyadanli** [comment]
关闭	QQ后再安装

**Comment by suenley** [comment]
![image](https://github.com/user-attachments/assets/5c10896f-1a43-4ffe-a7dd-1109ca86ed32)
我是因为这个问题来的，刚开始没仔细看报错，以为和楼主问题一样来着。

**Comment by 1onelyman** [comment]
> 重启电脑后，不要启动QQ，直接安装试试

还得是重启大法
