### ISSUE TITLE
微信防撤回好像会影响截图功能，Alt+A 慢了许多，并且容易卡顿

### ISSUE THREAD

**Issue by qienanxiang** [huiyadanli/RevokeMsgPatcher#87]
微信防撤回好像会影响截图功能，Alt+A 慢了许多，并且容易卡顿

希望大佬能看看

**Comment by huiyadanli** [comment]
防撤回修改的逻辑和影响范围不会造成这种现象。

可以还原补丁或者重装最新版本的微信后，再使用一段时间试试。

**Comment by qienanxiang** [comment]
好的谢谢！

辉鸭蛋 <notifications@github.com> 于 2020年4月20日周一 13:48写道：

**Comment by penwong** [comment]
我也是，不知道是不是微信自己的bug

**Comment by huiyadanli** [comment]
2.9.0.112 测试正常
