### ISSUE TITLE
影响了手机端微信的使用（变卡顿了）

### ISSUE THREAD

**Issue by BradYang666** [huiyadanli/RevokeMsgPatcher#88]
你好，我参照您的教程自行修改了dll文件。遇到的问题是当有人撤回时，手机端微信会非常卡顿，不知道是怎么回事。

**Comment by huiyadanli** [comment]
我测试的时候都是会在手机端进行确认的，没有遇到你所说的情况。
电脑端微信影响手机端微信信息收发的可能性极其低微。

请先确认手机端是否有安装一些微信插件、防撤回工具等等微信辅助工具，有的话应该就是这些工具造成的卡顿。

**Comment by BradYang666** [comment]
感谢回复。
为了给后面的朋友们提示，我使用的iPhone，且没使用任何插件和第三方工具（电脑和手机都是），我猜是自己电脑端贸然升级到了2.9.0版本的Windows微信导致的问题。我换回支持的最新版本（2.8.0.112)就没问题了。
感谢您的教程。

**Comment by sisuch** [comment]
> 感谢回复。
> 为了给后面的朋友们提示，我使用的iPhone，且没使用任何插件和第三方工具（电脑和手机都是），我猜是自己电脑端贸然升级到了2.9.0版本的Windows微信导致的问题。我换回支持的最新版本（2.8.0.112)就没问题了。
> 感谢您的教程。

猜测是2.9有文件同步功能，可以试试关闭聊天文件自动下载和同步

**Comment by huiyadanli** [comment]
我测试了下安卓正常。
