### ISSUE TITLE
重要！QQ报错：文件被破坏或丢失

### ISSUE THREAD

**Issue by cxzlw** [huiyadanli/RevokeMsgPatcher#90]
昨天突然出现的，还以为被盗号了，重装完QQ又报错，再重装没事了结果想起来没装防撤回又回来下载安装装完就又提示了。。。望修复，谢谢

**Comment by cxzlw** [comment]
求修复

**Comment by huiyadanli** [comment]
请提供下QQ的具体版本

**Comment by cxzlw** [comment]
我也不知道版本叫啥，反正QQ最新版这样

**Comment by cxzlw** [comment]
重装完装防撤回后360报IM.dll设置关键启动项

**Comment by huiyadanli** [comment]
QQ界面左下角菜单 - 帮助 - 关于，可以看到QQ版本

360应该会报关键dll被注入修改，而不是设置启动项

**Comment by cxzlw** [comment]
是启动项，QQ9.3.2(26869)，360反而不报关键修改，报的是IM.dll试图设置关键启动项，貌似这个要么允许要么拒绝都得快点点，不然就会弹QQ损坏

**Comment by yws112358** [comment]
有一样的问题  去年发生的，主要是QQ  微信 重装过一会就又不行了，qq的protect服务会一直提示文件损坏，后来嫌麻烦重装了系统。因为即使清理了QQ 微信的安装目录（可能还有其他地方） 导致qq 微信无法使用 于是放弃使用了
