### ISSUE TITLE
请更新支持新版本2.9.0.112

### ISSUE THREAD

**Issue by kil-x** [huiyadanli/RevokeMsgPatcher#91]
微信又更新了2.9版本，请更新支持新版本2.9.0.112，谢谢

**Comment by huiyadanli** [comment]
请使用最新的 0.8 版本的防撤回补丁，每次微信更新重新打一次补丁就好了

**Comment by September999999999** [comment]
试过了，支持不了

**Comment by huiyadanli** [comment]
@kil-x @September999999999 我测试完全有效，注意新版本防撤回保留了撤回提示
