### ISSUE TITLE
QQ9.3.2版本重启系统后会打不开

### ISSUE THREAD

**Issue by hackgsl** [huiyadanli/RevokeMsgPatcher#94]
QQ9.3.2.26869，一键处理之后，不重启系统重启多少次QQ都没问题
如果重启了系统，打开QQ没任何反应，查询系统的事件查看器没看到任何报错
试着把QQ安装目录及appdata目录覆盖恢复也不行，必须重装（重装时会卸载）后才可以。
QQ9.2.5.26724则没有这个问题
系统为Windows10 1909 家庭版

**Comment by xyyyrc** [comment]
同QQ9.3.2.26869，重启后使用正常。
Windows10 1909 专业版，X64

**Comment by huiyadanli** [comment]
是不是先执行了备份还原操作？

暂时没法复现出这个问题。。实在不行只能重装QQ后再执行防撤回了。。
