### ISSUE TITLE
微信2.9.0版本，打了补丁之后，登陆时无法获取二维码，用旧版2.8.0版本也不行

### ISSUE THREAD

**Issue by qq421962914** [huiyadanli/RevokeMsgPatcher#95]
跪求更新
今天重做系统了，然后下载最2.9版本，打补丁之后，就无法获取二维码。
又下载旧版，打补丁之后，也是登陆时候无法获取二维码。

**Comment by qq421962914** [comment]
2020年5月24日22:20:16，速报！
我把360关掉之后，再打补丁，就可以获取二维码登陆了！
--------------------------
记得上一次打补丁，好像是开了360的，不知道为啥这次就不行了。

**Comment by huiyadanli** [comment]
无论补丁安装成功还是失败，应该都不会影响二维码登录。。

**Comment by qq421962914** [comment]
我把360关了，再打补丁，就没问题了，登陆什么的都正常了。
今天开机也是没问题，360开机自启动，直接打开微信登陆，可以正常使用了。
谢谢大佬。
&nbsp;

缒逐___


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "辉鸭蛋"<notifications@github.com&gt;; 
发送时间: 2020年5月25日(星期一) 上午10:27
收件人: "huiyadanli/RevokeMsgPatcher"<RevokeMsgPatcher@noreply.github.com&gt;; 
抄送: "__Simple、"<421962914@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [huiyadanli/RevokeMsgPatcher] 微信2.9.0版本，打了补丁之后，登陆时无法获取二维码，用旧版2.8.0版本也不行 (#95)





 
无论补丁安装成功还是失败，应该都不会影响二维码登录。。
