### ISSUE TITLE
实测WIN7 版本2.8.0.112无效

### ISSUE THREAD

**Issue by koen100** [huiyadanli/RevokeMsgPatcher#99]
![微信图片_20200609222709](https://user-images.githubusercontent.com/65277160/84160408-b8caa900-aaa0-11ea-8ff5-540b22529fff.png)
![132123](https://user-images.githubusercontent.com/65277160/84160556-e31c6680-aaa0-11ea-8a1c-7f097f49ad42.png)

**Comment by huiyadanli** [comment]
微信从 2.8.0.112 开始支持**带提示**的防撤回。

显示撤回提示，但是实际还能看到撤回内容。

ref: #79
